### ISSUE TITLE
Cannot use nano text editor

### ISSUE THREAD

**Issue by petebachant** [git-for-windows/git#334] opened 2015-08-29 16:36 UTC
As installed by the Software Carpentry installer: http://files.software-carpentry.org/SWCarpentryInstaller.exe

Trying to run `nano` produces

```
Pete@Pete-ZBook MINGW64 ~
$ nano

Redirection is not supported.
```

**Comment by GuentherVIII** [comment] 2015-08-29 17:44
Does `winpty nano` work?

**Comment by petebachant** [comment] 2015-08-29 17:51
Yep, that works.

**Comment by petebachant** [comment] 2015-08-29 18:56
Update: Nano does open, and I can type text, but the using the arrow keys gives "unknown command".

**Comment by dscho** [comment] 2015-08-30 17:19
If you want to use nano, you most likely have to switch from mintty to the conhost terminal emulator. In other words, you want to reinstall Git for Windows and change the setting of your terminal emulator.

**Comment by dscho** [comment] 2015-08-31 12:57
Okay, to clarify: @petebachant I would appreciate it if you could reinstall your Git, select the "conhost" terminal emulator instead of the "mintty" one while doing so, and then re-test. Your feedback is kinda necessary to move this ticket forward.

**Comment by petebachant** [comment] 2015-08-31 13:12
Using the "conhost" terminal emulator works fine. Happy to provide feedback!

**Comment by dscho** [comment] 2015-08-31 15:07
Okay, thank you. As the issue is really quite a bit far removed from Git (it is about a terminal emulator, designed for Cygwin, ported to MSys2, not working with nano), and as the text in the installer mentions this type of problem, I am closing this ticket.

Feel free to suggest improvements [in the installer](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in) and/or the [FAQ](https://github.com/git-for-windows/git/wiki/FAQ).

**Closed by dscho** 2015-08-31 15:07 UTC
Labels: question
