### ISSUE TITLE
Feature Request: Update mode in the installer

### ISSUE THREAD

**Issue by Shakil-Shahadat** [git-for-windows/git#2394] opened 2019-11-07 08:52 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Every time git updates, I have to go through every options I have set before. This is kind of boring and anti-do-not-repeat-yourself. When the installer detects previous installention, it may offer a update mode which will just update the installetion without changing any setting.

I wish to work on this, but I am not familiar with the code and also not proficient with desktop programming. Still, will give it a try next week.

Thank you.

**Comment by PhilipOakley** [comment] 2019-11-07 10:20
isn't this a duplicate of #2389 see thread to  https://github.com/git-for-windows/git/issues/2389#issuecomment-550987994.

If you could join with those contributors that would be great. I'll close this issue.

**Closed by PhilipOakley** 2019-11-07 10:20 UTC

**Comment by dscho** [comment] 2019-11-08 10:49
I don't think this is _quite_ a duplicate of #2389, but I would like to encourage @Shakil-Shahadat to look over there for hints how to get started, and it would be nice to coordinate with the contributor who already started work on a related feature.
