### ISSUE TITLE
git ask for a dvd in dvd player.

### ISSUE THREAD

**Issue by Chairn** [git-for-windows/git#329] opened 2015-08-28 14:52 UTC
I installed git for windows 2.5.0.windows.1 and it is possible that i opened and remove a DVD while installing git.
And now, everytime i use git in windows command shell, i got this message for every command:
http://i18.servimg.com/u/f18/11/55/83/62/git__d10.png
It just says : "There's no disk in player. Insert a disk in player D:".

**Comment by dscho** [comment] 2015-08-28 15:22
Please note that you can drag & drop images directly, no need to host them elsewhere:
![git__d10](https://cloud.githubusercontent.com/assets/127790/9550009/2d428fbe-4da9-11e5-9c2b-f5e0cd4d5f3d.png)

Now, the most likely explanation might be that your `PATH` environment variable contains a reference to `D:\`... What does

```sh
echo $PATH | tr ':' '\n'
```
say? (Please paste as text, *not* as screenshot)

**Comment by dscho** [comment] 2015-08-28 15:24
Oh, and it could also be the `mtab` or `fstab` files. Could you paste the contents of `/etc/mtab` and `/etc/fstab`, too, please?

**Comment by Chairn** [comment] 2015-08-28 15:39
I think you meant %PATH% ^^:
E:\>echo %PATH% | tr ':' '\n'
C
\Windows\system32;C
\Windows;C
\Windows\system32\wbem;C
\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
\ProgramData\Oracle\Java\javapath;C
\Program Files (x86)\Intel\iCLS Client;C
\Program Files\Intel\iCLS Client;C
\Windows\System32\WindowsPowerShell\v1.0;C
\Program Files\Intel\Intel(R) Management Engine Components\DAL;C
\Program Files\Intel\Intel(R) Management Engine Components\IPT;C
\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C
\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C
\Program Files (x86)\Graphviz2.38\bin;C
\gnuplot\bin;C
\Program Files (x86)\Skype\Phone;C
\Program Files\Oracle\VirtualBox;C
\Python34;C
\MinGW\bin;C
\Program Files (x86)\Git\cmd;C
\Program Files (x86)\MiKTeX 2.9\miktex\bin\;C
\Program Files (x86)\Git\usr\bin;C
\MinGW\bin

There's no D: in it.
I dont understand the /etc/mtab &/fstab, im on windows, not Linux.

**Comment by dscho** [comment] 2015-08-28 16:53
Call Git Bash and you will see `/etc/mtab` and `/etc/fstab`.

**Comment by Chairn** [comment] 2015-08-28 19:10
$ /etc/mtab
bash: /etc/mtab: Bad file descriptor
$ cd /etc/mtab
bash: cd: /etc/mtab: Not a directory

I really dont know what you mean...

**Comment by atrol** [comment] 2015-08-28 19:21
/etc/mtab is a file, not a directory or executable.
```
cat /etc/mtab
cat /etc/fstab
```
is what dscho asked for.

Furthermore you will notice that the original command that has been requested by dscho will work now in Git Bash.

```bash
echo $PATH | tr ':' '\n'
```

**Comment by Chairn** [comment] 2015-08-28 19:35
$ cat /etc/mtab
C:/Program Files/Git / ntfs binary,noacl,auto 1 1
C:/Program Files/Git/usr/bin /bin ntfs binary,noacl,auto 1 1
C:/Users/Valentin/AppData/Local/Temp /tmp ntfs binary,noacl,posix=0 1 1
C: /c ntfs binary,noacl,posix=0,user,noumount,auto 1 1
E: /e ntfs binary,noacl,posix=0,user,noumount,auto 1 1

$ cat /etc/fstab
# For a description of the file format, see the Users Guide
# http://cygwin.com/cygwin-ug-net/using.html#mount-table

# DO NOT REMOVE NEXT LINE. It remove cygdrive prefix from path
none / cygdrive binary,posix=0,noacl,user 0 0
none /tmp usertemp binary,posix=0,noacl 0 0

**Comment by atrol** [comment] 2015-08-28 19:55
Add also the output of

```bash
echo $PATH | tr ':' '\n'
```
to be complete sure that D:  is not in PATH of Git Bash.

**Comment by Chairn** [comment] 2015-08-28 20:44
$ echo $PATH | tr ':' '\n'
/c/Users/Valentin/bin
/mingw64/bin
/usr/local/bin
/usr/bin
/bin
/mingw64/bin
/usr/bin
/c/Windows/system32
/c/Windows
/c/Windows/system32/wbem
/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common
/c/ProgramData/Oracle/Java/javapath
/c/Program Files (x86)/Intel/iCLS Client
/c/Program Files/Intel/iCLS Client
/c/Windows/System32/WindowsPowerShell/v1.0
/c/Program Files/Intel/Intel(R) Management Engine Components/DAL
/c/Program Files/Intel/Intel(R) Management Engine Components/IPT
/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL
/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT
/c/Program Files (x86)/Graphviz2.38/bin
/c/gnuplot/bin
/c/Program Files (x86)/Skype/Phone
/c/Program Files/Oracle/VirtualBox
/c/Python34
/c/MinGW/bin
/c/Program Files (x86)/MiKTeX 2.9/miktex/bin
/cmd
/c/MinGW/bin
/c/Users/Valentin/AppData/Local/Code/bin
/usr/bin/vendor_perl
/usr/bin/core_perl

Its not in.

**Comment by dscho** [comment] 2015-08-30 17:08
Does the message box also appear when you call `git status` in the Git Bash? Does it really appear with every command, or does `echo 123` work without problems (or for that matter, `git var -l`)? What does `ps -W` in Git Bash show while the message box is shown?

**Comment by Chairn** [comment] 2015-08-30 19:39
No, the message box was only appearing in windows command shell, not git bash(which works perfectly fine, but no scrolling :().
It didnt appear with every command. Okay, i think i can reproduce it now.
I started my computer, and git was working fine. I inserted dvd, and then removed it, now the message shows up again.
Here is what ps -W gives:
http://pastebin.com/eHGhcpg8

git status pops up the message only if its a git repository.

**Comment by dscho** [comment] 2015-08-31 08:34
> git status pops up the message only if its a git repository.
> Other commands that pops up the message:
> git
> git commit
> git push(pops up twice, once after i press enter, second after i entered my pw).
> git checkout

Please set your environment variable `GIT_TRACE=1` and then trigger the message box. The console should print the most recently launched Git command (which I suspect to lead us to the root cause).

**Comment by odegroot** [comment] 2015-09-01 08:08
I have the same problem. When I'm at work, everything works fine. At home, I get this popup each time I refresh Git Gui or gitk (which is often). Git Bash does not have this problem. This started after upgrading to Git for Windows 2.5.0. Git for Windows 2.5.1 is also affected.

![image](https://cloud.githubusercontent.com/assets/807291/9598579/23dc3934-508d-11e5-954a-6646038601f3.png)

I've figured out that D: is one the memory card slots in my monitor at home, which explains why the problem depends on where I am.

![image](https://cloud.githubusercontent.com/assets/807291/9598618/677b661a-508d-11e5-942f-3c5849def5c0.png)

When I re-assign that drive to something else, say H:, then the problem disappears. So for some reason, git tries to access drive D:, but *not* drives E:/F:/G:/H:. I cannot figure out *why* git tries to access drive D:.

Using process explorer, I figured out that the git-process that gets launched by Git Gui is launched the following PATH (newlines inserted for easier reading).

```
C:/Program Files/Git/mingw64/libexec/git-core
C:/Program Files/Git/mingw64/bin\
C:/Program Files/Git/mingw64/mingw/bin
C:\Program Files\Git\mingw64\bin
C:\Program Files\Git\usr\bin
C:\ProgramData\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\Users\oscar.degroot\.dnx\bin
C:\Program Files\Microsoft DNX\Dnvm\
C:\Program Files (x86)\Skype\Phone\
C:\Program Files\TortoiseGit\bin
C:\Program Files\Microsoft\Web Platform Installer\
C:\Program Files\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\
C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\
C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\
C:\Program Files\Microsoft SQL Server\120\DTS\Binn\
```

Using this PATH, I was able to reproduce the problem in a fresh `cmd.exe` shell.

```
oscar.degroot@LT3932 C:\Users\oscar.degroot
> git
'git' is not recognized as an internal or external command,
operable program or batch file.

oscar.degroot@LT3932 C:\Users\oscar.degroot
> set PATH=C:/Program Files/Git/mingw64/libexec/git-core;C:/Program Files/Git/mingw64/bin\;C:/Program Files/Git/mingw64/mingw/bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Syst
em32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Users\oscar.degroot\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL
Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\
120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\

oscar.degroot@LT3932 C:\Users\oscar.degroot
> git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

(Dialog pops up here. Output continues after closing it.)

These are common Git commands used in various situations:
(...)
```

With some trial and error, I came up with this minimal setup that reproduces the problem. (This directory is *not* a git repo.)

```
oscar.degroot@LT3932 C:\Users\oscar.degroot
> set PATH=C:/Program Files/Git/mingw64/bin

oscar.degroot@LT3932 C:\Users\oscar.degroot
> git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

(Dialog pops up here. Output continues after closing it.)

These are common Git commands used in various situations:
(...)
```

I have tried getting more info using `GIT_TRACE=1`, but setting it doesn't seem to do anything.

```
oscar.degroot@LT3932 C:\Users\oscar.degroot
> set GIT_TRACE=1

oscar.degroot@LT3932 C:\Users\oscar.degroot
> git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

(Dialog pops up here. Output continues after closing it.)

These are common Git commands used in various situations:
(...)
```

I'm stuck at this point. Any ideas?

**Comment by dscho** [comment] 2015-09-01 08:15
The best idea would be to rebuild Git via the [SDK](http://git-for-windows.github.io/#download-sdk) after removing the `-O2` flag from the `Makefile`'s `CFLAGS` and then run `git.exe` in `gdb`.

However, this will take some time to set up and it will also download quite a bit of data. @odegroot do you have a chance to do that? If so, I'll try my best to walk you through the process.

**Comment by odegroot** [comment] 2015-09-01 08:23
> @odegroot do you have a chance to do that?

Not really, no. Maybe there's someone that already has a developer setup and is not using their D: drive? If they assign a removable drive to their D: drive and make sure that no media is inserted, then they should be able to reproduce the problem. DVD drive, cardreader, virtual DVD drive, any kind of removable drive should be ok.

**Comment by kgybels** [comment] 2015-09-08 14:57
Using Sysinternals' Process Monitor, I see this when just running git:

    16:42:44.3813086	git.exe	16128	CreateFile	D:\develop\msys64\mingw64\share\locale\locale.alias	PATH NOT FOUND	Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, AllocationSize: n/a

Seems something is trying to open `D:\develop\msys64\mingw64\share\locale\locale.alias`

Stack as shown in Process Monitor:

    0	fltmgr.sys	FltAcquirePushLockShared + 0x907	0xfffff88001037067	C:\Windows\system32\drivers\fltmgr.sys
    1	fltmgr.sys	FltIsCallbackDataDirty + 0x20ba	0xfffff880010399aa	C:\Windows\system32\drivers\fltmgr.sys
    2	fltmgr.sys	FltReadFile + 0x10363	0xfffff880010572a3	C:\Windows\system32\drivers\fltmgr.sys
    3	ntoskrnl.exe	MmCreateSection + 0x283b	0xfffff80003182b9b	C:\Windows\system32\ntoskrnl.exe
    4	ntoskrnl.exe	SeQueryInformationToken + 0xe3e	0xfffff8000317ebae	C:\Windows\system32\ntoskrnl.exe
    5	ntoskrnl.exe	ObOpenObjectByName + 0x306	0xfffff8000317f696	C:\Windows\system32\ntoskrnl.exe
    6	ntoskrnl.exe	MmCreateSection + 0xc3c	0xfffff80003180f9c	C:\Windows\system32\ntoskrnl.exe
    7	ntoskrnl.exe	NtCreateFile + 0x78	0xfffff8000318c5c8	C:\Windows\system32\ntoskrnl.exe
    8	ntoskrnl.exe	KeSynchronizeExecution + 0x3a23	0xfffff80002e82853	C:\Windows\system32\ntoskrnl.exe
    9	ntdll.dll	ZwCreateFile + 0xa	0x76e8df0a	C:\Windows\System32\ntdll.dll
    10	KernelBase.dll	CreateFileW + 0x2b6	0x7fefce24f66	C:\Windows\System32\KernelBase.dll
    11	kernel32.dll	CreateFileA + 0xb6	0x76d41ca6	C:\Windows\System32\kernel32.dll
    12	msvcrt.dll	sopen_s + 0x275	0x7fefd0987cd	C:\Windows\System32\msvcrt.dll
    13	msvcrt.dll	sopen_s + 0x9d	0x7fefd0985f5	C:\Windows\System32\msvcrt.dll
    14	msvcrt.dll	sopen_s + 0x2d	0x7fefd098585	C:\Windows\System32\msvcrt.dll
    15	msvcrt.dll	fsopen + 0x177	0x7fefd098513	C:\Windows\System32\msvcrt.dll
    16	msvcrt.dll	fsopen + 0x82	0x7fefd09841e	C:\Windows\System32\msvcrt.dll
    17	libintl-8.dll	libintl-8.dll + 0x2fc2	0x61cc2fc2	C:\Program Files\Git\mingw64\bin\libintl-8.dll
    18	libintl-8.dll	libintl-8.dll + 0x3411	0x61cc3411	C:\Program Files\Git\mingw64\bin\libintl-8.dll
    19	libintl-8.dll	libintl-8.dll + 0x1aa8	0x61cc1aa8	C:\Program Files\Git\mingw64\bin\libintl-8.dll
    20	libintl-8.dll	libintl-8.dll + 0x4cb7	0x61cc4cb7	C:\Program Files\Git\mingw64\bin\libintl-8.dll
    21	libintl-8.dll	libintl-8.dll + 0x193c	0x61cc193c	C:\Program Files\Git\mingw64\bin\libintl-8.dll
    22	git.exe	git.exe + 0xdd5f4	0x4dd5f4	C:\Program Files\Git\mingw64\bin\git.exe
    23	git.exe	git.exe + 0x11e50f	0x51e50f	C:\Program Files\Git\mingw64\bin\git.exe
    24	git.exe	git.exe + 0x994e1	0x4994e1	C:\Program Files\Git\mingw64\bin\git.exe
    25	git.exe	git.exe + 0x9a4d2	0x49a4d2	C:\Program Files\Git\mingw64\bin\git.exe
    26	git.exe	git.exe + 0x125135	0x525135	C:\Program Files\Git\mingw64\bin\git.exe
    27	git.exe	git.exe + 0x126b77	0x526b77	C:\Program Files\Git\mingw64\bin\git.exe
    28	git.exe	git.exe + 0x213db	0x4213db	C:\Program Files\Git\mingw64\bin\git.exe
    29	git.exe	git.exe + 0x1f45	0x401f45	C:\Program Files\Git\mingw64\bin\git.exe
    30	git.exe	git.exe + 0x1521d2	0x5521d2	C:\Program Files\Git\mingw64\bin\git.exe
    31	git.exe	git.exe + 0x13ed	0x4013ed	C:\Program Files\Git\mingw64\bin\git.exe
    32	git.exe	git.exe + 0x152b	0x40152b	C:\Program Files\Git\mingw64\bin\git.exe
    33	kernel32.dll	BaseThreadInitThunk + 0xd	0x76d35a4d	C:\Windows\System32\kernel32.dll
    34	ntdll.dll	RtlUserThreadStart + 0x21	0x76e6b831	C:\Windows\System32\ntdll.dll

**Comment by dscho** [comment] 2015-09-08 16:05
@kgybels this is an excellent analysis, and an excellent hint:

```sh
$ strings /mingw64/bin/libintl-8.dll |grep develop
D:/develop/msys64/mingw64/share/locale
D:/develop/msys64/mingw64/share/locale
```

So it would seem that there is a hard-coded path in `libintl-8.dll`.

**Comment by dscho** [comment] 2015-09-08 16:11
```sh
$ pacman -Qo /mingw64/bin/libintl-8.dll
/mingw64/bin/libintl-8.dll is owned by mingw-w64-x86_64-gettext 0.19.5.1-1
```

The package definition is here: https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gettext/PKGBUILD

It can be rebuilt using

```sh
$ cd /usr/src/MINGW-packages
$ git pull
$ git checkout master
$ cd mingw-w64-gettext
$ makepkg-mingw -s
```

See also our wiki: https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages

**Comment by Chairn** [comment] 2015-09-09 19:12
I got makepkg-mingw command not found :( in git bash.

**Comment by kgybels** [comment] 2015-09-09 22:51
@Chairn You have to use the [SDK](http://git-for-windows.github.io/#download-sdk).

@dscho I have followed your instructions to rebuild the mingw-w64-gettext package, however, it seems the problem is not present in my local build:

    Kim@KIM-PC MINGW64 /usr/src/MINGW-packages/mingw-w64-gettext (master)
    $ strings ./pkg/mingw-w64-x86_64-gettext/mingw64/bin/libintl-8.dll | grep share/locale
    /mingw64/share/locale
    /mingw64/share/locale
    
    $ strings /c/Program\ Files/Git/mingw64/bin/libintl-8.dll | grep share/locale
    D:/develop/msys64/mingw64/share/locale
    D:/develop/msys64/mingw64/share/locale

Maybe the problem is not with the package itself, but with how it was build? If I have more time, I will take a closer look at how the build works.

**Comment by dscho** [comment] 2015-09-10 06:59
Thank you for the analysis. Did you save the output of the build (I also built `mingw-w64-gettext` in the background while working on other bugs, but I did not think of redirecting the output via `| tee build.log` :frowning:). I would imagine that some `-DBLIBLAHBLOOB=\"/mingw64/share/locale\"` flag is passed to the C compiler. Come to think of it, a `find src/gettext-* -type f -exec grep -l /mingw64/share/locale {} \;` might find the file(s) (most like a `Makefile` and/or `config.h`) that contain that hard-coded path.

> Maybe the problem is not with the package itself, but with how it was build?

Yes, it looks like that. If so, with a little bit more information we should be able to convince the MSys2 people to rebuild `mingw-w64-gettext` with the proper setting.

Maybe even by opening a Pull Request that modifies `mingw-w64-gettext/PKGBUILD` in such a way that it detects the problem and aborts the build?

**Comment by dscho** [comment] 2015-09-10 10:02
So it seems as if the `LOCALEDIR` constant is `#define`d in several `configmake.h` files (and I was wrong, those files do not live in `src/gettext-*/**/*`, but instead in `src/build-*/**/*`). According to `configure:795`, the `LOCALEDIR` value is `${datarootdir}/locale`, and according to `configure:781`, `datarootdir='${prefix}/share'`. Since the prefix is [defined explicitly as `/mingw64/`](https://github.com/Alexpux/MINGW-packages/blob/ee0cfb3366218cd8df53c09623150da55453cb3f/mingw-w64-gettext/PKGBUILD#L64), it *should* work correctly.

And indeed, it works correctly, for both of us.

I had the idea that maybe our MSys2 runtime that mangles POSIX paths differently might be at fault (it should not, because the POSIX-to-Windows mangling does not happen when running any MSys2 executable, such as `bash.exe` which executes that `configure` script). And indeed, building in an MSys2 build environment (i.e. *not* the Git for Windows SDK) still seems to Work Just Fine...

**Comment by dscho** [comment] 2015-09-10 10:29
Okay, I take that one back... It looks as if the `libintl-8.dll` built with regular MSys2 *does* have that hard-coded path.

**Comment by dscho** [comment] 2015-09-10 19:58
See https://github.com/git-for-windows/MINGW-packages/releases/tag/temporary-gettext-release for temporary packages (until upstream releases fixed ones).

**Closed by dscho** 2015-09-10 19:58 UTC
Labels: bug, sdk-packages

**Comment by dscho** [comment] 2015-09-16 12:36
I just verified that the version 0.19.6-1 of the mingw-w64-x86_64-gettext passes the `strings /mingw64/bin/libintl-8.dll | grep /share/` test: no DOS drives recorded. (I hoped that somebody here would care as much about this issue as I do...)
