### ISSUE TITLE
Vimdiff Mergetool Regressed Between 2.36.1.windows.1 and 2.37.0.windows.1

### ISSUE THREAD

**Issue by bambams** [git-for-windows/git#3945] opened 2022-07-11 20:32 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.0.windows.1
cpu: x86_64
built from commit: 989c3a6832b035f6124b0a23da9c0f8f18afa550
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1766]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that come to mind.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git mergetool
```
 - What did you expect to occur after running these commands?

vim opens in diff mode with 4 buffers open in the default arrangement with the correct files open in each buffer.

 - What actually happened instead?

vim opens in diff mode with 7 buffers open. Paths with spaces in them are split into multiple buffers instead of opening the singular file per path, and so all of the buffers are empty because they refer to the wrong files.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

I downgraded to git version 2.36.1.windows.1 as described below and the issue went away. I also tried 2.37.0.rc0.windows.1, 2.37.0.rc1.windows.1, and 2.37.0.rc2.windows.1, but none of them worked either.

```
$ git --version --build-options

git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled```

**Comment by rimrul** [comment] 2022-07-12 04:24
This sounds like 0041797449da61f4131bb1673fa5d4c3af48240d could be the culprit

**Comment by rimrul** [comment] 2022-07-12 04:30
At a glance that looks like it still quotes all the  filename arguments to vim correctly.

**Comment by dscho** [comment] 2022-07-12 09:46
@bambams could you please re-run after setting the environment variable `GIT_TRACE=1`, and paste the output verbatim? (If you are not able to divulge the exact file names, please do work on an [MCVE](https://stackoverflow.com/help/mcve).)

**Comment by dscho** [comment] 2022-07-12 09:48
> At a glance that looks like it still quotes all the filename arguments to vim correctly.

I fear that is not quite correct. Note the `eval` in https://github.com/git-for-windows/git/commit/0041797449da61f4131bb1673fa5d4c3af48240d#diff-bea8946dbd4d91f9de41e06b22d641c3bc1458891815f90b3796fe8b11d8a849R398-R399:

```sh
	eval "$merge_tool_path" \
			-f "$FINAL_CMD" "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
```

At a first glance, it all looks quoted, right? But that's quoting it for the `eval` invocation, not for the invocation of the actual merge tool.

**Comment by rimrul** [comment] 2022-07-12 10:43
> ```sh
> 	eval "$merge_tool_path" \
> 			-f "$FINAL_CMD" "$LOCAL" "$BASE" "$REMOTE" "$MERGED"
> ```
> 
> At a first glance, it all looks quoted, right? But that's quoting it for the `eval` invocation, not for the invocation of the actual merge tool.

Good catch.

**Comment by dscho** [comment] 2022-07-12 12:45
@bambams to find out whether our suspicion is correct, would you mind editing (as administrator) `C:\Program Files\git\mingw64\libexec\git-core\mergetools\vimdiff` by finding those two quoted lines and prefixing every double-quote character with a backslash, like so:

```
	eval \"$merge_tool_path\" \
			-f \"$FINAL_CMD\" \"$LOCAL\" \"$BASE\" \"$REMOTE\" \"$MERGED\"
```

and then running your `git mergetool` reproducer again?

**Comment by bambams** [comment] 2022-07-12 15:16
create-merge-failure.cmd is a cmd command script that creates a demo repo to reproduce the issue in. It tracks a single file with a space in the file's name and attempts to merge conflicting branches for that file.

[create-merge-failure.cmd.txt](https://github.com/git-for-windows/git/files/9094025/create-merge-failure.cmd.txt)

This is the output I was able to capture from `GIT_TRACE=1 git mergetool` (in Git Bash, because the issue is reproducible in both shells):

[git-mergetool-trace.txt](https://github.com/git-for-windows/git/files/9094142/git-mergetool-trace.txt)

The shell prompt was overwritten in the scrollback so I'm not certain that's everything. Redirecting the output seemed to anger the command (perhaps because part of the output becomes Vim's UI?).

I tried escaping the quotes in the two eval commands of the vimdiff script, but it does not work either.

[vimdiff.patch.txt](https://github.com/git-for-windows/git/files/9093968/vimdiff.patch.txt)

[git-mergetool-trace-after-edit.txt](https://github.com/git-for-windows/git/files/9094245/git-mergetool-trace-after-edit.txt)

**Comment by landstander668** [comment] 2022-07-12 16:25
@dscho I could be wrong, but wouldn't this require quoting doubling up the quoting (once for the execution, and once for the `eval`? Like:
````
eval "\"$merge_tool_path\"" \
			-f "\"$FINAL_CMD\"" "\"$LOCAL\"" "\"$BASE\"" "\"$REMOTE\"" "\"$MERGED\""

**Closed** 2022-07-22 23:25 UTC
Labels: bug, git-upstream
