### ISSUE TITLE
cd-ing into "//" is possible

### ISSUE THREAD

**Issue by smulhall1337** [git-for-windows/git#3340] opened 2021-07-30 14:35 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

Git for Windows v2.29.2(2) 

```
$ git --version --build-options

git version 2.29.2.windows.2
cpu: x86_64
built from commit: 3464b98ce6803c98bf8fb34390cd150d66e4a0d3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

10 Pro

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19042.1110]**
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Microsoft Windows [Version 10.0.19042.1110]

```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

```git bash``` 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
cd //
```
 - What did you expect to occur after running these commands?

```Wanted to see what / was for git bash but hit another / ```

 - What actually happened instead?

``ended up in the '//' directory

I dont know if this is actually an issue. If you 'ls' in '//' you just get a permission issue. I dont think you can do much in this directory but its just weird that its possible ``

**Comment by rimrul** [comment] 2021-07-31 04:50
That `cd //` is possible is [intended behaviour](https://stackoverflow.com/a/20690872) of bash, but the error shouldn't happen.

**Comment by dscho** [comment] 2021-08-02 11:40
> the error shouldn't happen.

This also happens in [MSYS2](https://msys2.github/io/), though. Therefore I think this is an upstream issue. However, before reporting it upstream, I think the original poster might want to research a bit more what the intended behavior should be.

**Comment by dscho** [comment] 2023-08-29 12:57
Closing as an upstream MSYS2 behavior.

**Closed by dscho** 2023-08-29 12:57 UTC
Labels: msys2
