### ISSUE TITLE
Git-2.7.0-64-bit cant work on Windows10 Pro Insider Preview Build 14251.rs1

### ISSUE THREAD

**Issue by NateLing** [git-for-windows/git#632] opened 2016-01-29 03:53 UTC
Git-2.7.0-64-bit cant work on Windows10 Pro Insider Preview Build 14251.rs1,I cant do anything about git,cant commit,cant push,cant clone...

**Comment by linquize** [comment] 2016-01-29 05:30
What is the error message?

**Comment by NateLing** [comment] 2016-01-29 05:43
@linquize Running git from CMD results in a "Git for Windows has stopped working" message.

**Comment by phpfaber** [comment] 2016-01-29 05:53
Same here..

**Comment by shiftkey** [comment] 2016-01-29 06:14
Duplicate of #627

**Comment by tvatavuk** [comment] 2016-01-29 06:15
and here...

Windows Event Log
---

Fault bucket 120399744865, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: git.exe
P2: 2.7.0.0
P3: 00000000
P4: ntdll.dll
P5: 10.0.14251.1000
P6: 56a54488
P7: c0000005
P8: 00000000000a6eeb
P9: 
P10: 

Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0x38cc
Faulting application start time: 0x01d15a5b765ce8ee
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: ea504009-242f-49e8-86c1-955e79dd9894
Faulting package full name: 
Faulting package-relative application ID: 


Visual Studio Debugger
---

An unhandled win32 exception occurrered in git.exe [14540].

Unhandled exception at 0x00007FFB2FF06EEB (ntdll.dll) in git.exe: 0xC0000005: Access violation writing location 0x00000000005BC520.

Exception thrown at 0x00007FFB2FF06EEB (ntdll.dll) in git.exe: 0xC0000005: Access violation writing location 0x00000000005BC520.

**Comment by dscho** [comment] 2016-01-29 06:38
Please, people, realize that opening duplicate tickets distracts the developers who can tackle the issues from actually tackling those issues!

**Closed by dscho** 2016-01-29 06:38 UTC

**Comment by sc0ttwad3** [comment] 2016-01-31 23:06
@dscho -- I'm not seeing any duplicate tickets, and not sure why this issue has been closed, since it is still a problem with git-2.7.0-64-bit...

Any and every attempt to run git.exe fails with the same message (below) and this only started with the release/upgrade to Windows 10 Pro Insider build 14251.rs1_release.160124-1059.

    Unhandled exception at 0x00007FF8B0966EEB (ntdll.dll) in git.exe: 0xC0000005: Access violation writing location 0x00000000005BC520.

If this actually addressed somewhere else, I apologize, but this is the only place I see the issue reported at all, and no updated info.

**Comment by shiftkey** [comment] 2016-01-31 23:12
@sc0ttwad3 please refer to the last few comments here https://github.com/git-for-windows/git/issues/627#issuecomment-177193591

**Comment by dscho** [comment] 2016-02-01 07:40
@sc0ttwad3 Indeed, @shiftkey [clarified three days ago](https://github.com/git-for-windows/git/issues/632#issuecomment-176595748) that #627 is the first ticket describing the problem. In the meantime, it also describes the solution: upgrade to internal build 14253 or later. I even tested this myself and verified that at least 14256 fixed the problem. The ticket to which @shiftkey referred you also contains two helpful links to Twitter statements by the project manager handling the internal builds where you can see that your claim gently refuted that "it is still a problem with git-2.7.0-64-bit...": It was a memory management bug in the internal Windows build all along.

**Comment by sc0ttwad3** [comment] 2016-02-02 04:53
Thank you very much for the clarification...  Also, just announced today directly from Microsoft in the Insiders Hub... the following *Known issues for PC flight 14251*:

Due to a recent memory management change, you may see periodic app crashes or other memory related app errors. Rebooting your PC may correct the issue. Due to this issue, **the Github client will not launch. If you need to use the Github client – the workaround is to rollback to the previous build**

...to which I'll now add upgrading to at least 14256 as another alternative.

Thx.
