### ISSUE TITLE
Unwanted stdout output from fsmonitor-daemon

### ISSUE THREAD

**Issue by Shauren** [git-for-windows/git#3383] opened 2021-08-22 10:42 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.1
cpu: x86_64
built from commit: fb59c1de9fd599a3eeb8459eb7cab731c6672ea3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```
 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: master
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmake-gui

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Running this in cmake script
```
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" describe --long --match init --dirty=+ --abbrev=12
      WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
      OUTPUT_VARIABLE rev_info
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET
    )
```
 - What did you expect to occur after running these commands?

`init-34785-g4fa639fc7ead` to be printed to stdout

 - What actually happened instead?

This was printed
```
starting fsmonitor-daemon in 'C:/Users/shaur/Desktop/Sources/TrinityCore'
init-34785-g4fa639fc7ead
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

n/a

**Comment by dscho** [comment] 2021-08-23 09:54
> starting fsmonitor-daemon in 'C:/Users/shaur/Desktop/Sources/TrinityCore'
> init-34785-g4fa639fc7ead

@jeffhostetler I think this should go to `stderr`. What do you think?

**Comment by dscho** [comment] 2021-08-28 07:02
Not that this question is relevant, but no: I did read the message and was glad to understand _why `git status` was still slow this time_.

You see, when `git status` refreshes the index and auto-starts the FSMonitor, it still has to enumerate all the entities in the worktree. Only the next time can Git benefit from the information the FSMonitor provides.

So maybe you now understand why the message is useful: it helps in situations where users enabled FSMonitor and would otherwise be puzzled about slow performance.

**Comment by jeffhostetler** [comment] 2021-08-30 14:18
Would it be better to print the `starting fsmonitor-daemon in <dir>` message on stderr than on stdout ??

We could add a `--quiet` arg to `git fsmonitor--daemon` so that implicit starts (from say, `git status`) would not print unexpected output.  Would that help??

**Comment by SetTrend** [comment] 2021-08-30 14:39
> We could add a `--quiet` arg to `git fsmonitor--daemon` so that implicit starts (from say, `git status`) would not print unexpected output. Would that help??

Sounds very good to me.

Would it make sense to add an option to git config, so people interested in the output could add a corresponding config key to have this string output (end vice versa)
.

**Comment by jeffhostetler** [comment] 2021-08-30 17:26
I've added a --quiet option to my dev build.  Subsequent releases will use this to avoid altering expected output.
Thanks for the report.

**Comment by jeffhostetler** [comment] 2021-08-30 17:31
Also, since the output is suppressed during implicit launches, we should only see it during explicit daemon launches, so it makes sense to let the daemon print the message on stdout.

**Comment by dscho** [comment] 2021-08-30 18:13
> the output is suppressed during implicit launches

To me, that reduces the usability...

**Comment by derrickstolee** [comment] 2021-08-30 19:48
> > the output is suppressed during implicit launches
> 
> To me, that reduces the usability...

I think your perspective is biased because you are an expert. You notice that something is slow and want feedback why. A message about this "fsmonitor" thing getting started is helpful to you.

I think this message is complete noise to a normal user who _might_ notice that things are slow but then shrugs it off when later commands are faster. Better to reduce the noise here, I think.

**Comment by Shauren** [comment] 2021-08-30 20:23
> 
> 
> > > the output is suppressed during implicit launches
> > 
> > 
> > To me, that reduces the usability...
> 
> I think your perspective is biased because you are an expert. You notice that something is slow and want feedback why. A message about this "fsmonitor" thing getting started is helpful to you.
> 
> I think this message is complete noise to a normal user who _might_ notice that things are slow but then shrugs it off when later commands are faster. Better to reduce the noise here, I think.

Worse than noise. This breaks scripts relying on output being formatted in a certain way. I am not familiar with how fsmonitor is implicitly started but having to possibly guard every single git execution with "did it print fsmonitor message to stdout" makes it unusable - and I can't go tell every one of my users to disable fsmonitor on their end

**Comment by dscho** [comment] 2021-08-30 22:54
> I think your perspective is biased because you are an expert.

Fair!

**Comment by rimrul** [comment] 2021-08-31 02:53
> This breaks scripts relying on output being formatted in a certain way.

Even with this specific change being removed, `git describe` is clearly documented as porcelain an [the documentation clearly says](https://git-scm.com/docs/git#_low_level_commands_plumbing)

> The interface to Porcelain commands on the other hand are subject to change

So relying on the exact output of porcelain commands for scripted use isn't exactly ideal.

**Comment by Shauren** [comment] 2021-08-31 09:54
> 
> 
> > This breaks scripts relying on output being formatted in a certain way.
> 
> Even with this specific change being removed, `git describe` is clearly documented as porcelain and [the documentation clearly says](https://git-scm.com/docs/git#_low_level_commands_plumbing)
> 
> > The interface to Porcelain commands on the other hand are subject to change
> 
> So relying on the exact output of porcelain commands for scripted use isn't exactly ideal.

Thank you for this information, I replaced my use of `git describe` with `git rev-parse` and `git diff-index`

**Comment by vermiculus** [comment] 2021-09-01 13:42
Another option for turning this on conditionally is respecting `GIT_TRACE`. See [these docs](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables).

**Comment by AMPivovarov** [comment] 2021-09-16 16:11
Discussion is finished, but I'd like to point out, that the problem is not limited to the 'less stable' porcelain commands:
```
$ git cat-file -p -- :README.md | head -n 2
starting fsmonitor-daemon in 'C:/work/misc/git'
[![Build status](https://github.com/git/git/workflows/CI/PR/badge.svg)](https://github.com/git/git/actions?query=branch%3Amaster+event%3Apush)
```

Another observation:
```
$ git cat-file -p -- :README.md | head -n 1
starting fsmonitor-daemon in 'C:/work/misc/git'
fatal: unable to stream eb8115e6b04814f0c37146bbe3dbc35f3e8992e0 to stdout
```

**Comment by jeffhostetler** [comment] 2021-09-16 16:38
Sorry for the inconvenience.  My next version will not print this message.

You can turn off FSMonitor by setting `core.useBuiltinFSMonitor` and `feature.experimental` to false.

**Comment by dscho** [comment] 2021-10-04 12:32
FWIW the newest [snapshot](https://wingit.blob.core.windows.net/files/index.html) has the latest FSMonitor.

**Comment by dscho** [comment] 2021-10-05 11:53
> 
> 
> FWIW the newest [snapshot](https://wingit.blob.core.windows.net/files/index.html) has the latest FSMonitor.

Please test. I will close this ticket preemptively.

**Closed by dscho** 2021-10-05 11:53 UTC
Labels: git
