### ISSUE TITLE
Uninstalling does not remove Explorer/Shell extensions

### ISSUE THREAD

**Issue by Jan-Bruun-Andersen** [git-for-windows/git#553] opened 2015-12-01 13:34 UTC
As a new Git user (and old TortoiseSVN user) I installed TortoiseGit and then Git for Windows v. 2.3.3 (64 bit). And added a couple of Git packages to my Cygwin installation. It worked well. I even got TortoiseGit to work with my PuTTY/Pageant setup and my SSH-key. Encouraged by that success, I started to wonder if I really needed Git for Windows at all? I had all the Bash'ism I wanted in my Cygwin installation (and I also have a MinGW/MSYS install up and running). So I went ahead and uninstalled Git for Windows using the normal Windows 10 Pro (64-bit) Add/Remove Programs control panel.

But the "Git GUI Here" and "Git Bash Here" Explorer/Shell extensions remains after the uninstall. I tried installing again, this time with the choices for Windows Explorer unchecked, hoping that it might  somehow remove them. No luck. Running the installer again and unchecking on top of the already installed Git for Windows, just told that the Explorer was already installed and would not be removed.

Is this a bug? A feature? Do I have to enter into the darkness of RegEdit and manually remove them?

**Comment by Jan-Bruun-Andersen** [comment] 2015-12-01 22:45
Seems like these keys are not being cleared during uninstall:


[HKEY_CURRENT_USER\Software\Classes\Directory\shell\git_shell]
@="Git Ba&sh Here"

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\git_shell\command]
@="\"C:\\Users\\jabba\\AppData\\Local\\Programs\\Git\\git-bash.exe\" \"--cd=%1\""

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\git_shell]
@="Git Ba&sh Here"

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\git_shell\command]
@="\"C:\\Users\\jabba\\AppData\\Local\\Programs\\Git\\git-bash.exe\" \"--cd=%v.\""

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\git_gui]
@="Git &GUI Here"

[HKEY_CURRENT_USER\Software\Classes\Directory\shell\git_gui\command]
@="\"C:\\Users\\jabba\\AppData\\Local\\Programs\\Git\\cmd\\git-gui.exe\" \"--working-dir\" \"%1\""

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\git_gui]
@="Git &GUI Here"

[HKEY_CURRENT_USER\Software\Classes\Directory\Background\shell\git_gui\command]
@="\"C:\\Users\\jabba\\AppData\\Local\\Programs\\Git\\cmd\\git-gui.exe\" \"--working-dir\" \"%v.\""

**Comment by dscho** [comment] 2015-12-02 12:13
@Jan-Bruun-Andersen thank you for your report. I will try to find time to reproduce this. In the meantime, could you have a look at https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss and see whether any obvious bug sticks out to you?

**Comment by Jan-Bruun-Andersen** [comment] 2015-12-05 00:43
A guess would be an issue with who is running the uninstaller. In particular this piece of logic in DeleteContextMenuEntries:

    if IsAdminLoggedOn then begin
        RootKey:=HKEY_LOCAL_MACHINE;
    end else begin
        RootKey:=HKEY_CURRENT_USER;
    end;

Notice that my stuck keys were all in HKCU. It could be that when the uninstaller is launched using the standard Windows control panel (appwiz.cpl) it actually runs under some System/Admin account while the Git installer is simply run using my own account WITH Admin privileges. So the uninstaller will blindly try to delete keys under HKLM and ignores my keys.

**Comment by dscho** [comment] 2015-12-07 11:29
Good point. So we need to record what root key we installed in and not rely on the IsAdminLoggedOn function at uninstall time.

But that would not solve your problem because the uninstaller of a previous cannot be fixed in hindsight... Any idea how to go about it?

**Comment by Jan-Bruun-Andersen** [comment] 2015-12-07 17:42
I know that some installers simply asks "Should this be installed for all users, or just for you?". I guess the answer is then used to determine where to create such keys. 

As for how to retro-actively fix orphaned keys, how about checking if they have valid values (point to existing or non-existing files)? If the EXE is not on the disk, then ask(?) for permission to clean them up?

What I did was to download and install a neat, free utility: Wise Registry Cleaner. It found those keys and a whole bunch of other crap in the registry,

**Comment by dscho** [comment] 2015-12-07 18:59
> As for how to retro-actively fix orphaned keys, how about checking if they have valid values (point to existing or non-existing files)? If the EXE is not on the disk, then ask(?) for permission to clean them up?

That sounds like a valid strategy. Are you up to the task to implement it?

**Comment by Jan-Bruun-Andersen** [comment] 2015-12-08 04:47
I guess... But don't hold your breath. What programming language are we talking about? Is there a description somewhere on how to setup a development environment? Can I use my existing 32-bit MinGW/MSYS environment or do I have to install the 64-bit versions? Will Cygwin do?

**Comment by Jan-Bruun-Andersen** [comment] 2015-12-08 04:49
Seems like the instructions for getting started is here: https://github.com/git-for-windows/git/wiki/Building-Git

Looks promising.

**Comment by dscho** [comment] 2015-12-08 16:56
Yep, and also https://github.com/git-for-windows/git/wiki/Making-an-installer. The definition of the InnoSetup-based installer is in https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss (which will be in `/usr/src/build-extra/installer` once you cloned `build-extra`).

**Comment by glen-84** [comment] 2015-12-21 15:03
I have the same issue.

**Comment by dscho** [comment] 2015-12-23 08:34
> I have the same issue.

Please don't. This is not helping resolve the issue in any way. If you can help, please, by all means, do so, but do understand that useful information can be drowned out *very* easily in "me, too" comments. Which would be a shame, because that makes it *less* likely that your issue gets addressed, and that's the opposite of what we want.

**Comment by glen-84** [comment] 2015-12-23 09:07
@dscho I'm sorry, but I was going absolutely crazy yesterday trying to figure out what was going on, and that is all I had left.

I've had all sorts of weirdness with this installer. At one stage it was installing to `C:\Users\{username}\AppData\Local\Programs`, and then the latest version moved back to `C:\Program Files`, so I had to update a whole bunch of software to fix all the paths again.

Perhaps it installed there due to a lack of admin permissions for whatever reason, and that's why the latest-version installer didn't update those registry keys.

Maybe it should just delete from both HKLM *and* HKCU when `IsAdminLoggedOn` in case the installer was once run without sufficient privileges. Either that, or you'd need to somehow ensure that the installer and uninstaller are always run by an administrator.

**Comment by dscho** [comment] 2015-12-23 19:32
> Maybe it should just delete from both HKLM and HKCU when IsAdminLoggedOn in case the installer was once run without sufficient privileges

I would welcome a Pull Request to make it so. Thanks!

**Comment by dscho** [comment] 2016-01-03 15:21
*sigh*. That +1 indeed managed to let me overlook the real state of this ticket. As I said, +1s are bad ideas.

Back to @Jan-Bruun-Andersen's questions.

> What programming language are we talking about?

It is a Pascal dialect used by InnoSetup. The file containing most of the code is [`install.iss`](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss).

> Is there a description somewhere on how to setup a development environment?

Yes. The quickest way forward is actually to follow the steps in this wiki page: https://github.com/git-for-windows/git/wiki/Making-an-installer

> Can I use my existing 32-bit MinGW/MSYS environment or do I have to install the 64-bit versions?

Unfortunately, an existing MinGW/MSYS environment will not do. You need to use Git for Windows' own SDK: https://git-for-windows.github.io/#download-sdk

> Will Cygwin do?

No. A full Cygwin environment is actually pretty incompatible with Git for Windows. Technical note, if you are *really* interested: Git for Windows is based on MSys2, whose runtime is a friendly & active fork of Cygwin's runtime, but that is pretty much the extent of overlap with the Cygwin project.

**Comment by glen-84** [comment] 2016-01-03 16:20
> sigh. That +1 indeed managed to let me overlook the real state of this ticket. As I said, +1s are bad ideas.

Seriously? You hadn't commented here for nearly 2 weeks, but it's my fault? Get over it.

**Comment by dscho** [comment] 2016-01-03 16:28
@glen-84 what exactly did you intend to achieve, now? Bury the current state of the ticket again?

**Comment by glen-84** [comment] 2016-01-03 16:37
I apologized for my "+1" (which I also did because there is no other way to communicate this in GitHub), but you had to bring it all up again out of nowhere and for no good reason.

I will delete my comments so that you are less distracted. Happy new year (I hope).

**Comment by dscho** [comment] 2017-02-21 23:42
@Jan-Bruun-Andersen shall we just close this ticket?

**Closed** 2017-04-04 21:39 UTC
Labels: help wanted
