### ISSUE TITLE
SChannel SSL backend does not use HTTP2 (HTTP/2)

### ISSUE THREAD

**Issue by jw013** [git-for-windows/git#4077] opened 2022-10-20 17:31 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1706]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

With SChannel SSL backend, git always uses HTTP/1.1 for https URL's, HTTP/2 is not negotiated and even the `http.version HTTP/2` config has no effect.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git init http2test
cd http2test
git remote add origin https://github.com/octocat/Hello-World.git
git config http.sslbackend schannel
git config http.version HTTP/2
GIT_TRACE_CURL=2 GIT_TRACE_CURL_NO_DATA=2 git fetch
```
 - What did you expect to occur after running these commands?

Expected HTTP/2

```
Send header: GET /octocat/Hello-World.git/info/refs?service=git-upload-pack HTTP/2
```

 - What actually happened instead?

```
Send header: GET /octocat/Hello-World.git/info/refs?service=git-upload-pack HTTP/1.1
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Observed on any HTTP/2 enabled server. 

 - Additional notes

Replacing the libcurl dll's in the Git windows with the versions from https://curl.se/windows/ resulted in HTTP/2 being used with SChannel.

**Comment by dscho** [comment] 2022-10-21 06:59
Thank you for the report, and particularly for clear, concise steps to reproduce. I can confirm that the same is happening here:

```console
$ GIT_TRACE_CURL=1 GIT_TRACE_CURL_NO_DATA=1 git -c http.sslbackend=schannel -c http.version=HTTP/2 ls-remote https://github.com/octocat/Hello-World test 2>&1 | grep HTTP
08:55:00.314556 http.c:662              => Send header: GET /octocat/Hello-World/info/refs?service=git-upload-pack HTTP/1.1
08:55:00.449139 http.c:662              <= Recv header: HTTP/1.1 200 OK
08:55:00.456235 http.c:662              => Send header: POST /octocat/Hello-World/git-upload-pack HTTP/1.1
08:55:00.603343 http.c:662              <= Recv header: HTTP/1.1 200 OK
```

In the latest [cURL build of Git for Windows, support for HTTP/2 is enabled](https://dev.azure.com/Git-for-windows/git/_build/results?buildId=83039&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=f6e52bf1-392c-5833-08b3-72976acad80f&l=876).

And when I run the command above with `http.sslbackend=openssl`, it _does_ use HTTP/2...

Will investigate.

**Comment by dscho** [comment] 2022-10-21 07:48
As you can see [here](https://github.com/git-for-windows/git/blob/v2.38.1.windows.1/http.c#L817-L825), we have code that is guarded at compile time to only ask for HTTP/2 if the curl library supports it. Since the command works with the OpenSSL backend, this code is actually run. And nothing in that code seems to say "disable this for Secure Channel".

So I tried to patch Git's source code to see whether this flag is set, and it is.

Then I tried to run the regular `curl.exe`, forcing the backend to Secure Channel via `CURL_SSL_BACKEND=schannel` _and_ trying to force HTTP/2 via `--http2` and lo and behold, it _also_ uses HTTP/1.1!

Naturally, I then tried to find something in cURL's bug tracker about this, and found [this ticket](https://github.com/curl/curl/issues/4391) and I think that that explains things. There is code in cURL that specifically enables the use of ALPN (which, if I understand correctly, is a prerequisite for HTTP/2) _only_ when compiling with MSVC and with a new-enough SDK. But in Git for Windows, we build cURL using GCC! That would explain things, but there might also be a way to enable ALPN with GCC...

I am continuing to investigate.

**Comment by dscho** [comment] 2022-10-21 08:00
I tried to force the use of ALPN via this patch:

```diff
diff --git a/lib/vtls/schannel.c b/lib/vtls/schannel.c
index dfec66d51..2a8a3af6a 100644
--- a/lib/vtls/schannel.c
+++ b/lib/vtls/schannel.c
@@ -61,7 +61,7 @@
 
    https://technet.microsoft.com/en-us/library/hh831771%28v=ws.11%29.aspx
 */
-#if defined(_MSC_VER) && (_MSC_VER >= 1800) && !defined(_USING_V110_SDK71_)
+#if 1 || defined(_MSC_VER) && (_MSC_VER >= 1800) && !defined(_USING_V110_SDK71_)
 #  define HAS_ALPN 1
 #endif
 
```

However, trying to run `CURL_SSL_BACKEND=schannel curl --trace /tmp/a1 -i -o /tmp/a2 --http2 https://nghttp2.org/` says that it falls back to HTTP/0.9! The detailed trace says this:

```
== Info:   Trying 2400:8902::f03c:91ff:fe69:a454:443...
== Info:   Trying 139.162.123.134:443...
== Info: Connected to nghttp2.org (2400:8902::f03c:91ff:fe69:a454) port 443 (#0)
== Info: schannel: disabled automatic use of client certificate
== Info: ALPN: offers h2
== Info: ALPN: offers http/1.1
== Info: ALPN: server accepted h2
== Info: Using HTTP2, server supports multiplexing
== Info: Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
== Info: h2h3 [:method: GET]
== Info: h2h3 [:path: /]
== Info: h2h3 [:scheme: https]
== Info: h2h3 [:authority: nghttp2.org]
== Info: h2h3 [user-agent: curl/7.85.0]
== Info: h2h3 [accept: */*]
== Info: Using Stream ID: 1 (easy handle 0x215e8496dc0)
=> Send header, 73 bytes (0x49)
0000: 47 45 54 20 2f 20 48 54 54 50 2f 32 0d 0a 48 6f GET / HTTP/2..Ho
0010: 73 74 3a 20 6e 67 68 74 74 70 32 2e 6f 72 67 0d st: nghttp2.org.
0020: 0a 75 73 65 72 2d 61 67 65 6e 74 3a 20 63 75 72 .user-agent: cur
0030: 6c 2f 37 2e 38 35 2e 30 0d 0a 61 63 63 65 70 74 l/7.85.0..accept
0040: 3a 20 2a 2f 2a 0d 0a 0d 0a                      : */*....
== Info: schannel: remote party requests renegotiation
== Info: schannel: renegotiating SSL/TLS connection
== Info: ALPN: server did not agree on a protocol. Uses default.
== Info: schannel: SSL/TLS connection renegotiated
== Info: schannel: remote party requests renegotiation
== Info: schannel: renegotiating SSL/TLS connection
== Info: ALPN: server did not agree on a protocol. Uses default.
== Info: schannel: SSL/TLS connection renegotiated
== Info: Received HTTP/0.9 when not allowed
== Info: Connection #0 to host nghttp2.org left intact
```

At this point, it looks as if the mingw-w64 toolchain maybe uses a too-old version of the MSVCRT to be able to negotiate the ALPN-based SSL/TLS connection to support HTTP/2. There _might_ be tricks to get it to work, but it does not seem as easy to me as flipping a switch.

@jw013 are you interested in continuing the investigation?

**Comment by jw013** [comment] 2022-10-21 16:28
@dscho You've already gone further than I would have known where to look, but if there's anything specific you want me to take a look, I'm happy to do what I can.

I did find this [curl#9451](https://github.com/curl/curl/issues/9451) issue, could it be relevant?

**Comment by dscho** [comment] 2022-10-23 20:20
> I did find this [curl#9451](https://github.com/curl/curl/issues/9451) issue, could it be relevant?

It is vaguely related, but note that building with a current MSVC always uses a newer SDK than building with GCC (which, for backwards-compatibility reasons, is stuck at the equivalent of an older SDK version).

So I am afraid that that ticket won't really help.

The only way we could hope to get cURL with Secure Channel to use HTTP/2 would be to find a way to get sufficient ALPN support with the MSVC runtime that is used by mingw-w64's GCC.

I won't lie: This could potentially be very challening, the investigation (to find out what exactly is going wrong with that MSVC runtime, what it should do instead, and then considering how to get there) alone would take longer than I have time for.

**Comment by dscho** [comment] 2022-11-11 21:19
After thinking about this for a good while, I realize that this is not at all a Git for Windows issue, but a cURL issue, square and fair. So let's close this here ticket.

**Closed by dscho** 2022-11-11 21:19 UTC
Labels: Help Wanted
