### ISSUE TITLE
git svn dcommit doesn't work anymore

### ISSUE THREAD

**Issue by hleskien** [git-for-windows/git#2695] opened 2020-06-17 14:35 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

PortableGit-2.27.0-64-bit.7z.exe

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
git-bash.exe --no-cd --command=post-install.bat
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn dcommit
```
 - What did you expect to occur after running these commands?

committing my changes in my git master to a remote subversion repository

 - What actually happened instead?

```
> git svn dcommit
svn: E235000: In file 'subversion/bindings/swig/perl/libsvn_swig_perl/swigutil_pl.c' line 1666: assertion failed (get_current_pool_cb != NULL)
      0 [main] perl 1810 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no, sorry

But the bug must have been introduced after 2.26.2. With PortableGit-2.26.2-64-bit.7z.exe (and many versions before) everything was ok.

Thank you in advance and kind regards

Holger

**Comment by rimrul** [comment] 2020-06-17 14:41
Duplicate of #2649, #2662 and #2670. Should be fixed in the latest snapshots.

**Comment by hleskien** [comment] 2020-06-17 15:03
I'm really sorry for the inconvenience! I didn't see those. Will wait for release.

**Comment by dscho** [comment] 2020-06-17 18:13
@hleskien can you test with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by hleskien** [comment] 2020-06-17 20:14
Seems to work! Tested with PortableGit-prerelease-2.27.0.windows.1-7-g3c88881ab7-20200616203852-64-bit.7z.exe

**Comment by dscho** [comment] 2020-06-17 20:28
Excellent!

**Closed by dscho** 2020-06-17 20:28 UTC
Labels: duplicate
