### ISSUE TITLE
.gitattributes doesn't affect existing files

### ISSUE THREAD

**Issue by orgads** [git-for-windows/git#881] opened 2016-09-13 09:53 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.0.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
echo -en "line\r\nline\r\nline\r\n" > a.txt
git add a.txt
git commit -m 'commit'
sleep 2
echo 'a.txt -text' >> .gitattributes
git add .gitattributes
git commit -m 'attributes'
git status
# nothing to commit
touch a.txt
git status
# a.txt modified
```
- What did you expect to occur after running these commands?

I expect `a.txt` to appear as modified right when .gitattributes is added.
- What actually happened instead?

It is not until I touch it.
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

It doesn't reproduce to me on a clean repository, but I tried a few long-lived repos and it reproduced on them.

**Comment by tboegi** [comment] 2016-09-13 14:51
Can you modify the setup somewhat ?
----------------------
echo -en "line\r\nline\r\nline\r\n" > a.txt
git add a.txt
git commit -m 'commit'
sleep 2
## Please add this line here (and past the output to us):
git ls-files --eol

echo 'a.txt -text' >> .gitattributes
git add .gitattributes
git commit -m 'attributes'
git status
# nothing to commit
touch a.txt
git status
# a.txt modified
## And please add another
git ls-files --eol
--------------------
As you installed Git with CRLF Option: CRLFAlways
I speculate that the first commit produces
"line\nline\nline\n" in the index.
Adding the .gitattributes tells Git, "Don't  change the line endings.
Which means that "line\nline\nline\n" in the index does not match
"line\r\nline\r\nline\r\n"  in the working tree.
And this is the expected behavior

**Comment by orgads** [comment] 2016-09-13 14:59
Thanks for your reply, but you got it wrong.

CRLFAlways means that the file is stored with `\n` in the git repo, but remains `\r\n` in the working directory.

Even if you delete and `checkout -f` the file, it will still have `\r\n`.

Setting -text for the file in .gitattributes means *not* to do these transformations, and let the file remain with `\n` only (exactly like it is stored in the repo).

```
$ git ls-files --eol a.txt
i/lf    w/crlf  attr/-text              a.txt

$ git status
HEAD detached from 365ec14
nothing to commit, working tree clean

$ touch a.txt

$ git status
HEAD detached from 365ec14
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   a.txt

no changes added to commit (use "git add" and/or "git commit -a")

$ git ls-files --eol a.txt
i/lf    w/crlf  attr/-text              a.txt

$ git checkout -f a.txt
$ git ls-files --eol a.txt
i/lf    w/lf    attr/-text              a.txt
```

**Comment by tboegi** [comment] 2016-09-14 16:06
After setting the attributes, there is a mismatch:
LF in the repo and CRLF in the working tree.
Git doesn't detect that, until you run touch and change the timestamp.
This is a known limitation. Files should be normalized after adding .gitattributes.

**Comment by rygorous** [comment] 2016-10-26 02:01
I just ran into a similar problem: one person added "*,sh text eol=lf" to .gitattributes in a repo, and it turns out someone else had erroneously checked in a shell script with CRLF line endings earlier.

"Known limitation" or not, it is really easy to accidentally get into that state; within a minute of looking at the issue tracker, I found issues #777 and #694 which appear to be instances of the same problem. "You should normalize your repo after changing .gitattributes" is all well and good but doesn't help if the offending change lies in the past and your repo is in that inconsistent state already. So, therefore, some questions:

* Is it possible to warn when editing the attributes? The docs mention the `rm .git/index` / `git reset` dance, but it's not something you run into if you don't already know to look for it. This might be high-noise, but OTOH from my quick sampling, problems related to this appear to account for something like 4% of your open issues, so it's evidently not a rare occurrence.
* Even better, is it possible to make git re-scan the working directory on a gitattributes edit _without_ the user having to do the brute-force index removal? As-is, it seems way too easy to accidentally get yourself into an inconsistent state.
* Separately, the docs could use a section on what to do after you accidentally got CRLFs into the repo. In my case, I ended up creating one commit that removed the "eol=lf" for shell scripts, and then another that re-added it and simultaneously checked in a normalize version of the CRLF-containing shell scripts. No idea if that's the best solution or not, but since it appears to be a common issue, the docs should probably have some recipes for you to use.

**Comment by tboegi** [comment] 2016-10-26 12:24
All this may be possible -  I am happy to review patches

**Comment by PhilipOakley** [comment] 2016-10-26 13:05
This should not viewed as a "Known limitation", rather that it's the way version control ought to be. That is, the content stored in the history under that revision (its sha1) should be inviolate. So no amount of after the fact changing of the attributes file could change the content of that sha1 (and it's ancestors).

That said, it maybe that you need an attribute that says, when you fetch such a shell file back from the repo, then please could Git convert it, on the fly, to the appropriate local line endings. 

The EOL problem is difficult as both sides (Windows/Linux?) think they are right, the same as the metric Mars lander issue. If you are round tripping the data, then such normalisation have to be reversible as well. Ultimately it becomes a social problem.

For my sins I remember real teletypes, and if anything it should be the CR that is the default EOL char, because it's that one that really took the time (returning the printer carriage from the 10" width from the right hand side to the left hand side, needing a 10 char wait before the next character could be printed, which is why CR is before LF.. ;-)

If you are up for a good read, have a look at the thread http://public-inbox.org/git/20160825155255.28929-1-tboegi@web.de/ for the discussions about handling EOL conversion.

**Comment by rygorous** [comment] 2016-10-26 21:29
I disagree about the first part; .gitattributes is a special case, in that semantically a line in the attributes belongs to the files it matches, every bit as much as their file names or file modes do. It does not (and I agree that it should not) change the file blob itself, but it does change how that blob is interpreted, how it should be materialized in the form of a file in the index/working directory, and when said file is considered "changed".

Consider what happens on a Windows machine with core.autocrlf=true right now if you take, say, a text file with LF line endings in the repo and add a "-text" attribute. On checkout, that file was materialized on the Windows machine with CRLF line endings. Once you commit the attributes change, your working directory is effectively dirty (since its version of that file does no longer match the file in the repository - as in, the on-disk data doesn't match what you would get if you were to do a clean checkout at that point), yet it gets reported as clean. And it will stay that way until you either touch/change the file or wipe the index and working directory. Which is already bad.

Now say the Windows user in question actually edits that file. They still have the CRLF version of the file (it never got updated) and are now doing edits on top of that. Once they commit a change, said change will consist of a) rewriting the file in the repo from LF to CRLF line endings, b) the actual intended change the user intended to make. That's bad, and making that attributes change on a Windows machine that has some of the files checked out already effectively sets a time bomb where the affected files don't match the repo yet are reported as clean.

At the point when you edited the attributes, your working directory was clean, and the repository was unchanged. As soon as you add the "-text", your working directory, despite none of the files on disk (except for the attributes file) having changed, is *not* clean anymore: it does not match what you would get on a clean checkout. Physically, nothing in the repo has changed yet. Logically, changing the atttributes dirties the affected text files. At that point, you could either decide to commit the CRLF version currently in the working directory as non-text, or you could follow up by checking out the CRLF-containing files again, which (with the new attributes) will now show up with LF line endings and match the repo.

I completely agree that this is tricky and messy, but I disagree that allowing what is effectively a form of data corruption (files reported as clean that aren't, with the potential to cause further issues down the line when changes start off the dirty data) is "the way version control ought to be".

Especially since, in other constellations (file in repo has CRLF, attributes state eol=lf), you can get into a separate, even uglier state where the file on disk is bit-identical to the repo yet is reported as changed, and checking out the repository version won't help; you end up with users stuck in a "file is modified" state with no obvious way to undo or fix it, and no indication of what went wrong. See the issues I linked for some examples of that.

(I looked at the message thread you linked but didn't see anything actually relevant to the present issue; if there is, could you point me at a specific message?)

**Comment by PhilipOakley** [comment] 2016-10-27 12:59
Hi @rygorous I see you are thinking through all the awkward issues that occur with the CR/CRLF/LF EOL issues.

At the moment the EOL processing (as I understand it) asserts that there is but one EOL conversion (which is then specified in the config/attributes), and that Git can trust that it's true, and that it ever sees a non conforming EOL sequence that it can throw a wobbly, which it does. E.g. what should happen if Git found a lone CR in your (in blob) shell file, or a lone LF in the checked out Windows file, what status should it give, and what changes should it report...

It's not often noticed but Git is treated as a first class social partner ("My friend the computer"), so there are lots of optimisations that are misunderstood, e.g. "assumed unchanged"[1], and "untouched means clean", which are promises 'we' make to our friend Git. When we  change the attributes file, Git still believes our optimisation that if the worktree file is untouched (same date stamp) relative to the index, then it's still as clean as when it was checked out - a trap we easily forget, and a point you raised.

At the moment we really don't have a good way of handling any non-reversible checkouts, as we don't have a good way of deciding what should be checked back in if the user does make a change. Essentially you get two diffs, one for the checkout filter/normalisation step, and then one for the user change. It is then unclear how to commit those two diffs, or even if the user diff can be applied to the original pre-filter blob.

I think I did get the reference wrong. Torsten (IIRC) had been doing a number of changes, and Junio was being rather firm with regard to the smudge/clean filter round trip issues. It may have been this thread http://public-inbox.org/git/xmqqy4arw089.fsf@gitster.mtv.corp.google.com/ - certainly this message does talk about the round trip problems.

Essentially it is a type of 'evil merge' issue.

If you could even suggest a documentation patch that shows how to get passed such normalisation issues, I'm sure it would be welcome.


[1] http://public-inbox.org/git/481910fd-5a5f-ffc6-b98c-61d48b4a2e49@gmail.com/

**Comment by dscho** [comment] 2017-01-20 16:17
Could somebody summarize the current state of this ticket for me?

**Comment by tboegi** [comment] 2017-01-20 20:50
The problem, in my understandig, is that Git does evaluate the CRLF conversion when then
file is touched in the working tree, and the timestamp recorded in the index does no longer match against what lstat() returns.
It does not evaluate if "the" .gitattributes have a newer timestamp than what the index has recorded.
This is fixable, in theory.
In practice we haven't seen a patch, so that we don't know about performance penalties.
Does this answer anything ?

**Comment by PhilipOakley** [comment] 2017-01-22 22:54
I think Junio's response to a very recent question on modification status  https://public-inbox.org/git/xmqqinp6vjey.fsf@gitster.mtv.corp.google.com/T/#m1b7a6ab4cda1f6272e1f06a7502ea64d0086d0da , could be a useful baseline for certain expectations, and if they are correct for this CRLF issue. (Here, it is whether the .gitattributes is treated as updated for the CRLF change detection).

I believe the ultimate question is : Is this response to be expected and hence a documentation update is needed to help make it plain, or the response isn't reasonable for the specific plumbing / porcelain command split and some code needs patching for this .gitattributes change case.

**Comment by PhilipOakley** [comment] 2017-01-24 18:38
I did a bit more investigating using the code snippets from @orgads and @tboegi for checking the different status responses. 

**In summary**, I think the code is performing as expected and documented, but the emergent property isn't expected or that well highlighted in the gitattributes(5) documentation.

Git notices when files are changed (via the lstat() modify times, file size, etc.), but Git doesn't notice when an EOL/CRLF attribute setting is changed and that would affect those unmodified files and how they are stored in the repository relative to the worktree.

There is a "_ Note _" under the `text=auto` section covering the issue, but that specific setting wasn't the one used here.

To fully (?) resolve the issue, the users need to read the manual, the notes needs to be at the places that the users would read (which is often where we fail), and the code to pick up and correct the issue should have a much simpler invocation than implied by the 7 line sample in the manual! 

I.e. for the possible code change `git reset`, `git status` and `git update-index` need to gain a `--CRLF` option that is more rigourous in detecting which files are now deemed modified because of the current EOL/CRLF setting. (I haven't checked if the `git ls-files --eol` uses the attributes in the working directory or the ones in the index, which is another user gotcha!).

I would expect that the code already written in `ls-files --eol` could be used to provide consistency in determining is the file is to be marked as 'modified' (`touch`ed).

cc @dscho.

**Comment by PhilipOakley** [comment] 2017-01-24 22:02
Adding an extra link to the previous work by Torsten for updating the CRLF processing on the main Git list (which spanned much of 2016).

Subject: Re: [PATCH v8 07/10] convert: unify the "auto" handling of CRLF
https://public-inbox.org/git/5502e894-bb22-e8b9-ab7a-49346d238283@web.de/ and 

Subject: Re: [PATCH/RFC v1 1/1] New way to normalize the line endings
https://public-inbox.org/git/xmqqshqaf67c.fsf@gitster.mtv.corp.google.com/

These last two relate to the "the normalization instruction" part.

**Comment by dscho** [comment] 2017-10-08 12:14
@PhilipOakley based on your understandin, of @tboegi's work, do you think we can close this ticket now?

**Comment by PhilipOakley** [comment] 2017-10-08 14:54
@dscho I beleive there is yet more going on regarding the documentation. 

The latest on the Git list is just a few days ago @tboegi  https://public-inbox.org/git/20171006175815.GA31970@tor.lan/ and the original Question from Robert Dailey was for GfW 2.13.1, though some of the response was regarding the GitHub support page.

So I think it is a waiting game for the Github documenation page to update (root cause) and any of Torsten's code to land.

**Comment by dscho** [comment] 2017-10-08 19:54
Nothing we can do here. Thanks for the confirmation.

**Closed by dscho** 2017-10-08 19:54 UTC
