### ISSUE TITLE
Emoji failing to display in Visual Code using Git Bash after Windows Update

### ISSUE THREAD

**Issue by mikegwhit** [git-for-windows/git#2343] opened 2019-10-02 03:14 UTC
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
32 bit
```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.356]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disable

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Should be MinTTY

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
echo -e '\U0001F602'
```
 - What did you expect to occur after running these commands?

😂

 - What actually happened instead?

Unicode block (specials) character

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

:Shrug:

**Comment by dscho** [comment] 2019-10-02 12:35
> Should be MinTTY

Could you add more detail?

I just tried in the _internal_ terminal of VS Code (which is definitely _not_ MinTTY), and I indeed see `�` printed there. Switching to another terminal tab and then switching back, however, I see `�😂`. If this is the bug you want to report, I think that it is not a bug in Git for Windows, but rather in VS Code. [This SO post](https://stackoverflow.com/questions/53868342/no-emojis-are-shown-in-the-vscode-terminal) suggests so, and I guess a good starting point would be https://github.com/microsoft/vscode/issues/68207.

If you indeed wanted to report a VS Code bug, please close this Git for Windows ticket.

**Comment by dscho** [comment] 2019-10-05 20:26
> > Should be MinTTY
> 
> Could you add more detail?

Could you?

**Closed** 2020-03-07 20:47 UTC
