### ISSUE TITLE
Nondescriptive "bad address" error

### ISSUE THREAD

**Issue by md-5** [git-for-windows/git#303] opened 2015-08-22 10:56 UTC
Using both the 32 bit and 64bit 2.5.0 portable installs on Windows 7:
````
Michael@michael-pc MINGW32 ~
$ git
bash: /mingw32/bin/git: Bad address
````
Not sure how to debug further

**Comment by dscho** [comment] 2015-08-22 13:42
Obviously I cannot reproduce that... Any more details on your setup? Like: did you install as admin, but run as non-admin? Or do you have a virus scanner that quarantines files first?

Also: where do you install the portable Git? The default location? If so, is your home directory in an unmapped Windows share?

**Comment by md-5** [comment] 2015-08-22 21:46
Portable install, non admin, in my C:/Users/Michael folder. It's just a
normal ntfs drive.

**Comment by md-5** [comment] 2015-08-23 01:47
Disabling Windows defender didn't help.

**Comment by dscho** [comment] 2015-08-24 08:48
Do you have a `/mingw32/bin/git.exe` file? If so, can you call it from `cmd.exe` using the absolute path?

**Comment by md-5** [comment] 2015-08-24 09:08
Works fine from cmd.

Seems to be limited to bash, and not just git:
````
Michael@michael-pc MINGW64 ~
$ openssl
bash: /mingw64/bin/openssl: Bad address
````

**Comment by dscho** [comment] 2015-08-24 10:01
You mean, all MinGW programs fail with said "Bad address"? Are there maybe some entries in the system logs?

**Comment by md-5** [comment] 2015-08-24 10:17
They don't always fail, sometimes they work.
Unclear as to reproduction steps.

Nothing useful in the system logs.

**Comment by md-5** [comment] 2015-08-24 10:20
````
Michael@michael-pc MINGW64 ~
$ while true; do git --version ; done;
git version 2.5.0.windows.1
bash: /mingw64/bin/git: Bad address
git version 2.5.0.windows.1
Aborted (core dumped)
bash: /mingw64/bin/git: Bad address
Aborted (core dumped)
git version 2.5.0.windows.1
git version 2.5.0.windows.1
git version 2.5.0.windows.1
git version 2.5.0.windows.1
git version 2.5.0.windows.1
bash: /mingw64/bin/git: Bad address
bash: /mingw64/bin/git: Bad address
bash: /mingw64/bin/git: Bad address
bash: /mingw64/bin/git: Bad address
bash: /mingw64/bin/git: Bad address
Aborted (core dumped)
git version 2.5.0.windows.1
bash: /mingw64/bin/git: Bad address
Aborted (core dumped)
Aborted (core dumped)
Aborted (core dumped)
Aborted (core dumped)
git version 2.5.0.windows.1
````

**Comment by md-5** [comment] 2015-08-24 10:23
Stackdump seems useless:
````
Stack trace:
Frame        Function    Args
0000023AA90  00180071EC3 (00000000000, 00000000000, 00000000000, 00000000000)
00000000002  00180073574 (00000000064, FFFFE00100000000, 000000002E8, 00000000000)
0000023B180  0018012DB4F (7FFE87941E40, 00000000000, 00000000000, 0018030D728)
0000023B470  0018012A870 (00000000000, 00000000000, 00000000000, 00000000000)
0000023B660  0018012AD39 (00180312958, 00180313418, 00000000000, 00000000006)
0000023B660  0018012AF0C (000000009F5, 0000023B750, 00000000000, 101010101010101)
0000023B660  0018012B36F (000FFFFFFFF, 0000023B660, 0060016D3D0, 0060016D3D0)
0000023B660  0018015FAEA (001800F0D5E, 00000000000, 00000000C20, 00600047FA0)
0000023B660  001800CCC83 (0000023B700, 00180311468, 00180311ECF, 00000000000)
0000023B660  00180131A76 (00000000000, 0060016D3B0, 00600047FA0, 00600000003)
0060016D3B0  00180133459 (0018012681B, 00000000014, 001005E6C44, 00100438BD0)
00600047FA0  0018012681B (0018012681B, 00000000014, 001005E6C44, 00100438BD0)
00600047FA0  0010041307C (00000000001, 0010045FF80, 0060016D260, 00000000000)
0060016D2B0  00100414BAF (00000000002, 006FFFFFFFF, 00000000000, 00600168470)
00000000000  00100415669 (00000000025, 00000000025, 0060004B150, 00600168470)
001005E7460  00100417994 (00000000000, 00600161C60, 00000000000, 0000004B150)
End of stack trace (more stack frames may be present)
````

**Comment by md-5** [comment] 2015-08-24 10:24
Seems changing dirs makes the issue a lot more prevelant, ie: just changing to `cd ~/Music` then running:
`while true; do git --version ; done;`
64bit portable install

**Comment by dscho** [comment] 2015-08-24 10:53
Hmm. This is funny. It works without problems here...

How did you install portable Git BTW? Did you unpack it with 7-Zip, or did you run it as self-extracting installer?

**Comment by dscho** [comment] 2015-08-24 10:57
Or maybe you have an application running in the background which is in [Cygwin's Big List Of Dodgy Applications](https://cygwin.com/faq/faq.html#faq.using.bloda)?

**Comment by md-5** [comment] 2015-08-24 10:57
Self extracting installer.

**Comment by dscho** [comment] 2015-08-24 11:01
> Self extracting installer.

I asked because sometimes similar problems occur when the executables and DLLs have not been rebased (see https://github.com/git-for-windows/git/wiki/32-bit-issues for details). In those cases, closing all Git for Windows terminals and running the following from `cmd.exe` often helps:

```cmd
cd \path\to\Git\usr\bin
dash rebaseall
```

But I really would suggest comparing the list of running applications/services against [Cygwin's Big List Of Dodgy Applications](https://cygwin.com/faq/faq.html#faq.using.bloda).

**Comment by dscho** [comment] 2015-08-27 09:50
> I really would suggest comparing the list of running applications/services against Cygwin's Big List Of Dodgy Applications.

@md-5 could you do that, please?

**Comment by md-5** [comment] 2015-08-27 10:51
Already did.
Only Windows defender, which I disabled.
Older msysgit works flawlessly.

**Comment by dscho** [comment] 2015-08-27 11:46
You do not happen to have a Logitech webcam running, do you? Running out of ideas...

**Comment by md-5** [comment] 2015-08-27 11:52
Nope.

I haven't tried the rebase stuff yet, so I'm gonna give that a shot. The only issue with that is the article claims it only affects 32bit, but I'm 64bit.

Heck I might try safe mode just to see what happens.

Really I just need a more descriptive error than "bad address".

**Comment by dscho** [comment] 2015-08-27 12:17
> Really I just need a more descriptive error than "bad address".

That makes two of us.

If you're in a 64-bit setup, could you try the 32-bit portable Git?

**Comment by dscho** [comment] 2015-08-27 12:17
Woops, I meant the 32-bit installer?

**Comment by dscho** [comment] 2015-08-27 12:19
And another stab in the dark: where do you install your portable Git? On a network drive?

**Comment by md-5** [comment] 2015-08-27 21:16
I'll try the 32bit installer, as mentioned above, portable doesn't work.

No it's just on C;\

**Comment by dscho** [comment] 2015-08-28 08:17
The real odd thing is that it is intermittent. Otherwise I would have suggested a `PATH` problem. But no, that would kick in *all* the time. So it looks more like *some* process is grabbing a hold on the executables or their `.dll` files from time to time.

Any chance to resolve this via Skype or some such?

**Comment by md-5** [comment] 2015-08-28 10:57
Just reproduced it via safe mode, so yeah...
I'm on IRC (freenode et al) as md_5

**Comment by dscho** [comment] 2015-08-28 12:25
@md-5 Just tried to ping you, but you seem to be in UTC+<large number>? Could you ping me here when you are available (not this weekend, but I will be online for a couple more hours today, and of course again on Monday)?

**Comment by md-5** [comment] 2015-08-28 21:42
@dscho Melbourne, so UTC+10 at the moment. How about Monday morning?
Feel free to chuck me an email (git@md-5.net) if you wanna set an exact time.

**Comment by md-5** [comment] 2015-08-31 09:04
@dscho 
I think I have it!
1) Install PortableGit in `C:\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
2) `cd ~/Music` - I think any directory should work, but I use that one
3) Run `while true; do git --version; done;` (or any other cygwin command)
4) Observe crashes
5) Rename install to `C:\AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`
6) Observe no crashes

You will notice that the path length is 65 characters, and removing it by one stops the crash. I'm guessing the cygwin / bash code somewhere flips out on a 64byte array overflow.
nb: my folder name wasn't 64 chars long, but once you added all the folders from C:\ it exceeded that.

**Comment by dscho** [comment] 2015-08-31 09:53
I just tried that, on Windows Server 2012 R2 and it does not crash...

**Comment by dscho** [comment] 2015-08-31 09:57
Okay, adding a couple *more* `A`s caused it to crash, I would guesstimate ~10-25% of the time.

**Comment by dscho** [comment] 2015-08-31 10:56
Further debuggin reveals that `git.exe` is really not called at all (`GIT_TRACE=1` does not trigger any output if the `bad address` error occurs).

And unfortunately, running this through `strace.exe` seems to work around the issue.

**Comment by md-5** [comment] 2015-08-31 11:53
Strace actually crashes with the bad address for me. Since both work fine in cmd its probably a bash issue.

**Comment by dscho** [comment] 2015-08-31 12:36
> Since both work fine in cmd its probably a bash issue.

In the meantime, I managed to get a combination of options to `strace` that make it fail.

And yes, since the error reads `/usr/bin/bash: /mingw/bin/git: bad address`, yes, it is a Bash issue.

**Comment by dscho** [comment] 2015-09-01 08:32
Okay, while this is not a reliable reproduction recipe, it still *should* be helping in identifying the issue (which most likely lies deep within the msys2-runtime).

**Comment by dscho** [comment] 2015-09-06 12:21
I have a tentative fix for this, but a still chasing a bug in `t9164` that happens only on 32-bit. It might have been there before, though, as I have not run the complete regression tests on 32-bit in a while.

**Comment by dscho** [comment] 2015-09-09 12:33
This bug was fixed.

**Closed by dscho** 2015-09-09 12:33 UTC
Labels: bug, msys2
