### ISSUE TITLE
cann't install git 2.7&2.6.4 on window 10(64bit) insider preview(14251.1000)

### ISSUE THREAD

**Issue by jackspec** [git-for-windows/git#638] opened 2016-02-01 07:33 UTC
I have tried git 2.7 & 2.6.4,  and at the end of the installtion(the progress bar is 100%),will appear a dialog: git is stop work。   and I have check the windows application event log, the log is : 

错误应用程序名称: git.exe，版本: 2.7.0.0，时间戳: 0x00000000
错误模块名称: ntdll.dll，版本: 10.0.14251.1000，时间戳: 0x56a54488
异常代码: 0xc0000005
错误偏移量: 0x00000000000a6eeb
错误进程 ID: 0x26a4
错误应用程序启动时间: 0x01d15cbd2d1242b8
错误应用程序路径: C:\Program Files\Git\mingw64\bin\git.exe
错误模块路径: C:\WINDOWS\SYSTEM32\ntdll.dll
报告 ID: 64e56d24-496d-45bf-89df-4400d309b40e
错误程序包全名: 
错误程序包相对应用程序 ID:

**Comment by meancrazy** [comment] 2016-02-01 07:44
Repeats for me. Git 2.6.2 & Git 2.7 & Windows 10 Insider Preview 10.0.14251.1000

**Comment by dscho** [comment] 2016-02-01 07:47
This is the fourth (!) duplicate of #627: #632, #633 and #636 *already* duplicated the bug report. Please note that all the time I have to spend closing duplicates has an immediate impact on real bugs: I cannot address them when I have to clean up tickets.

**Closed by dscho** 2016-02-01 07:47 UTC
Labels: duplicate

**Comment by jackspec** [comment] 2016-02-01 08:45
I am sorry. I am a newbie here, and not good at english. I'll attention next time before report a bug
