### ISSUE TITLE
[Suggestion] Checkout as-is, commit as-is to default

### ISSUE THREAD

**Issue by tldzyx** [git-for-windows/git#2994] opened 2021-01-25 06:11 UTC
![image](https://user-images.githubusercontent.com/5987706/105667537-6696a500-5f16-11eb-8590-fc21018a8454.png)

If there no reason to do something, just keep it!

The Windows Setup recommended line ending conversions is "Checkout Windows-style, commit Unit-style line endings", It's not a good idea, it's often broken the resource files, like .xml/.json etc. and make newb feel strange in out team.

actually, the IDE such as IDEA can do convert as well, because there has syntax parsing, it known which is the code file, but git sample process anything as a text file without syntax.

> Ability to chain program together to perform complex tasks.
> Write programs that do one thing and do it well.

**Comment by PhilipOakley** [comment] 2021-01-25 11:09
The key is the "Cross-Platform" expectation. 

Maybe the wording could be adjusted/improved so that it's more obvious (PRs always welcomed, but note that the explanatory message is limited to 3 lines for reasons).

Maybe include some note/comment about using the .gitattributes file use for the resource/xml/json files.

**Comment by dscho** [comment] 2021-01-25 13:32
No, the key is "backwards compatibility".

**Comment by dscho** [comment] 2021-01-30 13:37
I think that "cross-platform compatibility" actually *dictates* that we need to keep the current default. Otherwise, you _ask_ for mismatching line endings to be checked in.

In any case, I consider https://www.edwardthomson.com/blog/git_for_windows_line_endings.html to speak the truth. The question is not about `core.autoCRLF` but about the appropriate `eol` attributes.

**Closed** 2021-01-30 13:37 UTC

**Comment by thorn0** [comment] 2021-02-27 18:16
`autocrlf` is anachronism in 2021. See [this great answer on SO](https://stackoverflow.com/a/2825829/76173) that confirms that it was an anachronism even back in 2010. Even notepad.exe understand LF-only line breaks today.

**Comment by rimrul** [comment] 2021-02-27 18:44
`core.autocrlf` is still an important feature to many users. Feel free to set it to false if it isn't needed for you.

>Even notepad.exe understand LF-only line breaks today.

Not on all operating systems Git for Windows supports. Only on Windows 10 (and corresponding server operating systems). And only on v1809 or newer. If it's not disabled in the registry.  And even then

>New files created within Notepad will use Windows line ending (CRLF)

So that isn't exactly a strong argument.

**Comment by thorn0** [comment] 2021-02-27 18:55
In my experience, this preselected `autocrlf=true` creates strictly more harm than good. I'd like to doubt the very idea that converting line endings is something a VCS should be concerned with. A VCS is a tool for storing and exchanging files. It shouldn't do anything with the content of the files. At all. Why should it? If somebody wants to commit a text file with CRLF, so be it. If this is a problem for a specific project, there are other great tools exactly for that like code formatters and EditorConfig. It's simply not Git's job.

**Comment by thorn0** [comment] 2021-02-27 19:02
Browsers don't convert line endings when they download text files. File managers don't convert line endings when they copy files. This functionality simply doesn't belong in Git. It looks like an Easter egg that went hilariously out of control because of this preselected radio button in the installer.

**Comment by PhilipOakley** [comment] 2021-02-27 19:28
> A VCS is a tool for storing and exchanging files.

Git is the VCS for Linux, so LF is the default line ending for that exchange.  

The Git for Windows project is not a re-write of Git, rather it is a compatibility shim on top of Git, so the LF line ending is kept for compatibility with the base code.

I would agree that the dialog box offered at install time doesn't (isn't) able to be informative enough, but we need to work within the constraints we have. 

Working out how to be more informative within the dialog would appear to one of the options. See also the https://github.com/git-for-windows/build-extra/pull/315

**Comment by thorn0** [comment] 2021-02-27 19:35
> Git is the VCS for Linux, so LF is the default line ending for that exchange.

Sorry, I really don't understand this. Files are just sequences of bytes. Why does Git even need the notion of line ending to store and exchange them? What is "the default line ending for exchange" when I send a file over email or download it using a browser?

> The Git for Windows project is not a re-write of Git, rather it is a compatibility shim on top of Git, so the LF line ending is kept for compatibility with the base code.

Okay. Git doesn't need to anything about that. Today, LF totally is a fist-class citizen on Windows.

**Comment by PhilipOakley** [comment] 2021-02-27 19:40
>  Files are just sequences of bytes. Why does Git even need the notion of line ending to store and exchange them?

diffs. 
Extraneous CR characters matter. They are changes. That's why. They also pollute the history.

**Comment by rimrul** [comment] 2021-02-27 19:41
Git usually deals with changed parts of a file, not whole files.

**Comment by thorn0** [comment] 2021-02-27 19:44
> Extraneous CR characters matter. They are changes. That's why. They also pollute the history.

They're just bytes. Yes, they're changes. No, that's not up for Git to decide which changes are good. The VCS should be agnostic about such things.

**Comment by dscho** [comment] 2021-03-01 16:05
> They're just bytes

@thorn0 I strongly encourage you to read the responses you received more carefully, in particular the part that you cut from the quoted text: "diffs". There is nothing "just bytes" about diffs. And diffs (as well as merges, which are based on diffs, by the way) are _quite_ central to Git.

So maybe you should stop thinking about Git in terms of VCS and start thinking about it more in terms of SCM.

**Comment by thorn0** [comment] 2021-03-01 17:56
@dscho Sorry, I genuinely don't understand this. Sure, mixed line breaks is a bad, diff-unfriendly thing, but there exist many other ways to mess diffs up. For example, a source file is indented with spaces but somebody deliberately or accidentally adds lines with tabs to it and partially reindents some other lines using tabs. Definitely horrible, but the G4W project doesn't care about that. Somehow it's clear it's not Git's responsibility (at least by default). How are line endings different? Why when it comes to line endings G4W gets so overprotecting?

**Comment by dscho** [comment] 2021-03-02 15:21
> How are line endings different?

I have seen plenty of projects define whether they indent using spaces or tabs. I have yet to see a project that defines that it wants a certain type of line ending, this is historically the Operating System's choice. Quite different.

**Comment by dscho** [comment] 2021-03-02 17:35
> Do we live in different universes?

Sounds like it.

**Comment by mfriedrich74** [comment] 2021-03-02 18:32
Hi,

Typically there is a difference between the projects targeted operating
system and the one git is used on. Especially in projects for heterogeneous
environments, or where cross compilations is used, these two are often
different. Git could contain files to be compiled (target doest matter that
much) or simply e.g. files that get copied directly to a target system
(target matters).

In my company we always recommend our developers to use as-is. Most our
developers work on Windows, but develop for a mixture of systems, like
embedded systems (Linux-like, VxWorks), Ubuntu, and Windows. Only some
developers work on Ubuntu (VMs) targeting Ubuntu.

Git works perfectly fine with an as-is setting, on all platforms. If you
diff a Windows text file on Linux you get the extra characters at the end
of each line, this doesn't really happen that often for us (we treat that
as a coding bug). I am not sure how often other companies develop on
Windows and on Linux at the same time.

I don't care so much about what's the default at git install time (as long
as there is a choice), just wanted to highlight usage scenarios and point
out the issue is only visual. Functionality is fine as far as I can tell.

Best regards, Mike

**Comment by thorn0** [comment] 2021-03-03 13:55
@dscho Totally sounds like it. Clearly, you (the maintainers of G4W) firmly believe this preselected radio button causes more good than harm. I would like you at least to question this belief. `autocrlf` - a marginal feature of Git (Git itself has it disabled by default and rightfully so) - is kind of forced upon people who didn't ask for it. I don't question the goodness of the intentions behind this decision, but its consequences are definitely questionable.

**Comment by dscho** [comment] 2021-03-03 13:56
@thorn0 you seriously want me to break everybody's setup, don't you.

**Comment by thorn0** [comment] 2021-03-03 13:58
I seriously don't see how removing this part from the installer can break everybody's setup.

**Comment by thorn0** [comment] 2021-03-03 13:59
I know how setups are broken when people click Next without reading what they accept though.

**Comment by dscho** [comment] 2021-03-03 14:00
> 
> 
> I seriously don't see how removing this part from the installer can break everybody's setup.

So you think that Git for Windows users who for years, nay, over a decade relied on the fact that by default their files are checked out with CR/LF and are checked in with LF would be _totally_ happy if all of a sudden their perfectly fine CR/LF workfiles were checked in as CR/LF, messing up all collaboration with non-Windows developers?

I see a huge, enormous problem right there. And I cannot take any suggestion seriously that fails to take this into account.

**Comment by thorn0** [comment] 2021-03-03 14:30
The users of the `autocrlf` feature should know what they're doing and enable it themselves explicitly. Projects should have `.editorconfig`, `.gitattributes`, etc. Relying implicitly on that preselected radio button is asking for trouble. If the choice remains in the installer, just the default value changes, big red letters can be added for these users.

> messing up all collaboration with non-Windows developers

It's not that scary. When CRs manage to slip in, it's enough to notice them once to fix the problem for good. Just like (exactly like) tabs vs spaces.

**Comment by hh-lohmann** [comment] 2021-03-03 16:49
Just spend some time for a PR that will be rejected just because maintainer's pipeline breaks or automatically rejects due to unexpected formatting. Don't expect many maintainers to have time for basic discussions then.

**Comment by tldzyx** [comment] 2021-03-18 17:30
> > A VCS is a tool for storing and exchanging files.
> 
> Git is the VCS for Linux, so LF is the default line ending for that exchange.
> 
> The Git for Windows project is not a re-write of Git, rather it is a compatibility shim on top of Git, so the LF line ending is kept for compatibility with the base code.
> 
> I would agree that the dialog box offered at install time doesn't (isn't) able to be informative enough, but we need to work within the constraints we have.
> 
> Working out how to be more informative within the dialog would appear to one of the options. See also the [git-for-windows/build-extra#315](https://github.com/git-for-windows/build-extra/pull/315)

Even in linux program, there also have file with CRLF, because there not only source file, we have many other files, and may be it has data with "CRLF".

git is a VCS, the responsibility is version control, not content control, so git should not modify any file data, if we need LF, just use IDE or editor to do it.

**Comment by poke** [comment] 2021-04-09 11:06
@dscho
> So you think that Git for Windows users who for years, nay, over a decade relied on the fact that by default their files are checked out with CR/LF and are checked in with LF would be totally happy if all of a sudden their perfectly fine CR/LF workfiles were checked in as CR/LF, messing up all collaboration with non-Windows developers?

I don’t think anyone is suggesting to _change_ the setting users have chosen on their system (being that an intentional choice or not). I think what is being suggested is to change the _default_ (for systems where Git isn’t installed/configured yet) to the value `false` which Git considers to be the default if the option is not specified.

So people that have set their autocrlf to anything can continue with that setting and won’t be broken by an update. And when you are installing Git on a fresh system, then you can make the deliberate choice, or get the default unset value (= `false`).

Going by [the article you linked above](https://www.edwardthomson.com/blog/git_for_windows_line_endings.html), setting `autocrlf` doesn’t even help with the problems:

> The problem with `core.autocrlf` is that if some people have it set to `true` and some don’t, you’ll get a mix of line endings in your repository. And that’s not good - because his setting doesn’t _just_ tell Git what you want it to do with files going in to your repository. It also tells Git what you’ve already done, and what the line endings look like on the files that are already checked in.

So setting autocrlf is already a problem, regardless of what you option choose. Instead, the recommendation everywhere (including the Git documentation) is to specify this through the `.gitattributes` so that it’s shared with everyone on the team. This also goes in line with today’s standard to include an `.editorconfig` that can configure most editors what to do with line endings.

If you for example have an `.editorconfig` with the setting `end_of_line = lf` then you are effectively changing the line endings _every time_ when saving a file. This is not a problem directly because the line ending will be converted to `lf` anyway and `git diff` is able to deal with this; but external difftools might still show line ending differences, so you are causing more problems there. And you will keep getting these cryptic message _for every file_:

```
warning: LF will be replaced by CRLF in <filename>.
The file will have its original line endings in your working directory
```

Chances are, if you have an `.editorconfig`, then you don’t want your developers to really have to think about line endings. But if they have any kind of line ending conversion turned on in their configuration, then they *will* have to deal with it.

Contrast this to the different setup where everyone has autocrlf turned off by default, and you give full control to the team to configure this to the fullest through their repository setup.

---

For what it’s worth, our team was bit by this because we inherited a codebase which was originally using CRLF and the person creating the repository had autocrlf turned on. This converted everything to LF and caused lots of problems because our build system *on Linux* ended up with the LF files having different file hashes than originally (when the code was still CRLF) causing follow-up problems with specific tools. I can fix this now by essentially changing every file and establishing the correct conventions with the `.gitattributes` now (overriding any autocrlf setting), but issues like this could be avoided from the start.

I would really like to see this default configuration to change in the Git for Windows installer. I strongly believe that this would cause *less* problems going forward. And [others seem to agree with that](https://stackoverflow.com/a/2016763/216074).

**Comment by thorn0** [comment] 2021-04-09 11:29
Another option to consider is to show the radio buttons without a preselected value. The user will have to choose something to continue.
