### ISSUE TITLE
Can not connect to gitlab through ssh

### ISSUE THREAD

**Issue by szachara** [git-for-windows/git#1257] opened 2017-08-06 18:59 UTC
I have upgraded to `2.14.0 x64` version now and I can't connect through ssh to gitlab repo anymore.

I get this error:
```
Silver Zachara@merydeye-devel MINGW64 ~
$ git clone git@lab.kbs-development.com:fm-logistic/fm-logistic.git fmx
Cloning into 'fmx'...
GitLab: Disallowed command
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I don't have any problem with 2.13.3 version.
So I tried to connect to `github repo` through ssh and any problem too.

What can cause this problem?

Thank you for any suggestions.

**Comment by shiftkey** [comment] 2017-08-06 20:27
Without more information about the setup I'm going to close this as it seems like a duplicate of #1258. Please follow along there.

**Comment by shiftkey** [comment] 2017-08-06 20:30
Actually, this error is slightly different:

> `GitLab: Disallowed command`

@szachara could you please go back and fill out the template? This will help with troubleshooting.

**Comment by szachara** [comment] 2017-08-06 21:59
```

**Comment by szachara** [comment] 2017-08-06 22:03
```
$ git --version --build-options
git version 2.13.3.windows.1
built from commit: faaf2320f32f6ac52a69502c6b157b6ea4781f50
sizeof-long: 4
machine: x86_64
```
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```
```
λ type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

Is there any log file or some how can I obtain some debug info, e.g. during clone command? Let me know what info do you need.

**Comment by szachara** [comment] 2017-08-06 22:07
Is there any log file or how can I obtain some debug info, e.g. during clone command? I have to upgrade and then downgrade, because I need to work, I fill template tomorrow.

**Comment by shiftkey** [comment] 2017-08-06 23:08
@szachara I mentioned a way to test your SSH connection with debugging enabled here https://github.com/git-for-windows/git/issues/1258#issuecomment-320531945

**Comment by luckynum7** [comment] 2017-08-07 00:15
@shiftkey checkout [Cannot pull/fetch/clone/push with Git for Windows 2.14 over SSH]: https://gitlab.com/gitlab-org/gitlab-ce/issues/36028

Git for Windows `v2.13.3` works for now.

**Comment by shiftkey** [comment] 2017-08-07 00:20
@luckynum7 thanks for the link to the upstream issue. I'm going to close this out, as it sounds like they plan to support `git upload-pack` Real Soon™ and you can use an earlier build in the meantime.

**Closed by shiftkey** 2017-08-07 00:20 UTC

**Comment by szachara** [comment] 2017-08-07 09:38
thx, it exactly the problem
