### ISSUE TITLE
Version 2.6.2 installer requires Admin privileges

### ISSUE THREAD

**Issue by frohman-wd** [git-for-windows/git#511] opened 2015-10-27 13:46 UTC
Prior to version 2.6.2, the installer for Git for Windows could be run by a non-admin level user.  The release of 2.6.2 that is currently being distributed on git-scm.org errors out when trying to run with a non-admin account.

**Comment by dscho** [comment] 2015-10-28 13:15
This is a duplicate of https://github.com/git-for-windows/git/issues/497. The issue [was fixed](https://github.com/git-for-windows/build-extra/pull/86) and the next version will not require admin privileges any longer.

**Closed by dscho** 2015-10-28 13:15 UTC
