### ISSUE TITLE
Git for Windows 2.16.3.windows1 gives fatal: ArgumentNullException encountered. 2.16.2 works fine.

### ISSUE THREAD

**Issue by dev-bandai** [git-for-windows/git#1601] opened 2018-03-30 02:53 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.3.windows.1
cpu: x86_64
built from commit: 5d726e05e4c0ff9e11374e64e21d8300b0291c6d
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
(Windows7 Professional Service Pack 1 32bit)
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Same behaviour from bash, cmd, and when invoked by GitExtensions's GUI.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull

```
 - What did you expect to occur after running these commands?

Pulling origin

 - What actually happened instead?

```
17:43:08.670770 git.c:344               trace: built-in: git 'pull'
17:43:08.680536 run-command.c:627       trace: run_command: 'fetch' '--update-head-ok'
17:43:08.709834 git.c:344               trace: built-in: git 'fetch' '--update-head-ok'
17:43:08.717647 run-command.c:627       trace: run_command: 'remote-https' 'origin' 'https://github.com/dev-bandai/foobar-docs.git'
17:43:08.742062 git.c:576               trace: exec: 'git-remote-https' 'origin' 'https://github.com/dev-bandai/foobar-docs.git'
17:43:08.743038 run-command.c:627       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/dev-bandai/foobar-docs.git'
17:43:09.354390 run-command.c:627       trace: run_command: 'git credential-manager get'
17:43:09.416892 git.c:576               trace: exec: 'git-credential-manager' 'get'
17:43:09.417869 run-command.c:627       trace: run_command: 'git-credential-manager' 'get'
17:43:09.516506 ...\Common.cs:636       trace: [Main] git-credential-manager (v1.15.0) 'get'
17:43:09.562406 ...\Program.cs:496      trace: [Run] System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:path
   場所 Microsoft.Alm.Git.GitInstallation..ctor(String path, KnownGitDistribution version)
   場所 Microsoft.Alm.Git.Where.FindGitInstallations(List`1& installations)
   場所 Microsoft.Alm.Git.Where.GitSystemConfig(Nullable`1 installation, String& path)
   場所 Microsoft.Alm.Git.Configuration.LoadGitConfiguration(String directory, ConfigurationLevel types)
   場所 Microsoft.Alm.Git.Configuration.ReadConfiuration(String directory, Boolean loadLocal, Boolean loadSystem)
   場所 Microsoft.Alm.Cli.OperationArguments.LoadConfiguration()
   場所 Microsoft.Alm.Cli.OperationArguments.get_GitConfiguration()
   場所 Microsoft.Alm.Cli.CommonFunctions.TryReadBoolean(Program program, OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.Program.TryReadBoolean(OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.CommonFunctions.LoadOperationArguments(Program program, OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.LoadOperationArguments(OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.Get()
   場所 Microsoft.Alm.Cli.Program.Run(String[] args)
17:43:09.563382 ...\Common.cs:601       trace: [LogEvent] System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:path
   場所 Microsoft.Alm.Git.GitInstallation..ctor(String path, KnownGitDistribution version)
   場所 Microsoft.Alm.Git.Where.FindGitInstallations(List`1& installations)
   場所 Microsoft.Alm.Git.Where.GitSystemConfig(Nullable`1 installation, String& path)
   場所 Microsoft.Alm.Git.Configuration.LoadGitConfiguration(String directory, ConfigurationLevel types)
   場所 Microsoft.Alm.Git.Configuration.ReadConfiuration(String directory, Boolean loadLocal, Boolean loadSystem)
   場所 Microsoft.Alm.Cli.OperationArguments.LoadConfiguration()
   場所 Microsoft.Alm.Cli.OperationArguments.get_GitConfiguration()
   場所 Microsoft.Alm.Cli.CommonFunctions.TryReadBoolean(Program program, OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.Program.TryReadBoolean(OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.CommonFunctions.LoadOperationArguments(Program program, OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.LoadOperationArguments(OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.Get()
   場所 Microsoft.Alm.Cli.Program.Run(String[] args)
17:43:09.565336 ...\Program.cs:496      trace: [Run] fatal: ArgumentNullException encountered.
   値を Null にすることはできません。
パラメーター名:path
fatal: ArgumentNullException encountered.
   値を Null にすることはできません。
パラメーター名:path
17:43:09.579985 run-command.c:627       trace: run_command: 'git credential-manager get'
17:43:09.626861 git.c:576               trace: exec: 'git-credential-manager' 'get'
17:43:09.627838 run-command.c:627       trace: run_command: 'git-credential-manager' 'get'
17:43:09.724521 ...\Common.cs:636       trace: [Main] git-credential-manager (v1.15.0) 'get'
17:43:09.771398 ...\Program.cs:496      trace: [Run] System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:path
   場所 Microsoft.Alm.Git.GitInstallation..ctor(String path, KnownGitDistribution version)
   場所 Microsoft.Alm.Git.Where.FindGitInstallations(List`1& installations)
   場所 Microsoft.Alm.Git.Where.GitSystemConfig(Nullable`1 installation, String& path)
   場所 Microsoft.Alm.Git.Configuration.LoadGitConfiguration(String directory, ConfigurationLevel types)
   場所 Microsoft.Alm.Git.Configuration.ReadConfiuration(String directory, Boolean loadLocal, Boolean loadSystem)
   場所 Microsoft.Alm.Cli.OperationArguments.LoadConfiguration()
   場所 Microsoft.Alm.Cli.OperationArguments.get_GitConfiguration()
   場所 Microsoft.Alm.Cli.CommonFunctions.TryReadBoolean(Program program, OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.Program.TryReadBoolean(OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.CommonFunctions.LoadOperationArguments(Program program, OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.LoadOperationArguments(OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.Get()
   場所 Microsoft.Alm.Cli.Program.Run(String[] args)
17:43:09.772375 ...\Common.cs:601       trace: [LogEvent] System.ArgumentNullException: 値を Null にすることはできません。
パラメーター名:path
   場所 Microsoft.Alm.Git.GitInstallation..ctor(String path, KnownGitDistribution version)
   場所 Microsoft.Alm.Git.Where.FindGitInstallations(List`1& installations)
   場所 Microsoft.Alm.Git.Where.GitSystemConfig(Nullable`1 installation, String& path)
   場所 Microsoft.Alm.Git.Configuration.LoadGitConfiguration(String directory, ConfigurationLevel types)
   場所 Microsoft.Alm.Git.Configuration.ReadConfiuration(String directory, Boolean loadLocal, Boolean loadSystem)
   場所 Microsoft.Alm.Cli.OperationArguments.LoadConfiguration()
   場所 Microsoft.Alm.Cli.OperationArguments.get_GitConfiguration()
   場所 Microsoft.Alm.Cli.CommonFunctions.TryReadBoolean(Program program, OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.Program.TryReadBoolean(OperationArguments operationArguments, KeyType key, Nullable`1& value)
   場所 Microsoft.Alm.Cli.CommonFunctions.LoadOperationArguments(Program program, OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.LoadOperationArguments(OperationArguments operationArguments)
   場所 Microsoft.Alm.Cli.Program.Get()
   場所 Microsoft.Alm.Cli.Program.Run(String[] args)
17:43:09.775305 ...\Program.cs:496      trace: [Run] fatal: ArgumentNullException encountered.
   値を Null にすることはできません。
パラメーター名:path
fatal: ArgumentNullException encountered.
   値を Null にすることはできません。
パラメーター名:path
17:43:09.790930 run-command.c:627       trace: run_command: 'bash' '-c' 'test "a$SHELL" '\!'= "a${SHELL%.exe}" || exit 127; cat >/dev/tty && read -r line </dev/tty && echo "$line"'
Username for 'https://github.com': (Wait for input)
```
Gi
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I'm sorry. It is a private repository.
If there is something to do with it, it is the following.
* Internal file is multibyte
```
./930_管理者マニュアル/01_共通/ユーザー設定マニュアル.pdf
```
* User name is multibyte and space
```
田中　太郎
```

It may be similar to https://github.com/git-for-windows/git/issues/1599
Thank you.

**Comment by dscho** [comment] 2018-03-30 11:28
It probable *is* a duplicate of #1599. Have you read the advice there? Does your URL contain special characters? Does Git Credential Manager v1.15.1 (at https://github.com/Microsoft/Git-Credential-Manager-for-Windows/releases/tag/v1.15.1) fix it?

**Comment by kgybels** [comment] 2018-03-31 00:49
This issue happens on 32-bit systems, see Microsoft/Git-Credential-Manager-for-Windows#606.

**Closed** 2018-04-02 14:42 UTC
Labels: duplicate
