### ISSUE TITLE
CI failures on macos targets

### ISSUE THREAD

**Issue by derrickstolee** [git-for-windows/git#5159] opened 2024-09-19 02:10 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I'm not sure if this is new, but it doesn't seem to be related to my changes in my PR. [The PR builds are failing for all macos targets](https://github.com/git-for-windows/git/actions/runs/10929319400/job/30339790737?pr=5157#step:4:1950).

Here is one sample error log, though they are all the same:

```
=== Failed test: t5559-http-fetch-smart-http2 ===
The full logs are in the 'print test failures' step below.
See also the 'failed-tests-*' artifacts attached to this run.
Error: failed: t5559.30 large fetch-pack requests can be sent using chunked encoding
failure: t5559.30 large fetch-pack requests can be sent using chunked encoding 
  	GIT_TRACE_CURL=true git -c http.postbuffer=65536 \
  		clone --bare "$HTTPD_URL/smart/repo.git" split.git 2>err &&
  	{
  		test_have_prereq HTTP2 ||
  		grep "^=> Send header: Transfer-Encoding: chunked" err
  	}
  
  +++ GIT_TRACE_CURL=true
  +++ git -c http.postbuffer=65536 clone --bare https://127.0.0.1:5559/smart/repo.git split.git
  error: last command exited with $?=128
  not ok 30 - large fetch-pack requests can be sent using chunked encoding
  #	
  #		GIT_TRACE_CURL=true git -c http.postbuffer=65536 \
  #			clone --bare "$HTTPD_URL/smart/repo.git" split.git 2>err &&
  #		{
  #			test_have_prereq HTTP2 ||
  #			grep "^=> Send header: Transfer-Encoding: chunked" err
  #		}
  #	
```

**Comment by rimrul** [comment] 2024-09-19 04:00
> t5559.30

I think that's a regression in `curl` 8.10.0 that has been fixed in 8.10.1.

https://lore.kernel.org/git/ZuPKvYP9ZZ2mhb4m@pks.im/

**Comment by dscho** [comment] 2024-09-19 06:14
I concur. This seems to be Homebrew having upgraded to cURL v8.10.0; [It's hitting git/git's CI, too](https://github.com/git/git/actions/runs/10932986544/job/30350707939#step:4:1981).

While Homebrew [did upgrade to v8.10.1 yesterday](https://github.com/Homebrew/homebrew-core/commit/711252449223fdc4b0dda05116bc0ba4498175b8), the `macos-13` runner images [were most recently updated 3 days ago and only include cURL v8.10.0](https://github.com/actions/runner-images/commit/7dd907d86e47e9f770b6b38d215131804c310b34), which contains the bug.

Now, we _could_ update Homebrew every time we run CI, but... [that would regress on a work-around git/git specifically introduced to avoid breaking CI builds due to Homebrew changing things around that require `ci/install-dependencies.sh` to adapt](https://github.com/git/git/commit/f2f47150330c619e03e80886b314cba929543200).

So I fear that the only thing we can do is to wait.

The good news is that we'll probably not have to wait all _that_ long: From looking at [the history of the `runner-images`' included software](https://github.com/actions/runner-images/commits/HEAD/images/macos/macos-13-Readme.md), I get the impression that they are updated on a weekly cadence; It looks like the intervals are between 6-9 days which makes me believe that they are supposed to happen on the same weekday but sometimes are delayed for one reason or another, and the schedule is not adjusted in relation to those delays.

**Comment by dscho** [comment] 2024-09-20 19:51
Judging by [this announcement](https://github.com/actions/runner-images/issues/10559) which is placed [prominently at the top of the current list of included software](https://github.com/actions/runner-images/blob/macos-13/20240916.98/images/macos/macos-13-Readme.md) of the `macos-13` runners, I would expect this here ticket to be addressed on Sep 23rd or very soon thereafter.

**Comment by dscho** [comment] 2024-09-24 07:08
Turns out that I cannot wait it out: v2.46.2 crashed this party! So I opened #5165 to address this issue so that Git for Windows v2.46.2's CI builds won't show it as broken.

**Closed** 2024-09-24 10:07 UTC
