### ISSUE TITLE
VSCode is not set as default editor

### ISSUE THREAD

**Issue by ungps** [git-for-windows/git#1795] opened 2018-08-16 15:57 UTC
Hello,

While writing this, I managed to find the problem (check "P.S").

My setup:
```
$ git --version --build-options
git version 2.18.0.windows.1
cpu: x86_64
built from commit: cd1a74fc9dc8a07626c216940db9a51f25206e03
sizeof-long: 4
```

```
cmd.exe /c ver
Microsoft Windows [Version 6.3.9600]
```

```
Editor Option: VisualStudioCode
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

I was trying to add SublimeText and Atom in the list of possible default editors in Git-For-Windows installer. So, I implemented them, made an installer and tried to test it, but it didn't work (by "didn't work" I mean that it installed successfully, both Sublime and Atom could be selected, but neither one of them were added as default editor)... So, I started debugging, although everything seemed alright.

So:

 * I installed Notepad++ and Git-For-Windows (using the official installer) with Notepad++ as default editor. This worked fine.
 * I installed Git-For-Windows (using the official installer) with Nano as default editor. This also worked.
 * I installed Git-For-Windows (using the official installer) with VSCode as default editor. This did not work. By "did not work" I mean that it installed, but VSCode was not the default editor. I looked in the git system configuration file and, indeed, "code.editor" was not set.

P.S: I just looked one more time through registry and observed that:

 * Data of `HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\notepad++.exe` is:
`C:\Program Files (x86)\Notepad++\notepad++.exe`

 * Data of `HKLM\SOFTWARE\Classes\Applications\Code.exe\shell\open\command` is:
`"C:\Program Files\Microsoft VS Code\Code.exe" "%1"`

` "%1"` is removed from the string at line [1135](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss#L1135), but the `"` at the beginning and at the end of the line are not removed at all. I fixed this, compiled it and now it works. I am going to send a fix for this. I guess that putting your thoughts into words helps debugging. :smile:

**Comment by ungps** [comment] 2018-08-16 22:07
I installed `VSCode - Insiders` to test it as well and it wasn't even detected by installer. Now it is late, but I hope I will get back to it soon. Until that, I fixed the problem with `VS Code` and added `Sublime Text` and `Atom` as default editors.

https://github.com/git-for-windows/build-extra/pull/200

**Comment by zaaraameera2014** [comment] 2018-08-29 21:34
No comment

**Comment by zaaraameera2014** [comment] 2018-08-29 21:35
Check ps

**Comment by SteveALee** [comment] 2018-09-16 13:14
Yup seeing this as well and using the new @code installer and trying to update to G4W 2.19.0

Is there a work around? Can we edit something?

**Comment by shiftkey** [comment] 2018-09-16 15:03
@SteveALee as a workaround you can edit your `~/.gitconfig` to set the `core.editor` value:

![](https://user-images.githubusercontent.com/359239/45597854-87df4200-b9a8-11e8-9d53-6d3f2b30e549.png)

**Comment by SteveALee** [comment] 2018-09-16 16:10
@shiftkey well this is strange. During the update install (overwrite older) I selected notepad++ and autocrlf=auto but I see the following in my `%USERPROFILE%\.gitconfig`

```
[core]
	editor = code --wait
	autocrlf = true
```

**Comment by shiftkey** [comment] 2018-09-16 16:32
@SteveALee the installation configuration is applied to the system Git configuration, not your global Git configuration

**Comment by illusive-man** [comment] 2018-09-17 13:01
I think the problem is that couple months back Microsoft has switched to new type of installation distributive which doesn't require admin access in order to install/update VS Code. I believe Git installer is looking for VS Code installed "old way" and obviously just can't find it.

**Comment by alexbuzzbee** [comment] 2018-09-17 13:05
Also having this issue. Some looking shows VS Code installed at `$USERPROFILE/AppData/Local/Programs/Microsoft VS Code`. This is now the default because it prevents UAC prompts when installing/updating. Git for Windows should check for VS Code in AppData.

**Comment by shiftkey** [comment] 2018-09-17 14:04
For everyone chiming in:

 - Git for Windows would look at a location under `HKEY_LOCAL_MACHINE` in the registry, because up until recently VSCode was a machine-wide install by default
 - Around VSCode version 1.26 they changed the install to not require elevation, which means it would install to a new location `HKEY_CURRENT_USER` for the current user, and Git for Windows doesn't detect that currently
 - On top of the new registry location, there's no "user install" option for Git for Windows, so there's some tricky questions to figure out about how to support this properly over in https://github.com/git-for-windows/build-extra/pull/200#discussion_r211560985

**Comment by dscho** [comment] 2018-12-26 22:01
This has been addressed in the meantime. If `VS Code` is chosen as default editor *and* that editor is installed user-wide only, the `core.editor` setting will be adjusted in `~/.gitconfig` instead of the system-wide config.

**Closed by dscho** 2018-12-26 22:01 UTC
