### ISSUE TITLE
Large LFS file is showed always as changes

### ISSUE THREAD

**Issue by mvorisek** [git-for-windows/git#4396] opened 2023-04-26 12:52 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.0.windows.1
cpu: x86_64
built from commit: 1d90ca2906dd4b7ddaf0669a13c173ec579d794a
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2846]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

nothing special

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

both PowerShell and cmd is affected

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git clone git@github.com:atk4/repro_composer_lfs.git
Cloning into 'repro_composer_lfs'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 18 (delta 0), reused 15 (delta 0), pack-reused 0
Receiving objects: 100% (18/18), 28.89 MiB | 2.93 MiB/s, done.
Updating files: 100% (11/11), done.
Encountered 1 file that should have been a pointer, but wasn't:
        data/GeoLite2-City.mmdb

$ git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   data/GeoLite2-City.mmdb

no changes added to commit (use "git add" and/or "git commit -a")
```
⚠️ please notice some warning during the clone, but the file is checkout correctly and the `git status` on the same checkouted data run on WSL is showing the repo as clean, also the hash of the file is fine everywhere (PowerShell and WSL)

 - What did you expect to occur after running these commands?

I expect `git status` to show cleanly cloned/checkout repo with large LFS file(s) as clean, like on linux/WSL.

 - What actually happened instead?

`git status` and `git diff` is showing cleanly cloned/checkout repo with large LFS file as changed.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/atk4/repro_composer_lfs

**Comment by PhilipOakley** [comment] 2023-04-26 12:58
how large is that file `data/GeoLite2-City.mmdb` ?
Is it larger than 2^31-1, or 2^32-1 which are the current 32 bit signed / unsigned int limit value in Git for Windows (rather than size_t)

**Comment by mvorisek** [comment] 2023-04-26 12:59
about 60 MB

**Comment by mvorisek** [comment] 2023-04-26 13:01
about 60 MB - https://github.com/atk4/repro_composer_lfs/blob/main/data/GeoLite2-City.mmdb

repo is public, can you please reproduce?

**Comment by dscho** [comment] 2023-04-26 13:02
> Encountered 1 file that should have been a pointer, but wasn't:
>         data/GeoLite2-City.mmdb

Doesn't this explain everything? This file was committed as-is by mistake, when it should have been committed using Git LFS, in which case the file that _Git_ sees is a very, very small file.

So the problem is with the repository shape, not with Git for Windows nor with Git LFS.

**Comment by PhilipOakley** [comment] 2023-04-26 13:05
The "should have been a pointer" looks to be an LFS error message, rather than a Git-for-Windows message, so I concur with @dscho

**Comment by mvorisek** [comment] 2023-04-26 13:09
It was commit using GitKraken which should support LFS.

When I was pushing the repro repo, initially I tried to push it under `mvorisek` GH org, that is my private GH account and the push failed, as I have no LFS storage on that org. Then I pushed the repo under `atk4` org which is padi pro GH account and it passed. So I belive the push was done using LFS correctly.

How to debug if the LFS push was done correctly? Can you please check?

Also, can you please do a clean LFS push from your side, I have added a write permission to you both, so I can recheck if the problem is gone?

**Comment by mvorisek** [comment] 2023-04-26 13:21
Thank you guys, the problem is really in the GitKraken client:

- https://github.com/atk4/repro_composer_lfs/blob/cbbf9061694c680d73f76d784dc655171948dba6/data/GeoLite2-City.mmdb - pushed with GitKraken
- https://github.com/atk4/repro_composer_lfs/blob/main/data/GeoLite2-City.mmdb - pushed from CLI

![image](https://user-images.githubusercontent.com/2228672/234588412-391ae870-d9f8-4386-94f8-5cc0e42946fc.png)

**Closed** 2023-04-26 13:22 UTC
Labels: question
