### ISSUE TITLE
the sh in git bash doesn't works properly.

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#68] opened 2015-04-06 14:01 UTC
$ sh
sh: __git_ps1: 未找到命令

**Comment by dscho** [comment] 2015-04-06 16:02
@lygstate as I mentioned a couple of times already, I would appreciate it if you spent time to craft thorough and helpful reports.

This:

> $ sh
> sh: __git_ps1: 未找到命令

tells me exactly nothing. Not what the problem is, not what is expected, not how to reproduce, not which version you tested, not which OS version you are using, not which architecture this is on, nothing.

It does not even present a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve). With the amount of time I spent to explain to you what is required, I would have expected much better.

**Comment by lygstate** [comment] 2015-04-06 17:02
@dscho You need to run sh command
in mingw64 shell, then the error will appear

**Comment by dscho** [comment] 2015-04-06 17:21
No, it does not.

Look, I really spend *a lot* of time trying to make sense of these one- or two-line issues, and it is always frustrating. I also try to figure out whether I can reproduce the issue, no matter how incomplete the report is. So I tried to reproduce even this here issue.

And guess what, as I made clear in my request for more information, I have no idea what the problem is: I see no problem in my command prompt here.

Now, if you would grace me with the information of what *exact* steps you took to get there, I could probably help you get to the same point as I am right now: no problem here.

**Comment by lygstate** [comment] 2015-04-06 17:30
Start mingw64_shell.bat in Git-SDK.
```
$ sh
```
If the problem doesn't reproduce, then maybe it's my computer's problem.

**Comment by dscho** [comment] 2015-04-07 06:24
It really puts a lot of burden on me to ask me to not only fix a problem, but essentially to investigate how to reproduce the problem in the first place. It would have been so much better practice to investigate on your side whether you can reproduce the issue with English locale, too, and report *all* of your findings.

**Comment by lygstate** [comment] 2015-04-07 06:56
@dscho  I don't believe you have ever tried with my instructions.
This is not related the locale

**Comment by dscho** [comment] 2015-04-07 07:39
> speak less, do more

Given that you definitely did not say *enough*, let me follow up with my analysis (because that's what I ended up having to do: this issue report left a *lot* of details out).

I had to ask Google Translate to translate "未找到命令" for me because you did not. It says "Command not found".

That rang a bell: it is a bug that was fixed *long* ago, identified and addressed by @nalla: https://github.com/git-for-windows/build-extra/commit/484f8d092d9ef55806b20c6585fe9f5e81d156ff.

My guess is that you ran the 1.0.0-rc-1 net installer which still contained this bug (and you did not rebuild the net installer from scratch to verify that the bug was actually already fixed, neither did you research the bug database nor the commit history, otherwise you would have found what I found).

So: the Chinese serving as an untranslated red herring, and the lack of really vital information were the culprits that made this bug (that was fixed before being reported) so frustrating for both of us.

**Closed by dscho** 2015-04-07 07:39 UTC

**Comment by lygstate** [comment] 2015-04-07 07:45
I hope you are right, but the fact is not, I am using the newest sdk just installed, and problem appear again. so you have ever type sh in your ming64 shell?
```

 MINGW64 /usr/bin
$ sh
sh: __git_ps1: 未找到命令

 MINGW64 /usr/bin
$ echo $LANG
zh_CN.UTF-8
sh: __git_ps1: 未找到命令

 MINGW64 /usr/bin
$ exit
exit

 MINGW64 /usr/bin
$ export LANG=en_US.UTF-8

 MINGW64 /usr/bin
$ sh
sh: __git_ps1: command not found

 MINGW64 /usr/bin
$


```

**Comment by dscho** [comment] 2015-04-07 07:53
Have a look at the explanation of https://github.com/git-for-windows/build-extra/commit/484f8d092d9ef55806b20c6585fe9f5e81d156ff (yes, I referenced that exact commit above already): if the Git prompt was initialized and you want to start an interactive subshell, you have to pass the `--login` option.
