### ISSUE TITLE
Failure when receiving data from the peer

### ISSUE THREAD

**Issue by melnele** [git-for-windows/git#4194] opened 2022-12-22 04:05 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 
   64-bit

```
$ git --version --build-options
Git-2.39.0.2-64-bit.exe
```

 - Which version of Windows are you running? 
    Windows 11 64-bit
```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.22621.963]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```
### Details

 - Which terminal/shell are you running Git from? 
   Bash/CMD 

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git fetch
or
git push
```
 - What actually happened instead?

   fatal: unable to access 'https://bitbucket.org/*/*.git/': Failure when receiving data from the peer

  I then downgraded to git version 2.38.1.windows.1 and it worked

**Comment by dscho** [comment] 2022-12-22 09:39
> I then downgraded to git version 2.38.1.windows.1 and it worked

@melnele That's a large step, testing only v2.39.0(2) and v2.38.1.

Could you bisect through [the snapshots](https://wingit.blob.core.windows.net/files/index.html) to figure out what causes the regression? My guess is that it's the cURL update, and only v2.39.0(2) has the regression, but not the preceding snapshot (could you also test [this snapshot](https://dev.azure.com/git-for-windows/git/_build/results?buildId=111244&view=artifacts&pathAsName=false&type=publishedArtifacts) which sadly failed to upload?).

**Comment by melnele** [comment] 2022-12-22 16:14
@dscho you are correct I just instaled Git-2.39.0-64-bit.exe and it's working

**Comment by melnele** [comment] 2022-12-22 16:47
> (could you also test [this snapshot](https://dev.azure.com/git-for-windows/git/_build/results?buildId=111244&view=artifacts&pathAsName=false&type=publishedArtifacts) which sadly failed to upload?).

@dscho I tested it and it's working

**Comment by dscho** [comment] 2022-12-22 20:19
@melnele would you have any public URL with which I could try to reproduce the problem?

**Comment by melnele** [comment] 2022-12-22 21:09
@dscho unfortunately the repos I'm working on are private on bitbucket
but I found a similar repo that is public

`$ git clone https://bitbucket.org/anand980980/angular-9-with-angular-material.git`

> Cloning into 'angular-9-with-angular-material'...
> error: RPC failed; curl 56 Failure when receiving data from the peer
> Receiving objects: 100% (276/276), 351.28 KiB | 524.00 KiB/s, done.
> Resolving deltas: 100% (142/142), done.

**Comment by dscho** [comment] 2022-12-22 22:59
> `$ git clone https://bitbucket.org/anand980980/angular-9-with-angular-material.git`

That reproduces here, but only with the Secure Channel backend. It does work with the OpenSSL backend. That suggests that this is a Secure Channel-specific regression in cURL.

I won't be able to investigate or drive this any further in the next few weeks, so @melnele please use this as a workaround if you want to upgrade: `git config --global http.sslBackend openssl`.

**Comment by melnele** [comment] 2022-12-23 01:33
This indeed works thank you for your help.

**Comment by Nashrah-Fatima** [comment] 2022-12-27 07:40
fatal: unable to connect to github.com:
github.com[0: 20.207.73.82]: errno=Unknown error
 This error I got in gitbash

**Comment by malshunaef** [comment] 2023-01-11 15:22
Git Pull Behavior Option: Merge

**Comment by malshunaef** [comment] 2023-01-11 15:23
git fetch

**Comment by dscho** [comment] 2023-01-11 15:46
> > `$ git clone https://bitbucket.org/anand980980/angular-9-with-angular-material.git`
> 
> That reproduces here, but only with the Secure Channel backend. It does work with the OpenSSL backend. That suggests that this is a Secure Channel-specific regression in cURL.

I just tried the same command with a custom build of `libcurl-4.dll` off of https://github.com/curl/curl's tip revision and it did not fail (read: it seems that the regression might have been fixed). Next stop: I'm building `libcurl-4.dll` off of the `curl-7_87_0` tag. If that shows the regression, I will bisect to figure out whether we can quickly do a backport (seeing as no hot-fix version of cURL was released).

**Comment by dscho** [comment] 2023-01-11 20:07
It was a bit harder to bisect this than expected because somewhere in the middle the regression became a flake, and only later did it get fixed. After testing a while I am pretty confident that the regression is fixed by https://github.com/curl/curl/commit/54120efdf64c40c93308dee3935bbed7e1cdc1aa. I'll test with this a bit more, and pending that testing I will open a PR and get fixed Pacman packages deployed.

**Comment by dscho** [comment] 2023-01-11 21:09
/add release note bug A [regression introduced in Git for Windows v2.39.0(2)](https://github.com/git-for-windows/git/issues/4194) that prevented cloning from Bitbucket [was fixed](https://github.com/git-for-windows/MINGW-packages/pull/64).

**Closed** 2023-01-11 22:35 UTC
Labels: bug, sdk-packages

**Comment by dscho** [comment] 2023-01-12 20:51
@melnele @jurko-gospodnetic please test [the latest snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by melnele** [comment] 2023-01-12 22:32
> @melnele @jurko-gospodnetic please test [the latest snapshot](https://wingit.blob.core.windows.net/files/index.html).

@dscho 
I switched back to 
`git config --global http.sslBackend schannel
`
and it's working.

**Comment by dscho** [comment] 2023-01-13 07:28
> > @melnele @jurko-gospodnetic please test [the latest snapshot](https://wingit.blob.core.windows.net/files/index.html).
> 
> @dscho 
> I switched back to 
> `git config --global http.sslBackend schannel
> `
> and it's working.

Thank you for confirming the fix!

**Comment by kandersondaxsonics** [comment] 2023-01-18 13:32
Thank you for this fix.  I apologize for not filing this earlier myself.  I figured it was something local to my machine and/or network, not something more global, as I was the only one in my office having the issue.  I was apparently the only one on the December release!  I will also confirm that the latest release (2.39.1) fixed this for me.

The really frustrating part is that it would work about 1/10 of the time, so it would _usually_ fail, but not always.

**Comment by dscho** [comment] 2023-01-18 20:11
> The really frustrating part is that it would work about 1/10 of the time, so it would _usually_ fail, but not always.

Yep, I also found that very frustrating during my bisecting.

**Comment by jurko-gospodnetic** [comment] 2023-01-22 19:11
On 12.1.2023. 21:51, Johannes Schindelin wrote:
> @melnele <https://github.com/melnele> @jurko-gospodnetic 
> <https://github.com/jurko-gospodnetic> please test the latest snapshot 
> <https://wingit.blob.core.windows.net/files/index.html>.

  Only now got to this and yeah, the problem seems to have been 
resolved. Thanks!

   Best regards,
     Jurko Gospodnetić
