### ISSUE TITLE
Curl bad argument

### ISSUE THREAD

**Issue by glenstewartdev** [git-for-windows/git#5260] opened 2024-11-14 15:16 UTC
I am trying to update git for windows. This command in bash, and powershell cli causes an error and the update fails.

**Command**
git update-git-for-windows

**Error Message**
curl: (43) A libcurl function was given a bad argument

**Comment by rimrul** [comment] 2024-11-14 15:50
Duplicate of #5083

**Closed** 2024-11-14 15:51 UTC
