### ISSUE TITLE
Absolute symbolic links causes change for unmodified file (after switching branch)

### ISSUE THREAD

**Issue by hansfn** [git-for-windows/git#3047] opened 2021-02-16 15:21 UTC
- [ x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

```
Microsoft Windows [Version 10.0.19041.804]
```

```
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
Plink Path: C:\Program Files\PuTTY\plink.exe
SSH Option: Plink
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
```

 - I'm running Git Bash as administrator to be sure that there are no problems with creating symlinks and I have core.symlinks set to true.

### Details

We have many repositories with symbolic links, and we have no problem with relative symbolic links.

I recently added some absolute symbolic links (from my Linux machine). "git pull" didn't show any problems, but after switching branch, I get the following:

```
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Utils/Docker/archiso-builder/config/airootfs/etc/localtime
        modified:   Utils/Docker/archiso-builder/config/airootfs/etc/resolv.conf
[...]
```

Checking one file I see:

```
$ git diff Utils/Docker/archiso-builder/config/airootfs/etc/localtime
diff --git a/Utils/Docker/archiso-builder/config/airootfs/etc/localtime b/Utils/Docker/archiso-builder/config/airootfs/etc/localtime
index 0e35b576..f07da99e 120000
--- a/Utils/Docker/archiso-builder/config/airootfs/etc/localtime
+++ b/Utils/Docker/archiso-builder/config/airootfs/etc/localtime
@@ -1 +1 @@
-/usr/share/zoneinfo/UTC
\ No newline at end of file
+C:/usr/share/zoneinfo/UTC
\ No newline at end of file
```
Any amount of "git restore" or "git stash" will get me back to a clean unmodified status. (Switching back to the original branch doesn't change anything - as expected.)

**Any Git (Bash) options that can fix this or is it a proper bug?**

**Comment by dscho** [comment] 2021-02-16 19:20
This is a duplicate of https://github.com/git-for-windows/git/issues/1772. And it is also a duplicate of https://github.com/git-for-windows/git/issues/2829.

**Closed by dscho** 2021-02-16 19:20 UTC

**Comment by hansfn** [comment] 2021-02-17 08:50
This is embarrassing - I didn't search for symlink(s). Other people doing the same will hopefully find this issue.

Thank you for the quick reply and pointers to existing issues. In my case disabling symlinks for this specific repo was an acceptable work-around, but also sparse-checkout (ignoring the directories with symlinks) would have worked.
