### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by ptoye** [git-for-windows/git#562] opened 2015-12-07 19:16 UTC
I've just downloaded git-for-windows. It uninstalled an earlier
version that I had (about 5 years old) and I got some problems.

1)  It wanted to install into my User directory instead of the
Program Files directory, which is the best place for all programs.
The installer told me that this had access right problems, so I
installed it into another directory. It seemed to go OK.

2)  However, the icons on the desktop pointed to the place that my
previous installation had been ( C:\Program Files (x86)\Git ) - that's
where I'd have hoped that the new installation would go in step 1!

3)  I uninstalled it to see if a cleaner installation would work, and
the GIT-GUI icon didn't disappear from the desktop - minor bug I
suspect.

I uninstalled it and went through the installation again and this time I didn't get any desktop icons at all - I'm pretty sure I asked for them!

Any help in getting it installed with the desktop icons would be welcome.

I'm using Windows 7 home premium 64 bit.

**Comment by dscho** [comment] 2015-12-07 19:25
I am pretty certain that my answer to your email to the Git mailing list crossed with this bug report. As I stated in that answer, I am pretty certain that this is the permission bug that will be fixed in the next Git for Windows version.

**Comment by imiten** [comment] 2016-02-06 09:49
I have citrix desktop at work and I would like to use gitbash as unix emulator.  If I can just extract the software and have it all setup it will be nice.  I can then add bin directory to path and execute bash.  The citrix desktop does not have internet access to all sites so I cannot install cygwin either so prefer downloadable full zip.  current gitforwindows does not let me choose destination install folder.

**Comment by dscho** [comment] 2016-02-06 14:17
Oh my. There have been a couple of releases in the meantime, and since the original report omits the Git for Windows version it talks about, it is now unclear what it talked about. But as I stated, there was a permission bug and it has been fixed in 2.6.4. So I'll close this ticket (I forgot about it, also because of lack of feedback).

@imiten Git for Windows is not a Bash emulator. Current Git for Windows lets you choose the destination install folder: if you use the installer, it is the `/DIR` command-line option, and if you use the portable version, you are asked when you run the `.exe`. In any case, what you ask for is 1) not a bug report, and 2) unrelated to the bug report to which you attached your comment.

**Closed by dscho** 2016-02-06 14:17 UTC
