### ISSUE TITLE
`git show/log/diff --stat` always behaves as is if given `--stat-width=80`

### ISSUE THREAD

**Issue by phil-blain** [git-for-windows/git#3830] opened 2022-04-29 20:22 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.18363.2212]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

none.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Tried in Windows Terminal/PowerShell, Windows Terminal / Git Bash (is that how it's called in this context?) and Mintty / Git Bash (i.e. the "Git Bash" from the  Start menu)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```bash
git clone -b realpath-homedir http://github.com/phil-blain/vscode.git
cd vscode
git show --oneline --stat
```
 - What did you expect to occur after running these commands?

See this output (what I get on Linux):
~~~bash
$ git show --oneline --stat
60a9f3178ec (HEAD -> realpath-homedir, origin/realpath-homedir) environment - canonicalize value of homedir()
 src/vs/platform/environment/node/environmentService.ts           |  3 ++-
 src/vs/platform/environment/test/node/environmentService.test.ts | 31 +++++++++++++++++++++++++++++++
 2 files changed, 33 insertions(+), 1 deletion(-)
~~~

 - What actually happened instead?

Saw this output:
~~~powershell
PS > git show --oneline  --stat
c82a22f3fe6 (HEAD -> realpath-homedir, origin/realpath-homedir) environment - canonicalize value of homedir()
 .../environment/node/environmentService.ts         |  3 ++-
 .../test/node/environmentService.test.ts           | 30 ++++++++++++++++++++++
~~~

i.e. filenames are truncated, behaves as if given `--stat-width=80`.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

See above.

**Comment by dscho** [comment] 2022-05-02 10:16
Git tries to guess the terminal width, the code to do that is encapsulated in [the `term_columns()` function](https://github.com/git-for-windows/git/blob/v2.36.0.windows.1/pager.c#L152-L186).

The problem is that MinTTY (Git for Windows' default terminal) is an _MSYS_ program and uses the emulated pseudo terminals, whereas `git.exe` is _not_ an MSYS program (and therefore has no access to said pseudo terminals).

As a consequence, the canonical way for Win32 console programs to determine the current terminal width fails: [`GetConsoleScreenBufferInfo()`](https://docs.microsoft.com/en-us/windows/console/getconsolescreenbufferinfo) tries to query the Win32 Console, but MinTTY does not use any Win32 Console (and therefore, whatever Console `git.exe` has access to is bogus). The canonical way for _Unix_ programs to determine the current terminal width _also_ fails: `git.exe` has no access to the `ioctl(... TIOCGWINSZ...)` call that the MSYS2 runtime emulates.

Git _does_ try to use the `COLUMNS` variable, but that is typically only defined for the currently-running shell, not for any spawned process (and besides, if you call `git.exe` from, say, a PowerShell window, no Bash is involved). Here is a bit more information: https://stackoverflow.com/a/48016366/1860823

So what we _could_ do is something similar to [what we do in `git_terminal_prompt()` to disable echoing characters when querying passwords](https://github.com/git-for-windows/git/blob/v2.36.0.windows.1/compat/terminal.c#L322-L350): we spawn the `stty.exe` program, which _is_ an MSYS program.

If we start doing this, we must be careful only to do this if we're running interactively: spawning processes is expensive on Windows, and if we start doing this nilly-willy whenever running within a script, the performance impact would be unacceptable.

@phil-blain I hope I gave you enough information to start working on this.

**Comment by phil-blain** [comment] 2022-05-03 17:31
@dscho Thanks a lot for that head-start.

Interestingly, the problem does not manifest itself if running under GDB (!)  At least not when I `run` Git directly, I've not tried attaching instead. I think GDB itself sets `COLUMNS` and this is inherited by the debugee...

So if I understand correctly, we could add a call to `GetConsoleScreenBufferInfo` in `term_columns` (with appropriate CPP macros) and this would fix the problem when running under {cmd, powershell, pwsh, Git Bash} x  {conhost, Windows Terminal}, right ? 

And we would need to separately add a call to `stty` to cover running under MinTTY / Git Bash ?

**Comment by dscho** [comment] 2022-05-04 20:58
> So if I understand correctly, we could add a call to `GetConsoleScreenBufferInfo` in `term_columns` (with appropriate CPP macros) and this would fix the problem when running under {cmd, powershell, pwsh, Git Bash} x {conhost, Windows Terminal}, right ?

It would fix the problem when running in ConHost or in the Windows Terminal, but not in MinTTY, yes.

> And we would need to separately add a call to `stty` to cover running under MinTTY / Git Bash ?

We would do that first, and only fall back to the `GetConsoleScreenBufferInfo()` call if `stty` fails. Or we could first ensure that our [`stdin`/`stdout` is connected to an MSYS-emulated pseudo terminal](https://github.com/git/git/blob/v2.36.0/compat/winansi.c#L560-L590) and only run `stty` if that is the case.

**Comment by phil-blain** [comment] 2022-05-05 13:35
OK I'll try to find some time to try this.

By the way, I tried attaching GDB to the `git` executable, and it fails with:
~~~
$ gdb -q -p $(pgrep git)
Can't attach to process 925 (error 87)
(gdb)
~~~

Both GDB and Git are running in the SDK, both in Windows Terminal. Is that normal ? I'm not administrator (work computer) and do not have "Developer mode" enabled.

Funnily, if I instead use my GDB from MinWG-w64's [mingw builds](https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/), running in PowerShell, and Git's PID from `tasklist`, then I can attach...

**Comment by dscho** [comment] 2022-05-05 18:21
Oh, `git` is a MINGW process all right, probably your SDK only has `/usr/bin/gdb.exe`, i.e. the MSYS variant.

**Comment by phil-blain** [comment] 2022-05-06 12:54
Ah! I understand. ` /mingw64/bin/gdb` (first in PATH) needs the Windows PID (from `tasklist`) whereas `/usr/bin/gdb` understand both the Windows PID or the MSYS PID (from `/usr/bin/pgrep` of the `procps` package)

**Comment by dscho** [comment] 2022-07-14 10:11
@phil-blain any progress?

**Comment by phil-blain** [comment] 2022-07-14 17:08
not on my side.

**Comment by dscho** [comment] 2022-07-15 13:06
Let's leave this open for a while, and if nobody grabs it, close it.

**Comment by dscho** [comment] 2022-08-31 11:48
Let's close it.

**Closed by dscho** 2022-08-31 11:48 UTC
Labels: enhancement, up for grabs
