### ISSUE TITLE
.gitattributes working-tree-encoding bugs with UTF-16 encoding

### ISSUE THREAD

**Issue by stevewgr** [git-for-windows/git#5078] opened 2024-07-28 00:49 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Windows 11
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
 type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I tried both on Powershell, Git Bash and CMD, similar behavior, but partially different.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

All for testing purposes

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```sh
# git version 2.45.2.windows.1
git --version

# open Git Bash
mkdir /tmp/git-bug-poc && cd /tmp/git-bug-poc
git init

# Add the BOM, since iconv doesn't include it
printf '\xFF\xFE' > text.utf16

echo 'hello' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add text.utf16 && git commit -m initial

# append changes to text.utf16
echo 'world' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff1 -a

# create the .gitattributes
echo '*.utf16 text working-tree-encoding=UTF-16LE-BOM eol=LF' > .gitattributes
git add .gitattributes && git commit -m gitattributes

# append changes to text.utf16
echo 'broken' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff2 -a

# reproduce the bug
# note that git bash will silently corrupt the file, whilst on powershell it will actually report the error:
# error: failed to encode 'text.utf16' from UTF-8 to UTF-16LE-BOM
# and leave you with a broken worktree where you can't discard the changes unless you git reset --hard to the commit
# before adding the .gitattributes file.
git checkout HEAD~1

# fix the corruption
git reset --hard HEAD~1
```

 - What did you expect to occur after running these commands?

To not corrupt the files and no error should be thrown.

 - What actually happened instead?

Files corrupted and error is thrown, git worktree is broken.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Full report: https://github.com/ko4life-net/ko/issues/243

**Comment by zufuliu** [comment] 2024-07-31 13:12
I think you need to run `git add --renormalize .` after change `.gitattributes` file?

**Comment by stevewgr** [comment] 2024-08-03 05:28
> I think you need to run `git add --renormalize .` after change `.gitattributes` file?

@zufuliu thanks for this, despite `--renormalize` being one of the first solutions I attempted without success, your advice encouraged me to investigate further. It's important to note that `git add --renormalize .` does not work implicitly. To achieve the desired effect, I had to specify the exact file names. Therefore, I used `find . -name "*.utf16" -type f -exec git add --renormalize {} \;` to properly renormalize the Git index.

A more robust and perhaps more aggressive approach is:
```sh
git rm -rf --cached .
git add .
```
This method ensures that every affected file is thoroughly renormalized according to the `.gitattributes` configurations.

Through trial and error, I discovered that renormalization must occur within the same commit when modifying the `.gitattributes` file. Failing to do so can lead to file corruption in one of the revisions (as documented below). This critical detail is not clearly outlined in the documentation, and I encountered numerous discussions on this issue, highlighting the ambiguity and unreliability of this feature when making such changes to a repository.

This raises the question of why Git does not automatically renormalize files based on `.gitattributes` configurations. One would expect this behavior when these configurations are added.

### UTF-16 Little Endian without BOM (UTF-16LE)

```sh
# open Git Bash
mkdir /tmp/git-bug-poc && cd /tmp/git-bug-poc
git init

echo 'hello' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add text.utf16 && git commit -m initial

echo 'world' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff1 -a

echo '*.utf16 text working-tree-encoding=UTF-16LE eol=LF' > .gitattributes
git add .gitattributes && git commit -m gitattributes

echo 'broken' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add --renormalize text.utf16 && git commit -m diff2

git checkout HEAD~1
```

Suddenly `text.utf16` file is corrupted and git converted it to 4 bytes per character:
```
Offset(h) 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F  Decoded text

00000000  68 00 00 00 65 00 00 00 6C 00 00 00 6C 00 00 00  h...e...l...l...
00000010  6F 00 00 00 0A 00 00 00 77 00 00 00 6F 00 00 00  o.......w...o...
00000020  72 00 00 00 6C 00 00 00 64 00 00 00 0A 00 00 00  r...l...d.......
```

I would have to `git checkout HEAD~2` before the adding the `gitattributes` commit for the file to be fixed. Same behavior with or without the `--renormalize` argument.


### UTF-16 Little Endian with BOM (UTF-16LE-BOM)

```sh
# open Git Bash
mkdir /tmp/git-bug-poc && cd /tmp/git-bug-poc
git init

# Add the BOM, since iconv doesn't include it
printf '\xFF\xFE' > text.utf16

echo 'hello' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add text.utf16 && git commit -m initial

echo 'world' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff1 -a

echo '*.utf16 text working-tree-encoding=UTF-16LE-BOM eol=LF' > .gitattributes
git add .gitattributes && git commit -m gitattributes

echo 'broken' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add --renormalize text.utf16 && git commit -m diff2

git checkout HEAD~1
```

### Solution (?)

```sh
# open Git Bash
mkdir /tmp/git-bug-poc && cd /tmp/git-bug-poc
git init

# Add the BOM, since iconv doesn't include it
printf '\xFF\xFE' > text.utf16

echo 'hello' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add text.utf16 && git commit -m initial

echo 'world' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff1 -a

echo '*.utf16 text working-tree-encoding=UTF-16LE-BOM eol=LF' > .gitattributes
find . -name "*.utf16" -type f -exec git add --renormalize {} \;
git add .gitattributes && git commit -m gitattributes

echo 'worked' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff2 -a

git checkout HEAD~1
```

**Comment by zufuliu** [comment] 2024-08-03 06:42
@stevewgr good to know your problem is solved 👍.

**Comment by stevewgr** [comment] 2024-08-03 06:52
> @stevewgr good to know your problem is solved 👍.

Indeed, thank you! 👍 but just to highlight and note to git's maintainers, something should still be done here, like updating the docs or|and fixing git's implementation to handle such edge cases.

**Comment by PhilipOakley** [comment] 2024-08-03 09:42
On 03/08/2024 07:52, Steve Williams wrote:
>     @stevewgr <https://github.com/stevewgr> good to know your problem is
>     solved 👍.
> 
> Indeed, thank you! 👍 but just to highlight and note to git's
> maintainers, something should still be done here, like updating the docs
> or|and fixing git's implementation to handle such edge cases.
> 

Ideal time to get involved and submit a patch to upstream Git ;-)

**Comment by tboegi** [comment] 2024-08-03 19:47
@stevewgr Thanks for the report, and reproducable example.

One side question: You are the first one (?) to report, that this command didn't work:

`git add --renormalize .
`
Did you run the command in the right directory ?
What does 
`git ls-files --eol`
say before and after the command ?

Another thing, please see my comment(s) inline

```
git init

echo 'hello' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add text.utf16 && git commit -m initial

echo 'world' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git commit -m diff1 -a

echo '*.utf16 text working-tree-encoding=UTF-16LE eol=LF' > .gitattributes
git add .gitattributes && git commit -m gitattributes

````
 Now we have a somewhat "weird" situation:
 text.utf16 is commited with utf16 (in  the index), but the .gitattributes file
 says that it is utf-8 in the index. This is important below.
````
echo 'broken' | iconv -f UTF-8 -t UTF-16LE >> text.utf16
git add --renormalize text.utf16 && git commit -m diff2

git checkout HEAD~1
````
 so yes, we will see a kind of UTF32 in the worktree.
 Why that ?
 Because the text.utf16 is still commited with UTF-16 in the index,
but the .gitattributes file says "it is commited with UTF-8, so please convert
into UTF-16LE when checking it out."
So what happens ?
For each byte in the index you get 2 bytes in the working-tree.
That is all what had been asked for, and I do not see a problem/bug here.


If you think, that the documentation can be improved:
We are all maintainers of the project.
Do you think that you can issue a patch / pull request to improve things ?

**Comment by dscho** [comment] 2024-08-06 08:55
Seems that the follow-up tasks for the original reporter are to submit a patch to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently). I'll therefore close this here ticket.

**Closed by dscho** 2024-08-06 08:55 UTC
