### ISSUE TITLE
gitk's "touching paths" is broken (has both false positives and false negatives)

### ISSUE THREAD

**Issue by anthonyvdotbe** [git-for-windows/git#3914] opened 2022-06-24 06:26 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.739]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: FFOnly
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not that I can think of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell Core 7.2.4

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir foo
pushd foo
git init
echo a > a.txt
git add a.txt
git commit -m a
echo b > b.txt
git add b.txt
git commit -m b
echo aa > a.txt
echo bb > b.txt
git add a.txt b.txt
git commit -m ab
gitk
Find commit touching paths: a.txt
```
 - What did you expect to occur after running these commands?

Only commits `a` and `ab` are highlighted.

 - What actually happened instead?

Commits `b` and `ab` are highlighted.

**Comment by rimrul** [comment] 2022-06-24 07:44
This regression in `git diff-tree --stdin` [has been fixed in Git 2.36.1](https://github.com/git/git/blob/master/Documentation/RelNotes/2.36.1.txt#L10-L13).

Duplicate of #3815

**Closed** 2022-06-24 07:45 UTC
Labels: bug, duplicate, git-upstream
