### ISSUE TITLE
Unlink of file XXX failed. Should I try again?

### ISSUE THREAD

**Issue by gpakosz** [git-for-windows/git#500] opened 2015-10-21 12:37 UTC
Hello,

Sometimes, after a e.g. `git fetch`, Git decides to auto GC a repository. In the process, it fails to remove `.pack` and `.idx` files. Likely, those files are locked.

Git can ask the question for more than 50 times depending on the number of unreachable commits there are following branch deletion and remotes pruning. When Git starts to complain, either you answer "no" repeatedly until the auto GC ends, or you have to CTRL-C. Ultimately, invoking `git gc` manually removes most of the pack files

**Comment by dscho** [comment] 2015-10-21 14:45
@gpakosz hmm. Do you think you can come up with a reproducible example? Something like a shell script that creates a small repository, clones it, then sets `gc` thresholds ridiculously low, adds more commits and then fetches them?

**Comment by kgybels** [comment] 2015-10-21 15:32
@dscho Something like this?

    KGybels@PC-KG MINGW64 /c/git/bug
    $ git --version
    git version 2.6.1.windows.1
    
    KGybels@PC-KG MINGW64 /c/git/bug
    $ ls
    steps.sh*
    
    KGybels@PC-KG MINGW64 /c/git/bug
    $ cat steps.sh
    #!/bin/bash
    
    git init origin
    cd origin
    touch test1.txt
    git add test1.txt
    git commit -m v1
    originpath=`pwd`
    cd ..
    git clone file://$originpath clone
    cd origin
    touch test2.txt
    git add test2.txt
    git commit -m v2
    cd ../clone
    git config gc.autoPackLimit 1
    git fetch
    
    KGybels@PC-KG MINGW64 /c/git/bug
    $ ./steps.sh
    Initialized empty Git repository in C:/git/bug/origin/.git/
    [master (root-commit) 775d4c6] v1
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 test1.txt
    Cloning into 'clone'...
    remote: Counting objects: 3, done.
    remote: Total 3 (delta 0), reused 0 (delta 0)
    Receiving objects: 100% (3/3), done.
    Checking connectivity... done.
    [master 25c50c7] v2
     1 file changed, 0 insertions(+), 0 deletions(-)
     create mode 100644 test2.txt
    remote: Counting objects: 2, done.
    remote: Compressing objects: 100% (2/2), done.
    remote: Total 2 (delta 0), reused 0 (delta 0)
    Unpacking objects: 100% (2/2), done.
    From file:///c/git/bug/origin
       775d4c6..25c50c7  master     -> origin/master
    Auto packing the repository in background for optimum performance.
    See "git help gc" for manual housekeeping.
    Counting objects: 5, done.
    Delta compression using up to 4 threads.
    Compressing objects: 100% (3/3), done.
    Writing objects: 100% (5/5), done.
    Total 5 (delta 0), reused 3 (delta 0)
    Unlink of file '.git/objects/pack/pack-97e500b3cd7317acb865c29bb44d66886116c51a.pack' failed. Should I try again? (y/n) n
    Unlink of file '.git/objects/pack/pack-97e500b3cd7317acb865c29bb44d66886116c51a.idx' failed. Should I try again? (y/n) n
    
    KGybels@PC-KG MINGW64 /c/git/bug
    $

**Comment by dscho** [comment] 2015-10-22 13:02
@kgybels very nice!

**Comment by gpakosz** [comment] 2015-10-22 13:06
Oh nice @kgybels, I added the task in my TODO but I'm thankful you took over. :+1:

**Comment by cs96and** [comment] 2016-01-13 15:02
I sometimes have this problem and I believe it is related to TortoiseGit's TGitCache.exe having those files open.

**Comment by gpakosz** [comment] 2016-01-13 15:14
It's definitely not related to TortoiseGit. As you can see above, @kgybels provided a script that reproduces the problem. It's totally unrelated to any Git frontend

**Comment by dscho** [comment] 2016-01-13 16:37
@gpakosz sorry for the long delay! In the meantime, I had taken care of https://github.com/git-for-windows/git/issues/446 which made this fix substantially quicker, though.

**Comment by cs96and** [comment] 2016-01-13 16:40
@gpakosz But is TortoiseGit installed?  It can have those files locked even though you are currently using git on the command line.

**Comment by dscho** [comment] 2016-01-13 16:41
@cs96and if TortoiseGit, or for that matter, *any* software locks pack files, the "Unlink of file XXX failed." is actually the proper response and there is no bug in Git.

The bug at hand is caused by Git *itself* keeping locks on the files that it wants to garbage-collect. And that bug is what I just fixed.

**Comment by linquize** [comment] 2016-01-13 16:46
Not just TortoiseGit, Atom text editor also sometimes locks the packfile too.

**Comment by dscho** [comment] 2016-01-13 16:47
Well, Atom text editor is included in "*any* software", no?

Apart from that, what business does Atom *text* editor have to lock pack files? Seriously.

**Comment by kostix** [comment] 2016-01-13 17:06
@dscho, because it's more of an IDE (written in HTML5 on top of node.js and craploads of other bits of what is considered "hot stuff" these days) than a text editor. IDEs strive to provide VCS integration. Supposedly they're using `libgit2` or something. Since it's done by github folks I'd not be surprised to actually find pieces of GfW inside (as it's AFAIK true for that piece of software named "Github for Windows").

All in all, failing to lock a locked file is for sure the only sensible way to go IMO.

**Comment by gpakosz** [comment] 2016-01-13 20:00
@dscho no worry, thanks for taking care of fixing it, much appreciated

**Comment by dscho** [comment] 2016-01-27 10:04
This hit [upstream's `master`](https://github.com/git/git/commit/3c809405cb35679dd5205bf0ea118b7ee9256abb), so it will be fixed in the next release of Git for Windows.

**Closed by dscho** 2016-01-27 10:04 UTC
Labels: bug, git

**Comment by gpakosz** [comment] 2016-01-27 12:10
Thank you @kgybels, @dscho and @gitster. This one has been nagging me literally for years.

**Comment by dscho** [comment] 2016-01-27 15:32
@gpakosz note that in Open Source, you can always work on your own itches... :smiley:

**Comment by gpakosz** [comment] 2016-01-27 16:32
@dscho That's true. I confess I never really tried to climb the learning curve of being able to compile and debug Git For Windows. And the first years it was all too easy to blame NTFS ;)

**Comment by dscho** [comment] 2016-01-27 19:10
It's always easy to blame NTFS. And for the record: when I started working on Git, I also had no idea how to compile and debug Git for Windows...

**Comment by kgybels** [comment] 2018-06-30 14:01
There is a regression from `2.17.1.windows.2` to `2.18.0.windows.1`. I already send a [patch](https://public-inbox.org/git/20180630133822.4580-1-kgybels@infogroep.be/T/#u) to the Git mailing list.

**Comment by dscho** [comment] 2018-07-01 12:30
> I already send a patch to the Git mailing list.

Thanks! Can you let me know when it gets into `next` so I can cherry-pick? (I would like to avoid cherry-picking a commit that I later have to revert in order to cherry-pick a newer iteration... maintenance... or do you want me to pick it as a quick fix already?)

**Comment by kgybels** [comment] 2018-07-26 17:48
> @dscho Can you let me know when it gets into next so I can cherry-pick?

Change is merged to `next` on 2018-07-24 at 71c05d27b6. It will also be merged to `master`.

**Comment by dscho** [comment] 2018-07-27 15:55
I opened a PR. Thank you so much!
