### ISSUE TITLE
Providing an option to open GIT application on the right click menu

### ISSUE THREAD

**Issue by yansari88** [git-for-windows/git#3532] opened 2021-11-12 14:49 UTC
Hi, 

After a Windows 10 update, it looks like my option to launch GIT via the right-click menu has gone away.  Is this a known issue right now? Could you someone please provide me the steps on how to enable this.

Thanks

**Comment by derrickstolee** [comment] 2021-11-12 14:58
Likely you mean you upgraded to Windows 11, which changed the task menu. It now looks like this:
![image](https://user-images.githubusercontent.com/570044/141487128-676c54db-d7ea-4e56-9c73-02b23e8ff4eb.png)

But, if you select "Show more options" then you'll see "Git Bash Here"

![image](https://user-images.githubusercontent.com/570044/141487210-6a1e6412-38c2-4df7-915b-35760ea340fd.png)

**Comment by rimrul** [comment] 2021-11-13 08:17
If you didn't upgrade to Windows 11, you might be experiencing the same issue as #3109.

In that case it should be fixed by just rerunning the Git for Windows installer.

**Comment by dscho** [comment] 2021-11-15 06:52
Due to the lack of detail in the report, it is unclear whether it was a Windows 11 upgrade or [a Windows upgrade removing context menu entries by accident](https://github.com/git-for-windows/git/issues/3109). I will therefore close this ticket preemptively.

@yansari88 if the issue is still not addressed, please feel free to provide [a full report](https://github.com/git-for-windows/git/tree/HEAD/.github/ISSUE_TEMPLATE.md).

**Closed by dscho** 2021-11-15 06:52 UTC
Labels: question, unclear
