### ISSUE TITLE
git update-git-for-windows 2.246.0 ERROR

### ISSUE THREAD

**Issue by chicleduro** [git-for-windows/git#5085] opened 2024-07-30 15:19 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bits

```
$ git --version --build-options

git version 2.45.2.windows.1
cpu: x86_64
built from commit: 91d03cb2e4fbf6ad961ace739b8a646868cb154d
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

11 64-bits

```
$ cmd.exe /c ver

Microsoft Windows [Versión 10.0.22631.3958]
(c) Microsoft Corporation. Todos los derechos reservados.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Update

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git update-git-for-windows 
Git for Windows 2.45.2.windows.1 (64-bit)
Update 2.46.0.windows.1 is available
curl: (43) A libcurl function was given a bad argument
```

 - What did you expect to occur after running these commands?

```
$ git update-git-for-windows 
Git for Windows 2.45.2.windows.1 (64-bit)
Update 2.46.0.windows.1 is available
curl: (43) A libcurl function was given a bad argument
```

 - What actually happened instead?

ERROR

**Comment by squidfall** [comment] 2024-07-30 20:34
This is a duplicate of #5083.

**Closed** 2024-07-31 04:41 UTC
Labels: duplicate

**Comment by chicleduro** [comment] 2024-07-31 19:01
No puedo actualizar mi git batch
