### ISSUE TITLE
msysGit used to provide an ssh command that could be used in Powershell too. With git-for-windows, is there a way to get ssh work in PowerShell again?

### ISSUE THREAD

**Issue by behrangsa** [git-for-windows/git#393] opened 2015-09-16 00:48 UTC
Hi,

msysGit used to provide an ssh command that could be used in Powershell too. With git-for-windows, is there a way to get ssh work in PowerShell again?

**Comment by nalla** [comment] 2015-09-16 05:31
this is what I did, and it seems to work:

```
PS C:\User\nalla> cd C:\git-sdk-64
PS C:\git-sdk-64> cd .\usr
PS C:\git-sdk-64\usr> cd .\bin
PS C:\git-sdk-64\usr\bin> ./ssh.exe
usage: ssh [-1246AaCfGgKkMNnqsTtVvXxYy] [-b bind_address] [-c cipher_spec]
           [-D [bind_address:]port] [-E log_file] [-e escape_char]
           [-F configfile] [-I pkcs11] [-i identity_file]
           [-L address] [-l login_name] [-m mac_spec]
           [-O ctl_cmd] [-o option] [-p port]
           [-Q cipher | cipher-auth | mac | kex | key]
           [-R address] [-S ctl_path] [-W host:port]
           [-w local_tun[:remote_tun]] [user@]hostname [command]
```

So I think you only need to add your `C:\path\to\git-installation\usr\bin\` folder to your global `PATH` environment variable if you want to have that functionality.

**Comment by dscho** [comment] 2015-09-16 06:36
> With git-for-windows, is there a way to get ssh work in PowerShell again?

Come on, you can do better than this. Seriously, you overestimate my mind reader capabilities.

You might want to consider improving this report substantially, according to our [guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), and if you want to use our time wisely, you would be well advised to provide a [Minimal, Complete and Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by behrangsa** [comment] 2015-09-16 08:16
@dscho :smiley: 

Okay, here's the scenario: Previously when msysGit was not deprecated and Git for Windows was not released, msysGit would add `ssh.exe` to the `PATH` and it would become also available under PowerShell.

If I am not wrong, rather than mingw, it was using cygwin.

However after a vanilla installation of Git for Windows, I noticed the `ssh` command is no longer available under windows.

Here's a somewhat related story: [Making a better, somewhat prettier, but definitely more functional Windows Command Line](http://www.hanselman.com/blog/MakingABetterSomewhatPrettierButDefinitelyMoreFunctionalWindowsCommandLine.aspx). However I prefer avoiding installing a third-party app and creating a `.bat` file for executing `ssh`.

Re @nalla's advice, unfortunately `ssh.exe` does not even exist in that directory for me:

![git for windows](https://cloud.githubusercontent.com/assets/18451/9899628/60b64904-5c9e-11e5-9506-c07f6850cef0.png)

So I was wondering if you could add `ssh.exe` to your distro such that it can be used in PowerShell as well. Again, ideally don't want to have both of cygwin and mingw installed on my PC.

Thanks.

**Comment by nalla** [comment] 2015-09-16 08:34
Please read my commit again. I was speaking of the directory `Git\usr\bin`.

**Comment by dscho** [comment] 2015-09-16 08:52
> msysGit would add ssh.exe to the PATH

Careful. The equivalent of msysGit is Git for Windows' *SDK*. And that SDK still has `ssh.exe` in the `PATH`.

> If I am not wrong, rather than mingw, it was using cygwin.

Careful! There is no Cygwin in Git for Windows. There are parts of MSys2, though. And you probably meant to say that `ssh.exe` was an MSys program and now is an MSys2 program. If that is what you meant to say, I would agree with you.

> However after a vanilla installation of Git for Windows, I noticed the ssh command is no longer available under windows.

Now, vanilla means that you clicked through all of those installer pages. And one of them said explicitly that you have a choice as to what gets added to your `PATH`. We spent a lot of time to write the explanations, you should read them, they are really good ! :stuck_out_tongue_winking_eye: 

> Re @nalla's advice, unfortunately ssh.exe does not even exist in that directory for me:

As @nalla pointed out, you missed the `usr/` in `C:\Program Files\Git\usr\bin`.

Now, if all of these ramblings in this ticket basically point to a mistake in the installer where it prefixes the `PATH` with `/bin/` instead of the entire `/bin/:/mingw64/bin/:/usr/bin/`, then that would be a useful outcome for me. Let's see...

<clickety-click>

But no, there is no such bug. As intended, both `/mingw64/bin` *and* `/usr/bin` are [added to the `PATH`](https://github.com/git-for-windows/build-extra/blob/d930be0c2063e1f1499676db005f719dbfb78de3/installer/install.iss.in#L1454-L1458) if you choose the correct option, i.e. the one that reads

> ## Use Git and optional Unix tools from the Windows Command Prompt
>
> Warning: This will override Windows tools like "find" and "sort". Only
> use this option if you understand the implications.

If you have *any* idea how to improve the descriptions so that people in a similar situation as yours would have an easier time understanding what those options are about, I would welcome a Pull Request.

**Comment by behrangsa** [comment] 2015-09-16 09:47
My man (or men should I say)! :grinning:

First of all thanks for helping me with this issue – I manually added the `usr/bin` folder to my `PATH` and now it works as expected.

Besides, we are humans and we are not always at our best all the time. A sleepless night, an argument at work, a headache, etc. and we do stupid things (e.g. clicking through all the installation steps without paying attention).

Now for whatever reason I liked your humorous response and it put a smile on my face. But come on, no need to throw it in my face! :smiley: Or maybe you didn't because as I said reading your comment put a smile on my face :-)

Anyway, thanks for this great project and all the best!

**Comment by behrangsa** [comment] 2015-09-16 09:53
Plus:

> if you have any idea how to improve the descriptions so that people in a similar situation as yours would have an easier time understanding what those options are about, I would welcome a Pull Request.

I think there can be a confirmation step such as "Are you sure you **don't** want to add the optional Unix tools to the Windows Command Prompt?" That might be helpful.

However I am afraid I am not a C/C++ programmer. I am not even a Windows programmer – I mainly do Java, JavaScript, and Ruby so unfortunately I can't help with a pull request.

**Comment by dscho** [comment] 2015-09-16 10:05
Hahaha! ;-) You put that smile right back on *my* face.

In any case, the Pull Request would be for a part of our InnoSetup configuration that is self-explanatory to any Java/JavaScript/Ruby programmer, I would think. [Judge for yourself](https://github.com/git-for-windows/build-extra/blob/d930be0c2063e1f1499676db005f719dbfb78de3/installer/install.iss.in#L598-L610).

As your question was answered, I close this ticket. Feel free, however, to reopen it (or just comment on it) if anything is left unclear.

**Closed by dscho** 2015-09-16 10:05 UTC
Labels: question
