### ISSUE TITLE
Warning message: "Terminal is not fully functional"

### ISSUE THREAD

**Issue by johne53** [git-for-windows/git#1572] opened 2018-03-21 07:45 UTC
I initially reported this on the mailing list (for Git for Windows) but it got no response so maybe it needs to get flagged up to the developers....

Some years ago I installed TortoiseGit (back when it was around v1.something) and it was then using MsysGit to provide its services. Everything worked well so I just carried on using it. Then (a couple of weeks ago) I needed to upgrade. I uninstalled both TortoiseGit and MsysGit and I re-installed TortoiseGit (now at v2.6). The newer version needs Git for Windows so I installed 2.16.2 (the latest version?)

Mostly everything works - but if I open a Command Prompt and type "git branch" I see this output:-  "WARNING: terminal is not fully functional - (press RETURN)" And if I do press RETURN the command seems to complete normally. FWIW the same thing happens if use the Command Prompt that comes with Git for Windows ("Git CMD"). Just wondering if anyone can explain what's wrong here? All other git commands seem to work normally (i.e. it's just an annoyance rather than a major problem).

### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Microsoft Windows [Version 6.1.7601] (Windows 7 - 32-bit)

 - What options did you set as part of the installation? Or did you choose the
   defaults?
Defaults AFAICR

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
Updated from an older copy of TortoiseGit (which was previously running with MsysGit). However, I uninstalled both TGit and MsysGit before updating.

### Details
 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
Git for Windows command prompt and also Visual Studio's command prompt

 - What commands did you run to trigger this issue?
git branch

 - What did you expect to occur after running these commands?
I expected it to list my (checked out) branches

 - What actually happened instead?
WARNING: terminal is not fully functional
-  (press RETURN)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
All repositories

**Comment by kgybels** [comment] 2018-03-21 15:49
Since you get this problem even in Git CMD, you probably have a global TERM variable set in Windows. Please remove it, and try again.

**Comment by johne53** [comment] 2018-03-21 16:14
Thanks, you're absolutely right. Unfortunately I've no idea what might be setting it :-(

However... if (instead of unsetting it) I set it to something unexpected (e.g. an empty string), 'git branch' now gives me this:-

      4 [main] less 2832 cygwin_exception::open_stackdumpfile: Dumping stack trace to less.exe.stackdump

Does that offer any clue as to what might be setting it? Cygwin isn't installed on my system so I'm guessing it's possibly some 3rd party app which maybe got built with Cygwin.

**Comment by dscho** [comment] 2018-03-21 23:40
> Thanks, you're absolutely right. Unfortunately I've no idea what might be setting it :-(

I *think* there were reports that some other software sets `TERM` to `dumb`.

> However... if (instead of unsetting it) I set it to something unexpected (e.g. an empty string), 'git branch' now gives me this:-
> 
>   4 [main] less 2832 cygwin_exception::open_stackdumpfile: Dumping stack trace to less.exe.stackdump

This is a bug that should be already fixed in our latest preview: https://github.com/git-for-windows/git/releases/tag/v2.17.0-rc0.windows.1

Could you test whether this fixes that issue for you?

**Comment by johne53** [comment] 2018-03-22 09:16
Thanks. I'll probably be able to try the preview version tomorrow. Do I need to uninstall Git for Windows (currently at 2.16.2) or will the new installer just update it) ?

Also... if we assume that some other s/ware needs TERM to be set to "dumb" for some reason, could GFW be modified somehow to ignore that or will they both be constantly fighting each other?

From what I've observed, unsetting TERM seems to make GFW display coloured text (whereas when TERM=dumb it's just normal black+white). Maybe there are other differences too - but that's the only obvious one.

Thanks for all your help.

**Comment by dscho** [comment] 2018-03-22 17:10
> Do I need to uninstall Git for Windows (currently at 2.16.2) or will the new installer just update it) ?

You can use the Portable Git to have a side-by-side installation, in addition to your "official" one.

> if we assume that some other s/ware needs TERM to be set to "dumb" for some reason, could GFW be modified somehow to ignore that or will they both be constantly fighting each other?

Sure. The problem is: how/where? Any ideas?

**Comment by johne53** [comment] 2018-03-23 06:24
Leave a comment

**Comment by johne53** [comment] 2018-03-23 06:25
> Sure. The problem is: how/where? Any ideas?

if I open a Command Prompt and type "git branch" I see this output:- "WARNING: terminal is not fully functional - (press RETURN)" And if I do press RETURN the command seems to complete normally.

**Comment by johne53** [comment] 2018-03-23 06:27
> Sure. The problem is: how/where? Any ideas?

Going back to my original post...

**Comment by johne53** [comment] 2018-03-23 06:38
> Sure. The problem is: how/where? Any ideas?

Going back to my original post....

> if I open a Command Prompt and type "git branch" I see this output:- "WARNING: terminal is not fully functional - (press RETURN)" And if I do press RETURN the command seems to complete normally

Given that "git branch" seems to complete normally, maybe the warning message could just get missed out in this particular case?

**Comment by dscho** [comment] 2018-03-23 13:45
> > Sure. The problem is: how/where? Any ideas?
> 
> Going back to my original post....
> 
> > if I open a Command Prompt and type "git branch" I see this output:- "WARNING: terminal is not fully functional - (press RETURN)" And if I do press RETURN the command seems to complete normally
> 
> Given that "git branch" seems to complete normally, maybe the warning message could just get missed out in this particular case?

I meant: *where* should we unset that `TERM`? How do we intuit that it was unintentional?

> I just updated to version 2.17.0.rc0 but my Command Line git is now worse!! Whenever I issue any git command I now see this getting printed (usually multiple times) :-
> 
> > warning: failed to restrict file handles (1450)

Could you please untangle this ticket by opening a new ticket about that problem? It is really important to hammer out bugs in the -rc phase, otherwise every user might be bitten by the time v2.17.0 is final.

**Comment by johne53** [comment] 2018-03-23 14:13
> I meant: where should we unset that TERM? 

Ah sorry, I misunderstood. This might be a red herring but on my systems, TERM="dumb" seems to be present on each system where Microsoft's Visual Studio is installed (and not present if it's not installed). So I'm guessing it probably is needed for some reason. Couldn't it just be ignored in that particular case? I was previously using MsysGit which didn't give me this problem.

> warning: failed to restrict file handles (1450)
> 
> Could you please untangle this ticket by opening a new ticket about that problem?

 

Yes - firstly I'll revert back to version. If the problem goes away I'll then create a new ticket.

**Comment by dscho** [comment] 2018-03-24 11:34
I guess that Git for Windows 1.x (*not* msysGit, you never developed Git for Windows 1.x, so you never had that development environment called msysGit) had a bug where it would override the `TERM` veriable.

The thing is: what if the user *intended* to set `TERM`? In that case, Git for Windows *must not* override it.

In other words, there must be a place in the installer where the user can opt-in to override `TERM` *just* inside Git for Windows.

**Comment by johne53** [comment] 2018-03-24 12:33
Hi dscho - there's no need to override TERM. From what I can see, an intelligent terminal (i.e. non-dumb) enables certain enhancements (e.g. coloured text) whereas a dumb terminal disables them. So it's obvious from reading the text whether those enhancements are present or not - I can't see why the user needs to be warned about the situation (especially over & over again). Just don't print the warning (or maybe print it once but give the user an option to disable future warnings).

**Comment by dscho** [comment] 2018-03-24 12:46
You see the warning because terminfo-aware software *does* interpret the value of `TERM`, as intended.

**Comment by johne53** [comment] 2018-03-24 12:50
But why does the user constantly need to get warned about this? Let him see the warning if he wants to but surely he should be able to turn it off somehow?

**Comment by dscho** [comment] 2018-03-24 20:49
Him *or her*, you meant.

And there *is* a way to turn the warning off: by changing `TERM`.

In my opinion, there is room for improvement here by telling the user about a potentially unwanted `TERM` value, and letting them override it. But this needs to be done carefully. There are several millions Git for Windows users, and if we mess this up, I will pay for it. So I want to avoid that.

**Comment by johne53** [comment] 2018-03-25 07:41
Is there a way where I can turn off the warning message somehow - but without ending up with coloured text?

**Comment by dscho** [comment] 2018-03-25 13:13
If you don't want colored text, set `diff.color=false` and `ui.color=false`.

**Comment by johne53** [comment] 2018-03-25 14:04
Do I set this up from TortoiseGit somehow? Or from a Command Line? Or is there a file somewhere that I'll need to edit? I tried issuing these commands from a Command Prompt:-

> git config --global diff.color false
> git config --global ui.color false

and I also tried these variants:-

> git config --global diff.color "false"
> git config --global ui.color "false"

but none of them made any difference :-(

**Comment by johne53** [comment] 2018-03-28 10:37
> If you don't want colored text, set diff.color=false and ui.color=false

I tried a couple of attempts (above) but I still got the coloured text Is there somewhere else I should be setting this up?

**Comment by kgybels** [comment] 2018-03-28 20:34
@johne53 It's `color.ui` not `ui.color`. @dscho led you astray, since he's very busy you should consult the manual instead, [color.ui](https://git-scm.com/docs/git-config#git-config-colorui):
> This variable determines the default value for variables such as color.diff and color.grep that control the use of color per command family. Its scope will expand as more commands learn configuration to set a default for the --color option. Set it to false or never if you prefer Git commands not to use color unless enabled explicitly with some other configuration or the --color option. Set it to always if you want all output not intended for machine consumption to use color, to true or auto (this is the default since Git 1.8.4) if you want such output to use color when written to the terminal.

However, even then it won't work for `git branch`. The problem is that Git For Windows sets `color.branch=auto` in `C:\ProgramData\Git\config`, so `color.ui` won't be used, as stated in the documentation for [color.branch](https://git-scm.com/docs/git-config#git-config-colorbranch):
> A boolean to enable/disable color in the output of git-branch[1]. May be set to always, false (or never) or auto (or true), in which case colors are used only when the output is to a terminal. If unset, then the value of color.ui is used (auto by default).

I just did a clean installation of Git for Windows, with all options default in the installer, and I got the following configuration:
```
$ git --version
git version 2.16.2.windows.1

$ cat /c/ProgramData/Git/config
[core]
        symlinks = false
        autocrlf = true
        fscache = true
[color]
        diff = auto
        status = auto
        branch = auto
        interactive = true
[help]
        format = html
[rebase]
        autosquash = true
```

@dscho Do these color configurations still need to be there, or can we change the installer to omit them?

@johne53 Here is what you need to disable color, given the current situation:
```
git config --global color.diff false
git config --global color.status false
git config --global color.branch false
git config --global color.ui false

**Comment by johne53** [comment] 2018-03-29 08:05
@kgybels Thanks for clarifying all that. I typed those 4 lines you suggested and it seems to have done the trick (i.e. as long as I unset the value of TERM).

> Do these color configurations still need to be there, or can we change the installer to omit them?



This mighn't be practical but IMHO it'd be better to have a config option to display (or not display) the warning message - i.e.

> [warning]
>         branch = true

(or 'false' if needed...)

**Comment by kgybels** [comment] 2018-03-29 21:12
@johne53 The warning message is not from `git`, but from `less`, which is used as the [default pager](https://git-scm.com/docs/git-config#git-config-corepager) by `git`.

If you specify `less -d` as pager, less will not warn about your terminal:
```
$ less --help | grep -A 1 dumb
  -d  ........  --dumb
                  Dumb terminal.
```

You can configure this with: `git config --global core.pager "less -d"`
However, you will not be able to scroll back in `less` when using a dumb terminal.

Since the documentation for [core.pager](https://git-scm.com/docs/git-config#git-config-corepager) states `The value is meant to be interpreted by the shell.`, you can also use: `git config --global core.pager "TERM=cygwin less"`. This will give you a more functional pager.

Yet another solution is to create a batch file:
```
$ cat less.bat
@set TERM=
@less.exe %*
```

And use it as your pager: `git config --global core.pager "/c/path/to/batch/less.bat"`.

If this is still not sufficient, you can try improving less yourself. The code can be found at:
http://www.greenwoodsoftware.com/less/

For version 530 the code that prints the warning is at lines 236-237 in main.c:
```
	if (missing_cap && !know_dumb)
		error("WARNING: terminal is not fully functional", NULL_PARG);
```

You could add a patch for the MSYS2 package of less that Git for Windows uses at:
https://github.com/Alexpux/MSYS2-packages/tree/master/less

Alternatively, you can try figuring out which software sets a global TERM variable, and file a bug for said software.

**Comment by johne53** [comment] 2018-03-30 08:27
@kgybels Some great information there and thanks for all your help with this (and thanks again to everyone who's contributed). Initially I've applied the simpler option:-: 

git `config --global core.pager "less -d"`

which seems fine at the moment. I'll try the alternative option ("TERM=cygwin less") if I hit any problems. BTW...

FWIW I haven't homed in precisely on what sets **TERM=dumb** but it only seems to be present on systems where I've got visual C++ installed (so I'm assuming that's the culprit...)

**Comment by dscho** [comment] 2018-03-30 10:24
> Do these color configurations still need to be there, or can we change the installer to omit them?

@kgybels I don't know... what are Git's own defaults?

**Comment by kgybels** [comment] 2018-04-19 19:58
>@dscho I don't know... what are Git's own defaults?

They all default to color.ui, which defaults to auto, according to the documentation.

**Comment by dscho** [comment] 2018-04-20 21:17
> They all default to color.ui, which defaults to auto, according to the documentation.

It is correct. In color.c, we see that passing -1 to `want_color()` lets it use `git_use_color_default`, which defaults to `GIT_COLOR_AUTO`. And the three respective settings do default to -1: `branch_use_color` is initialized to -1, `wt_status_prepare()` sets `use_color` to -1, and `diff_use_color_default` is also set to -1.

So I guess these defaults can go...

**Comment by dscho** [comment] 2020-01-01 19:21
I'll just close this ticket: while it would be an easy thing to remove the defaults, nobody seemed to be interested in opening a PR.

**Closed by dscho** 2020-01-01 19:21 UTC
Labels: question
