### ISSUE TITLE
Git for windows crashed in Windows 10 latest build (14251.1000)

### ISSUE THREAD

**Issue by likidu** [git-for-windows/git#627] opened 2016-01-28 06:47 UTC
Hi,

I got Git crash immediately running under latest insider build of 14251.1000. I knew its arguable about the "latest" one, but please help. Thank you.

Git for Windows version 2.7.0.

**Comment by lashchev** [comment] 2016-01-28 06:55
Same problem here :-(

**Comment by alexsh** [comment] 2016-01-28 08:10
Same problem here, error module is ntdll.dll, exception code:  0xc0000005

**Comment by dscho** [comment] 2016-01-28 08:26
People. Please read our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) and improve this report accordingly. Anything else will only result in major frustration on all sides, and that is not what anybody would possibly want.

**Comment by paladox** [comment] 2016-01-28 11:23
I also get this problem when using git command. It crashes git. I also get Segmentation fault inside the git program.

**Comment by dscho** [comment] 2016-01-28 11:44
@paladox and you also do not list precise version informations as well as a precise account (preferably with a copy-paste of the output) of what you did. Really, please read [the issue reporting guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines). It is really frustrating to receive so incomplete information.

**Comment by paladox** [comment] 2016-01-28 11:47
Sorry. When running git --version  I get Segmentation fault because of git command being faulty in the latest windows 10 insider build as of 27/01/2016. Also I am running 2.7.0 64-bit.

**Comment by paladox** [comment] 2016-01-28 11:48
@dscho All I do is start git bash from the windows start button then in git bash I do this command git to test it. And returns Segmentation fault.

**Comment by dscho** [comment] 2016-01-28 11:49
Did you try cmd, what commands crash, etc etc etc etc etc

**Comment by paladox** [comment] 2016-01-28 11:52
yes. As soon as I enter git in cmd running as admin it brings up the crash dialog for git for windows.

Also when starting git ui I get this error popup 

cannot determine git version:

child kild: segmentation violation

git gui requires git 1.5.0 or later.

**Comment by dscho** [comment] 2016-01-28 12:01
What happens when you run `net use /?` in cmd?

**Comment by paladox** [comment] 2016-01-28 12:03
When I run  net use /? it brings up the Net Command has stopped working.

**Comment by paladox** [comment] 2016-01-28 12:48
When I run net use /? it brings up the Net Command has stopped working.

**Comment by Briles** [comment] 2016-01-28 16:00
I'm having the same issue in `Windows 10 14251.1000 64-bit` and 64-bit Git versions later than `2.6.2.windows.1`

Running installed or portable `git.exe` results in `Git for Windows has stopped working` error message and logs the following in Event Viewer:

```
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0xc50
Faulting application start time: 0x01d159deab2de7c2
Faulting application path: C:\PortableGit-2.7.0-64-bit\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 31967d76-6b7d-4e9f-af3b-40ae2867739c
Faulting package full name: 
Faulting package-relative application ID:
```


Running `net use /?` results in:

```
Faulting application name: net.exe, version: 10.0.14251.1000, time stamp: 0x56a54798
Faulting module name: ucrtbase.dll, version: 10.0.14251.1000, time stamp: 0x56a5447e
Exception code: 0xc0000005
Fault offset: 0x0000000000021415
Faulting process id: 0xf58
Faulting application start time: 0x01d159dbc6b316a7
Faulting application path: C:\WINDOWS\system32\net.exe
Faulting module path: C:\WINDOWS\system32\ucrtbase.dll
Report Id: 89cf4fbc-8269-41c7-8595-970945bda050
Faulting package full name: 
Faulting package-relative application ID: 
```


Git-gui also fails to start with:

```
Cannot determine Git version:
child killed: segmentation violation
Git Gui requires Git 1.5.0 or later.
```

Running `git`  from Bash results in:

```

Brian@Brian-PC MINGW64 /
$ git --version
Segmentation fault
```

**Comment by jaccarmac** [comment] 2016-01-28 17:28
Running `git` from CMD results in a "Git for Windows has stopped working" message. Running the command from Git Bash results in a segmentation fault.

Windows 10 `rs1_release 14251`, Git, `2.7.0.0`.

```
Log Name:      Application
Source:        Application Error
Date:          28-Jan-16 10:24:27
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      valentine
Description:
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0x1188
Faulting application start time: 0x01d159f0bd604efe
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 26293b56-fb4b-4f4f-a875-399a099f81de
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-28T17:24:27.501423400Z" />
    <EventRecordID>625</EventRecordID>
    <Channel>Application</Channel>
    <Computer>valentine</Computer>
    <Security />
  </System>
  <EventData>
    <Data>git.exe</Data>
    <Data>2.7.0.0</Data>
    <Data>00000000</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14251.1000</Data>
    <Data>56a54488</Data>
    <Data>c0000005</Data>
    <Data>00000000000a6eeb</Data>
    <Data>1188</Data>
    <Data>01d159f0bd604efe</Data>
    <Data>C:\Program Files\Git\mingw64\bin\git.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>26293b56-fb4b-4f4f-a875-399a099f81de</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by heldchen** [comment] 2016-01-28 18:15
same here: Windows 10 rs1_release 14251 x64, Git, 2.7.0.0 x64. if the WER reports are of any use, I can provide them privately.

```
Log Name:      Application
Source:        Application Error
Date:          28.01.2016 18:58:48
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      X-WING
Description:
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0x3188
Faulting application start time: 0x01d159f589ae1376
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 67e92489-a5fa-4010-9adf-8d04be5d0f31
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-28T17:58:48.285256200Z" />
    <EventRecordID>655</EventRecordID>
    <Channel>Application</Channel>
    <Computer>X-WING</Computer>
    <Security />
  </System>
  <EventData>
    <Data>git.exe</Data>
    <Data>2.7.0.0</Data>
    <Data>00000000</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14251.1000</Data>
    <Data>56a54488</Data>
    <Data>c0000005</Data>
    <Data>00000000000a6eeb</Data>
    <Data>3188</Data>
    <Data>01d159f589ae1376</Data>
    <Data>C:\Program Files\Git\mingw64\bin\git.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>67e92489-a5fa-4010-9adf-8d04be5d0f31</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

```
Log Name:      Application
Source:        Windows Error Reporting
Date:          28.01.2016 18:58:50
Event ID:      1001
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      X-WING
Description:
Fault bucket 120399744865, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: git.exe
P2: 2.7.0.0
P3: 00000000
P4: ntdll.dll
P5: 10.0.14251.1000
P6: 56a54488
P7: c0000005
P8: 00000000000a6eeb
P9: 
P10: 

Attached files:
C:\ProgramData\Microsoft\Windows\WER\Temp\WER4CE5.tmp.WERInternalMetadata.xml
C:\Users\Thomas\AppData\Local\Temp\WER54C6.tmp.appcompat.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_git.exe_d792d3b2e130c95f532e21b8c261b227ab646c8_da76d18a_36f75532

Analysis symbol: 
Rechecking for solution: 0
Report Id: 67e92489-a5fa-4010-9adf-8d04be5d0f31
Report Status: 1
Hashed bucket: 97b4e7a1d26115cd399602c67e2da1ff
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Windows Error Reporting" />
    <EventID Qualifiers="0">1001</EventID>
    <Level>4</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-28T17:58:50.532295500Z" />
    <EventRecordID>656</EventRecordID>
    <Channel>Application</Channel>
    <Computer>X-WING</Computer>
    <Security />
  </System>
  <EventData>
    <Data>120399744865</Data>
    <Data>4</Data>
    <Data>APPCRASH</Data>
    <Data>Not available</Data>
    <Data>0</Data>
    <Data>git.exe</Data>
    <Data>2.7.0.0</Data>
    <Data>00000000</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14251.1000</Data>
    <Data>56a54488</Data>
    <Data>c0000005</Data>
    <Data>00000000000a6eeb</Data>
    <Data>
    </Data>
    <Data>
    </Data>
    <Data>
C:\ProgramData\Microsoft\Windows\WER\Temp\WER4CE5.tmp.WERInternalMetadata.xml
C:\Users\Thomas\AppData\Local\Temp\WER54C6.tmp.appcompat.txt</Data>
    <Data>C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_git.exe_d792d3b2e130c95f532e21b8c261b227ab646c8_da76d18a_36f75532</Data>
    <Data>
    </Data>
    <Data>0</Data>
    <Data>67e92489-a5fa-4010-9adf-8d04be5d0f31</Data>
    <Data>1</Data>
    <Data>97b4e7a1d26115cd399602c67e2da1ff</Data>
  </EventData>
</Event>
```

**Comment by kowsheek** [comment] 2016-01-28 19:35
Same issue here

```
Log Name:      Application
Source:        Application Error
Date:          1/28/16 2:33:34 PM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      KATRA
Description:
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a6eeb
Faulting process id: 0x1da4
Faulting application start time: 0x01d15a02c7130628
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: cf21ce19-c83a-46d1-9a44-3dba8a9e6971
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-28T19:33:34.754836400Z" />
    <EventRecordID>1363</EventRecordID>
    <Channel>Application</Channel>
    <Computer>KATRA</Computer>
    <Security />
  </System>
  <EventData>
    <Data>git.exe</Data>
    <Data>2.7.0.0</Data>
    <Data>00000000</Data>
    <Data>ntdll.dll</Data>
    <Data>10.0.14251.1000</Data>
    <Data>56a54488</Data>
    <Data>c0000005</Data>
    <Data>00000000000a6eeb</Data>
    <Data>1da4</Data>
    <Data>01d15a02c7130628</Data>
    <Data>C:\Program Files\Git\mingw64\bin\git.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data>
    <Data>cf21ce19-c83a-46d1-9a44-3dba8a9e6971</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>
```

**Comment by sailro** [comment] 2016-01-28 20:00
Same issue here, but probably due to this Windows build in my opinion (Windows 10 Pro Insider Preview x64 build 14251.rs1_release.160124-1059). Git 2.7.0 x32 or x64 is completely broken, unable to run Git (the installer is also failing when trying to call git). Git 2.6.2 works but I cannot push (git-remote-https was unable to start correctly error code 0x0000142)

**Comment by kowsheek** [comment] 2016-01-28 20:36
@sailro I restarted several times (before reinstall and after) no luck.

I installed `git version 1.9.4.msysgit.0` and it seems to be working with push and no crashes as yet.

**Comment by shiftkey** [comment] 2016-01-28 20:40
It was brought to my attention by @onovotny that you should be able to workaround this issue by installing an earlier version of Git for Windows:

> For those people running into git crashes on Windows 10 14521, install 2.6.1 (it'll downgrade higher vers): https://github.com/git-for-windows/git/releases/tag/v2.6.1.windows.1
> https://twitter.com/onovotny/status/692538905539780609

**Comment by onovotny** [comment] 2016-01-28 20:44
Seems like 2.6.2 also works.

**Comment by sailro** [comment] 2016-01-28 20:45
onovotny 2.6.2 works locally but crash with network actions (pull/push). I will try 2.6.1 then 1.9.x

**Comment by sailro** [comment] 2016-01-28 20:50
@onovotny 2.6.1 crash also with network actions (pull/push)

**Comment by onovotny** [comment] 2016-01-28 20:51
awesome! isn't it great to be on beta OS code :)

**Comment by sailro** [comment] 2016-01-28 20:52
I love that :(. After next release I will opt out

**Comment by onovotny** [comment] 2016-01-28 20:53
So now the Q is what's the latest version that works? :)

**Comment by sailro** [comment] 2016-01-28 20:54
https://github.com/msysgit/msysgit/releases/tag/Git-1.9.5-preview20150319 works

**Comment by sailro** [comment] 2016-01-28 20:55
We have to rollback to the 1.9.x generation with msysgit

**Comment by onovotny** [comment] 2016-01-28 21:00
Or us VS 2015 with LibGit2 to do network ops, at least until the next build ;)

**Comment by paladox** [comment] 2016-01-28 21:20
I rolled back to prevous build and now git works.

**Comment by darrelmiller** [comment] 2016-01-28 22:28
Just as a point of reference, I'm running GFW 3.0.11.2 on Win10 14251.rs1_release.160124-1059 on a Surface Pro 3 and I am not seeing any issues.

**Comment by singhkay** [comment] 2016-01-28 22:30
@darrelmiller I'm currently broken with the 3.0.12.0 GFW update on that build but I believe GFW ships with it's own version of a portable git. Look under ``%LocalAppData%\GitHub``

**Comment by shiftkey** [comment] 2016-01-28 22:32
@darrelmiller @singhkay we're shipping v2.5.3 and my testing suggests anything network related is silently failing right now. I'm also investigating to give a more solid repro so we can see just what has been impacted here.

**Comment by dscho** [comment] 2016-01-29 06:36
> isn't it great to be on beta OS code :)

@onovotny could you imagine what such a comment does to somebody who did worked (unlike you) on this bug for the entire day yesterday?

**Comment by dscho** [comment] 2016-01-29 06:45
So for everybody who actually appreciates that they can sit in the peanut gallery, doing exactly nothing while waiting for others to work on Open Source:

I have to test this a bit more, but it looks as if the `-fstack-protector-strong` flag we introduced with version 2.6.3 causes a bad interaction with the changes in said internal build. It will take quite a substantial time, still, to figure out exactly what is going wrong, but if my further tests indicate that this is indeed the only culprit here, I will remove that flag for the next release. My hunch is that libcurl might have been compiled with the same flag, which would be consistent with the problems with `git-remote-https.exe` (but then also `fetch` should have the problem, I missed whether that was tested at all).

**Comment by dscho** [comment] 2016-01-29 06:59
> > isn't it great to be on beta OS code :)
> 
> @onovotny could you imagine what such a comment does to somebody who did work (unlike you) on this bug for the entire day yesterday?

@onovotny just to make sure that you understand: this lack of respectful tone is not acceptable in the Git for Windows project, [as per our code of conduct](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md) by which I also expect bug reporters and even commenters like you to abide.

By your own choosing you are but a guest in this project, and now I am forced to ask you to exercise a friendly tone. It cannot be in your interest, either, to distress the developers who help you by fixing the problems you experience; We definitely deserve so much better. However satisfying that venting might have been for you in the moment, it now forces me to enforce the code of conduct, which is unfair for two reasons: it is highly unpleasant for me, and it also further distracts me quite a bit from doing what I actually want to do: make Git for Windows better.

So let's stop all that dissonant conversation now and continue in an appropriate manner.

**Comment by shiftkey** [comment] 2016-01-29 07:36
@dscho

> but if my further tests indicate that this is indeed the only culprit here, I will remove that flag for the next release

As the one who encouraged this change, I'm :thumbsup: to dropping that flag now to help ameliorate the situation until we can get to the root of the problem.

> My hunch is that `libcurl` might have been compiled with the same flag, which would be consistent with the problems with `git-remote-https.exe` (but then also fetch should have the problem, I missed whether that was tested at all)

This is interesting - and might explain why i can see Git for Windows 2.5.3 (the one we ship in GitHub Desktop - and before `-fstack-protector-strong` was incorporated) silently failing when doing `fetch`/`push`/pull`.

Is there anything I can do to help move this along?

**Comment by dscho** [comment] 2016-01-29 08:05
Hey @shiftkey, thanks for chiming in (and helping actively).

> Is there anything I can do to help move this along?

I had a brief look at the `mingw-w64-x86_64-curl` package and it seems that it does have code in `ltmain.sh` that looks at the `-fstack-protector` flag (note that also the weak form triggered this bug here, and it seems to be related to code in `compat/mingw.c` because I do not get the crash with the flag but without `mingw.o` in `libgit.a` (which does require a *ton* of hacks to be able to link)).

At this point, I think the safest bet is for me to continue, unless you have cycles to spend on [rebuilding](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages) `mingw-w64-x86_64-curl`?

**Comment by dscho** [comment] 2016-01-29 08:10
> I love that :(. After next release I will opt out

@sailro Please note that while it might have given you momentary relief to vent like this, the effect it has on developers who try to fix this bug is horrible. That is why we ask in our [code of conduct](https://github.com/git-for-windows/git/blob/master/CONTRIBUTING.md) to keep the tone friendly and patient.

It is also in your own best interest to do so: such comments do nothing but delay the fix. So let's go back to a constructive conversation.

**Comment by shiftkey** [comment] 2016-01-29 08:17
@dscho I've punched out for the week (and am kind of exhausted from unrelated stuff achieved this week) but I'll have a read over those links when I get a quiet moment on Monday morning.

Happy hunting!

**Comment by dscho** [comment] 2016-01-29 08:19
@shiftkey no worries! I know you work hard (and you certainly worked hard for Git for Windows previously), so you did your due. Will keep you updated via this ticket.

**Comment by NateLing** [comment] 2016-01-29 09:27
@dscho How long can you solve this problem ,I cant work now.

**Comment by heldchen** [comment] 2016-01-29 09:39
@dscho I have just noticed that the curl.exe file from the git mingw package also fails in the same manner as git.exe. but if i read your comment regarding

> At this point, I think the safest bet is for me to continue, unless you have cycles to spend on rebuilding mingw-w64-x86_64-curl?

correct, you probably already know this as well... thanks for your continued efforts!

**Comment by dscho** [comment] 2016-01-29 12:47
@NateLing I am sorry that you cannot work now, but if you really need this so badly, you should consider putting some effort into fixing this yourself. It is Open Source for that reason, after all, that you are empowered to fix things that do not work for you.

**Comment by dscho** [comment] 2016-01-29 13:13
So here is a temporary (unsigned) installer that Works For Me (except fetching/pushing via HTTPS): https://github.com/dscho/git/releases/download/v2.7.0.windows.1.win10.14251/Git-2.7.0-win10.14251-64-bit.exe. Note: this file will go away, and is provided only for your information. If it is not working for you or eats your children, you have been warned.

**Comment by paladox** [comment] 2016-01-29 13:14
Could it be this know issue in that build causing the problem

Due to a recent memory management change, you may see periodic app crashes or other memory related app errors. The workaround is to reboot your PC.

Please try rebooting your computer and see if that works.

**Comment by onovotny** [comment] 2016-01-29 13:15
@dscho Wow....first, my response was totally sarcasm, not any kind of insult on anyone working on Git (or anything else). My apologies if it was misinterpreted.

Microsoft has said repeatedly that the beta builds *will* break things. In this case, it broke Git, which is hugely inconvenient for all of us.

That said, it *is* a beta. I would not expect this to continue or be in the released OS. My main point, if any, is that this is a Windows bug, not a Git bug and so it's on them to fix it.

Oren

**Comment by dscho** [comment] 2016-01-29 13:16
> Please try rebooting your computer and see if that works.

@paladox it does not fix it here.

**Comment by dscho** [comment] 2016-01-29 13:16
> first, my response was totally sarcasm

@onovotny And my response made it clear that it is not at all appreciated, yes?

**Comment by dscho** [comment] 2016-01-29 13:17
@onovotny and please note that you clarification, while you probably intended well, still takes me away from further work on this bug.

**Comment by onovotny** [comment] 2016-01-29 13:18
@dscho as you wish

**Comment by dscho** [comment] 2016-01-29 13:18
@onovotny it has nothing to do with "as I wish". Do you want me to work on the bug or to be distracted by the issue tracker? As *you* wish...

**Comment by onovotny** [comment] 2016-01-29 13:20
@dscho Far be it for me to say who should work on what. My point in all of this is that it is a Windows bug and that there should be nothing for Git to fix. This bug should be closed as *External* and efforts could be spent fixing real issues.

**Comment by paladox** [comment] 2016-01-29 13:22
I'm going to report this to Windows here http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_web/upgrading-from-11099-to-14251-is-causing-git-for/f306090a-788e-4514-ae66-66b9ae94b5ff?tm=1454073751268

**Comment by dscho** [comment] 2016-01-29 13:24
> Far be it for me to say who should work on what. [...] This bug should be closed as External and efforts could be spent fixing real issues.

So first you say you do not tell people what to do. And then you finish by telling people what to do?

And you're still distracting me from fixing the bug.

**Comment by dscho** [comment] 2016-01-29 13:26
> I'm going to report this to Windows here http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_web/upgrading-from-11099-to-14251-is-causing-git-for/f306090a-788e-4514-ae66-66b9ae94b5ff?tm=1454073751268

@paladox would you not want to make it easier for the good Windows developers by first coming up with a *minimal*, complete & verifiable example? I mean, we can make it inconsiderately hard for them, or incredibly easy. My preference would be with the latter, but of course, that would entail more than just shooting off a cheap message.

**Comment by paladox** [comment] 2016-01-29 13:27
Hi well I was only trying to help. maybe Microsoft know what the problems is and could tell us what needs fixing.

**Comment by dscho** [comment] 2016-01-29 13:32
@paladox And I was trying to help you to help them. After all, we can do better than just coughing out some sloppy bug report.

**Comment by darrelmiller** [comment] 2016-01-29 13:38
@dscho Just as an FYI, considering you brought it up.  You are not being friendly, patient, welcoming, considerate, nor respectful.  But hey, don't let me distract you from working on the temporary workaround to avoid the bug in the beta Windows OS..

**Comment by dscho** [comment] 2016-01-29 13:48
@darrelmiller I am sorry if the conversation has led me to forget my manners. My apologies!

**Comment by heldchen** [comment] 2016-01-29 13:49
@darrelmiller what if it's *not* a bug in windows beta, but a new feature that will break git in any future windows builds? after all, they seem to be introducing some new malware prevention services/functions starting with this build. nobody knows at this point

at least @dscho is actively working on reproducing/mitigating the problem. I can understand his frustration when comments here are demanding, sarcastic or otherwise non-helpful while he invests significant amounts of his time looking for a fix. keeping calm in such situations can be difficult.

**Comment by dscho** [comment] 2016-01-29 13:52
@heldchen thank you for translating my sentiments into correct and polite English. You read my mind!

**Comment by atrol** [comment] 2016-01-29 14:17
> awesome! isn't it great to be on beta OS code :)

Maybe there also some kind of misunderstanding in this conversation.
Could be that @onovotny means OS = Operating System wherase @dscho means OS = Open Source = Git.

@dscho, keep up the good work.

**Comment by 810** [comment] 2016-01-29 14:44
Microsoft is working on a fix:
https://twitter.com/demyte/status/692831900256186368

**Comment by paladox** [comment] 2016-01-29 15:09
@dscho sorry I will add more details just that I didn't have enough time to add the information about how I got the error. But Microsoft is aware and is fixing it.

**Comment by dscho** [comment] 2016-01-29 15:12
@paladox My guess is that by the time you have more information to add, the developers who got tasked to take care of your report will have developed at least partially the same information, causing a lot of duplicated effort. I wanted to avoid that.

**Comment by paladox** [comment] 2016-01-29 15:29
Ok sorry.

**Comment by dscho** [comment] 2016-01-29 16:55
> Microsoft is working on a fix:
> https://twitter.com/demyte/status/692831900256186368

And more information from Gabe Aul: https://twitter.com/GabeAul/status/692850509590335488:
> It's due to the memory management bug that was in the known issues

@shiftkey to keep you updated: neither libcurl nor any of its dependencies uses `-fstack-protect`. So this is likely just a red herring for the real issue, and I will unfortunately not be able to provide a full work-around, short of suggesting to use Cygwin ;-)

**Comment by shiftkey** [comment] 2016-01-29 22:34
@dscho thanks for the update

> I will unfortunately not be able to provide a full work-around

Totally understandable! I'm happy to stop here and see what happens when the next fast ring release drops...

> short of suggesting to use Cygwin ;-)

Uh, I'll wait to see what MSFT comes back with - the suggestion to "restart the machine" didn't seem to work for me either.

**Comment by dscho** [comment] 2016-01-30 14:39
According to insider information, this bug is fixed in Windows 10 build 14253 and later.

**Closed by dscho** 2016-01-30 14:39 UTC
Labels: bug, unclear

**Comment by dscho** [comment] 2016-01-30 15:41
I confirm that this bug is fixed in Windows 10 build 14256.

**Comment by heldchen** [comment] 2016-01-30 15:42
cool, thanks for your efforts!

**Comment by bachagas** [comment] 2016-02-03 11:59
Hello there,

> I confirm that this bug is fixed in Windows 10 build 14256.

I didn't get access to build 14256 yet, did anybody already have?

For those experiencing this issue and who really needs Git daily, a (maybe better) workaround than the suggested by Microsoft on the known issues (rollback to the previous build) is to use another git client that is independent of "Git for Windows", such as [GitKraken ](http://www.gitkraken.com/).

Regards,

**Comment by dscho** [comment] 2016-02-03 12:24
> I didn't get access to build 14256 yet, did anybody already have?

Yes, I do ;-)

Seriously, you need to be prepared for things to break when you are on any kind of early access program. The entire point is to *catch* breakages early there. You will most likely find that Git for Windows is *not* the only application affected by the memory management issue, so eventually you will have to roll back anyway instead of keeping fire-fighting.

**Comment by SeanBlader** [comment] 2016-02-03 16:22
Apologies to the interruption to dscho's day with this notification, but I just wanted to say thank you for the patch. I'm still on 14251 but as soon as I get access to 14256 I'll switch to the slow ring. If it makes you feel any better Microsoft also broke VirtualBox with this release. Those are the only two problems I've seen so far.

**Comment by shiftkey** [comment] 2016-02-04 00:12
Build 14257 has just landed on the Fast Ring - https://twitter.com/GabeAul/status/695034380524216320

**Comment by 810** [comment] 2016-02-04 01:44
For me Jenkins with git is now working, only there is still a issue with git desktop:

trace: built-in: git 'clone' '--progress' '--recursive' '--' 'https://github.com/810/Kunena-Forum.git' 'Kunena-Forum'
02:38:40.375513 run-command.c:335       trace: run_command: 'git-remote-https' 'origin' 'https://github.com/810/Kunena-Forum.git'
Cloning into 'Kunena-Forum'...
fatal: Unable to find remote helper for 'https'

**Comment by shiftkey** [comment] 2016-02-04 02:22
@810 can you confirm this is working with Git for Windows 2.7.x - I'm planning to update GitHub Desktop to this version very soon, and don't quite have access to the latest Fast Ring build...

**Comment by 810** [comment] 2016-02-04 02:27
im running Git Desktop 3.0.12.0

But i have a response, from a microsoft edge program manager, and he said that the fix isn't in the new release. But he has to double check the issue now

**Comment by shiftkey** [comment] 2016-02-04 02:29
@810 GitHub Desktop is using Git 2.5.3 for some operations - are you able to install Git for Windows 2.7.0 (can be installed alongside) and see that a clone succeeds?

**Comment by 810** [comment] 2016-02-04 02:34
with 2.7.0 the same: fatal: Unable to find remote helper for 'https'

**Comment by shiftkey** [comment] 2016-02-04 02:34
Ok cool, so we're not completely fixed yet. Thanks for confirming my suspicion.

**Comment by shiftkey** [comment] 2016-02-04 04:41
@810 after discussing with more people as they've updated to 14257, I don't believe this is a general issue with the new release but something specific to your setup (as you could reproduce it across different versions of Git for Windows).

Please open a new issue with a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) to help us understand the issue you're seeing.

**Comment by dscho** [comment] 2016-02-04 07:29
> Apologies to the interruption to dscho's day with this notification

@SeanBlader apologies accepted. But please note that you are not interrupting my day. You are probably referring to my earlier unfortunate outbreaks when I was really struggling to get this bug fixed as soon as possible or at least to provide a work-around, and all I got for trying were remarks that seemed to be designed to make me feel bad for my efforts. I am certain you understand!

**Comment by dscho** [comment] 2016-02-04 07:40
> with 2.7.0 the same: fatal: Unable to find remote helper for 'https'

@810 @shiftkey this sounds like something deleted `git-remote-https.exe`. Or it could be there, but fails to find a dependency (maybe related to #390? But why would it still fail in 2.7.0, then?).

@810 can you look for the file `C:\Program Files\Git\mingw64\libexec\git-core\git-remote-https.exe`? (If you installed elsewhere, or the 32-bit version, please adjust the path accordingly.)

If it is not there, is it possible that some overzealous anti-virus in your setup quarantined it?

If it is there, could you open a Git Bash and try to run `git remote-https` bare-bones? It should output this:

```sh
$ git remote-https
error: remote-curl: usage: git remote-curl <remote> [<url>]
```

If it does not show that, could you use the [Dependency Walker](http://www.dependencywalker.com/) to see whether there are any DLL files that `git-remote-https.exe` depends on that are found in a strange place (you will want to switch on full paths with F9 or by right-clicking into the upper left panel)? For me, it shows this:

![remote-https-depends](https://cloud.githubusercontent.com/assets/127790/12808913/db362b78-cb1a-11e5-8bd5-68de9dd38e71.png)

(sorry, I did not find a way to copy & paste this as text).

Another approach might be to look whether `curl https://git-for-windows.github.io/` works as expected, or displays the same problems.

**Comment by dscho** [comment] 2016-02-04 09:37
Update: I believe that this issue is related to top-down DLL loading. VirtualBox had similar issues: https://www.virtualbox.org/ticket/10128. When I set those registry entries accordingly, Git for Windows starts failing again, even with build 14257.

**Comment by oysteinkrog** [comment] 2016-02-04 11:28
I can confirm that setting AllocationPreference as described causes mingw-w64-x86_64-git-2.7.0.2.57599f7-1 to crash with segmentation fault.
Windows 10 w/latest updates (not fast track).

**Comment by dscho** [comment] 2016-02-04 12:23
Hmm. According to the [release notes of VirtualBox 4.2.2](https://www.virtualbox.org/wiki/Changelog-4.2), issue 10128 was fixed with the note

> NAT: fixed a crash under rare circumstances (Windows hosts only; bug ~~#10128~~)

But the commit with the message

> Main/VirtualBox: fix crash in rare circumstances (only saw it with a severely corrupted inaccessible VM) on VM unregistration or on VBoxSVC termination

is particularly unhelpful: https://github.com/mirror/vbox/commit/e1f2bdec755146c93fc071c339184f680f24c87e

So it sadly seems that we cannot imitate their fix.

**Comment by 810** [comment] 2016-02-04 12:26
> @810 can you look for the file  C:\Program Files\Git\mingw64\libexec\git-core\git-remote-https.exe ? (If you installed elsewhere, or the 32-bit version, please adjust the path accordingly.)
C:\Users\jelle\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\mingw32\libexec\git-core File is there

> If it is not there, is it possible that some overzealous anti-virus in your setup quarantined it?
Just windows defender

> If it is there, could you open a Git Bash and try to run  git remote-https  bare-bones? It should output this

fatal: 'remote-https' appears to be a git command, but we were not able to execute it. Maybe git-remote-https is broken?

>Another approach might be to look whether  curl https://git-for-windows.github.io/  works as expected, or displays the same problems.

i see some html. so that worked.

**Comment by dscho** [comment] 2016-02-04 12:42
@810 hmpf. It does not really look as if your problem matches the title of this ticket.

So let's avoid utter confusion and can I please have a new ticket for your issue?

**Comment by dscho** [comment] 2016-02-05 09:31
Back to this ticket:

> I can confirm that setting AllocationPreference as described causes mingw-w64-x86_64-git-2.7.0.2.57599f7-1 to crash with segmentation fault.
> Windows 10 w/latest updates (not fast track).
> Edit: gdb also segfaults

I found the culprit, and it has nothing to do with the reported crash in 14251. So let's stop here: a new Insider Preview has been released to the Fast Track, and Git for Windows works without any patch, so there was nothing Git for Windows had to fix.

**Comment by oysteinkrog** [comment] 2016-02-05 19:29
dscho: That's awesome! Thanks for you hard work, this issue does not affect me, but I follow development of this project closely and I am very grateful for your efforts :)
