### ISSUE TITLE
Windows: line 2123: Unable to run post-install scripts.

### ISSUE THREAD

**Issue by karlpatrickespiritu** [git-for-windows/git#1598] opened 2018-03-29 03:12 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```

*Windows 10 Home Single Language
*Version 1703

 - What did you expect to occur after running these commands?

Complete Installation.

 - What actually happened instead?

<img width="379" alt="postinstall" src="https://user-images.githubusercontent.com/10472504/38068109-efb976a4-3341-11e8-8f57-dbbe75a57c5d.png">

**Comment by larsxschneider** [comment] 2018-03-29 07:43
Might that be a duplicate of #1585 ?

**Closed** 2018-03-29 12:57 UTC
Labels: duplicate
