### ISSUE TITLE
Weird intermittent compilation error related to _pgmptr

### ISSUE THREAD

**Issue by glandium** [git-for-windows/git#5016] opened 2024-06-20 10:15 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

I'm building parts of git-for-windows as part of git-cinnabar and am currently getting the following error intermittently:
```
    In file included from D:/a/git-cinnabar/git-cinnabar/src/mingw.c:11:
    D:/a/git-cinnabar/git-cinnabar/git-core/compat/mingw.c: In function 'open_in_gdb':
    D:/a/git-cinnabar/git-cinnabar/git-core/compat/mingw.c:35:9: error: function declaration isn't a prototype [-Werror=strict-prototypes]
       35 |         extern char *_pgmptr;
          |         ^~~~~~
    In file included from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/mm_malloc.h:27,
                     from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/xmmintrin.h:34,
                     from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/immintrin.h:31,
                     from C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/14.1.0/include/x86intrin.h:32,
                     from C:/msys64/mingw64/include/winnt.h:1658,
                     from C:/msys64/mingw64/include/minwindef.h:163,
                     from C:/msys64/mingw64/include/windef.h:9,
                     from C:/msys64/mingw64/include/windows.h:69,
                     from C:/msys64/mingw64/include/winsock2.h:23,
                     from D:/a/git-cinnabar/git-cinnabar/git-core/git-compat-util.h:215,
                     from D:/a/git-cinnabar/git-cinnabar/git-core/compat/mingw.c:1:
    D:/a/git-cinnabar/git-cinnabar/git-core/compat/mingw.c:35:22: error: '__p__pgmptr' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
       35 |         extern char *_pgmptr;
          |                      ^~~~~~~
    cc1.exe: all warnings being treated as errors
    make: *** [D:\a\git-cinnabar\git-cinnabar\src\build.mk:143: mingw.o] Error 1
    make: *** Waiting for unfinished jobs....
```

The intermittence may or may not come from github actions caching, but the error is plain weird.

This is using a fresh-ish msys2 environment, and I suspect something changed recently in some of the mingw headers that causes problems with `_pgmptr`.

On the other hand, it doesn't even seem to be used at all? So I'm wondering what it's doing there in the first place?

**Comment by dscho** [comment] 2024-06-20 10:18
I opened a PR at https://github.com/gitgitgadget/git/pull/1752 but did not hear back about it on the Git mailing list. @glandium would you be willing to test the patch and if it works as intended, provide feedback [for the patch on the Git mailing list](https://lore.kernel.org/git/pull.1752.git.1718777398765.gitgitgadget@gmail.com)?

**Comment by glandium** [comment] 2024-06-20 10:52
Done. I should have checked the mailing list.

I'm still baffled this is not happening consistently for me... in fact, I disabled github actions cache, and... it reliably doesn't happen in that case.

**Comment by glandium** [comment] 2024-06-20 19:45
I'm not using the git-sdk, I'm using my own copy of msys2.

**Comment by dscho** [comment] 2024-06-21 06:22
> I'm using my own copy of msys2.

Right, that would trigger the compile error.

**Comment by glandium** [comment] 2024-06-21 09:14
Sure, but I would expect it to happen reliably. Now that I think about it, the discrepancy might have been coming from https://github.com/msys2/setup-msys2?tab=readme-ov-file#cache

**Comment by dscho** [comment] 2024-06-21 10:45
Ah, that sounds highly plausible.

**Comment by dscho** [comment] 2024-06-21 13:25
@glandium can you please verify that after merging https://github.com/git-for-windows/git/pull/5017 it now works?

**Comment by glandium** [comment] 2024-06-21 19:44
I had applied the patch locally already and haven't had an error since.

**Comment by dscho** [comment] 2024-06-21 19:45
> I had applied the patch locally already and haven't had an error since.

Excellent, let's close this issue, then.

**Closed by dscho** 2024-06-21 19:45 UTC
