### ISSUE TITLE
Continuous Ctrl+C freezes Bash started via git-cmd

### ISSUE THREAD

**Issue by bviktor** [git-for-windows/git#227] opened 2015-06-29 14:49 UTC
Start a bash session with

```
c:\git\git-cmd.exe --command=usr\bin\bash.exe --login -i
```

Then keep pressing Ctrl+C. Within a minute (it's random, sometimes it's 2 seconds, sometimes it's 30) the shell will freeze and no longer respond to user input. Within another minute or so it'll return the prompt and display everything that's been typed in the meanwhile.

Always reproducible for me. Tested with 64 bit Git 2.4.5.1 on Windows 8.1 x64 and Windows 10 x64.

Related: #205

**Comment by dscho** [comment] 2015-08-17 13:48
I just tried it and can reproduce it. Unfortunately, I do not have enough time to look into it.

**Comment by laggingreflex** [comment] 2015-08-22 05:09
Came here looking for a similar issue. I just upgraded from v1.8 and I feel like something fundamentally has changed in the way <kbd>Ctrl-c</kbd> is handled now in v2.5. 
For example I had a bash function like this:

    run(){
        sleep 10
        echo ctrl-c was pressed
    }

Earlier if I pressed <kbd>Ctrl-c</kbd> before 10 seconds, it would display the echo message "ctrl-c was pressed". But not anymore.

**Comment by laggingreflex** [comment] 2015-08-22 05:49
In the following multi-command scenario, pressing Ctrl+C (before 10 seconds) doesn't display the "hi":

    $ sleep 10; echo hi

Same thing if you have a function

    function run(){
        sleep 10
        echo hi
    }

It happens with both `git-bash.exe` and if run from a cmd: `bin\bash.exe -li`

**Comment by harriha** [comment] 2015-08-31 18:11
I'm seeing the same with latest 2.5.1. Seeing this occasionally, mostly when I have a file watcher such as [chokidar-cli](https://github.com/kimmobrunfeldt/chokidar-cli) or [nodemon](https://github.com/remy/nodemon) running, exiting the process is painfully difficult. 

Seen on Windows 10 and Windows 7 today.

**Comment by ashelley** [comment] 2015-10-09 16:58
Hello,

I would like to confirm that I'm having this issue still on git 2.6.1 on windows 10.  

Symptoms:

pressing ctrl+c when a program is running sporadically takes 10-60 seconds to return to the prompt.  The process is killed instantly (but you can't really tell) and the time it takes for the $ prompt to show up is prolonged. 

Here is how i can reproduce it albeit not a very minimal test case.  

Step 1) make sure you have node installed (I don't think it matters what version since I believe this is a git-bash issue it seems)

Step 2) make sure you have node-dev installed (npm install -g node-dev), details below

Step 3) use this script app.js:
```javascript
function run() {
   console.log('waiting 5 seconds');
   setTimeout(function() {
      run();
   }, 5000)
}
run();
```

Step 4) show that node works with ctrl+c (no delay issues)
```
$ node app.js
waiting 5 seconds
waiting 5 seconds
waiting 5 seconds
waiting 5 seconds
<ctrl+c>
```
Process exits normally here

Step 5) run with node-dev (sporadic delay issues).  This might exit and return you to the command prompt right away but often it takes a long delay to get back to the command prompt 
```
$ node-dev app.js
waiting 5 seconds
waiting 5 seconds
waiting 5 seconds
waiting 5 seconds
<ctrl+c>
```
If you hit ctrl+c right away it seems more likely it will exit fine.  However after letting this loop a couple of times it seems to pretty consistently exhibit the "delay problem"

internally node-dev uses https://nodejs.org/docs/latest/api/fs.html#fs_fs_watchfile_filename_options_listener

which correlates to what @harriha has reported.

I know node has nothing to do with git but I just wanted to post my testcase so that it might help someone reproduce or confirm a fix.

-Adam

**Comment by dscho** [comment] 2015-10-09 17:11
@ashelley thank you. This test case will indeed be incredibly valuable to verify a fix.

**Comment by laggingreflex** [comment] 2015-10-19 21:08
This might be related and/or helpful in someone understand what's happening.. 

It seems bash is "forwarding" the Ctrl-C over onto the underlying cmd.exe process. (disclaimer: I don't actually understand how bash or git-for-windows' bash works so that statement may sound vague)

I opened cmd.exe (win8) and in it I ran `C:\Program Files\Git\bin\bash.exe`. 
Then I hit Ctrl-C and it started behaving strangely:

![][scr1]

I downloaded a previous version **Git 1.9** (the latest one before 2.5 update) and that one **works good**

![][scr0]

But back in **Git 2.5** Ctrl-C creates all sorts of **strange behaviour**:

![][scr2]


[scr1]: http://i.imgur.com/CBqK1Us.png
[scr0]: http://i.imgur.com/cZw3h0i.png
[scr2]: http://i.imgur.com/qrJyBBW.png

**Comment by laggingreflex** [comment] 2015-10-20 06:00
Cygwin's `bash.exe` has the same issue. Does this (git-for-windows) uses the same `bash.exe` as Cygwin's, or do they both have a same source? If so, the problem would be linked to it.

**Comment by dscho** [comment] 2015-10-20 08:56
> Does this (git-for-windows) uses the same bash.exe as Cygwin's

Yes. See https://github.com/git-for-windows/git/wiki#about for details.

**Comment by clintwood** [comment] 2015-10-28 19:06
I'm having same issue with nodemon - using Sysinternals Process Explorer I notice that the process tree initially looks like this:
![image](https://cloud.githubusercontent.com/assets/2149388/10799383/39db2e0c-7db5-11e5-9f47-0328f751097e.png)
Then running nodemon it looks like this (notice that it has spawned sh.exe as a root process which is not in the original process tree below bash.exe):
![image](https://cloud.githubusercontent.com/assets/2149388/10799420/699ee192-7db5-11e5-9352-0f1afa1d2e05.png)
Then after Ctrl-c it looks like this (notice that sh.exe is an orphaned process and not part of the original process tree):
![image](https://cloud.githubusercontent.com/assets/2149388/10799449/90c200b0-7db5-11e5-8721-1100ab0484d7.png)
Finally after about 60s the orphaned process (she.exe) terminates and the prompt returns.

Prior to gfw 2.x sh.exe always existed in the process tree below bash.exe. Lastly I also noticed that uname.exe and a few other utility processes are all created as root processes which was not the case in pre 2.x gfw.  Hope this helps!

**Comment by clintwood** [comment] 2015-10-28 19:10
BTW this is not unique to git-bash.exe.  I have the same issue using either bash.exe or sh.exe from via ConEmu.  And it's really annoying... ;)

**Comment by SystemDisc** [comment] 2015-10-30 09:14
In MinTTY, when using Ctrl+C to exit an HTTP server running in Node.JS, node.exe is always left open.
In ConEmu, when using Ctrl+C to exit an HTTP server running in Node.JS, node.exe occasionally hangs before closing, and an sh.exe sometimes hangs, too.

**Comment by dscho** [comment] 2016-04-02 13:00
I believe that I fixed this with https://github.com/git-for-windows/git/commit/b7a95d0be09864f073e6f75b4e0680b9955055a2

**Comment by bviktor** [comment] 2016-04-02 13:03
Actually, not quite. I can still reproduce it.

**Comment by dscho** [comment] 2016-04-02 15:10
You're right, it freezes at random points.

Except that it does not really freeze. It does not react to input for an extended amount of time, but then comes back...

**Comment by laggingreflex** [comment] 2016-04-02 20:21
I think the issue is with Cygwin's bash itself (version 4) because I was able to reproduce the same issue in it, without git-for-windows involved

It must have been introduced somewhere between Cygwin bash v3 (which was used in Git 1.9 and works fine) and v4

**Comment by dscho** [comment] 2016-04-04 07:06
@laggingreflex thank you for weighing in.

The links in https://www.google.de/search?q=cygwin+Ctrl-C are unrelated for me, though: they show that Ctrl+C is not working *at all* for some people. Here, it is freezing after repeatedly hitting Ctrl+C.

Would you have a more concrete link that shows that this freezing behavior also occurs with Cygwin?

**Comment by dscho** [comment] 2016-04-04 13:51
@laggingreflex hmpf. I went ahead and tried to freeze Cygwin's Bash in CMD in the same way as described in this ticket, and failed to reproduce it there. Could you try again and come back with your findings?

**Comment by dscho** [comment] 2016-04-07 11:56
Further findings (these will be the last findings from my side at least for a while):

- the freezes only happen if calling `bin\bash`, not `usr\bin\bash`, i.e. when running Bash through the Git wrapper.
- very short before the freeze happens, the output of `strace.exe` shows that it is calling `pinfo::maybe_set_exit_code_from_windows` and that the windows exit value is `0xDEADBEEF`, i.e. [it is not available](https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/pinfo.cc#L183-L191).
- it seems that the [`ctrl_c_handler()` function](https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/exceptions.cc#L1090-L1179) is entered at least twice when Ctrl+C is pressed, more times still when the freeze happens.
- Most notably, when the freeze happens, the `ctrl_c_handler()` function is entered in *two different* processes. This is not the case when the freeze is not happening, then the function is entered in only one process (which is still not the main process, I think it is a separate process that is spawned for the sole purpose of sending the `SIGINT` signal, but it should not be spawned twice, which is what might be happening).

If anybody savvy enough could continue from here, that would be awesome!

**Comment by dscho** [comment] 2017-05-15 21:45
So it looks as if nobody is really interested in fixing this. I wonder whether this bug is so critical after all.

**Comment by SystemDisc** [comment] 2017-05-15 22:07
I'm definitely interested in getting this fixed but did not receive any notification from GitHub on this until your last comment (perhaps because you pre-emptively closed the issues?). I'm also not sure how I can help.

**Comment by dscho** [comment] 2017-05-15 22:24
@SystemDisc one way to help would be to start from my findings that I reported [in this comment](https://github.com/git-for-windows/git/issues/227#issuecomment-206833189).

To continue, you need to [build the MSYS2 runtime locally](https://github.com/git-for-windows/git/issues/227), and then patch in debug statements (e.g using `small_printf()` as described in https://github.com/git-for-windows/msys2-runtime/blob/7509443b9a90cffc4ed02ea456c1b4838e2a882b/winsup/cygwin/how-to-debug-cygwin.txt#L130-L134) in strategic places. The goal would be to find out which callers cause that dead-lock.

it is quite possible that the problem may lie with the `kill_process_tree()` function I introduced into the MSYS2 runtime: maybe it should not traverse children of MSYS2 processes, but I am not quite sure yet how MSYS2 can identify those. Maybe it has an internal enumeration of MSYS2 processes (if you launch `ps` without further arguments, you will see only MSYS2 processes, which makes me think that there should be an API, and I would try to find out about that by running `strace -i log.txt ps` and then scrolling backwards through that `log.txt`).

**Comment by dscho** [comment] 2017-06-13 20:13
> t is quite possible that the problem may lie with the kill_process_tree() function I introduced into the MSYS2 runtime

Alas, it is not. In v2.13.1, I changed the way Ctrl+C works and the problem described in this ticket still persists.

Any help would be very much appreciated.

**Comment by SystemDisc** [comment] 2017-06-13 20:28
I have no idea how to debug this. For now, I've switched to using the
Windows Subsystem for Linux which comes with Windows 10.

**Comment by kevison** [comment] 2017-12-08 16:10
Still a problem in 2.15....

**Comment by dscho** [comment] 2018-04-23 06:57
After testing this with my fix for https://github.com/git-for-windows/git/issues/1491 (which will hit https://wingit.blob.core.windows.net/files/index.html soon, so you can verify my claim, and you should, if you are interested in this issue) it would appear that there is no longer a freeze (although quite a bit of delay if you hit <kbd>Ctrl</kbd>+<kbd>C</kbd> *tons* of times).

**Comment by dscho** [comment] 2018-04-23 12:47
The newest snapshot at https://wingit.blob.core.windows.net/files/index.html should fix this. Please test.

**Comment by avindra** [comment] 2018-04-23 14:37
@dscho Seems fixed for me! the only slowness now seems to be coming from the default PS1 which includes Git info. I'm using this:

```
PS1='\033[33m\]\w\[\033[36m\] \[\033[0m\] $ '
```

which renders a simplified PS1 without any Git branch:

![image](https://user-images.githubusercontent.com/126848/39133443-3258f44a-46e2-11e8-890e-7890993f8639.png)

**Comment by dscho** [comment] 2018-04-25 08:49
> Seems fixed for me!

Thanks for the feedback!

> the only slowness now seems to be coming from the default PS1

That would be a different issue, though ;-)

**Closed by dscho** 2018-04-25 08:49 UTC
Labels: up for grabs

**Comment by Koudy** [comment] 2018-12-21 21:03
Have this problem.
Git-2.20.1-64-bit on Windows 7.

**Comment by Koudy** [comment] 2018-12-21 21:32
Have this problem.
Git-2.20.1-64-bit on Windows 7 x64.
