### ISSUE TITLE
Blocking failures (app and installer) on Wn10 Build 14251.rs1_release.160124-1059

### ISSUE THREAD

**Issue by kferrio** [git-for-windows/git#636] opened 2016-01-31 23:31 UTC
I had Git 2.64 installed for some time. Several Win10 fast ring updates later, I noticed that git operations (via shell or Tortoise) where failing. The command line reports a segfault. Unfortunately, I did not capture any traces. I just uninstalled and grabbed the newer 2.7 installer. Same issue.  Here's the error from the Git installer:

![git broken](https://cloud.githubusercontent.com/assets/1403507/12705962/f0cf8c94-c837-11e5-8cbb-21d40329c7ab.PNG)

Did a complete uninstall of Git, TortoiseGit and the VS2015 git plugin.  Reboot. Reinstall just git. Same problem.  

Anyone else?

**Comment by shiftkey** [comment] 2016-01-31 23:34
Can you confirm you're on build 14251?

This was reported last week https://github.com/git-for-windows/git/issues/627 and has a known issue with memory management - it was confirmed by Microsoft and resolved in an internal build https://github.com/git-for-windows/git/issues/627#issuecomment-177193591 - it just hasn't been made available to the Fast Ring track just yet...

**Comment by kferrio** [comment] 2016-02-01 00:03
Regret I missed that report in my search. Yes, I am definitely on the Win10
build 14251 patch level as noted in subject. Thanks for the info!

**Comment by dscho** [comment] 2016-02-01 06:21
So this is a duplicate of #627 after all.

**Closed by dscho** 2016-02-01 06:21 UTC
