### ISSUE TITLE
Ipython doesn't work properly in git bash/mingw

### ISSUE THREAD

**Issue by kj809** [git-for-windows/git#436] opened 2015-09-24 17:56 UTC
In the shell for git 2.5.3 Ipython doesn't work properly with ipython 4.0.0. I tried both 64 and 32 bit git installations and the same problem persists - The Out[#] line doesn't show for ipython commands.

Some system details below:

Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
IPython 4.0.0 -- An enhanced Interactive Python.

I found an exe for git 1.9.5 and it works perfectly so I figure it's 2.5.3 that is the problem, rather than my installation of python. Just in case, here are my installed packages for python:

$ pip list
alabaster (0.7.3)
argcomplete (0.8.9)
astropy (1.0.3)
Babel (1.3)
bcolz (0.9.0)
beautifulsoup4 (4.3.2)
binstar (0.11.0)
bitarray (0.8.1)
blaze (0.8.0)
blz (0.6.2)
bokeh (0.9.0)
boto (2.38.0)
Bottleneck (1.0.0)
certifi (14.5.14)
cffi (1.1.0)
clyent (0.3.4)
colorama (0.3.3)
conda (3.17.0)
conda-build (1.14.1)
conda-env (2.4.2)
configobj (5.0.6)
cryptography (0.9.1)
Cython (0.22.1)
cytoolz (0.7.3)
datashape (0.4.5)
decorator (4.0.2)
docutils (0.12)
fastcache (1.0.2)
Flask (0.10.1)
greenlet (0.4.7)
h5py (2.5.0)
idna (2.0)
ipykernel (4.0.3)
ipython (4.0.0)
ipython-genutils (0.1.0)
itsdangerous (0.24)
jdcal (1.0)
jedi (0.8.1)
Jinja2 (2.8)
jsonschema (2.4.0)
jupyter-client (4.0.0)
jupyter-console (4.0.2)
jupyter-core (4.0.6)
llvmlite (0.5.0)
lxml (3.4.4)
MarkupSafe (0.23)
matplotlib (1.4.3)
menuinst (1.0.4)
mistune (0.7.1)
mock (1.0.1)
multipledispatch (0.4.7)
nbconvert (4.0.0)
nbformat (4.0.0)
networkx (1.9.1)
nltk (3.0.3)
nose (1.3.4)
notebook (4.0.5)
numba (0.19.1)
numexpr (2.4.3)
numpy (1.9.2)
odo (0.3.2)
openpyxl (1.8.5)
pandas (0.16.2)
path.py (0.0.0)
patsy (0.3.0)
pep8 (1.6.2)
pickleshare (0.5)
Pillow (2.8.2)
pip (7.1.2)
ply (3.6)
psutil (2.2.1)
py (1.4.27)
pyasn1 (0.1.7)
pycosat (0.6.1)
pycparser (2.14)
pycrypto (2.6.1)
pyflakes (0.9.2)
Pygments (2.0.2)
pyOpenSSL (0.15.1)
pyparsing (2.0.3)
pyreadline (2.0)
pytest (2.7.1)
python-dateutil (2.4.2)
pytz (2015.4)
pywin32 (219)
PyYAML (3.11)
pyzmq (14.7.0)
qtconsole (4.0.1)
requests (2.7.0)
rope-py3k (0.9.4-1)
runipy (0.1.3)
scikit-image (0.11.3)
scikit-learn (0.16.1)
scipy (0.15.1)
setuptools (18.1)
simplegeneric (0.8.1)
six (1.9.0)
snowballstemmer (1.2.0)
sockjs-tornado (1.0.1)
sphinx (1.3.1)
sphinx-rtd-theme (0.1.7)
spyder (2.3.5.2)
SQLAlchemy (1.0.5)
statsmodels (0.6.1)
sympy (0.7.6)
tables (3.2.0)
toolz (0.7.2)
tornado (4.2.1)
traitlets (4.0.0)
ujson (1.33)
Werkzeug (0.10.4)
wheel (0.26.0)
xlrd (0.9.3)
XlsxWriter (0.7.3)
xlwings (0.3.5)
xlwt (1.0.0)

**Comment by dscho** [comment] 2015-09-24 18:43
Is this not a duplicate of https://github.com/git-for-windows/git/issues/399, see in particular [this comment](https://github.com/git-for-windows/git/issues/399#issuecomment-141049958)?

**Comment by kj809** [comment] 2015-09-24 19:35
Thanks for replying so quickly - is there any future plan to restore the
original functionality? As a complete newbie to building from source I'm
already running into problems trying to install winpty. With the previous
version of git/msys I was using it was sufficient to type ipython into the
console to have it running in command line mode - it just worked.

On 24 September 2015 at 19:43, Johannes Schindelin <notifications@github.com

**Comment by dscho** [comment] 2015-09-24 21:30
> Thanks for replying so quickly - is there any future plan to restore the
> original functionality?

Not so fast. First you should look at the ticket I linked and follow the discussion. In particular, you will want to test whether the `winpty` method works for you and report back.

**Comment by dscho** [comment] 2015-09-25 10:26
> As a complete newbie to building from source I'm already running into problems trying to install winpty.

But it is already part of Git for Windows... So just running `winpty ipython` should do the trick. And if it does, you need to tell me. And if it does not, you need to tell me.

**Comment by kj809** [comment] 2015-09-25 10:30
I'll have to get back to you on this on Monday because I'm away from that
machine over the weekend


On 25 September 2015 at 11:26, Johannes Schindelin <notifications@github.com

**Comment by dscho** [comment] 2015-09-25 12:38
> I'll have to get back to you on this on Monday

Please do!

**Comment by kj809** [comment] 2015-09-28 20:23
Just confirming that winpty ipython did the trick. It seems to be working fine now. Many thanks!

**Closed** 2015-09-28 20:53 UTC
Labels: question
