### ISSUE TITLE
`bash.exe` intermittently hanging with 2.36.1 when fetching or building source

### ISSUE THREAD

**Issue by bsclifton** [git-for-windows/git#3870] opened 2022-05-26 07:37 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

`2.36.1` (latest; 64 bit)

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1706]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Yes. Reverting to an older version of git bash works just fine and I don't see the problem. Specifically, I reverted to:
```
git version 2.36.0.windows.1
cpu: x86_64
built from commit: ea1e13f73339d57cbe81a0bae6fba669aaccf656
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Using [conemu](https://conemu.github.io/) version `210912 [64] {Stable}` (latest)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Building Brave from source. Usually, it will hang even just fetching a remote.
Full build instructions are here: https://github.com/brave/brave-browser
But the following steps might be enough to cause a problem:
```
git clone git@github.com:brave/brave-browser.git
cd brave-browser
npm run init
# this will take a really long time
```
 - What did you expect to occur after running these commands?

Shell should continue to accept user input (ex: hitting enter should put a newline) and stdout should continue to print

 - What actually happened instead?

Inside of conemu, the stdout just hangs from bash.exe. It's still processing (I can see what it's running because conemu is showing the processes that it's creating). Trying Ctrl + S / Ctrl + Q doesn't have any effect. If you hit enter, nothing happens either (no newline). Conemu remains responsive; I can even restart the git-bash shell that is hung and I'm back in business (it's just a pain since this resets the CWD).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Although instructions above share `brave-browser`, this (during the `npm run init`) clones a sub-repository to the `src/brave` folder. That repo is the one I've ran into issues with (maybe because the history is large). Repo is https://github.com/brave/brave-core

You may try cloning and fetching that inside a conemu instance using git-bash

**Comment by dscho** [comment] 2022-05-26 11:24
It looks like this might be caused by some MSYS2 runtime changes.

Could you first test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) (you can use the Portable Git variant so that you do not have to touch your working setup), and if the problem persists, replace the `usr\bin\msys-2.0.dll` file with the version of v2.36.0 to figure out whether that is enough to re-introduce the regression?

**Comment by bsclifton** [comment] 2022-05-26 20:38
@dscho thanks for the quick response; I grabbed latest from https://wingit.blob.core.windows.net/files/index.html and installed over my existing install. I was quickly able to reproduce the problem
```
git version 2.36.1.windows.1.5.g590ade545d.20220519185956
cpu: x86_64
built from commit: 590ade545daf06dd371450005890ebfe6f8112e9
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Let me try to replace the `msys-2.0.dll` with the one from the known working install (2.36.0) and I'll report back

**Comment by bsclifton** [comment] 2022-05-26 20:58
## Binaries
There are two `msys-2.0.dll` binaries I downloaded into separate folders:
```
brian@DESKTOP-DRCJVG6 (master *=) $ shasum bad/msys-2.0.dll
0df72569b3526fe0b27d56bf3babb07aa9508715 *bad/msys-2.0.dll
[13:49:56] (~/OneDrive - Clifton family/desktop)
brian@DESKTOP-DRCJVG6 (master *=) $ shasum good/msys-2.0.dll
07321a450b1d80ff9718750667b1022b73e32f76 *good/msys-2.0.dll
```
- `good/msys-2.0.dll` was downloaded from https://github.com/git-for-windows/git/releases/download/v2.36.0.windows.1/MinGit-2.36.0-64-bit.zip (in `usr/bin`).

- `bad/msys-2.0.dll` was the binary included when I did the install of 2.36.1 (the version shared in above post) from my directory:
`C:\Program Files\Git\usr\bin`

## Findings
- With 2.36.1 and the GOOD version of `msys-2.0.dll` I *WAS NOT* able to reproduce the problem
- With 2.36.0 and the BAD version of `msys-2.0.dll` I *WAS* able to reproduce the problem

When the problem is present, Brave is building and opening a lot of pipes from Python to generate the build files and compile the targets with LLVM. If you do nothing and just watch the compile, it eventually hangs stdout.  However, I also noticed when the problem is present, you can let it build for a while and then CTRL+C to send abort signal and stdout never shows this

When the problem is NOT present, I can actually see the echo out for the signal:
`ninja: build stopped: interrupted by user.`

**Comment by AlexCourtney18** [comment] 2022-05-27 16:44
I am having the exact same problem. All git commands work fine in the git bash terminal however, when I go to pull or push it only works 1 time then every additional pull or push requests hang with nothing happening. This happens specifically in git bash 2.36.1 on windows 10 19044.1706 64 bit. I am able to pull or push using powershell, cmd, or WSL terminal within VSC.

**Comment by bsclifton** [comment] 2022-05-27 17:41
So far, so good w/ the 2.36.1 snapshot build:
```
git version 2.36.1.windows.1.5.g590ade545d.20220519185956
cpu: x86_64
built from commit: 590ade545daf06dd371450005890ebfe6f8112e9
```

and the `msys-2.0.dll` with SHA `07321a450b1d80ff9718750667b1022b73e32f76`. I haven't had any hangs since doing this in the last 21 hours (have done several pulls/pushes with git on large repos and rebuilding source)

**Comment by dscho** [comment] 2022-05-31 13:06
> * With `2.36.1` and the **GOOD** version of `msys-2.0.dll` I **WAS NOT** able to reproduce the problem

v2.36.1 [shipped with MSYS2 runtime v3.3.4-4](https://github.com/git-for-windows/build-extra/blob/main/versions/package-versions-2.36.1.txt#L114), while v2.36.0 [shipped with MSYS2 runtime v3.3.4-2](https://github.com/git-for-windows/build-extra/blob/main/versions/package-versions-2.36.0.txt#L110). There is one other version in between that might be useful to test, and of course the latest one, which is MSYS2 runtime v3.3.5-1.

You can download those versions via https://github.com/git-for-windows/git-sdk-64/commits/HEAD/usr/bin/msys-2.0.dll

**Comment by jeffmaury** [comment] 2022-06-28 14:39
Seems to be still there on 2.37.0

**Comment by bsclifton** [comment] 2022-06-28 19:53
Sorry for lack of updates; I've just been needing to be heads down. After the work-around above (using `590ade545daf06dd371450005890ebfe6f8112e9` with older `msys-2.0.dll`), I haven't had any issues

I'm a bit scared to update and don't plan on updating. But if there is a potential fix, I can dedicate some time to testing and verifying the fix. Please let me know

**Comment by dscho** [comment] 2022-11-12 22:09
If anyone here can bisect to the exact revision where the bug was introduced, we _might_ be able to figure this out. Until that time, I will close this ticket.

**Closed by dscho** 2022-11-12 22:09 UTC
Labels: msys2

**Comment by bsclifton** [comment] 2023-04-11 07:00
I finally upgraded at some point to `2.36.1.windows.1.5.g590ade545d.20220519185956` and I don't see this anymore

Thanks for helping triage @dscho 😄
