### ISSUE TITLE
fatal: detected dubious ownership in repository when ownership is a group

### ISSUE THREAD

**Issue by wolfbeast** [git-for-windows/git#4177] opened 2022-12-16 17:18 UTC
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

2.38.1 64-bit

```
git version 2.38.1.windows.1
cpu: x86_64
built from commit: b85c8f604d375d4d773a36842964e8a7ec056aae
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 64-bit

```
Microsoft Windows [Version 10.0.19044.2364]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Custom Editor Path:
Default Branch Option: master
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not running from shell. Running from SourceTree instead.
Sometimes using the built-in Git Bash

Description of the issue: when trying to load or refresh the tree view in SourceTree (which launches a `git log` command in the background) git refuses to provide a response with the below error.

 - What actually happened instead?

fatal: detected dubious ownership in repository
Followed by individual S-* ownership details it expects to match, specifically expecting the directories to have individual user ownership.

- Cause

The cause of this is that, for group management reasons, ownership of the repo directories on the filesystem is set to the user group, not individual users, so they can be shared among users in those groups. git, since the overzealous directory file system checks have been put in place, no longer likes this because it does a naive check on direct user ownership and not group ownership.

- Workaround

We've temporarily worked around this issue by setting safe.directory to '*' 

- Desired solution

Accept not only user S-* ownership, but also the ownership of all of the groups the user belongs to.

**Comment by rimrul** [comment] 2022-12-16 18:39
Duplicate of #3798

**Closed by rimrul** 2022-12-16 18:39 UTC
