### ISSUE TITLE
Plain HTTP Auth Proxy & "Unknown SSL protocol error in connection to ..."

### ISSUE THREAD

**Issue by ciis0** [git-for-windows/git#913] opened 2016-10-10 13:00 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen http auth)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed http auth) issue
  matching what I'm seeing
  - both #234 & #373 are about NTLM
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

Git Bash, 64bit

```
$ git --version --build-options
git version 2.9.0.windows.1
```

MSYS2, 64bit

```
$ git --version --build-options
git version 2.9.1
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7, 64bit

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

The HTTP Proxy uses Plain HTTP Auth, no NTLM or such.
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
  - Git Bash
  - MSYS2
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ env https_proxy=http://user:pw@proxy https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git
```
- What did you expect to occur after running these commands?

Cloning the repo.
- What actually happened instead?

```
fatal: unable to access 'https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git/': Unknown SSL protocol error in connection to gist.github.com:443
```

Full output (proxy address `proxy`, proxy ip `1.2.3.4`, w/  `GIT_TRACE=1 GIT_CURL_VERBOSE=1`): [proxy.log.txt](https://github.com/git-for-windows/git/files/519504/proxy.log.txt).
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

https://gist.github.com/dc59a80d4408424699ecde7b67095ab7.git

**Comment by dscho** [comment] 2017-02-21 21:06
Sorry to have let this slip for so long (I hoped that other, more competent people would chime in). It sounds as if the proxy has troubles relaying HTTPS, at least the version GitHub offers... Which proxy software is this?

**Comment by michael-o** [comment] 2017-02-21 21:13
This is not a proxy error. I am suffering from this bug too. If authentication fails to the target host or the proxy requires auth and any of both fails and target URL is HTTPS, git assumes TLS nego has failed.

**Comment by dscho** [comment] 2017-02-21 22:43
> This is not a proxy error.

Aha! So the problem is not that the clone fails, but that the error message is misleading?

**Comment by michael-o** [comment] 2017-02-22 07:56
Exactly, every HTTP action fails. This is not a Git on Windows problem. Please see here: https://groups.google.com/forum/#!searchin/git-users/osipov%7Csort:relevance/git-users/VihKV8_wEEc/S5C9VfD7CgAJ

**Comment by dscho** [comment] 2017-02-22 12:40
> This is not a Git on Windows problem.

Maybe report it to [the Git mailing list](mailto:git@vger.kernel.org), then (note: send plain text, HTML will silently be swallowed)? They have *substantially* more resources for bug fixes like this one than we have here...

**Comment by dscho** [comment] 2017-02-22 12:46
Oh, and another note: I cannot see anything close to the string "Unknown SSL protocol error" in Git's source code, but I can see it in cURL's source code: https://github.com/curl/curl/blob/028391df5d84d9fae3433afdee9261d565900355/lib/vtls/openssl.c#L2281

So maybe the optimal place to report this problem is actually https://github.com/curl/curl/issues/new? (I did not see any existing reports about this, but I only looked very briefly...)

**Comment by michael-o** [comment] 2017-02-22 13:04
@dscho Good catch. I'll try to isolate the issue from Git to Curl.

**Comment by dscho** [comment] 2017-04-04 21:39
@michael-o any luck so far?

**Comment by michael-o** [comment] 2017-04-04 21:49
@dscho Not yet, simply forgotten this. Will try next week.

**Comment by whoisj** [comment] 2017-04-11 18:59
@michael-o we've seen a lot of these issues in Visual Studio since switching to Git for Windows (instead of Libgit2). In general, the fix has been to use the WinSsl feature in Git for Windows 2.12.0++.

I recommend trying that and seeing if you get an easy win or not.

**Comment by michael-o** [comment] 2017-04-11 19:23
@whoisj How is this supposed to fix the issue? I have the same issue on RHEL 6 and FreeBSD. This isn't Windows-related or related to any TLS implementation in my opinion. It is either Git or libcurl.

**Comment by shiftkey** [comment] 2017-04-11 23:07
Given it's reproducible on RHEL, FreeBSD and Windows, I'd have a look into this squid error:

```
* Read response immediately from proxy CONNECT
< HTTP/1.1 407 Proxy Authentication Required
< Mime-Version: 1.0
< Date: Mon, 10 Oct 2016 12:55:35 GMT
< Content-Type: text/html
< Content-Length: 3181
< X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0
< Proxy-Authenticate: Negotiate
* gss_init_sec_context() failed:  An unsupported mechanism was requested. unknown mech-code 0 for mech unknown. 
< Proxy-Authenticate: Basic realm="Web-Proxy"
< X-Cache: MISS from s3000c
< X-Cache-Lookup: NONE from s3000c:80
< Connec
```

The `X-Squid-Error: ERR_CACHE_ACCESS_DENIED 0` seems to be normal squid behaviour, but the second message is more interesting:

```
* gss_init_sec_context() failed:  An unsupported mechanism was requested. unknown mech-code 0 for mech unknown. 
```

A quick Google check suggests `gss_init_sec_context()` is part of Oracle's Global Single Schema (some authentication system?), and maybe there's some mis-configuration between the proxy server and the authentication server.

@michael-o do you get the same behaviour and log messages on the other operating systems? Let's see if we can isolate the setup for this error...

**Comment by whoisj** [comment] 2017-04-12 03:03
> @whoisj How is this supposed to fix the issue? I have the same issue on RHEL 6 and FreeBSD. This isn't Windows-related or related to any TLS implementation in my opinion. It is either Git or libcurl.

Then I'd ask why are you posting this issue here on the Git **for Windows** issue tracker? Seems like the Git mailing list is the better place to report it. Regardless, @shiftkey is awesome as usual and probably is already on the right path to helping you.

**Comment by michael-o** [comment] 2017-04-14 16:11
@shiftkey This has nothing to do with Oracle's Global Single Schema.
@whoisj I did not, I just kicked it to say that this is not a Git for Windows issue. Please read my very first message.

**Comment by shiftkey** [comment] 2017-04-14 22:27
@michael-o please give some more details on what you're seeing on the other operating systems
 
> do you get the same behaviour and log messages on the other operating systems? Let's see if we can isolate the setup for this error...

**Comment by dscho** [comment] 2017-04-27 13:30
> I have the same issue on RHEL 6 and FreeBSD.

Please report this issue to [the Git mailing list](mailto:git@vger.kernel.org) which has a lot more volunteers to spare than the Git for Windows project.

**Closed by dscho** 2017-04-27 13:30 UTC
Labels: help wanted, missing-info, unclear
