### ISSUE TITLE
Receiving console output from ssh.exe 10mins after git.exe aborted/terminated?

### ISSUE THREAD

**Issue by ghost** [git-for-windows/git#1762] opened 2018-07-18 19:23 UTC
Hi @ll,

I hope I'm posting to the right group but I've got
a weird problem using GIT:

By accident I've tried to push a repository (containing an already
commited but not yet pushed submodule reference).
This fails immediately with an error of course BUT

after 10 mins I get an output on the console though the command exited!?
(... $Received disconnect from <GIT serverIP>: User session has timed out idling after 6000000 ms....)

Does anyone have an explanation why I still get an output after the command was aborted?

/Frank

**Comment by dscho** [comment] 2018-07-21 22:20
If you think that this might be a bug (from the account, it looks like a question better directed to a mailing list or to StackOverflow), please provide a full bug report instead of simply deleting all those pesky questions (whose answers, however, would possibly enable somebody to even help you).

**Comment by PhilipOakley** [comment] 2018-07-22 08:53
Hi Frank (@fhw72) , 

I see it was posted upstream at [1. Receiving console output from GIT 10mins after abort/termination?
   - by Frank Wolf @ 2018-07-18  6:38 UTC](https://public-inbox.org/git/1536686621.139255.1531895907281@ox.hosteurope.de/)  

> By accident I've tried to push a repository (containing an already
commited but not yet pushed submodule reference).
This fails immediately with an error of course BUT

> after 10 mins I get an output on the console though the command exited!?
(... $Received disconnect from <GIT serverIP>: User session has timed out idling after 6000000 ms....)

> Does anyone have an explanation why I still get an output after the command was aborted?

But got no replies. I do believe that it will be part of the Git For Windows overall environment, and something to do with the many ways the Windows has of maintaining contact with servers, especially if you are conneted remotely. I have a very vague recollection of an issue (you will need to search the closed tracker issues) of some connections timing out too earlyduring, I think, fetch or maybe push, while the packfile was being prepared, with a result that the time out was extended. It maybe that your 'error condition wasn't caught.

If you could fill in the template, and in the details section, expand as much as possible of your particular setup as web master that would help. Even better is an [MVCE  (minimal, verifiable, complete example)](https://stackoverflow.com/help/mcve) that others can repeat from scratch. Do include any session and proxy  types that you are using as they may well be the root cause.

Philip

**Comment by fhw72** [comment] 2018-07-22 15:34
I will try to provide an MVCE; will post it then. thanks!

**Closed** 2019-02-27 13:47 UTC
Labels: question
