### ISSUE TITLE
git doesn't work after updating Windows 10 Pro Insider Preview 1511 (segmentation fault)

### ISSUE THREAD

**Issue by Rumo-Arf** [git-for-windows/git#640] opened 2016-02-01 13:23 UTC
![default](https://cloud.githubusercontent.com/assets/11865340/12718511/5f74a4a4-c932-11e5-96cc-191606ea711b.PNG)

My git version is 2.7.0 and I will try down grading...

**Comment by dscho** [comment] 2016-02-01 13:53
This is the fifth duplicate of #627.

**Closed by dscho** 2016-02-01 13:53 UTC
Labels: duplicate
