### ISSUE TITLE
.bashrc doesn't execute

### ISSUE THREAD

**Issue by kjeremy** [git-for-windows/git#191] opened 2015-06-11 17:27 UTC
In trying to use git through ConsoleZ I invoke it with the following command: `PathToGit\Git\git-cmd.exe --command=PathToGit\Git\usr\bin\bash.exe --login -i`

Logging in this way does not execute the user's `.bashrc`.

**Comment by dscho** [comment] 2015-06-11 17:49
Probably related to https://github.com/msysgit/msysgit/pull/301.

**Comment by kjeremy** [comment] 2015-06-15 22:43
Yes I think it is related.  If I ```$ cp .bashrc .bash_profile``` then my aliases work.

**Comment by dscho** [comment] 2015-06-17 06:54
@kjeremy so how about giving it a try? [This commit would still need some work](https://github.com/ArloL/msysgit/commit/ebf60bd55e88693ceb73dea49783b5965cd2619b), but it should be straight-forward to address my feedback (and to adjust the commit message).

**Comment by dscho** [comment] 2015-06-20 15:50
@kjeremy are you still interested in resolving this issue?

**Comment by kjeremy** [comment] 2015-06-20 21:00
Sure.  Hopefully I'll get some time to work on it next week.  What exactly
was your issue with the commit that was proposed?

**Comment by dscho** [comment] 2015-06-21 12:44
> What exactly was your issue with the commit that was proposed?

- https://github.com/ArloL/msysgit/commit/ebf60bd55e88693ceb73dea49783b5965cd2619b#commitcomment-10329926
- https://github.com/msysgit/msysgit/pull/301#issuecomment-84588506
- https://github.com/msysgit/msysgit/pull/301#issuecomment-90927073

**Comment by dscho** [comment] 2015-08-17 13:59
@kjeremy so... did you get a chance to address your issue yet?

**Comment by kjeremy** [comment] 2015-08-19 14:50
I just copied my .bashrc to .bash_profile.

**Comment by dscho** [comment] 2015-08-19 14:59
> I just copied my .bashrc to .bash_profile.

That's a work-around, not a solution, of course. A proper fix would be much more desirable.

**Comment by gordontyler** [comment] 2015-08-19 15:55
The generally accepted solution is to add a line to your `.bash_profile` which sources `.bashrc`. Something like this:

    [ -f .bashrc ] && source .bashrc

This will ensure that your .bashrc is read for both login shells and interactive, non-login shells.

**Comment by dscho** [comment] 2015-08-19 16:17
@gordontyler That sounds good. Are you sure we do not need to use an explicit `$HOME/.bashrc`?

I think we need to do this as part of `git-extra` because there is no `/etc/bash.bash_profile` yet...

**Comment by gordontyler** [comment] 2015-08-19 17:03
I don't need to use `$HOME` with msys1/git1. In theory, a login shell is executed with the user's home directory as the current working directory.

I have a `/etc/profile` but it doesn't source `~/.bash_profile`. bash should do that automatically for login shells.

**Comment by cristovaov** [comment] 2015-08-19 18:10
Just a chiming in: @kjeremy starts up the Bash shell with login ( --login) and interactively (-i) just like me (consoleZ ftw!) and like older releases of Git for Win used to launch Bash. And doing so will not load the .bashrc file in the home dir with Bash V4.3 -- See:
http://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html  

However the `etc/profile` file sources the system-wide `etc/bash.bashrc` file and by simply adding the following conditional at the bottom of this `bash.bashrc` file, it will restore that old (unnatural?) behavior:
`if [ -f "$HOME/.bashrc" ]; then`
`  . "$HOME/.bashrc" `
`fi`

Hope this is helpful!
I'd be happy to PR if you can point to where and how

**Comment by gordontyler** [comment] 2015-08-19 18:47
However, that page specifically states:

> So, typically, your ~/.bash_profile contains the line
>
>     if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
>
> after (or before) any login-specific initializations.

Perhaps the Git installer should create a `$HOME/.bash_profile` that does this, if the file doesn't already exist.

**Comment by kjeremy** [comment] 2015-08-19 23:21
@dscho How do I find out where bash.bashrc comes from?  I've installed the sdk and checked out `build-extra` but don't see what I should be touching.

**Comment by cristovaov** [comment] 2015-08-20 09:05
While following the manual be the proper way to do it, I think we can forgive the exception for Windows: 
Elaborating on my previous comment:

Like @descho suggested adding a `home_bashrc.sh` (ex. filename) as part of `git-extra` with the suggested lines (or better) in my previous comment would be more sensible. 
I'd rather leave the choice to more knowledgeable users to make use of `.bash_profile` (by deleting that one `git-extra` file and not have the installer create any file in the %HOME% dir.

**Closed** 2015-08-20 09:20 UTC
Labels: enhancement, help wanted, sdk-packages

**Comment by dscho** [comment] 2015-08-20 11:05
> How do I find out where bash.bashrc comes from?

@kjeremy `pacman -Qo /etc/bash.bashrc` in the Git SDK.

@cristovaov let's leave @descho out of this, okay? She probably is wondering what us cranky old guys want from her, discussing things that are far, *far* away from visual design...

**Comment by Francisc** [comment] 2015-08-20 11:07
Is the renaming of `.bashrc.` to `.bash_profile` final? As in future releases will always look at `.bash_profile` and ignore `.bashrc`?

**Comment by nalla** [comment] 2015-08-20 11:17
@Francisc this is not a rename. See http://www.gnu.org/software/bash/manual/html_node/Bash-Startup-Files.html.

Especially

> When Bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes commands from the first one that exists and is readable. The --noprofile option may be used when the shell is started to inhibit this behavior. 

and

> When an interactive shell that is not a login shell is started, Bash reads and executes commands from ~/.bashrc, if that file exists. This may be inhibited by using the --norc option. The --rcfile file option will force Bash to read and execute commands from file instead of ~/.bashrc.

They just have different "meanings".

**Comment by cristovaov** [comment] 2015-08-20 11:26
@dscho Oh Dear! I apologise I've tagged by mistake :$

**Comment by dscho** [comment] 2015-08-20 12:07
@cristovaov no worries. I would never have seen her photos if it weren't for your tyop. Among others, I like [this one](https://instagram.com/p/4KzsuqyLA6/?taken-by=descho) a *lot*.

**Comment by Francisc** [comment] 2015-08-20 12:59
Thanks a lot, @nalla. Awesome reply and everything clear now.

**Comment by travi** [comment] 2015-08-20 14:12
I'd like to voice another vote to please keep this consistent with other bash environments and not make this behavior be specific to windows. I know of several people, myself included, that share dotfiles across windows, osx, and linux. 

While I agree that the logic determining when `.bashrc` vs `.bash_profile` is confusing, now that I've sorted it out I expect it to be predictable. If I provision a new machine and a file is added that causes different behavior, the cause would cost me enough time to track down that I would be pretty frustrated if I didn't have the background of this thread. 

If there is confusion around when to use which one, I've always found this [superuser answer](http://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile#answer-183980) to be a good sanity check in addition to the link above.

**Comment by dscho** [comment] 2015-08-20 14:54
@travi no worries. There was never a plan to deviate from the behavior in other Bash environments. It is really useful to have a `.bash_profile` that is only run when logging in, and a `.bashrc` that is executed whenever a new, non-login bash process is started. That is too useful to give up ;-)

**Comment by cristovaov** [comment] 2015-08-22 10:45
@dscho That is great! It turns out she is an acquaintance of mine - Please do tell her, I think she'd appreciate it :)

**Comment by dscho** [comment] 2015-08-22 13:38
@cristovaov [already done](https://twitter.com/JSchindelin/status/634321326929518592)...
