### ISSUE TITLE
fatal: credential-cache unavailable; no unix socket support

### ISSUE THREAD

**Issue by jeroen** [git-for-windows/git#4594] opened 2023-09-06 13:34 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.42.0.windows.2
cpu: x86_64
built from commit: 2f819d1670fff9a1818f63b6722e9959405378e3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Happens for all Windows
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
defaults
```

### Details

If we run `git help -a` we see that `credential-cache` is available:

```
git help -a 
....
   credential-cache        Helper to temporarily store passwords in memory
```

However, if we select it, the credential manager just returns errors all the time:

```
fatal: credential-cache unavailable; no unix socket support
```

This is something that changed relatively recently.

**Comment by rimrul** [comment] 2023-09-06 23:23
Duplicate of #3892

**Closed** 2023-09-06 23:23 UTC
Labels: duplicate
