### ISSUE TITLE
[regression 2.9.3.2 > 2.10.0.1] Signing fails

### ISSUE THREAD

**Issue by jrappen** [git-for-windows/git#897] opened 2016-09-22 09:50 UTC
### Setup

 - GitPortable `v2.10.0.windows.1`
 - Win10 Pro x64 Version 1607

### Details

 - using [cmder](https://github.com/cmderdev/cmder) `v1.3.1` which came with GitPortable `v2.9.3.windows.2`. However I had manually replaced it with GitPortable `v2.10.0.windows.1`.
 - `git commit -S -m "..."`

```text
error: gpg failed to sign the data
fatal: failed to write commit object
```

- verified that `gpg` is available and setup is correct via `echo "1234" | gpg --no-use-agent -o /dev/null --local-user <KEYID> -as - && echo "The correct passphrase was entered for this key"`

### Temporary workaround

Downgraded to GitPortable `v2.9.3.windows.2`.

---

/cc @cmderdev

**Comment by landstander668** [comment] 2016-09-22 14:29
I'm not familiar with cmdr, but for what it's worth this seems to be working under the [latest pre-release](https://github.com/git-for-windows/git/releases/tag/prerelease-v2.10.0.windows.1.11.geda474c).

```
$ git version --build-options
git version 2.10.0.windows.1.11.geda474c
sizeof-long: 4
machine: x86_64

$ git init foo && cd foo
Initialized empty Git repository in C:/Users/adric.norris/foo/.git/

$ git commit --allow-empty -S -m Empty

You need a passphrase to unlock the secret key for
user: "Adric Norris <landstander668@gmail.com>"
4096-bit RSA key, ID 47B2E725, created 2014-05-06

[master (root-commit) 448853c] Empty

$ git log --show-signature
commit 448853c3414fccfc270af6a98349973864a637f3
gpg: Signature made Thu, Sep 22, 2016  9:17:56 CDT
gpg:                using RSA key 83C5DE3A47B2E725
gpg: Good signature from "Adric Norris <landstander668@gmail.com>"
Author: Adric Norris <landstander668@gmail.com>
Date:   Thu Sep 22 09:17:56 2016 -0500

    Empty
```

**Comment by dscho** [comment] 2016-09-22 18:53
Isn't this a duplicate of https://github.com/git-for-windows/git/issues/871?

**Comment by landstander668** [comment] 2016-09-22 20:04
I believe you're correct, dscho.

**Comment by jrappen** [comment] 2016-09-22 20:13
@dscho Seems to be a duplicate of #871, yes.

I'll leave this open for now. I suggest not merging pre-releases into master going forward, so issues remain open until there is a stable release with the included fixes.

**Comment by dscho** [comment] 2016-09-23 20:49
Leaving this open when it is a known duplicate only creates work. Please either volunteer to help with the workload, or leave this closed.

**Closed by dscho** 2016-09-23 20:49 UTC
