### ISSUE TITLE
Python Windows launcher breaks history when run from Git Bash

### ISSUE THREAD

**Issue by evanunderscore** [git-for-windows/git#1013] opened 2016-12-29 03:42 UTC
When I use Git Bash to run Python using the Windows launcher (py.exe), the Python shell cannot store history (pushing up/down/F1-F9 always behave as though the history buffer is empty). This bug does not occur when running `py` in cmd.exe, or `/path/to/python` in Git Bash, or `winpty py` in Git Bash. (Note that I did *not* pick the default MinTTY option, so Windows binaries should function normally).

I only noticed this after upgrading to Python 3.6.0, but the issue affects any version of Python that I run using the launcher. I've tried uninstalling Python 3.6.0 and reinstalling 3.5.2 and 3.4.4, but the bug persists. I also tried uninstalling Git 2.11.0 and installing 2.8.4 and 2.5.0, which also made no difference.

At this stage it seems the bug is with the Python Windows launcher and not Git Bash, but any help investigating this issue would be appreciated.

Python bug report: http://bugs.python.org/issue29093

> Have you reported this to the git bash folks? We'll probably need someone who understands what their shell is actually doing to make any progress here.

---

Issue template completed below.

---

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Python 2.7.10 (32 bit)
Python 3.4.4 (64 bit)
Python 3.5.1 (64 bit)
Python 3.6.0 (64 bit)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ py
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1
>>> # pressing up here has no effect
```
 - What did you expect to occur after running these commands?

 Pressing up should set the line buffer to `a = 1`.

 - What actually happened instead?

Pressing up/down/F1-F9 all behave as though the history buffer is empty.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by evanunderscore** [comment] 2016-12-29 07:49
I've now confirmed this affects every version of the Python Windows launcher. Some versions of Python on my machine had pyreadline installed which was hiding the bug.

**Comment by evanunderscore** [comment] 2016-12-29 13:41
`ps | grep mintty` displays no results. I've never had any other issues running native Windows binaries from this shell.

**Comment by dscho** [comment] 2016-12-30 07:52
For the record, Git Bash is not really intended as anything else than a terminal to run Git. It is based on [MSYS2](https://msys2.github.io/) which *does* come with a Python that works even in MinTTY.

Having said that, if you fill in the missing information where exactly *your* Python was downloaded (an exact download link would be best), I will try to find some time to investigate.

**Comment by evanunderscore** [comment] 2016-12-30 08:04
The particular one I installed most recently is https://www.python.org/ftp/python/3.6.0/python-3.6.0-amd64.exe. Thanks.

**Comment by evanunderscore** [comment] 2016-12-31 10:51
I've noticed some more weirdness - running Python from a Batch or Python script seems to also suffer from this bug, but running it from a Bash script only sometimes does (at least on my machine).

```
$ cat test.bat
@echo off
"C:\Program Files\Python36\python.exe"

$ ./test.bat
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1
>>> # up key consistently does not show history
```

```
$ cat test.py
import subprocess
subprocess.run(['C:/Program Files/Python36/python.exe'])

$ "/c/Program Files/Python36/python.exe" test.py
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1
>>> # up key consistently does not show history
```

```
$ cat test.sh
#!/usr/bin/env bash
"/c/Program Files/Python36/python.exe"

$ ./test.sh
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> a = 1
>>> # up key sometimes works (bug occurs in ~1/3 runs)
```

**Comment by evanunderscore** [comment] 2016-12-31 10:58
This appears to have nothing to do with Python at all:

```
$ cat test.bat
@echo off
cmd.exe

$ ./test.bat
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

D:\test>echo hi
hi

D:\test> # up key does not work
```

The bug does not occur when cmd.exe is run directly, as is the case with Python.

**Comment by dscho** [comment] 2016-12-31 15:20
Thanks, that will make it much more straight-forward to reproduce when I am back at a computer.

**Comment by evanunderscore** [comment] 2017-01-01 10:59
Eryk Sun has posted an explanation of why this happens here: http://bugs.python.org/issue29093#msg284414

Increasing the number of history buffers fixes the issue for me. Is there any way we could get Git Bash to do this by default? Is altering the system-wide default an acceptable thing for the installer to do?

**Comment by dscho** [comment] 2017-01-03 14:17
I spent the entire morning on trying to implement an alternative idea to modifying global settings (which is a big no-no): edit the `.lnk` file directly. Alas, I was not too successful, as I could not easily find out how to infer the proper defaults for all of the `NT_CONSOLE_PROPS` settings (unfortunately, we cannot set *only* the history buffer size and number of history buffers). Maybe somebody else is more successful.

I will leave this open for a couple of days, in the hope that some helpful developer out there will make it work, and otherwise close it in a week or so.

**Comment by eryksun** [comment] 2017-01-04 07:29
At startup, conhost.exe queries options in the subkey matching the console title, e.g. "HKCU\Console\Git Bash". Anything not explicitly set there falls back on the defaults stored in "HKCU\Console". The "Git Bash" subkey only needs `NumberOfHistoryBuffers`, and maybe `FaceName` and `FontSize` to ensure it uses a TrueType font. You can set the console title via the `STARTUPINFO` `lpTitle` field when calling `CreateProcess`.

I'm not familiar with this code base, but it looks like the source for git-bash.exe is in [git-wrapper.c](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-wrapper.c#L617), with the command-line and other options defined as resources in [git-bash.rc](https://github.com/git-for-windows/MINGW-packages/blob/master/mingw-w64-git/git-bash.rc). By the way, there's no reason to use the `%ComSpec%` shell. It can run bash directly via `"""@@EXEPATH@@\\usr\\bin\\bash.exe"" --login -i"`.

**Comment by dscho** [comment] 2017-01-04 12:14
> I'm not familiar with this code base

Well, apparently familiar enough to figure that much out. If you could just go the last step further, contributing a Pull Request, that would be really, really helpful, as I have zero time to spend on this ticket for the rest of January.

**Comment by dscho** [comment] 2017-02-21 23:15
I also wonder whether [`CreateConsoleScreenBuffer`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682122(v=vs.85).aspx) may help. Just a suggestion: I still have no time to work on this issue myself.

**Comment by dscho** [comment] 2017-08-05 23:24
Closing this. I won't have time to work on this, and apparently nobody else, either.

**Comment by dscho** [comment] 2017-08-05 23:25
For the record: should my observation (nobody wanting to work on this) turn out to be wrong, I will gladly reopen this ticket at the point when somebody steps forward.

**Closed by dscho** 2017-08-05 23:24 UTC

**Comment by brdacost** [comment] 2021-07-01 06:47
The error still persists. Isn't there anyone available (willing) to work on this yet?

**Comment by rimrul** [comment] 2021-07-01 18:36
We could probably extend [`configure_via_resource()`](https://github.com/git-for-windows/MINGW-packages/blob/main/mingw-w64-git/git-wrapper.c#L540) to take a `HISTORY_BUFFERS=` parameter and a `CONSOLE_TITLE=` parameter. (The title could be tricky due to a potential space in the middle of "Git Bash") We could then use [`SetConsoleTitle()`](https://docs.microsoft.com/en-us/windows/console/setconsoletitle) (so we don't override global settings), and then fetch the current settings using [`GetConsoleHistoryInfo()`](https://docs.microsoft.com/en-us/windows/console/getconsolehistoryinfo) and write a modified amount of history buffers using [`SetConsoleHistoryInfo()`](https://docs.microsoft.com/en-us/windows/console/setconsolehistoryinfo). With that we could [include those parameters in the installer](https://github.com/git-for-windows/build-extra/blob/main/installer/install.iss#L3067) for Conhost Git Bash.
