### ISSUE TITLE
Source user's .bashrc

### ISSUE THREAD

**Issue by petebachant** [git-for-windows/git#333] opened 2015-08-29 14:01 UTC
The preview version of Git Bash sourced `~/.bashrc` by default, which was nice. Can you bring this back?

**Comment by maoueh** [comment] 2015-08-30 03:51
Duplicate of #191 (and others if I remember correctly). Sorry if it feels harsh, but take time to search issues before posting a new one.

**Comment by dscho** [comment] 2015-08-30 17:20
Yep, I agree that this is a duplicate. The good news is: this was already fixed and the next release will not have that bug.

**Closed by dscho** 2015-08-30 17:20 UTC
