### ISSUE TITLE
bash: /c/.../...WindowsApps/python3: Permission denied in git-bash

### ISSUE THREAD

**Issue by gemini4545** [git-for-windows/git#3030] opened 2021-02-09 08:30 UTC
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

**
 git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
**
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.18363.1256] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** NA **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** git-bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
**python3 **
```
 - What did you expect to occur after running these commands?

** python3 **

 - What actually happened instead?

**bash: /c/Users/Administrator/AppData/Local/Microsoft/WindowsApps/python3: Permission denied **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment] 2021-02-09 08:40
Duplicate of #2675

**Closed** 2021-02-09 08:40 UTC
Labels: duplicate
