### ISSUE TITLE
Git 2.13.1 crashes on branch checkout

### ISSUE THREAD

**Issue by bawejakunal** [git-for-windows/git#1206] opened 2017-06-15 18:30 UTC
`git checkout -b branchname` segfaults repeatedly

**Comment by dscho** [comment] 2017-06-15 19:41
This report is too terse to investigate. Happily, there have been more complete reports that allowed even a fix that has been released almost five hours ago: https://github.com/git-for-windows/git/releases/tag/v2.13.1.windows.2.

Besides, this is a duplicate of #1202.

**Closed by dscho** 2017-06-15 19:41 UTC
