### ISSUE TITLE
Typo in installer

### ISSUE THREAD

**Issue by nunoperalta** [git-for-windows/git#2664] opened 2020-06-04 19:25 UTC
"forard" => "forward"

![image](https://user-images.githubusercontent.com/487079/83801691-7ae51380-a6a1-11ea-87f9-2d26ee03a318.png)

**Comment by dscho** [comment] 2020-06-04 20:10
Fixed in https://github.com/git-for-windows/build-extra/pull/291.

Duplicate of #2652, #2654, #2656, #2657, #2660 and #2663.

**Closed by dscho** 2020-06-04 20:10 UTC
Labels: duplicate
