### ISSUE TITLE
Windows Installer Setup Display Left Blank -- Version 2.47.0.2

### ISSUE THREAD

**Issue by jerryfleurival** [git-for-windows/git#5273] opened 2024-11-24 16:10 UTC
**Configuring experimental options** (_only on last display page before Installation_).
     - What  experimental options or features?  Left Blank.  😕
        
Git Version: 2.47.0.2     
![git-for-windows-installer](https://github.com/user-attachments/assets/f2e040e2-e6e0-44c1-acf0-01434d6ef363)

**Comment by rimrul** [comment] 2024-11-24 16:24
Duplicate of #5231

**Closed** 2024-11-24 16:24 UTC

**Comment by jerryfleurival** [comment] 2024-11-25 13:16
@rimrul Thanks. Wow, a duplicate. I'm new to GitHub. I wonder how I overlooked this in the search. I must not have done a thorough search.
