### ISSUE TITLE
when the path contains chinese characters, git gui cannot be started

### ISSUE THREAD

**Issue by shanhongyue** [git-for-windows/git#549] opened 2015-11-28 15:18 UTC
when the path contains chinese characters, git gui cannot be started.

just like this:
![2015-11-28_231753](https://cloud.githubusercontent.com/assets/8165614/11452546/502028b4-9626-11e5-90e1-212a47ad81a5.png)

**Comment by dscho** [comment] 2015-11-28 15:29
Apart from [our bug reporting guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines) I have an additional suggestion: this might be a duplicate of https://github.com/git-for-windows/git/issues/410.

**Comment by shiftkey** [comment] 2016-12-08 04:35
Retested this in `2.11.0` (64-bit, Windows 10 14393) and it seems to be working fine now:

![](https://cloud.githubusercontent.com/assets/359239/20997665/ca8eed26-bd5b-11e6-9dcc-fca52e75b4b6.png)

**Closed by shiftkey** 2016-12-08 04:35 UTC
Labels: missing-info
