### ISSUE TITLE
error: Load key "C:\\Users\\bejelentkezni\\AppData\\Local\\Temp/.git_signing_key_tmp7F6VRw": invalid format?

### ISSUE THREAD

**Issue by ghost** [git-for-windows/git#3883] opened 2022-06-05 19:21 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.36.1.windows.1
cpu: x86_64
built from commit: e2ff68a2d1426758c78d023f863bfa1e03cbc768
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1741]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: CustomEditor
Custom Editor Path: D:\scripts\scoop\apps\vim\current\vim.exe
Default Branch Option: master
Path Option: CmdTools
SSH Option: ExternalOpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled

The defaults were also tried.
The portable version was also tried.
As a result, OpenSSH 8.9.1 (Windows) and 9.0 (Git) both exhibit the same behavior.

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No. Double-checked for any duplicate PATHs.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash, cmd, PowerShell 5, and PowerShell 7 all exhibit the same behavior.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit -Sam "test"
```

Context for the -S: ~/.gitconfig contained the following relevant options:

```
[user]
	signingkey = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSl0FGqSv/NUbhrNkDiOiy0qwdnc2HelqO22kJvS22b
[gpg]
	format = ssh
[commit]
	gpgsign = true
[tag]
	gpgsign = true
```

 - What did you expect to occur after running these commands?

A successful commit.

 - What actually happened instead?

```
error: Load key "C:\\Users\\Owner\\AppData\\Local\\Temp/.git_signing_key_tmp7F6VRw": invalid format?
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

[bejelentkezni/signingtest](https://github.com/bejelentkezni/signingtest)

**The reason I am opening a new issue** is because commit caeef01ea73ba126a6cd4dbf4a4564ecdca9a32c, which supposedly fixed this problem as it relates to CRLF line endings, either did not work or this issue is not related to line endings. With respect to #3647 and #3819, the same behavior is exhibited regardless of public or private key use or whether ssh-agent is invoked or not. Further, the latter was related to an external software that I do not use. So either there is a new bug causing this error or there was a regression in Git or OpenSSH, but since both versions of OpenSSH exhibit the same behavior and the other issues mentioned reverting to Git 2.35.3, I have to assume it is because of Git and unrelated to previous issues. I have no ability to further debug this. Again, I tried several combinations of Git settings and SSH versions and PATH problems. I also checked blog tutorials to make sure my config file was not malformed. Old fixes such as "use external OpenSSH" and "update Git/OpenSSH" do not work anymore.

**Comment by dscho** [comment] 2022-06-06 12:45
> [user]
> 	signingkey = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSl0FGqSv/NUbhrNkDiOiy0qwdnc2HelqO22kJvS22b

https://git-scm.com/docs/git-config#Documentation/git-config.txt-usersigningKey talks about this format being deprecated. Could you try the `key::` format?

Also, this strikes me as an issue that might not be Windows-specific. Maybe you could take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently)?

**Comment by dscho** [comment] 2022-06-06 12:50
> `git commit -Sam "test"`

This fails for me with "error: pathspec 'test' did not match any file(s) known to git". But if you uncuddle `-S -a -m test`, it works. However, I get this:

```console
$ ./git -c user.signingkey="ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSl0FGqSv/NUbhrNkDiOiy0qwdnc2HelqO22kJvS22b" commit --allow-empty -S -m "test"
gpg: skipped "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSl0FGqSv/NUbhrNkDiOiy0qwdnc2HelqO22kJvS22b": No secret key
gpg: signing failed: No secret key
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by bejelentkezni** [comment] 2022-06-06 15:19
> > [user]
> > signingkey = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPSl0FGqSv/NUbhrNkDiOiy0qwdnc2HelqO22kJvS22b
> 
> https://git-scm.com/docs/git-config#Documentation/git-config.txt-usersigningKey talks about this format being deprecated. Could you try the `key::` format?
> 
> Also, this strikes me as an issue that might not be Windows-specific. Maybe you could take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently)?

Hello, while I did miss trying `key::` while doing research, that leads to the same error again. I am really tempted to think that something about commit https://github.com/git-for-windows/git/commit/caeef01ea73ba126a6cd4dbf4a4564ecdca9a32c didn't work. It should be windows-specific, since I can't reproduce it in my Arch VM.

**Comment by dscho** [comment] 2022-06-06 18:21
> I am really tempted to think that something about commit [caeef01](https://github.com/git-for-windows/git/commit/caeef01ea73ba126a6cd4dbf4a4564ecdca9a32c) didn't work.

Could you verify that by [building Git](https://github.com/git-for-windows/git/wiki/Building-Git) from that commit, confirming that `./bin-wrappers/git [...]` fails in the indicated way, then build from the parent commit and confirm that it succeeds?

**Comment by dscho** [comment] 2022-06-08 13:42
> I am not sure what "parent commit" means

I had [this](https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefparentaparent) in mind.

> but even if it failed in the indicated way from that commit, a previous commit should fail in the same way. That commit was meant to fix this problem.

Oh right.

Still, I cannot reproduce the issue locally, so I will only be able to provide guidance for your own investigation.

> `error: Load key "C:\\Users\\Owner\\AppData\\Local\\Temp/.git_signing_key_tmp7F6VRw": invalid format?`

This error message seems to be produced by OpenSSH, not by Git, and I suspect [this code](https://github.com/openssh/openssh-portable/blob/ea97ec98c41ec2b755dfab459347db674ff9a5de/ssh-keygen.c#L324-L327) to be responsible for it.

Which makes me suspect that `ssh-keygen` is called with a file name where the corresponding file contents contain a Carriage Return.

To find out more, do execute the command with `GIT_TRACE=<logfilename>`, then inspect the generated log file (in particular, look for Carriage Returns in unexpected places!), then copy the contents of the referenced temporary file somewhere, inspect those, too. If everything else fails, instrument [the code](https://github.com/git-for-windows/git/blob/caeef01ea73ba126a6cd4dbf4a4564ecdca9a32c/gpg-interface.c#L482) to produce helpful debug messages that indicate where/how the execution stops, or [debug the program using `gdb`](https://github.com/git-for-windows/git/wiki/Debugging-Git#debugging-git-using-the-gnu-debugger-gdb).

Good luck, and please do not hesitate to share your findings along the way ;-)

**Comment by rimrul** [comment] 2022-07-28 18:17
>  I really hope it's just this, an incorrect bundling

No part of what you described sounds like anything wrong going on.

**Comment by dscho** [comment] 2022-07-29 10:20
> found myself unable to push or fetch

That is a totally different problem than what was reported in this ticket (which revolved around signing newly-created commits using an SSH key).

> the paths being used by [...] were nonsensical, like `/c/Users/tinne26/.ssh/`

But they are not non-sensical, you just misunderstood that the bundled SSH is an _MSYS_ program (see [our wiki page](https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2) about "MSYS vs MINGW").

**Comment by tinne26** [comment] 2022-07-29 11:59
Thanks for clarifying. I still think this is an extremely technical topic that's not really explained anywhere from the start / installation and can lead to much frustration except for those already deeply intimate with the idiosyncrasies of the system. I was personally offended by rimrul's dismissive reply. I've been a programmer for some years and many of the things exposed here clearly deviate from any kind of standard or expected behavior under Unix or Windows. I now understand the technical reasons behind it, but I can't help but suspect that there's a lot of personal bias and normalization about certain things from those working on the project that still look completely alien to outsiders and should be taken more in consideration.

I want to apologize for sidetracking the issue and the tone of my last comment. Please take it as just another unfiltered reaction from a user who had trouble with git-scm.

**Comment by lostmsu** [comment] 2022-08-23 23:42
The problem exists for me in `git version 2.37.2.windows.2`

**Comment by dscho** [comment] 2022-08-24 06:45
Closing this ticket, as the original poster's account has been deleted. @lostmsu you may want to open a new ticket with all the relevant information.

**Closed by dscho** 2022-08-24 06:45 UTC

**Comment by adamburgess** [comment] 2022-08-24 08:43
why close this issue because of that? Good to keep the discussion in one place...

I also have the same problem.
```cmd
error: Load key "C:\\Users\\Adam\\AppData\\Local\\Temp/.git_signing_key_tmpK7QlWj": invalid format?

fatal: failed to write commit object
```

```
[user]
	email = adamburgess@users.noreply.github.com
	name = Adam Burgess
	signingkey = ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE7GyYmr2U4Gnpq1KKAqmL/YPRreDv2gjZsfYoMsPLxr
[commit]
	gpgsign = true
[gpg]
	format = ssh
```

```
git version 2.37.2.windows.2
```

**Comment by lostmsu** [comment] 2022-08-24 16:08
@dscho not sure what the point would be. Nothing is wrong with this issue. Do you want me to build git from source to check the intermediate output? You mentioned the issue does not repro for you, are you saying you can sign git commits with SSH key on Windows without customized configuration?

**Comment by lostmsu** [comment] 2022-08-24 16:11
Some potentially relevant info:

```
➜ git config --list --global
user.name=REDACTED
user.signingkey=key::ssh-ed25519 REDACTED
core.excludesfile=C:\REDACTED\.gitignore_global
core.sshcommand=C:/Windows/System32/OpenSSH/ssh.exe
core.fsmonitor=true
core.untrackedcache=true
pull.ff=only
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
commit.gpgsign=true
gpg.format=ssh
tag.gpgsign=true

➜ git config --list --system
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
```

**Comment by lostmsu** [comment] 2022-08-24 18:02
Possibly relevant: https://superuser.com/questions/1695601/use-ssh-key-signing-with-git-and-ssh-agent-under-windows

**Comment by rimrul** [comment] 2022-08-24 18:09
> Possibly relevant: https://superuser.com/questions/1695601/use-ssh-key-signing-with-git-and-ssh-agent-under-windows

Unlikely, at least for the situation described by the original user, because the accepted answer says the fix is to install with the "external OpenSSH" option, but that's already how it was installed by that user.

**Comment by lostmsu** [comment] 2022-08-24 18:39
Is there a way to force git to use specific ssh-keygen executable similar to `core.sshcommand`?

**Comment by d-sanderson** [comment] 2022-08-26 23:12
I am also experiencing this issues, I tried installing git with external OpenSSH and the error persists

**Comment by dscho** [comment] 2022-08-27 05:53
> I am also experiencing this issues, I tried installing git with external OpenSSH and the error persists

Since the original repository with a reproduction no longer exists, I would like to ask you to open a new ticket, with a new [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) and a summary of what has been already found out in this here ticket.
