### ISSUE TITLE
Shebang for python in git-for-windows

### ISSUE THREAD

**Issue by ironmanproject** [git-for-windows/git#3100] opened 2021-03-10 19:05 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.30.1.windows.1
cpu: x86_64
built from commit: ca911fc9d050b3ec77ee1f1c44987794a4991e31
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.19042.804]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: Atom
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git-Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
https://stackoverflow.com/questions/66571129/python-shebang-permission-denied-in-git-bash-for-windows
```
'''#!/usr/bin/env python3

print('Test')'''
```
 - What did you expect to occur after running these commands?

'Test'

 - What actually happened instead?

'/usr/bin/env: ‘python3’: Permission denied'

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/ironmanproject/Russell.git

**Comment by dscho** [comment] 2021-03-10 20:38
Hi @ironmanproject, and welcome to the Git for Windows project!

>     * I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Here is a query: https://github.com/git-for-windows/git/issues?q=is%3Aissue+is%3Aopen+python+permission+denied. It finds https://github.com/git-for-windows/git/issues/2833 which looks quite like the same issue.

Could you verify that [Cygwin](https://cygwin.com) (from which Git Bash is derived) shares the same problem?

**Comment by rimrul** [comment] 2021-03-11 05:50
This (as well as #2833) is probably a duplicate of #2675, which is indeed an issue inherited from Cygwin.
What does `type -a python3` say?

**Comment by dscho** [comment] 2021-03-11 19:28
FWIW I _think_ I have a work-around for now. I create `$HOME/bin/` and write the following contents into `python3` in that directory:

```sh
#!/bin/sh

exec "$LOCALAPPDATA\Programs\Python\Python38-32\python.exe" "$@"
```

At least here, it works around the issue.

> What does `type -a python3` say?

For me, it says:

```
python3 is /c/Users/me/bin/python3
python3 is /c/Users/me/bin/python3
python3 is /c/Users/me/AppData/Local/Microsoft/WindowsApps/python3
python3 is /c/Users/me/AppData/Local/Microsoft/WindowsApps/python3
```

No idea why there are two lines per entry ;-)

Back to the issue. I do see that `python3.exe` is 0-bytes long:

```
08/23/2020  10:28 PM                 0 python3.exe
```

Permission is not only denied to execute this, by the way, reading it is also not permitted.

Funny thing is that calling the very same `.exe` through `cmd` _works_: `cmd //c "$LOCALAPPDATA"/Microsoft/WindowsApps/python.exe --help` shows the expected output.

This makes me think that there is a chance that we can fix the MSYS2 runtime to detect the situation and work around it by falling back to something like [`ShellExecute()`](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-shellexecutew).

**Comment by dscho** [comment] 2021-03-12 15:03
I _think_ I have a fix for this, in https://github.com/msys2/msys2-runtime/pull/27.

**Closed** 2021-03-27 08:40 UTC
