### ISSUE TITLE
Login with Visual Studio Team Services not working

### ISSUE THREAD

**Issue by letmaik** [git-for-windows/git#840] opened 2016-07-31 21:46 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
   output of `git version` as well.

64 bit

```
$ git --version
git version 2.9.2.windows.1
```

 - Which version of Windows are you running? 32-bit or 64-bit?

64 bit

 - What options did you set as part of the installation? Or did you choose the
   defaults?

defaults

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Trying to clone a repository via Visual Studio Team Services.

 - What did you expect to occur after running these commands?

Typically, the below login dialog field (as in other Microsoft websites with the same authentication procedure) would display a "please login at microsoft.com" link after entering the email address, which then would lead to finishing the login process. 

 - What actually happened instead?

An error is displayed:

![capture](https://cloud.githubusercontent.com/assets/530988/17279601/23029bbc-5770-11e6-9242-6ec1d367f3a7.PNG)

> You cannot use this account for this purpose because it belongs to an organisation. Please choose a different account or sign up for a new one.

**Comment by dscho** [comment] 2016-08-01 08:25
@whoisj any idea?

**Comment by whoisj** [comment] 2016-08-01 14:27
This happens when an account, which is tied to an organization which is in-turn tied to an Azure Authentication Directory, attempts to logon using Microsoft Account authentication (also known as Live, Outlook, etc.). There's, most likely, a confict at the account's administrative level.

I quickly looked at @letmaik profile to check for Microsoft employee status, but I see not. I checked because this most often is reported (to me) by MSFT employees because they often link their MSA to their corporate accounts to make things like downloading apps from the Microsoft App Store easier, then find that they've locked themselves out of VSTS.

Easiest solution: flush all cookies, try again.

@letmaik , what was the domain of the email account you are/were attempting to logon to VSTS with? I really **do not** want the whole email, just the part after the '@' character. Thanks

**Comment by letmaik** [comment] 2016-08-01 17:23
On 01/08/2016 15:27, J Wyman wrote:
>
> @letmaik <https://github.com/letmaik> , what was the domain of the 
> email account you are/were attempting to logon to VSTS with? I really 
> *do not* want the whole email, just the part after the '@' character. 
> Thanks
>
@microsoft.com (t- prefix)

**Comment by whoisj** [comment] 2016-08-01 20:23
> @microsoft.com

And, there we are: it's the MSA vs AAD scenario.

Please check with your group admin, or take advantage of the SSH support in VSTS now. This can be a deep hole into which you'll invest a lot of time getting IT to undo the bad things they've done.

This, in fact, most likely a Azure domain issue, caused by invalid settings or configuration on the part of the domain administrators.

**Comment by letmaik** [comment] 2016-08-03 18:51
Sorry, I can't be bothered really to investigate this. It Should Just 
Work. I'll use the git command line with the generated access tokens now.

**Comment by dscho** [comment] 2016-08-04 14:27
@letmaik I am sorry that it does not work. It seems, though, that we cannot try to resolve this if you do not have the time to investigate further on your side, because we simply have no idea how to reproduce the issue. The good news is that you found a work-around. So let's just close this ticket.

**Closed by dscho** 2016-08-04 14:27 UTC
