### ISSUE TITLE
Internal errors when cloning from bare repo on network drive

### ISSUE THREAD

**Issue by tkelman** [git-for-windows/git#554] opened 2015-12-02 05:14 UTC
Running 64 bit Windows Server 2008 R2, 64 bit git-for-windows 2.6.3.windows.1. The following works fine in git-cmd when I try it under C, but not under a network drive X:
```
X:\gittest>git clone --bare git://github.com/quinnj/Dates.jl.git Dates-bare
Cloning into bare repository 'Dates-bare'...
remote: Counting objects: 771, done.
emote: Total 771 (delta 0), reused 0 (delta 0), pack-reused 771
Receiving objects: 100% (771/771), 194.40 KiB | 0 bytes/s, done.
Resolving deltas: 100% (514/514), done.
Checking connectivity... done.

X:\gittest>git clone Dates-bare Dates-full
Cloning into 'Dates-full'...
done.
error: internal error: refs/remotes/origin/deprecated is not a valid packed refe
rence!
error: internal error: refs/remotes/origin/master is not a valid packed referenc
e!
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': Trying to
 write ref refs/heads/master with nonexistent object 3ccb8b94938518f75b789cd794f
495066482a2b7
fatal: The remote end hung up unexpectedly
```

Let me know if there's any additional information I can provide. With `GIT_TRACE=1` I get a couple extra lines, not sure if useful:
```
X:\gittest>set GIT_TRACE=1

X:\gittest>git clone Dates-bare Dates-full
05:11:33.816695 git.c:348               trace: built-in: git 'clone' 'Dates-bare
' 'Dates-full'
Cloning into 'Dates-full'...
05:11:34.347105 run-command.c:343       trace: run_command: 'git-upload-pack '\'
'X:/gittest/Dates-bare'\'''
done.
error: internal error: refs/remotes/origin/deprecated is not a valid packed refe
rence!
error: internal error: refs/remotes/origin/master is not a valid packed referenc
e!
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': Trying to
 write ref refs/heads/master with nonexistent object 3ccb8b94938518f75b789cd794f
495066482a2b7
fatal: The remote end hung up unexpectedly
```

edit: whoops, sorry for not searching carefully enough for this one, ref https://groups.google.com/forum/#!msg/msysgit/5J3ELvZND0s/2VPm-eUf0YMJ - there's a workaround of calling `git clone file://X:\gittest\Dates-bare Dates-full`, but is this still a bug that the relative path doesn't work?

**Comment by dscho** [comment] 2015-12-02 14:14
I just tried this with Windows 10 in a VirtualBox, where Z: is mapped to `\\vboxsrv\home`:

```cmd
Z:\>mkdir gittest

Z:\>cd gittest

Z:\gittest>git clone --bare git://github.com/quinnj/Dates.jl.git Dates-bare
Cloning into bare repository 'Dates-bare'...
remote: Counting objects: 771, done.
remote: Total 771 (delta 0), reused 0 (delta 0), pack-reused 771 eceiving objects:  81% (625/771)
Receiving objects: 100% (771/771), 194.40 KiB | 0 bytes/s, done.
Resolving deltas: 100% (514/514), done.
Checking connectivity... done.

Z:\gittest>git clone Dates-bare Dates-full
Cloning into 'Dates-full'...
done.

Z:\gittest>
```

Maybe it depends on the exact *type* of network drive? Are you using a Samba share or some such?

In any case, it would be real good if you could work out a way to reproduce this, with precise steps that hopefully do not require a separate server.

**Comment by tkelman** [comment] 2015-12-02 14:34
This is two separate servers on AWS. I specified the mapped drive via the public IP of the other server. Don't think it is a samba share, but not sure how to find out. I'll see if I can get this to happen in a more controlled situation. It may be hard-link related since the file:// prefix works as a workaround, will also try another few flag combinations.

**Comment by tkelman** [comment] 2015-12-02 17:32
I think it's going to require a separate server. A mapped drive on a local subnet is working. I tried using ExpandDrive to map a google drive account to a network drive (http://www.expandrive.com/map-google-drive-as-a-network-drive/), but that was having issues during the initial clone with lock synchronization
```
X:\gittest>git clone --bare git://github.com/quinnj/Dates.jl.git Dates-bare
Cloning into bare repository 'Dates-bare'...
error: could not lock config file X:/gittest/Dates-bare/config: File exists
error: could not lock config file X:/gittest/Dates-bare/config: File exists
error: could not lock config file X:/gittest/Dates-bare/config: File exists
error: could not lock config file X:/gittest/Dates-bare/config: File exists
error: could not lock config file X:/gittest/Dates-bare/config: File exists
error: could not lock config file X:/gittest/Dates-bare/config: File exists
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by dscho** [comment] 2015-12-03 14:43
If you can come up with a precise & concise list of steps how to reproduce e.g. setting up a Samba server inside Vagrant, I promise I will try my best to have a look at resolving this issue.

**Comment by tkelman** [comment] 2015-12-03 21:18
That might take me a while to get to. I'll see if maybe I could spin up a temporary AWS instance that I could send you login credentials for privately, that may be faster.

**Comment by Veve2** [comment] 2016-03-03 14:45
You have to include `file://<repository location>` when cloning to a mapped drive.

    git clone --bare git://github.com/quinnj/Dates.jl.git file://X:/gittest/Dates-bare

As additionnal tips, use quotes arround the whole file://... if of of the folders contains a space.

**Comment by tkelman** [comment] 2016-03-03 18:10
Yes, that was the workaround I went with. Omitting the `file://` probably shouldn't be causing an internal error though.

**Comment by dscho** [comment] 2016-04-02 13:18
Since we have a workaround, I'll just go ahead and close this as a wontfix.

**Closed by dscho** 2016-04-02 13:18 UTC
Labels: unclear

**Comment by tkelman** [comment] 2016-04-02 13:36
The discussions linked to in https://github.com/git-for-windows/git/issues/654 lead me to believe this might be a limitation of Windows mmap across network shares. There's probably still an underlying bug or better way of working around the issue here, but if you don't have access to a real network share on a separate system it's going to take more time to try to reproduce than I have.
