### ISSUE TITLE
Clone terminal from Task Bar in Windows 7+

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#207] opened 2015-06-18 18:28 UTC
In Windows 7 and up, you can MIDDLE CLICK an open application to open another instance of it. You can also Right-Click it and select the shortcut as well.

This does not work for the git-bash.exe terminal that is launched. Expected behavior is that a middle click functions the same as ALT+F2 when pressed inside a terminal instance.

**Comment by rcdailey** [comment] 2015-06-19 18:13
How is this a question? I didn't even use a `?` symbol. Maybe the label has some other meaning that isn't straightforward.

**Comment by dscho** [comment] 2015-06-19 19:50
Duplicate of https://github.com/git-for-windows/git/issues/167.

**Closed by dscho** 2015-06-19 19:50 UTC
