### ISSUE TITLE
Regression with process substitution (`<(echo foo)`)

### ISSUE THREAD

**Issue by michaelblyons** [git-for-windows/git#2325] opened 2019-09-09 13:37 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - 64-bit Git

```
$ git --version --build-options

git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

**Worked with v2.21.0.windows.1 but no longer with v2.23.0.windows.1**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

**Bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
 mapfile -t foo < <(echo -e "bar\nbaz")
```
 - What did you expect to occur after running these commands?

`$foo` contains (`bar`, `baz`)

 - What actually happened instead?

`bash: /dev/fd/62: No such file or directory`

**Comment by rimrul** [comment] 2019-09-09 13:57
This seems to be a duplicate of #2291 and #2322.

**Closed** 2019-09-09 14:36 UTC
