### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Envici** [git-for-windows/git#641] opened 2016-02-02 07:17 UTC
Every time I run a command no matter what it it is, I get "segmentation fault". Is there any way I can fix this? I have tested using several versions including the latest version.

**Comment by phileggel** [comment] 2016-02-02 07:51
Same issue for me. I am on windows 14251.
This seems to be an issue with that insider build.
http://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_web/upgrading-from-11099-to-14251-is-causing-git-for/f306090a-788e-4514-ae66-66b9ae94b5ff

**Comment by dscho** [comment] 2016-02-02 08:02
@Envici please note that your report is really lacking any sort of detail. Are you also on Windows 14251? I have to assume this, and note that this is the sixth duplicate of #627.

**Closed by dscho** 2016-02-02 08:02 UTC
Labels: duplicate
