### ISSUE TITLE
Getting "warning: url has no scheme: fatal: credential url cannot be parsed:" after upgrading to 2.26.2

### ISSUE THREAD

**Issue by dima-y** [git-for-windows/git#2596] opened 2020-04-22 23:29 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
cpu: x86_64
built from commit: 4267c88d0d8936ae723bba55e0576b1c4f3d4e1a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.207]
```

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd.exe

After upgrading from 2.26.1 to 2.26.2, I started receiving these messages on 'git pull' and some other commands:

```
warning: url has no scheme:
fatal: credential url cannot be parsed:
```
Yet all seems to work fine after that.

In my .git/config I have the following lines:

```
[credential]
	helper = store
```

Removing those 'fixed' the problem. Yet I'm not sure whether this is a bug or a feature. It started only after upgrading to 2.26.2. A similar issue is being discussed [here](https://github.com/desktop/desktop/issues/9597).

Thanks.

**Comment by dscho** [comment] 2020-04-23 12:09
> A similar issue is being discussed [here](https://github.com/desktop/desktop/issues/9597).

Indeed, this is the ticket where all the action is ;-)

**Comment by dscho** [comment] 2020-04-25 14:35
For the record, I could not reproduce that problem with v2.26.2, only with the backport included in GitHub Desktop (it uses a MinGit version that is based off of v2.23.0 plus patches).

Maybe you have a "funny" `[credential ""]` entry in one of your configs?

My current understanding is that this is not actually an issue with v2.26.2, but there are other issues that are being discussed on the mailing list e.g. at https://lore.kernel.org/git/pull.615.v3.git.1587728992.gitgitgadget@gmail.com/#r. Once the dust settles, I am relatively certain that a Git v2.26.3 will be released (and therefore also a Git for Windows v2.26.3). If not, I will weigh whether we need a Git for Windows v2.26.2(2).

**Comment by dima-y** [comment] 2020-04-25 14:44
@dscho I do not see any such "funny" credentials in my config:
```
> git config --list | grep creden
credential.helper=manager
credential.helper=manager
credential.helper=store
```
As I noted above, removing these lines from .git\config:
```
[credential]
	helper = store
```
"fixes" the issue. This definitely started after upgrading v2.26.1 to v2.26.2.

**Comment by dscho** [comment] 2020-04-25 14:46
> > git config --list | grep creden

For my better understanding, could you re-run this with `--show-origin`?

**Comment by dima-y** [comment] 2020-04-25 14:47
Here you go:
```
> git config --list --show-origin | grep creden
file:C:/Program Files/Git/etc/gitconfig credential.helper=manager
file:C:/Users/dima/.gitconfig   credential.helper=manager
file:.git/config        credential.helper=store
```

**Comment by dscho** [comment] 2020-04-25 14:54
I still cannot reproduce :-(

Can you verify that the sections look like this?

```ini
[credential]
        helper = store
```

**Comment by dima-y** [comment] 2020-04-25 14:56
Yes, this is copied/pasted from .git/config:
```
[credential]
	helper = store 
```
and here's the output:
```
> git pull
warning: url has no scheme:
fatal: credential url cannot be parsed:
Already up to date.
```

**Comment by dscho** [comment] 2020-04-25 15:00
Hmm. Maybe there is a hook at work? Could you try again after setting `GIT_TRACE=1`?

**Comment by dima-y** [comment] 2020-04-25 15:05
```
> git pull
11:01:37.252559 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
11:01:37.254559 git.c:439               trace: built-in: git pull
11:01:37.259556 run-command.c:663       trace: run_command: git fetch --update-head-ok
11:01:37.273547 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:37.276546 git.c:439               trace: built-in: git fetch --update-head-ok
11:01:37.281543 run-command.c:663       trace: run_command: GIT_DIR=.git git remote-https origin https://xxx@xxx.git
11:01:37.293536 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:37.295536 git.c:703               trace: exec: git-remote-https origin https://xxx@xxx.git
11:01:37.295536 run-command.c:663       trace: run_command: git-remote-https origin https://xxx@xxx.git
11:01:37.310527 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:37.527402 run-command.c:663       trace: run_command: 'git credential-manager get'
11:01:37.582371 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:37.585369 git.c:703               trace: exec: git-credential-manager get
11:01:37.585369 run-command.c:663       trace: run_command: git-credential-manager get
11:01:38.313458 run-command.c:663       trace: run_command: 'git credential-manager store'
11:01:38.430390 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:38.435386 git.c:703               trace: exec: git-credential-manager store
11:01:38.435386 run-command.c:663       trace: run_command: git-credential-manager store
11:01:38.662257 run-command.c:663       trace: run_command: 'git credential-manager store'
11:01:38.741212 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:38.744210 git.c:703               trace: exec: git-credential-manager store
11:01:38.744210 run-command.c:663       trace: run_command: git-credential-manager store
11:01:38.991068 run-command.c:663       trace: run_command: 'git credential-store store'
11:01:39.032044 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:39.034043 git.c:703               trace: exec: git-credential-store store
11:01:39.034043 run-command.c:663       trace: run_command: git-credential-store store
11:01:39.045542 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
warning: url has no scheme:
fatal: credential url cannot be parsed:
11:01:39.090515 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
11:01:39.116501 run-command.c:663       trace: run_command: git rev-list --objects --stdin --not --all --quiet --alternate-refs
11:01:39.128494 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:39.130493 git.c:439               trace: built-in: git rev-list --objects --stdin --not --all --quiet --alternate-refs
11:01:39.156478 run-command.c:1616      run_processes_parallel: preparing to run up to 1 tasks
11:01:39.156478 run-command.c:1648      run_processes_parallel: done
11:01:39.156478 run-command.c:663       trace: run_command: git gc --auto
11:01:39.168471 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:39.170470 git.c:439               trace: built-in: git gc --auto
11:01:39.182463 run-command.c:663       trace: run_command: git merge FETCH_HEAD
11:01:39.194456 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
11:01:39.197454 git.c:439               trace: built-in: git merge FETCH_HEAD
Already up to date.
```

**Comment by dscho** [comment] 2020-04-25 19:56
> ```
> [...]
> 11:01:39.034043 run-command.c:663       trace: run_command: git-credential-store store
> 11:01:39.045542 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
> warning: url has no scheme:
> fatal: credential url cannot be parsed:
> [...]
> ```

I tried for half an hour to reproduce this problem by trying various combinations of things to feed to `git credential-store store` via standard input in the hopes of recreating the problem, failing. Until I inspected the source code for `git-credential-store` and figured out that it saves credentials in the `.git-credentials` file in the user's home directory (which BTW I would highly discourage, as that file is not protected against prying eyes) in the form `https://user:password@host.com`.

So I had a hunch and added an empty line to that file. And bingo:

```sh
$ printf 'url=https://example.com\nusername=123\npassword=123\n' | git credential-store store
warning: url has no scheme:
fatal: credential url cannot be parsed:
```

So here are my recommendations, in no particular order:

- Stop using `git credential-store`. No, really. It is not safe.
- Use the Git Credential Manager. It uses at least the Windows Store, which is protected by your login.
- Actually, try to use 2-factor authentication whenever you can. Git Credential Manager supports that. Unlike `git credential-store`.
- Inspect the file `~/.git-credentials` and see whether there is an empty line; If so, delete it.
- Or maybe delete the whole file, after switching to Git Credential Manager.
- Don't ever, _ever_ give me shell access to your dot files in your home directory.

**Comment by dima-y** [comment] 2020-04-25 22:52
@dscho Thanks for the recommendations.
>> Don't ever, ever give me shell access to your dot files in your home directory.
Sorry, did I?

**Comment by rabrahamOpti** [comment] 2020-04-27 21:48
> 
> 
> > A similar issue is being discussed [here](https://github.com/desktop/desktop/issues/9597).
> 
> Indeed, this is the ticket where all the action is ;-)

I think my comment there technically belongs here, but that issue seems to be more active: https://github.com/desktop/desktop/issues/9597#issuecomment-620248876

**Comment by dscho** [comment] 2022-03-17 17:28
Closing as stale.

**Closed by dscho** 2022-03-17 17:28 UTC
