### ISSUE TITLE
`git add . -p` gets stuck in Windows Terminal

### ISSUE THREAD

**Issue by jfcherng** [git-for-windows/git#4339] opened 2023-03-11 10:56 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

The `add.interactive.useBuiltin` is no longer usable as of git v2.40 so I remove it. And now I encounter an issue that `git add . -p` gets stuck in Windows Terminal.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.0.rc2.windows.1
cpu: x86_64
built from commit: 7c33321434c33ab875d8989d1a838cc642c6dbd9
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19045.2673]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My issue seems to only happen in Git Bash in Windows Terminal.

```ini
[core]
        pager = delta
[delta]
        line-numbers = true
[interactive]
        diffFilter = delta --color-only
```

`delta` is https://github.com/dandavison/delta

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I use Git Bash in Windows Terminal.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

The issue happens when run `git add . -p` in any dirty repository.

 - What did you expect to occur after running these commands?
 
In plain git bash, the output is well-colored and not get stuck.

![image](https://user-images.githubusercontent.com/6594915/224480112-265f41f8-a118-4dfc-8575-04b6524d4f54.png)

 - What actually happened instead?

In git bash in Windows Terminal, the output shows in weird colors and git bash gets stuck (not respond to keyboard input).

![image](https://user-images.githubusercontent.com/6594915/224480103-5b793af1-c66d-42d9-928b-77b38ffcb089.png)

---

Also reported on https://github.com/dandavison/delta/issues/1344.

**Comment by rimrul** [comment] 2023-03-11 11:16
Duplicate of #4304

**Closed by rimrul** 2023-03-11 11:16 UTC
