### ISSUE TITLE
typo in installer

### ISSUE THREAD

**Issue by FredMaranhao** [git-for-windows/git#2727] opened 2020-07-01 22:30 UTC
when I use this installer:
https://github.com/git-for-windows/git/releases/download/v2.27.0.windows.1/Git-2.27.0-64-bit.exe

the installation was ok, but in the screen 'choose the default behavior of git pull', I find the following text:

'only ever fast-forard'

I imagine that the correct is:

'only ever fast-forward'

 - [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

###. Setup

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Microsoft Windows [versão 10.0.18363.657]

**Comment by rimrul** [comment] 2020-07-02 06:15
Duplicate of #2652 and a bunch of others. Fixed in git-for-windows/build-extra#291

**Closed** 2020-07-02 06:15 UTC
