### ISSUE TITLE
git-bash: redirection to file "rewrites" or rather expand the file name if file.exe available

### ISSUE THREAD

**Issue by sebres** [git-for-windows/git#2267] opened 2019-07-19 13:19 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

<details><summary>Setup</summary>

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8

$ sh --version
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt
Editor Option: Nano
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The same behavior (resp. issue is originated there) observed in Travis CI, that using git bash as default shell.
</details>

#### Details

 - Which terminal/shell are you running Git from?

The issue affects git bash.

 - What commands did you run to trigger this issue?
```bash
cd /tmp
# copy some executable and test it work:
cp $COMSPEC test.exe
./test.exe /? | grep 'CMD '
# execute echo and redirect to file test:
echo 'test' > test
# see how executable test.exe has been ruined:
cat ./test.exe
```
results in:
```
$ cp $COMSPEC test.exe
$ ./test.exe /? | grep 'CMD '
CMD [/A | /U] [/Q] [/D] [/E:ON | /E:OFF] [/F:ON | /F:OFF] [/V:ON | /V:OFF]
$ echo 'test' > test
$ cat ./test.exe
test
```
 - What did you expect to occur after running these commands?

After `echo 'test' > test` I expect to see a file `test` with content `test`, as well as file `test.exe` untouched.

 - What actually happened instead?

The command redirects the output to `test.exe` instead of `test`.

#### Remarks

The issue is originated in Travis CI, where `make` uses git bash as default shell and build process have made (previously created) executable broken in this way.

The same is tested with msys2/mingw64 shells - the test above as well as the same makefile (using that) work fine.

**Comment by dscho** [comment] 2019-07-22 10:51
That is indeed a curious bug. The best place to report it would be https://github.com/msys2/MSYS2-packages/issues, I think.

**Comment by sebres** [comment] 2019-07-22 10:54
> The best place to report it would be msys2/MSYS2-packages/issues, I think.

Why so? Bash in msys2 is not affected, only git bash does it...

**Comment by dscho** [comment] 2019-07-23 11:59
> > The best place to report it would be msys2/MSYS2-packages/issues, I think.
> 
> Why so? Bash in msys2 is not affected, only git bash does it...

Oh wow, I missed that in the original report...

And yes, I can confirm that this happens even with Git v2.22.0's Bash.

Since you have the setup already: what happens if you copy `msys-2.0.dll` from a working setup to a non-working one, or vice versa? And what about `bash.exe`?

**Comment by sebres** [comment] 2019-07-23 12:51
Oops, I take it back... 
I tried it in on my msys from mingw64, which seems to be older (or it is not cygwin based) as current msys2 from git.

Here as diff:
```diff
-#mingw64:
+#git bash:
$ bash --version
-GNU bash, version 3.1.17(1)-release (i686-pc-msys)
+GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)

$ cygpath --version
-sh: cygpath: command not found
+cygpath (cygwin) 3.0.7
```
So trying to obtain current binaries of msys2 to check that...

**Comment by sebres** [comment] 2019-07-23 13:05
OK, you are right - tested with current msys2 - same here as in git bash.
Will open an issue there.
Thx.

**Comment by dscho** [comment] 2019-10-13 23:52
> Will open an issue there.

Closing it here.

**Closed by dscho** 2019-10-13 23:52 UTC
Labels: bug, msys2
