### ISSUE TITLE
Missing GIT LFS Documentation

### ISSUE THREAD

**Issue by jasonnicholson** [git-for-windows/git#4327] opened 2023-03-07 01:46 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.2604]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash
CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git lfs --help
```
 - What did you expect to occur after running these commands?

I expected an HTML page to open up related to git lfs.

 - What actually happened instead?
I received the following error:

`fatal: 'C:/Program Files/Git/mingw64/share/doc/git-doc/git-lfs.html': documentation file not found.`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

repository not needed

The git-lfs documentation is included with git lfs.
https://github.com/git-lfs/git-lfs/releases/download/v3.3.0/git-lfs-windows-amd64-v3.3.0.zip
![image](https://user-images.githubusercontent.com/1058191/223296767-2810aa70-e750-4a3a-ab43-956751060b40.png)

**Comment by dscho** [comment] 2023-03-07 07:13
Wow, you're right. In all the years that Git for Windows ships with Git LFS, you're the first one to point that out.

To fix that, I suggest to 
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd mingw-w64-git-lfs`,
3. edit `PKGBUILD` to extend [the `package` function](https://github.com/git-for-windows/build-extra/blob/a5129d3495731b44f8c3023efbbadcd327586fd3/mingw-w64-git-lfs/PKGBUILD#L46-L51)
4. build a new package via `sdk build` and test by `pacman -U <just-built-package>` and then `git lfs --help`
5. If necessary, make a duplicate of `git-lfs.1.html` that misses the `.1` infix
6. commit, push and open a PR?

**Comment by rimrul** [comment] 2023-03-07 07:48
> 5. If necessary, make a duplicate of `git-lfs.1.html` that misses the `.1` infix

From a quick look it doesn't seem like `git-lfs --help` or any other dashed invocation tries to open these files, so we probably don't need a copy with the `.1` something like this should do the job:

```bash
for f in $srcdir/$folder/man/html/git-lfs*.1.html; do
    install -m755 $f $pkgdir/$MINGW_PREFIX/share/doc/git-core/${${f##*/}%.1.html}.html
done
```

**Comment by rimrul** [comment] 2023-03-08 13:25
> I'm slightly concerned that there are links _between_ those pages

From what I've seen there currently aren't any, but we probably shouldn't rely on that staying that way.

**Comment by dscho** [comment] 2023-03-24 14:10
@jasonnicholson how about [giving it a try](https://github.com/git-for-windows/git/issues/4327#issuecomment-1457668782)?

**Comment by jasonnicholson** [comment] 2023-03-25 00:47
Sure.  I will give it a try.

**Comment by jasonnicholson** [comment] 2023-03-27 01:04
I getting lost here. I looked at the PKGBUILD file. How do I debug the PKGBUILD file?

I tried @rimrul's code. However, it produces an error, "bad substitution" as shown below.

```
$ sdk build
==>  MINGW_ARCH: mingw64
  -> Building mingw64...
==> Making package: mingw-w64-git-lfs 3.3.0-1 (Sun Mar 26 19:59:23 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found git-lfs-windows-amd64-v3.3.0.zip
  -> Found v3.3.0.zip
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting git-lfs-windows-amd64-v3.3.0.zip with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting package()...
/usr/src/build-extra/mingw-w64-git-lfs/PKGBUILD: line 52: $pkgdir/$MINGW_PREFIX/share/doc/git-core/${${f##*/}%.1.html}.html: bad substitution
```

I tried to hack something together but it didn't work. I get an error as shown below. 

```bash
package() {
  install -d -m755 $pkgdir/$MINGW_PREFIX/bin
  install -m755 $srcdir/$folder/git-lfs$exesuffix.exe $pkgdir/$MINGW_PREFIX/bin/git-lfs.exe
  install -d -m755 $pkgdir/$MINGW_PREFIX/share/doc/git-lfs
  install -m755 $srcdir/$folder/README.md $pkgdir/$MINGW_PREFIX/share/doc/git-lfs/README.md
  for f in $srcdir/$folder/man/html/git-lfs*.1.html; do
    ff=${f##*/}
    install -m755 $f $pkgdir/$MINGW_PREFIX/share/doc/git-core/${ff%.1.html}.html
  done
}
```


```
$ sdk build
==>  MINGW_ARCH: mingw64
  -> Building mingw64...
==> Making package: mingw-w64-git-lfs 3.3.0-1 (Sun Mar 26 20:02:21 2023)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found git-lfs-windows-amd64-v3.3.0.zip
  -> Found v3.3.0.zip
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting git-lfs-windows-amd64-v3.3.0.zip with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting package()...
install: cannot create regular file '/usr/src/build-extra/mingw-w64-git-lfs/pkg/mingw-w64-x86_64-git-lfs//mingw64/share/doc/git-core/git-lfs-checkout.html': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
```

**Comment by dscho** [comment] 2023-03-27 06:16
@jasonnicholson could you commit what you have, push it, and open a draft PR? That will make it easier to see what needs to be changed.

**Comment by jasonnicholson** [comment] 2023-03-27 15:48
I will commit my changes when I get home this evening.

**Closed** 2023-03-29 11:17 UTC
Labels: sdk-packages, Potential Project, Help Wanted
