### ISSUE TITLE
git checkout hangs when its current working directory has no files in the target branch of the checkout command

### ISSUE THREAD

**Issue by wilbaker** [git-for-windows/git#1064] opened 2017-02-15 16:50 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.11.1.windows.1
built from commit: 1c1842bcba45569a84112ec64f72b08eb2d57c68
sizeof-long: 4
machine: x86_64

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10, 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

C:\Repos\gvfsGitTest\Scripts>type "C:\Program Files\Git\etc\install-options.txt"
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```

C:\Repos>git clone https://github.com/git-for-windows/git
C:\Repos>cd git\xdiff
C:\Repos\git\xdiff>del *
C:\Repos\git\xdiff\*, Are you sure (Y/N)? Y

[NOTE: xdiff is a folder with no subfolders inside of it, only files]

C:\Repos\git\xdiff>git checkout -b b1
C:\Repos\git\xdiff>git commit -a -m "del"
C:\Repos\git\xdiff>git checkout master
C:\Repos\git\xdiff>git checkout b1

```
 - What did you expect to occur after running these commands?

The final "git checkout b1" command (see above) would complete

 - What actually happened instead?

The "git checkout b1" command hung

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not repo specific

**Comment by dscho** [comment] 2017-02-15 17:20
@wilbaker thank you for your report!

Funnily enough, this is a duplicate of https://github.com/git-for-windows/git/issues/1062, even if it does not look like it at all.

The reason why it hangs is that it actually failed to delete the directory `xdiff`. Which makes sense because this is the current directory, so it cannot be deleted. What Git did was to print an error message

```
Deletion of directory 'xdiff' failed. Should I try again? (y/n)
```

and now waits for your input.

Except for one little detail... There is a bug in v2.11.1 where the error output is *buffered*, i.e. it is not printed immediately but the C runtime waits for "enough" characters to be printed before actually printing anything. This is wrong, of course, as the error output should *always* be *immediate*, i.e. unbuffered.

This has been fixed in `master`: 87ad093

I plan to provide at least a prerelease by the end of the week, or even a v2.11.1(2).

**Closed** 2017-02-26 08:55 UTC
