### ISSUE TITLE
git-2.18.0 win7 and win10  bug

### ISSUE THREAD

**Issue by EricBatty** [git-for-windows/git#1773] opened 2018-07-30 10:05 UTC
hello,
I found a memory leak bug in git-2.18.0 under windows7 and windows10.
When I downloaded and installed git and started it, my memory would fill up instantly, causing my computer to crash.
I hope the author can see the problem and respond to it.
please!

**Comment by dscho** [comment] 2018-07-30 15:52
> I hope the author can see the problem and respond to it.

You are so cute! The code base of Git is not exactly small, and Git for Windows relies on ~120 more, separate software components to do its job.

And instead of filling out the issue reporting template that was designed to help you provide at least a little bit of the information that could have helped navigate that rather large haystack, you simply deleted it. That is not only unfortunate, but it also makes it virtually impossible to help.

**Comment by dscho** [comment] 2018-07-30 15:53
I marked this bug report as invalid because of the lack of information, and will close it. I do promise, though, that I (or somebody else) will open it again as soon as there is at least some information that can allow somebody to wager a guess where things go wrong.

**Closed by dscho** 2018-07-30 15:53 UTC
Labels: invalid

**Comment by EricBatty** [comment] 2018-07-31 08:04
I'm sorry I didn't describe it clearly, I gave him up。Although it works very well.I'm using it in the next release.The buggy environment is in git-2.18.0 version 64 bit win7 and win10 systems.After installation, run it by right-clicking on git bash, and memory grows like crazy.

**Comment by EricBatty** [comment] 2018-07-31 08:06
Do you know where git's log files are?Maybe I can view the log file and send it out

**Comment by EricBatty** [comment] 2018-07-31 08:07
@dscho

**Comment by dscho** [comment] 2018-08-01 21:37
It is still not terribly clear. So if you open `Git Bash` from the Start Menu and let it sit, it wants to have more memory all the time?
