### ISSUE TITLE
Get VisualStudioCode to work as default editor

### ISSUE THREAD

**Issue by igorlino** [git-for-windows/git#1386] opened 2017-11-30 11:10 UTC
I have now installed the latest version of Git for windows and the default editor options where shown(nano, vim, notepad++). 

This got me thinking as I recently got a strong positive recommendation for VisualStudioCode, which I can nowadays confirm,  it is the fastest free open source editor that happens to have very good support for web.   

Its rated as #1 in quite a lot of places. (i.e.  https://ourcodeworld.com/articles/read/200/top-7-best-free-web-development-ide-for-javascript-html-and-css)

So I though maybe its something that could be included in git for windows as well. As GitHub has a majority of web-related projects, i think it makes sense.

Thanks

**Comment by PhilipOakley** [comment] 2017-11-30 11:26
Hi Igor, 

Sounds interesting - pull requests welcome... the https://git-for-windows.github.io/#contribute button is a good starting point. Browse a few of the now closed issues / PRs to see how the Notepad++ etc. was relatively easily integrated to get a flavour of where to start.

Philip

PS it does usually take a few rounds to make sure the PR is fully self explanatory and 'maintainable' (i.e. should not need any, but when it does folk can easily read the background info ;-)

**Comment by igorlino** [comment] 2017-11-30 12:00
Sure. I hope I get enough time. I maintain quite a lot of other open source projects, which also need love. 

For starters I found:
https://github.com/git-for-windows/build-extra/commit/339757bdaf2a2e964a3e795af83fb6486e4d16dd

**Comment by dscho** [comment] 2017-11-30 12:22
This is a duplicate of: https://github.com/git-for-windows/git/issues/1356

I put a ton of information there...

**Closed by dscho** 2017-11-30 12:22 UTC
