### ISSUE TITLE
after upgrading to git 2.7.2, windows 8 64bit, git svn fetch does not work

### ISSUE THREAD

**Issue by oertl** [git-for-windows/git#668] opened 2016-02-24 10:15 UTC
git version 2.7.2.windows.1
windows 8, 64bit

I got following errors when running git svn fetch:

git svn fetch
      2 [main] perl 41956 child_info_fork::abort: unable to map C:\Program Files\Git\usr\bin\msys-svn_subr-1-0.dll, Win32 error 1114
      3 [main] perl 35352 child_info_fork::abort: unable to map C:\Program Files\Git\usr\bin\msys-svn_subr-1-0.dll, Win32 error 1114
      2 [main] perl 25840 child_info_fork::abort: unable to map C:\Program Files\Git\usr\bin\msys-svn_subr-1-0.dll, Win32 error 1114

**Comment by dscho** [comment] 2016-02-24 10:34
Duplicate of https://github.com/git-for-windows/git/issues/650. Please search the existing tickets before opening new tickets.

**Closed by dscho** 2016-02-24 10:34 UTC
