### ISSUE TITLE
Conflict between Windows 1803 OpenSSH tooling and tooling bundled with Git for Windows.

### ISSUE THREAD

**Issue by pingzing** [git-for-windows/git#1683] opened 2018-05-17 10:29 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.17.0.windows.1
cpu: x86_64
built from commit: e7621d891d081acff6acd1f0ba6ae0adce06dd09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17134.48]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I recently updated to the 1803 Spring Creator's update (version 10.0.17134) version of Windows, which now ships [native versions of the OpenSSH tools](https://blogs.msdn.microsoft.com/commandline/2018/03/07/windows10v1803/) (see OpenSSH-based client and server near the bottom).

Those automatically placed themselves in my $PATH, and I decided to start using them, instead of those bundled with Git for Windows.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull
```

...for example, would request my ssh credentials even though the new native ssh-agent was running, and I had added my key to it.

 - What did you expect to occur after running these commands?

Git for Windows would use the new, native `ssh.exe` on my $PATH, as well as the running `ssh-agent.exe`, and do things.

 - What actually happened instead?

I was prompted for my key credentials.

I was able to work around this by taking advantage of the `GIT_SSH` environment variable, which I pointed to the new OpenSSH tooling at `C:\Windows\System32\OpenSSH\ssh.exe`.

I might suggest that for future releases, the installer could test for the native versions of the tools, and if those exist, not install Git for Windows versions of them.

**Comment by dscho** [comment] 2018-05-17 11:13
> I recently updated to the 1803 Spring Creator's update (version 10.0.17134) version of Windows, which now ships native versions of the OpenSSH tools (see OpenSSH-based client and server near the bottom).
> 
> Those automatically placed themselves in my $PATH, and I decided to start using them, instead of those bundled with Git for Windows.

I do have `C:\Windows\System32\OpenSSH\ssh.exe` but it is not in the `PATH` by default. Which makes me think that the best way forward would be to add an option to the installer. That option could default to true e.g. if ssh-agent.exe from that system directory exists and is running. The option should be disabled if that ssh.exe does not even exist.

Now for the fun part: this would make for an excellent first contribution! How, you ask? I am glad you asked, here is what I would suggest:

# Install Git for Windows' SDK

The easiest way is to download and run the installer from https://gitforwindows.org/#download-sdk.

Alternatively, you could clone it yourself with your current Git for Windows:

```cmd
git clone --depth 1 https://github.com/git-for-windows/git-sdk-64 C:\git-sdk-64
C:\git-sdk-64\git-bash.exe
```

# Build your first installer

Just to make sure that everything works as expected, call

```cd
sdk build installer
```

# Add the option

The options are defined in the [`installer/install.iss`](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss) of the `build-extra` project. Edit it via

```sh
sdk cd build-extra
git config -e -f installer/install.iss
```

(this "abuses" `git config` to run Git's default editor).

## Where?

Look for `ExtraOptions`, there may still be space. To test this, use a special mode of the script that normally bundles the installer, a mode designed to debug specific installer "wizard pages":

```sh
./installer/release.sh -d ExtraOptions
```

This *looks* like it runs the installer, but it really only shows one page. If you hit the <kbd>Next</kbd> button, it simply quits. This is great for debugging ;-)

## How?

The new option could be modeled after the one enabling symbolic links: https://github.com/git-for-windows/build-extra/blob/cc9e7490b13f51a3491f6744b1c42b90b20e11f0/installer/install.iss#L1370-L1381

You probably need to use the `FileExists()` function with the [`{sys}` constant](http://www.innosetup.com/ishelp/topic_consts.htm) (see [this example](https://github.com/git-for-windows/build-extra/blob/cc9e7490b13f51a3491f6744b1c42b90b20e11f0/installer/install.iss#L1457) how to call `FileExists()` in that way) to determine whether the option should be disabled.

Just like `EnableSymlinksByDefault()`, it could call a new function, say, `UseSystemSSHByDefault()` if the option is enabled, to determine whether it should be opt-in or opt-out. There are no good ways in InnoSetup's scripting language to test for a running process, but you could use the fact that we have a few MSYS2 utilities at our disposal. You could use [the same trick as we do for the `post-install.bat` script](https://github.com/git-for-windows/build-extra/blob/cc9e7490b13f51a3491f6744b1c42b90b20e11f0/installer/install.iss#L2154) to capture the output by redirecting to a temporary file and reading it into a string variable. The command to run would probably be `{app}\usr\bin\ps.exe` and it would need to be called with the argument `-W` to include non-MSYS2 processes.

Finally, just like with [the symbolic link option](https://github.com/git-for-windows/build-extra/blob/cc9e7490b13f51a3491f6744b1c42b90b20e11f0/installer/install.iss#L1966-L1972), you would configure `core.sshCommand` (or force-unset it) depending on the user's choice.

**Comment by cleidigh** [comment] 2018-05-18 03:29
@dscho 

I came across this while attempting to work on the SSH_ASKPASS for
Visual Studio code (where I'm a collaborator)

It is related enough I thought I could also work on this as a learning process.
I successfully installed the SDK per your comments in my other post.
The installation appears to be okay but, while I followed your detailed step-by-step 
instructions to the letter above, I get package manager lock errors
on a fresh install.  

While also attempting to compile the openSSH package I get errors also.
These may not be related but I capture both errors in case they are.
I did search for related issues without finding anything.

I'm hoping to contribute on this and get my integration with VS Code
working also.

Platform is Windows 7 professional.

Installer build errors:

![image](https://user-images.githubusercontent.com/25272315/40214566-81deb5fe-5a29-11e8-906f-1b4581cc80ff.png)

openSSH package errors:

![image](https://user-images.githubusercontent.com/25272315/40214621-c40da480-5a29-11e8-88fd-44a7b60d62c4.png)

![image](https://user-images.githubusercontent.com/25272315/40214641-dfd28604-5a29-11e8-8c8e-c57a431e33d0.png)


Thanks in advance

**Comment by Stanzilla** [comment] 2018-05-18 14:54
There was a recent Twitter discussion about this (https://twitter.com/nocentino/status/996895686166794240) and it seems like it should be on path by default but there are bugs preventing that for some users.

**Comment by dscho** [comment] 2018-05-21 13:34
> I get package manager lock errors on a fresh install.
>
> [... please paste plain text as text, not as an image...]
> ```
> error: could not lock database: File exists
>   if you're sure a package manager is not already
>   running, you can remove /var/lib/pacman/db.lck
> ```

@cleidigh that's strange.

Hmm. I also have an untracked `var/lib/pacman/db.lck` lying around, that's only two days old. Not sure where it came from...

Can you simply delete that file (after verifying that you have no other Git SDK Bash windows open) and re-run?

> ```
> $ makepkg -s
> /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: Not a directory
> [...]
> ```

OpenSSH is maintained as an *MSYS2* package. These have to be built in a special Bash that you start via

```sh
c:\git-sdk-64\msys2_shell.cmd -msys
```

For details why this is needed, please see https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages (I know, it is hard to miss, but there are [crucial differences between MSYS2 and MINGW](https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2)).

@cleidigh I must ask, though, why you want to rebuild OpenSSH? Don't you rather want to work on the installer side, which is what this here ticket is all about?

Not that I think @pingzing should be proud of herself to sit by idly on the sidelines...

> There was a recent Twitter discussion about this (https://twitter.com/nocentino/status/996895686166794240) and it seems like it should be on path by default but there are bugs preventing that for some users.

@Stanzilla for the record: I have a client version, and it is not installed by default. Maybe I have some company-wide settings preventing it? No idea. In any case, the reality is that we cannot rely on it to be installed by default, and that's that.

**Comment by cleidigh** [comment] 2018-05-23 02:48
@dscho 
Concerning general build issues (installer included):

After a series of install/build rounds, I think I have the main built environment working.  On my main machine I'm completely running out of disk space and ended up with build errors because of not enough room.  I installed on a different drive not realizing it was an HGFS partition. I have many inadvertently read on the MSYS requirement for NTFS.  I believe this was the cause for some of the errors.  Multiple installs perhaps caused the lock issues, that's less clear.  Deleting the lock file did nothing.

A fresh install on an older system that had no git Bash or SDK installs now builds GIT and the installer.
This should give me the opportunity to work on this issue.  My other issue still eludes me and I included the errors above because I thought they were related, sorry if this confused things.

If I start the MSYS shell I still have issues building openssh.  I could not get it to build as it always
complains about not finding Zlib despite it being there.  I will track this in my original issue
trying to get GIT_ASKPASS to work for Visual Studio code.

Just an FYI, I have to do all computer work and programming with voice as I am disabled so my output
is on the slow side just so you know, and I will typically have some fun Dragon dictation auto corrects ;-)

**Comment by dscho** [comment] 2018-05-24 13:12
> Just an FYI, I have to do all computer work and programming with voice as I am disabled so my output
> is on the slow side just so you know, and I will typically have some fun Dragon dictation auto corrects ;-)

Wow. I am impressed!

I am currently busy with day-job stuff, so I probably won't have time this week to look and see whether I can help with the other ticket. Hopefully somebody else is able to help, so that you do not have to wait for such a long time...

**Comment by cleidigh** [comment] 2018-05-26 17:36
@dscho 
I don't know about impressive, but I'm fortunate despite having ALS and a vent, I can talk which is most unusual.  Continuing to work on projects like Visual Studio code and GIT keep me sane and mostly out of trouble ;-)

Hopefully I can finally get open SS each to compile, I think that's the only way to understand why
GIT_ASKPASS is not working.

**Comment by cleidigh** [comment] 2018-05-30 20:03
@dscho 
After familiarizing myself with the inno installer, I see there is already  an SSH page that is presented if putty is found.  I assume it makes the most sense to modify this page to be presented if either putty OR openSSH is found.  Then use radio buttons to select between the three options, first being GIT SSH.

I'm not sure it makes sense to detect and or start any agents, do you agree?

**Comment by dscho** [comment] 2018-08-15 10:54
> I see there is already an SSH page that is presented if putty is found. I assume it makes the most sense to modify this page to be presented if either putty OR openSSH is found. Then use radio buttons to select between the three options, first being GIT SSH.

That's a good idea!

**Comment by dscho** [comment] 2020-01-01 20:33
I am not sure how to progress from here. After all, there have been worrisome reports about the native OpenSSH not working as intended. Maybe we should just leave this ticket alone, or even close it, for the time being?

**Comment by dscho** [comment] 2020-01-02 18:29
> After all, there have been worrisome reports about the native OpenSSH not working as intended.

To be precise, I mean this report: https://github.com/PowerShell/Win32-OpenSSH/issues/1322

**Comment by glen-84** [comment] 2020-03-29 18:12
@dscho,

What is the best way to deal with issues like [this](https://github.com/microsoft/terminal/issues/5166)?

1. Wait for GFW to upgrade Cygwin. _OR_
2. Somehow force the Windows SSH to be used ahead of the GFW SSH?
   * I'm not sure what controls the PATH order, how to change it, and whether or not that could affect Git in a negative way.

Thanks.

**Comment by dscho** [comment] 2020-03-29 19:17
> * Wait for GFW to upgrade Cygwin. _OR_

Git for Windows does not use Cygwin. We use MSYS2, _and_ we build our own version of the OpenSSH package.

If you are thinking about the MSYS2 runtime, which is based on the Cygwin runtime, then I fear you'll just have to wait it out. The MSYS2 and Git for Windows projects are waiting for the v3.1.x series of the Cygwin runtime to stabilize before porting the MSYS2 runtime on top of it.

> * Somehow force the Windows SSH to be used ahead of the GFW SSH?

You can easily do that.

>   * I'm not sure what controls the PATH order, how to change it, and whether or not that could affect Git in a negative way.

The easiest would be to avoid meddling with `PATH` and instead set [`core.sshCommand`](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresshCommand) in your user-wide config.

**Comment by glen-84** [comment] 2020-03-29 19:42
> The easiest would be to avoid meddling with PATH and instead set core.sshCommand in your user-wide config.

That would only affect Git though? Using the GFW SSH binary is causing issues with tools like fzf once connected via SSH, so I think that I need to adjust the PATH to put Windows SSH first – how do I do that?

**Comment by dscho** [comment] 2020-03-30 06:20
I have no idea what `fsf` is, nor do I have the bandwidth to support that tool.

**Comment by glen-84** [comment] 2020-04-03 14:18
> I have no idea what fsf is, nor do I have the bandwidth to support that tool.

I wasn't asking for support for a specific tool. Other tools are [affected as well](https://github.com/microsoft/terminal/issues/5167#issuecomment-608250964).

For now I've just added this alias to my `.bashrc` file:

```sh
alias ssh='winpty "C:\Windows\System32\OpenSSH\ssh.exe"'
```

**Comment by Okeanos** [comment] 2021-05-15 10:06
> > After all, there have been worrisome reports about the native OpenSSH not working as intended.
> 
> To be precise, I mean this report: [PowerShell/Win32-OpenSSH#1322](https://github.com/PowerShell/Win32-OpenSSH/issues/1322)

I am wondering, now that Windows ships with a newer version (`OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2` as per [Win32-OpenSSH#1693](https://github.com/PowerShell/Win32-OpenSSH/issues/1693)), whether this issue could be reexamined? Even newer 8.x versions are already being tracked in that repository [as well](https://github.com/PowerShell/Win32-OpenSSH/issues/1750).

Personally, I am looking at two-ish different aspects of this:
- allow (selectively) skipping parts of the bundled `ssh-*` executables during installation and subsequent updates; in particular the git bundled `ssh-copy-id` has no Windows native equivalent
- interoperability between the bundled `ssh-*` executables and the Windows OpenSSH (Agent) service(s), in particular Git for Windows being able to read from/write to the native `ssh-agent` service

My reasoning for the former is that this would prevent `$PATH`ing issues where the `ssh-*` binaries are picked arbitrarily between different environments (git-bash, IDEs, other Shells, …) causing communication issues with e.g. any configured `ssh-agent` process. There'd simply be only a single set of these binaries available. Users would have to manually intervene if they wanted something else but it'd be their choice.

The latter should be more obvious – it should enable support for more tools to take advantage of ssh key management and allow for easier (more diverse) key management solution. For instance the KeePassXC OpenSSH implementation can already talk to the Windows agent service and be used for key management. No need to fiddle with the `SSH_AUTH_SOCK` or registering `ssh-agent` start up scripts in the `.bashrc`.

Does the following suggestion still apply?

> > I see there is already an SSH page that is presented if putty is found. I assume it makes the most sense to modify this page to be presented if either putty OR openSSH is found. Then use radio buttons to select between the three options, first being GIT SSH.
> That's a good idea!

**Comment by Okeanos** [comment] 2021-07-20 19:39
@dscho based on this issue (and my comment above) as well as #2944 I was poking around the `build-extra/installer/install.iss`file and checking whether I could add an option to the OpenSSH vs. Putty page that would force the installer to skip installing the binaries [already supplied by Windows](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_overview), i.e. everything _except_ `ssh-copy-id`.

Now integrating the option on the page and maybe even detecting whether `%System%\OpenSSH\ssh.exe` exists (`%System%` [apparently](https://docs.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables) also links to `%System32%` which should cover 64Bit and 32Bit I think?) looks fairly straightforward (🤞), however, I have trouble locating at what point these Git bundled binaries are copied around, i.e. where I'd have to put a guard. Any pointers?

**Comment by dscho** [comment] 2021-07-22 11:47
> I have trouble locating at what point these Git bundled binaries are copied around, i.e. where I'd have to put a guard.

They are copied as part of the installation, via the `[Files]` section (which is populated by converting the output of `make-file-list.sh` into the `file-list.iss` file).

If you want to delete stuff in the `ssPostInstall` phase contingent on a user-specified option, just imitate [what we do with Git LFS](https://github.com/git-for-windows/build-extra/blob/317b1819ecb1d09916d758335ce7513b904f73e8/installer/install.iss#L3296-L3304).

**Comment by dscho** [comment] 2021-08-04 13:46
Addressed via https://github.com/git-for-windows/build-extra/pull/367

**Closed by dscho** 2021-08-04 13:46 UTC
Labels: enhancement, up for grabs

**Comment by TheBigBear** [comment] 2025-02-11 20:08
What helped me the most debugging this was to enable git tracing

in cmd line set GIT_TRACE=1

in powershell or pwsh $env:GIT-TRACE=1
