### ISSUE TITLE
Issues with passing arguments with spaces when running applications from Bash

### ISSUE THREAD

**Issue by fonic** [git-for-windows/git#2526] opened 2020-02-24 19:33 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.25.1.windows.1
cpu: x86_64
built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.3.9600]
Windows 8.1 Pro x64
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: BashOnly
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not running Git, running other applications from within Git Bash.

 - What commands did you run to trigger this issue?

I tried to call `msiexec` to perform an unattended installation of LibreOffice:
```
msiexec.exe //passive //i LibreOffice_6.4.0_Win_x64.msi INSTALLLOCATION="C:\Program Files\LibreOffice"
```
 - What did you expect to occur after running these commands?

I expected the installation to start/be performed. Or, in other words, I expected the command to do the same as this command run from within the Windows command prompt:
```
msiexec.exe /passive /i LibreOffice_6.4.0_Win_x64.msi INSTALLLOCATION="C:\Program Files\LibreOffice"
```

 - What actually happened instead?

A window describing `msiexec`'s usage instructions appeared. I tracked the problem down to `INSTALLLOCATION="C:\Program Files\LibreOffice"`. Without spaces, the command executes as expected.

This issue is not only related specifically to `msiexec`. For example, there seems to be no way to correctly run the following command from within Bash:
```
cmd.exe /c for %I in ("C:\Program Files") do echo %~sI
```
Expected output:
```
C:\PROGRA~1
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No.

**Comment by dscho** [comment] 2020-02-25 09:06
Since neither `msiexec.exe` nor `cmd.exe` are MSYS programs, they have their own (de-)quoting rules. Maybe it works if you surround the double-quoted argument with single quotes.

**Comment by dscho** [comment] 2020-02-25 09:20
> there seems to be no way to correctly run the following command from within Bash:
> 
> ```
> cmd.exe /c for %I in ("C:\Program Files") do echo %~sI
> ```

I fear you're right. I tried this (which should have worked), but it prepended extra backslashes to the double-quotes:

```sh
MSYS_NO_PATHCONV=1 cmd.exe /c 'for %I in ("C:\Program Files") do @echo %~sI'
```

Maybe there are other tricks that make this work, but I did not find any. The safest way would be to turn the statements into a `.bat` script, I would think, and then call that.

**Comment by fonic** [comment] 2020-02-25 09:46
> Since neither `msiexec.exe` nor `cmd.exe` are MSYS programs, they have their own (de-)quoting rules. Maybe it works if you surround the double-quoted argument with single quotes.

No, I tried every possible quoting combination I could think of, nothing works. But both commands work from within the Windows command prompt. Hence the bug, it seems Bash does not pass the arguments in a way Windows applications expect them to be passed.

**Comment by drizzd** [comment] 2020-03-08 06:39
Works for me. Am I seeing different behavior from yours? The backslashes are inserted for me only if I use the double slash.

```
$ pacman -Q msys2-runtime
msys2-runtime 3.0.7-3
$ cmd.exe /c 'for %I in ("C:\Program Files") do @echo %I'
"C:\Program Files"
$ cmd.exe //c 'for %I in ("C:\Program Files") do @echo %I'
\"C:\Program Files\"
$ MSYS_NO_PATHCONV=1 cmd.exe /c 'for %I in ("C:\Program Files") do @echo %I'
"C:\Program Files"
```

**Comment by fonic** [comment] 2020-03-08 09:26
@drizzd: what kind of environment did you run those commands in? This issue refers to Git for Windows.

Also, the command you are using will not demonstrate the problem. Try running this command:
```
$ cmd.exe /c for %I in ("C:\Program Files") do echo %~sI
```
which should output:
```
C:\PROGRA~1
```

**Comment by fonic** [comment] 2020-03-08 09:51
@drizzd was using MSYS2 - and indeed, MSYS2 is capable of running the command as expected. Maybe this helps developers for Git for Windows to fix this.

**Comment by dscho** [comment] 2020-03-08 10:12
That's good to know, but for the moment I am out of cycles to work on this.

Maybe you want to, @fonic? It is relatively easy to get started with it:
1. install [Git for Windows' SDK](https://gitforwindows.org/#download-sdk),
2. `sdk cd msys2-runtime`,
3. Perform an initial build via `sdk build`,
4. Now inspect the patches Git for Windows has on top of MSYS2. The easiest way should be to `cd src/msys2-runtime` and then look at `git log --graph --oneline HEAD^{/^"environ.cc: New facility/environment variable MSYS2_ENV_CONV_EXCL"}..`
5. The culprit is most likely to be found in [`winsup/cygwin/spawn.cc`](https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/spawn.cc) or in [`msys2_path_conv.cc`](https://github.com/git-for-windows/msys2-runtime/blob/master/winsup/cygwin/msys2_path_conv.cc).
6. If you find any candidate, try to modify the respective code and rebuild with `sdk build msys2-runtime` (the result will be in `/usr/src/MSYS2-packages/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin/msys0.dll`, and it will need to be copied over the `/usr/bin/msys-2.0.dll` of a recent portable Git; you will have to quit any Git Bash from that portable Git when you want to copy that file).
7. In my tests, I find that it makes most sense to put the commands into a `.sh` file, then call it via `<portable-Git>/git-cmd.exe --command=usr\\bin\\bash.exe -l <script>` (or use `... -lc "<commands>"`). I typically put this into an `&&` chain where I build the MSYS2 runtime, copy it, and then run the test, in one window, and edit the source code in another window (so that I can quickly test my code changes by <kbd>Cursor Up</kbd><kbd>Enter</kbd> in the first window). That usually results in a slightly unwieldy one-liner:
```sh
(cd /usr/src/MSYS2-packages/msys2-runtime/src/build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin/ &&
 make msys0.dll &&
 cp msys0.dll ~/Desktop/portable/usr/bin/msys-2.0.dll &&
 ~/Desktop/portable/git-cmd.exe --command=usr\\bin\\bash.exe -lc "echo hello")
```
7. To get more clarity, you can insert debug print statements. Due to implementation details, you _cannot_ use `fprintf(stderr, ...)` but you have to use the Cygwin-specific `small_printf()` instead (more information [here](https://github.com/git-for-windows/msys2-runtime/commit/7cddf264c9658af8c2d0f4513e7e6a1b3def28f3).
8. Once you figure it out, open a PR? Or alternatively share your findings here?

**Comment by drizzd** [comment] 2020-03-08 10:40
I was running `C:\git-sdk-64\git-bash.exe` from the Git-for-Windows. I did not expect that this was different from running `C:\Program Files\Git\git-bash.exe`. But I confirm that it _is_ different in this respect. I can reproduce the issue with `C:\Program Files\Git\git-bash.exe`.

**Comment by fonic** [comment] 2020-03-08 11:32
@dscho: I'll look into it.

**Comment by drizzd** [comment] 2020-03-08 21:11
Git for Windows includes a patched version of MSYS2. I believe the patches from 0017 to 0054 have been added to the Git-for-Windows fork of msys2-runtime: https://github.com/git-for-windows/MSYS2-packages/tree/master/msys2-runtime.

Git for Windows also depends on MSYS2 since some programs included in Git for Windows, such as for example bash, have not been ported natively to Windows (as opposed to git.exe itself). These programs need the MSYS2 runtime to emulate Linux APIs on Windows.

Note that while Git needs MSYS2 internally to run shell scripts and such, using MinTTY and git-bash is _optional_. In fact, just to avoid issues such as this, I recommend using cmd.exe or cmd.exe like shells such as https://github.com/mridgers/clink or https://github.com/drizzd/winsh.

**Comment by dscho** [comment] 2020-03-08 21:22
> the patches from 0017 to 0054 have been added to the Git-for-Windows fork of msys2-runtime: https://github.com/git-for-windows/MSYS2-packages/tree/master/msys2-runtime.

That is correct.

For some time, I pushed for those patches to become integrated into MSYS2 in one form or another, but got frustrated by the too short and unhelpful replies I got there. Maybe it is time to try again.

The rest of what @drizzd said is also correct.

**Comment by dscho** [comment] 2020-03-08 21:26
> I confirm that it _is_ different in this respect. I can reproduce the issue with `C:\Program Files\Git\git-bash.exe`.

I see the exact same result in Git for Windows' SDK, too:

```
$ MSYS_NO_PATHCONV=1 cmd.exe /c 'for %I in ("C:\Program Files") do @echo %~sI'
C:\"C:\Program Files\"
```

**Comment by fonic** [comment] 2020-03-09 07:51
> Git for Windows includes a patched version of MSYS2. I believe the patches from 0017 to 0054 have been added to the Git-for-Windows fork of msys2-runtime: https://github.com/git-for-windows/MSYS2-packages/tree/master/msys2-runtime.

So... if it works in vanilla MSYS2 but NOT in Git for Windows and the latter applies patches 0017 to 0054 to MSYS2, I would assume one of those patches breaks something, thus I should have a look at them. Correct?

> Note that while Git needs MSYS2 internally to run shell scripts and such, using MinTTY and git-bash is _optional_. In fact, just to avoid issues such as this, I recommend using cmd.exe or cmd.exe like shells such as https://github.com/mridgers/clink or https://github.com/drizzd/winsh.

Well, for me personally, it's about running Bash scripts on Windows without a complicated setup of something like WSL. Git for Windows portable fits that role perfectly.

**Comment by dscho** [comment] 2020-03-09 09:11
> > Git for Windows includes a patched version of MSYS2. I believe the patches from 0017 to 0054 have been added to the Git-for-Windows fork of msys2-runtime: https://github.com/git-for-windows/MSYS2-packages/tree/master/msys2-runtime.
> 
> So... if it works on vanilla MSYS2 but NOT on Git for Windows and the latter applies patches 0017 to 0054 to MSYS2, I would assume one of those patches breaks something, thus I should have a look at them. Correct?

That would be my interpretation, too.

**Comment by fonic** [comment] 2020-03-09 09:24
So far, I have not been able to set up the SDK per you instructions. `sdk cd msys2-runtime` throws lots of errors, but seems to succeed on a second run. `sdk build` fails immediately.

```
User@host MSYS /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime (makepkg)
$ sdk cd msys2-runtime
...
error: refs/tags/sid-snapshot-20150101 does not point to a valid object!
error: refs/tags/sid-snapshot-20150201 does not point to a valid object!
error: refs/tags/sid-snapshot-20150301 does not point to a valid object!
error: refs/tags/w32api-1_5 does not point to a valid object!
error: refs/tags/w32api-2_2 does not point to a valid object!
error: refs/tags/winsup-2000-02-17 does not point to a valid object!
error: refs/tags/x86_64versiong3 does not point to a valid object!
 * [new tag]             snapshot-2016-07-09 -> snapshot-2016-07-09
error: object directory /usr/src/MSYS2-packages/msys2-runtime/msys2-runtime/objects does not exist; check .git/objects/info/alternates

User@host MSYS /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime (makepkg)
$ sdk cd msys2-runtime

User@host MSYS /usr/src/MSYS2-packages/msys2-runtime/src/msys2-runtime (makepkg)
$ sdk build
fatal: cannot change to 'diff-files': No such file or directory
bash: cd: ../build-x86_64-pc-msys/x86_64-pc-msys/winsup/cygwin: No such file or directory
```

What am I missing?

**Comment by dscho** [comment] 2020-03-09 09:29
Oh wow, sorry for that.

The best way out of this is, for right now, to run `sdk cd MSYS2-packages && cd msys2-runtime && MAKEFLAGS=-j$(nproc) makepkg -s --noconfirm`.

**Closed** 2022-03-17 16:59 UTC
Labels: question
