### ISSUE TITLE
Perl access violation during "git svn fetch"

### ISSUE THREAD

**Issue by drauch** [git-for-windows/git#559] opened 2015-12-05 18:38 UTC
When "git svn fetch"-ing a repository with Git 2.6.3, git svn fails at a specific commit (huge, in terms of number of files) with an access violation. Unfortunately, I don't have time to analyze it any further, however, it looks like the bug is new: running "git svn fetch" with Git 2.5.0 works perfectly (I have used Git 2.5.0 as a workaround).

Here are the contents of the perl.exe.stackdump file:

    Exception: STATUS_ACCESS_VIOLATION at rip=0048360C10C
    rax=0000000601E54328 rbx=000000005219E248 rcx=000000060003B1C0
    rdx=0000000000000000 rsi=000000000000B256 rdi=0000000000000004
    r8 =0000000000000000 r9 =0000000000000000 r10=0000000000240000
    r11=000000048D78607A r12=0000000000000003 r13=000006FFFFFA92C8
    r14=0000000601E1F8D0 r15=000006FFFFFA92E0
    rbp=00000000000592B8 rsp=000000000023B830
    program=C:\Program Files\Git\usr\bin\perl.exe, pid 14736, thread main
    cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B

I'm sorry that I do not have further details (exact number of files, repro sample, etc.). I do not have the time, still wanted to at least drop a hint that there is something amiss. Maybe some other soul searching the web for this problem finds the thread and elaborates in more detail.

Happened on a Win 8.1 64bit machine with 32 GB of RAM and Git 2.6.3 for 64bit systems installed.

**Comment by dscho** [comment] 2015-12-07 11:37
Is this not a duplicate of https://github.com/git-for-windows/git/issues/274? Hopefully any other soul searching the web for this problem finds the other ticket...

**Closed by dscho** 2015-12-07 11:37 UTC

**Comment by drauch** [comment] 2015-12-07 12:40
I've found the other issue (of course, you've pointed it out to me in https://groups.google.com/forum/#!topic/msysgit/Q0sXW8JLW7o ;-)), however, I think it might not be the same problem -> they see crashes with Git 2.5.x as well, while I am not having any problems with Git 2.5.x.

**Comment by dscho** [comment] 2015-12-07 18:51
> they see crashes with Git 2.5.x as well, while I am not having any problems with Git 2.5.x.

Unless you prove me wrong, I will assume that this is just due to pure luck, i.e. the bug just *happens* not to be triggered in your use case when using Git 2.5.0.

`git svn` issues are notoriously easy to report, and notoriously hard to debug. And the indicated time constraints pretty much doom this ticket if it actually refers to a different issue, anyway...

**Comment by drauch** [comment] 2015-12-07 19:27
You do not have to defend yourself, I know it is hard work and I know a bug request is of much more value if provided with more background information and a full repro sample. Still, it should be possible to file a bug without feeling guilty about it - at least it indicates that there is a real problem somewhere in the software. I don't expect you to fix it, I already have a workaround.

**Comment by dscho** [comment] 2015-12-07 19:35
You do not need to feel guilty. I just closed this bug as a duplicate because from where I stand, it is *most likely* a duplicate and I lack the time to verify or reject this claim.
