### ISSUE TITLE
Filename too long when cloning a repo

### ISSUE THREAD

**Issue by vitaut** [git-for-windows/git#342] opened 2015-09-01 16:32 UTC
Git gives error "Filename too long" when cloning a repo and the resulting path is longer than 260 characters. Here's an example that reproduces the error:

```
C:\1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234>git clone -c core.longPaths=true http://github.com/cppformat/cppformat
fatal: could not create work tree dir 'cppformat': Filename too long
```

Tested with git version 2.5.1.windows.1 (32-bit) on Windows 2008 R2 (64-bit).

**Comment by vitaut** [comment] 2015-09-01 16:35
Note the `core.longPaths` is set to true as described in https://github.com/git-for-windows/build-extra/blob/master/installer/ReleaseNotes.md#known-issues.

**Comment by dscho** [comment] 2015-09-02 11:55
I am still working on another ticket but I can reproduce with that nice MCVE. From a cursory look it seems `git clone` does not pick up `core.longpaths` in time to create the initial directory (and something funky is going on there because it should not convert the short relative path into an absolute, long path). Will continue later and keep you posted.

**Comment by dscho** [comment] 2015-09-04 14:48
Okay, I give up (for now). This is my current state of affairs: https://github.com/git-for-windows/git/compare/master...dscho:clone-into-long-path

Long path^Wstory short: the `core.longpaths` code intends to support when insanely long paths are *inside* of the working directory, not when the working directory's path itself is already insanely long.

I guess we will never be able to support that properly, certainly not by passing the config variable into the clone call. Just think about it. Take *any* Git command that would have to run inside that directory. Most of them will need to read the config first, right? But what if that config already has an insanely long path? Then it does not matter if it specified `core.longPaths = true` now, does it?

It *might* be possible to specify `core.longPaths = true` in your `$HOME/.gitconfig` because it is read *before* `.git/config`.

However, there is one really ugly bug somewhere there. When I have a string `"cppformat"` and I want to create a directory of that name, then the path is not *yet* too long. It should not be converted into an absolute path in such a case. I will open another ticket for that and assign it to myself.

For now, I unfortunately have to leave this bug behind and tend to tickets that probably have a higher impact: you can easily work around this issue by assigning a drive to your base directory with this insanely long path and work with an insanely short one:

```cmd
net share verylong=1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234
net use L: \\localhost\verylong
```

If you find the time to work on this issue, feel free to pick up my branch and work from there.

**Closed by dscho** 2015-09-04 14:48 UTC
Labels: git, wontfix

**Comment by vitaut** [comment] 2015-09-04 16:04
Thanks for giving it a try. This is not critical for me and I can live with a workaround (I am not using Windows myself anyway, just noticed the issue on one of the build boxes).

**Comment by kblees** [comment] 2015-09-14 15:53
```git clone -c core.longPaths=true``` only sets the core.longPaths option in the config file of the newly cloned repository, it does *not* affect the clone command itself (unless you have ```core.longPaths=true``` in your system / user config file, or you use ```git -c core.longPaths=true clone -c core.longPaths=true```).

However, using such long work tree paths does not work, as git always CDs to the work tree directory, and the Windows ```SetCurrentDirectory``` API is limited to 260 characters [1]. IIRC there are even more limitations in git's core code, e.g. the object database paths (```.git/objects/ab/cdef...```) must fit within the 260 limit.

As @dscho already mentioned, ```core.longPaths``` is meant to support long paths *within* a repository, not long work tree or git dir paths.

[1] https://msdn.microsoft.com/en-us/library/windows/desktop/aa365530%28v=vs.85%29.aspx

**Comment by dscho** [comment] 2016-05-21 05:51
> Windows SetCurrentDirectory API is limited to 260 characters

@kblees I tested this yesterday (because @stefanbeller introduced a change into v2.8.3 where submodules' path were *forced* absolute), and on my Windows 10, `SetCurrentDirectory()` had no such limitation. So I lifted it.

Note that older Windows versions might display an error, but at least we spent our best effort to try.

**Comment by junneyang** [comment] 2016-05-23 02:00
is there any way to solve this problem? thanks!  #762

**Comment by dscho** [comment] 2016-05-23 05:37
> is there any way to solve this problem?

Yes:

1. Read #762.
2. Use my analysis as a quick start into the source code in question.
3. Download and install the [Git for Windows SDK](http://git-for-windows.github.io/#download-sdk).
4. Patch the source code.
5. Build, install and test the patch.
6. If it fails, go back to 4.
7. [Contribute](http://git-for-windows.github.io/#contribute).
