### ISSUE TITLE
Git for Windows crashes at start

### ISSUE THREAD

**Issue by michael-vostrikov** [git-for-windows/git#741] opened 2016-04-21 11:59 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

2.8.1 32-bit
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 7 32-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

Defaults
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

There is some Windows policy restrictions on my computer.
### Details

Me and my colleagues have found that recent versions of git for windows crashes at start on our computers. The latest working version is 2.6.0.
OS on our computers is Windows 7 32-bit.
There was similar bug for Windows 10: https://github.com/git-for-windows/git/issues/627
It seems I have found the reason.
### Description.

I tested the version 2.8.1.
"bin\git.exe" runs "mingw32\bin\git.exe"
When it is ran from Windows Explorer, APPCRASH is occured.
When it is ran form git bash, the message "Segmentation fault" is showed.

"mingw32\bin\git.exe" and other binaries are compiled with the same runtime library.
It contains pseudo-relocation mechanism.

I looked the source code here:
https://github.com/mirror/mingw-w64/blob/master/mingw-w64-crt/crt/pseudo-reloc.c#L180

do_pseudo_reloc() is called after start.
It calls __write_memory() function for each relocation item.
__write_memory() calls mark_section_writable() and then writes new value to required address.

It seems that in the compiled executable mark_section_writable() is called directly from do_pseudo_reloc().

On third iteration the exception is occured.
git.exe: The instruction at 0x146B662 referenced memory at 0x146D502. The memory could not be written (0x0146B662 -> 0146D502)

Instruction is:

```
call mark_section_writable_18B2B0
mov [esi], edi
```

Disassembly:

```
mark_section_writable_18B2B0 proc near

var_30          = dword ptr -30h
var_2C          = dword ptr -2Ch
var_28          = dword ptr -28h
var_24          = dword ptr -24h
var_1C          = dword ptr -1Ch
var_10          = dword ptr -10h
var_8           = dword ptr -8

                push    edi
                push    esi
                push    ebx
                sub     esp, 30h

        ; [I could not find related source code]
                mov     esi, ds:max_sections_22E240
                test    esi, esi
                jle     loc_18B39D

        ; for (i = 0; i < maxSections; i++)
                mov     edi, ds:the_secs_22E244
                xor     ebx, ebx
                lea     edx, [edi+4]
                nop

loc_18B2D0:
        ; if (the_secs[i].sec_start <= ((LPBYTE) addr)
        ;       && ((LPBYTE) addr) < (the_secs[i].sec_start + the_secs[i].hash->Misc.VirtualSize))
        ;           return;

                mov     ecx, [edx]
                cmp     ecx, eax
                ja      short loc_18B2E4
                mov     edi, [edx+4]
                add     ecx, [edi+8]
                cmp     eax, ecx
                jb      loc_18B396      ; return

loc_18B2E4:
        ; next loop iteration
                add     ebx, 1
                add     edx, 0Ch
                cmp     ebx, esi
                jnz     short loc_18B2D0

loc_18B2EE:
                mov     [esp+30h+var_30], eax
                mov     ebx, eax
                call    __mingw_GetSectionForAddress_18BBD0

                test    eax, eax
                mov     edi, eax
                jz      loc_18B3DA

                lea     ebx, [esi+esi*2]
                mov     esi, ds:the_secs_22E244
                shl     ebx, 2
                add     esi, ebx
                mov     [esi+8], eax
                mov     dword ptr [esi], 0
                call    _GetPEImageBase_18BD00
                add     eax, [edi+0Ch]
                mov     [esi+4], eax

                lea     eax, [esp+30h+var_1C]
                mov     [esp+30h+var_28], 1Ch
                mov     [esp+30h+var_2C], eax
                mov     eax, ds:the_secs_22E244
                mov     eax, [eax+ebx+4]
                mov     [esp+30h+var_30], eax
                call    ds:VirtualQuery
                sub     esp, 0Ch

                test    eax, eax
                jz      short loc_18B3BA
                mov     eax, [esp+30h+var_8]
                lea     edx, [eax-4]
                and     edx, 0FFFFFFFBh
                jz      short loc_18B38F
                sub     eax, 40h
                and     eax, 0FFFFFFBFh
                jz      short loc_18B38F

                mov     eax, [esp+30h+var_10]
                add     ebx, ds:the_secs_22E244
                mov     [esp+30h+var_28], 40h
                mov     [esp+30h+var_2C], eax
                mov     eax, [esp+30h+var_1C]
                mov     [esp+30h+var_24], ebx
                mov     [esp+30h+var_30], eax
                call    ds:VirtualProtect
                sub     esp, 10h

                test    eax, eax
                jz      short loc_18B3A4

loc_18B38F:
        ; ++maxSections;
                add     ds:max_sections_22E240, 1

loc_18B396:
        ; return
                add     esp, 30h
                pop     ebx
                pop     esi
                pop     edi
                retn
; ---------------------------------------------------------------------------

loc_18B39D:
                xor     esi, esi
                jmp     loc_18B2EE
; ---------------------------------------------------------------------------

; error handlers

loc_18B3A4:
...
loc_18B3BA:
...
loc_18B3DA:
...

mark_section_writable_18B2B0 endp
```
### Reason.

When mark_section_writable() is called first time, the global variable max_sections is 0.
If it is 0, mark_section_writable() runs VirtualQuery() with address = the_secs[i].sec_start, and then VirtualProtect() with returned b.RegionSize.
Here is some inconsistency between source code and binary code. I could not find check for 0 in the source code.

When mark_section_writable() is called next time, it checks the address via the_secs[i].hash->Misc.VirtualSize:

```
the_secs[i].sec_start <= ((LPBYTE) addr)
    && ((LPBYTE) addr) < (the_secs[i].sec_start + the_secs[i].hash->Misc.VirtualSize
```

Here is the error. The value of b.RegionSize differs from the_secs[i].hash->Misc.VirtualSize.
It seems that for some reasons Windows splits the ".text" section into 2 separate sections which are placed in sequence.

Values on my computer:
Region size (returned by VirtualQuery()): 16A000
Virtual size (the_secs[i].hash->Misc.VirtualSize): 16D774
Section size (in debugger): 16D800

I've tried to set writable bit for ".text" section via hex editor, and "git.exe" has started correctly without errors.
### Solution.

I think, the solution is always use Misc.VirtualSize instead of b.RegionSize, or don't use Misc.VirtualSize and always call VirtualQuery() + VirtualProtect().

**Comment by dscho** [comment] 2016-04-21 16:01
This is a very interesting analysis. Do you have the opportunity to verify that this only happens with 32-bit? Or is there any other special setting you have so that it crashes?

**Comment by michael-vostrikov** [comment] 2016-04-21 16:43
No, I haven't

**Comment by ColonelJ** [comment] 2016-05-01 03:43
I am experiencing the same problem, when trying to run Git on Windows XP (using the Git for Windows SDK 1.0.3 - which fails to install properly due to this issue, since when it tries to run Git, it gets a segmentation fault...).  The broken executable is the one from package mingw-w64-i686-git-2.8.1.1.5b8a668-1 (in my case) which installs at /mingw32/bin/git.exe.

It appears that the pseudo relocation code is trying to write an immediate value to code in a read-only memory region (part of the .text section).  Since the value being written appears to always be libssp-0.__stack_chk_guard, disabling libssp would likely remove the issue (this is not a terrible idea, because we don't want code meant to detect failures to be causing them instead!)

Anyway, the real problem is that, essentially, the code for making the memory writable is completely wrong, and has zero chance of working on any system where any memory pages in the .text section may have had their attributes changed since application start up.  This is because VirtualQuery only provides information for a contiguous region of pages which have the same attributes.  This means RegionSize can be pretty much anything (it could be as small as 0x1000 for a single page; though in my case I also got 0x16A000).  Also it only gives information starting at the page containing the address specified (so just giving it the address you want to write to is not good for this use case, where a lot of pages need to be written over).

Since it's impossible to know the base address of the page range, which shares the same attributes as the actual location you want to write to, the only option I can think of is to scan through the whole section until you find the right one.  Once found, you need to keep hold of it (in sec_start, which should be renamed to region_start) and you also need to keep the RegionSize (that would be added as a new field region_size in that structure).  The range check then becomes (region_start <= addr) && (addr < region_start + region_size).  Once done with the region you just need to call VirtualProtect again with the old attributes (so doing another VirtualQuery, as it currently does in restore_modified_sections, is totally pointless).

Obviously the naming of these functions and data structures is invalid, since for operating on the entire section to work, you'd need to change the attributes for every page in the section (which would make it impossible to restore the original attributes).  Also the way it allocates the memory for the sections is unsuitable since the number of page ranges may be much larger than section count.

Here's my manually annotated x86 ASM for reference:
```
0056B2B0 > $  57            PUSH EDI                                 ;  entry: mark_section_writable
0056B2B1   .  56            PUSH ESI                                 ;  param1: EAX(addr)
0056B2B2   .  53            PUSH EBX
0056B2B3   .  83EC 30       SUB ESP,30                               ;  stack: <params>, b(ESP+0x14)
0056B2B6   .  8B35 40E26000 MOV ESI,DWORD PTR DS:[60E240]            ;  ESI = maxSections
0056B2BC   .  85F6          TEST ESI,ESI
0056B2BE   .  0F8E D9000000 JLE git.0056B39D
0056B2C4   .  8B3D 44E26000 MOV EDI,DWORD PTR DS:[60E244]            ;  EDI = the_secs
0056B2CA   .  31DB          XOR EBX,EBX                              ;  EBX(i) = 0
0056B2CC   .  8D57 04       LEA EDX,DWORD PTR DS:[EDI+4]             ;  EDX = &the_secs[0].sec_start
0056B2CF   .  90            NOP
0056B2D0   >  8B0A          MOV ECX,DWORD PTR DS:[EDX]               ;  ECX = the_secs[i].sec_start
0056B2D2   .  39C1          CMP ECX,EAX
0056B2D4   .  77 0E         JA SHORT git.0056B2E4                    ;  jump if the_secs[i].sec_start > addr
0056B2D6   .  8B7A 04       MOV EDI,DWORD PTR DS:[EDX+4]             ;  EDI = the_secs[i].hash
0056B2D9   .  034F 08       ADD ECX,DWORD PTR DS:[EDI+8]             ;  ECX += the_secs[i].hash->Misc.VirtualSize
0056B2DC   .  39C8          CMP EAX,ECX
0056B2DE   .  0F82 B2000000 JB git.0056B396                          ;  jump if addr < ECX
0056B2E4   >  83C3 01       ADD EBX,1                                ;  i += 1
0056B2E7   .  83C2 0C       ADD EDX,0C                               ;  EDX = &the_secs[i]
0056B2EA   .  39F3          CMP EBX,ESI
0056B2EC   .^ 75 E2         JNZ SHORT git.0056B2D0                   ;  jump if EBX(i) != ESI(maxSections)
0056B2EE   >  890424        MOV DWORD PTR SS:[ESP],EAX               ; |<param1> = addr
0056B2F1   .  89C3          MOV EBX,EAX                              ; |
0056B2F3   .  E8 D8080000   CALL <git.__mingw_GetSectionForAddress>  ; \__mingw_GetSectionForAddress
0056B2F8   .  85C0          TEST EAX,EAX                             ;  EAX(h) = <section header>
0056B2FA   .  89C7          MOV EDI,EAX                              ;  EDI(h) = <section header>
0056B2FC   .  0F84 D8000000 JE git.0056B3DA                          ;  <not taken>
0056B302   .  8D1C76        LEA EBX,DWORD PTR DS:[ESI+ESI*2]         ;  EBX = 3*i
0056B305   .  8B35 44E26000 MOV ESI,DWORD PTR DS:[60E244]            ;  ESI = the_secs
0056B30B   .  C1E3 02       SHL EBX,2                                ;  EBX = 12*i
0056B30E   .  01DE          ADD ESI,EBX                              ;  ESI = &the_secs[i]
0056B310   .  8946 08       MOV DWORD PTR DS:[ESI+8],EAX             ;  the_secs[i].hash = h
0056B313   .  C706 00000000 MOV DWORD PTR DS:[ESI],0                 ;  the_secs[i].old_protect = 0
0056B319   .  E8 E2090000   CALL <git._GetPEImageBase>               ;  EAX = <image base>
0056B31E   .  0347 0C       ADD EAX,DWORD PTR DS:[EDI+C]             ;  EAX += h->VirtualAddress
0056B321   .  8946 04       MOV DWORD PTR DS:[ESI+4],EAX             ;  the_secs[i].sec_start = EAX
0056B324   .  8D4424 14     LEA EAX,DWORD PTR SS:[ESP+14]            ;  EAX = &b
0056B328   .  C74424 08 1C0>MOV DWORD PTR SS:[ESP+8],1C              ; |<param3>(BufSize) = sizeof(b) = 28
0056B330   .  894424 04     MOV DWORD PTR SS:[ESP+4],EAX             ; |<param2>(Buffer) = &b
0056B334   .  A1 44E26000   MOV EAX,DWORD PTR DS:[60E244]            ; |EAX = the_secs
0056B339   .  8B4418 04     MOV EAX,DWORD PTR DS:[EAX+EBX+4]         ; |EAX = the_secs[i].sec_start
0056B33D   .  890424        MOV DWORD PTR SS:[ESP],EAX               ; |<param1>(Address) = the_secs[i].sec_start
0056B340   .  FF15 24076200 CALL DWORD PTR DS:[<&KERNEL32.VirtualQue>; \VirtualQuery
0056B346   .  83EC 0C       SUB ESP,0C                               ;  (restore ESP)
0056B349   .  85C0          TEST EAX,EAX
0056B34B   .  74 6D         JE SHORT git.0056B3BA                    ;  <not taken>
0056B34D   .  8B4424 28     MOV EAX,DWORD PTR SS:[ESP+28]            ;  EAX = b.Protect
0056B351   .  8D50 FC       LEA EDX,DWORD PTR DS:[EAX-4]             ;  if b.Protect == 0x04(PAGE_READWRITE)
0056B354   .  83E2 FB       AND EDX,FFFFFFFB                         ;  or b.Protect == 0x08(PAGE_WRITECOPY)
0056B357   .  74 36         JE SHORT git.0056B38F                    ;  then jump
0056B359   .  83E8 40       SUB EAX,40                               ;  if b.Protect == 0x40(PAGE_EXECUTE_READWRITE)
0056B35C   .  83E0 BF       AND EAX,FFFFFFBF                         ;  or b.Protect == 0x80(PAGE_EXECUTE_WRITECOPY)
0056B35F   .  74 2E         JE SHORT git.0056B38F                    ;  then jump
0056B361   .  8B4424 20     MOV EAX,DWORD PTR SS:[ESP+20]            ;  EAX = b.RegionSize
0056B365   .  031D 44E26000 ADD EBX,DWORD PTR DS:[60E244]            ;  EBX = &the_secs[i]
0056B36B   .  C74424 08 400>MOV DWORD PTR SS:[ESP+8],40              ; |<param3>(NewProtect) = 0x40(PAGE_EXECUTE_READWRITE)
0056B373   .  894424 04     MOV DWORD PTR SS:[ESP+4],EAX             ; |<param2>(Size) = b.RegionSize
0056B377   .  8B4424 14     MOV EAX,DWORD PTR SS:[ESP+14]            ; |EAX = b.BaseAddress
0056B37B   .  895C24 0C     MOV DWORD PTR SS:[ESP+C],EBX             ; |<param4>(pOldProtect) = &the_secs[i].old_protect
0056B37F   .  890424        MOV DWORD PTR SS:[ESP],EAX               ; |<param1>(Address) = b.BaseAddress
0056B382   .  FF15 20076200 CALL DWORD PTR DS:[<&KERNEL32.VirtualPro>; \VirtualProtect
0056B388   .  83EC 10       SUB ESP,10                               ;  (restore ESP)
0056B38B   .  85C0          TEST EAX,EAX
0056B38D   .  74 15         JE SHORT git.0056B3A4                    ;  <not taken>
0056B38F   >  8305 40E26000>ADD DWORD PTR DS:[60E240],1              ;  maxSections += 1
0056B396   >  83C4 30       ADD ESP,30                               ;  (stack unwind)
0056B399   .  5B            POP EBX
0056B39A   .  5E            POP ESI
0056B39B   .  5F            POP EDI
0056B39C   .  C3            RETN
0056B39D   >  31F6          XOR ESI,ESI                              ;  ESI(i) = 0
0056B39F   .^ E9 4AFFFFFF   JMP git.0056B2EE
0056B3A4   >  FF15 6C066200 CALL DWORD PTR DS:[<&KERNEL32.GetLastErr>; [GetLastError
0056B3AA   .  C70424 64735B>MOV DWORD PTR SS:[ESP],git.005B7364      ;  ASCII "  VirtualProtect failed with code 0x%x"
0056B3B1   .  894424 04     MOV DWORD PTR SS:[ESP+4],EAX
0056B3B5   .  E8 96FEFFFF   CALL git.0056B250
0056B3BA   >  A1 44E26000   MOV EAX,DWORD PTR DS:[60E244]
0056B3BF   .  8B4418 04     MOV EAX,DWORD PTR DS:[EAX+EBX+4]
0056B3C3   .  894424 08     MOV DWORD PTR SS:[ESP+8],EAX
0056B3C7   .  8B47 08       MOV EAX,DWORD PTR DS:[EDI+8]
0056B3CA   .  C70424 30735B>MOV DWORD PTR SS:[ESP],git.005B7330      ;  ASCII "  VirtualQuery failed for %d bytes at address %p"
0056B3D1   .  894424 04     MOV DWORD PTR SS:[ESP+4],EAX
0056B3D5   .  E8 76FEFFFF   CALL git.0056B250
0056B3DA   >  895C24 04     MOV DWORD PTR SS:[ESP+4],EBX
0056B3DE   .  C70424 10735B>MOV DWORD PTR SS:[ESP],git.005B7310      ;  ASCII "Address %p has no image-section"
0056B3E5   .  E8 66FEFFFF   CALL git.0056B250
...
0056B656   .  89C7          MOV EDI,EAX                              ;  libssp-0.__stack_chk_guard
0056B658   .  8945 CC       MOV DWORD PTR SS:[EBP-34],EAX
0056B65B   .  89F0          MOV EAX,ESI                              ;  git.0056D502
0056B65D   .  E8 4EFCFFFF   CALL <git.mark_section_writable>         ;  (fails to do anything)
0056B662   .  893E          MOV DWORD PTR DS:[ESI],EDI               ;  ***!!CRASH!!***
```

And the [code it was apparently compiled from](https://github.com/mirror/mingw-w64/blob/d90b8bb82e9b3ece71b8e505fa9b3d75747d8046/mingw-w64-crt/crt/pseudo-reloc.c) (no discrepancies found):
```
extern int __mingw_GetSectionCount (void);
extern PIMAGE_SECTION_HEADER __mingw_GetSectionForAddress (LPVOID p);
extern PBYTE _GetPEImageBase (void);

typedef struct sSecInfo {
  /* Keeps altered section flags, or zero if nothing was changed.  */
  DWORD old_protect;
  PBYTE sec_start;
  PIMAGE_SECTION_HEADER hash;
} sSecInfo;

static sSecInfo *the_secs = NULL;
static int maxSections = 0;

static void
mark_section_writable (LPVOID addr)
{
  MEMORY_BASIC_INFORMATION b;
  PIMAGE_SECTION_HEADER h;
  int i;

  for (i = 0; i < maxSections; i++)
    {
      if (the_secs[i].sec_start <= ((LPBYTE) addr)
          && ((LPBYTE) addr) < (the_secs[i].sec_start + the_secs[i].hash->Misc.VirtualSize))
        return;
    }
  h = __mingw_GetSectionForAddress (addr);
  if (!h)
    {
      __report_error ("Address %p has no image-section", addr);
      return;
    }
  the_secs[i].hash = h;
  the_secs[i].old_protect = 0;
  the_secs[i].sec_start = _GetPEImageBase () + h->VirtualAddress;

  if (!VirtualQuery (the_secs[i].sec_start, &b, sizeof(b)))
    {
      __report_error ("  VirtualQuery failed for %d bytes at address %p",
		      (int) h->Misc.VirtualSize, the_secs[i].sec_start);
      return;
    }

  if (b.Protect != PAGE_EXECUTE_READWRITE && b.Protect != PAGE_READWRITE
      && b.Protect != PAGE_EXECUTE_WRITECOPY && b.Protect != PAGE_WRITECOPY)
    {
      if (!VirtualProtect (b.BaseAddress, b.RegionSize,
			   PAGE_EXECUTE_READWRITE,
			   &the_secs[i].old_protect))
	__report_error ("  VirtualProtect failed with code 0x%x",
	  (int) GetLastError ());
    }
  ++maxSections;
  return;
}
```

I guess now I've wasted so much time on this I may as well actually fix the code myself and make a pull request on mingw-w64, but this is definitely not what I wanted to be doing this weekend.  This bugged code should never have ended up running on my machine.

Because I have no idea when this will get fixed and actually get released, you might find the following steps helpful to repair your installation (a bit easier than using a hex editor):
- Download and install [Stud_PE](http://www.cgsoftlabs.ro/zip/Stud_PE.zip) from [CGSoftLabs](http://www.cgsoftlabs.ro/)
- Start the application, go to File->"Open PE File" and open your mingw32/bin/git.exe
- Select the 'Sections' tab and double click the '.text' entry
- Click the check box for MEM_WRITE characteristics flag to enable it and click Save

You should now be able to run your git.exe and hopefully everything should work as normal.

---

I am really disappointed that you are publishing such severely broken packages which simply DO NOT WORK and with no ability to retrieve older working versions, it's impossible to get a stable development environment you can actually use to do anything (maybe, if you're lucky, and still have an old copy cached, you can downgrade a broken package, but it's very difficult).  This means you are forced to either spend all day debugging and maybe find a workaround as I have done, or give up entirely on doing any work with the system.  This is totally unacceptable.

Packages containing vital core tools should not be published as updates unless they have been tested to make sure that they actually still function at a basic level, on a range of REAL systems (not just toy ones) having antivirus/firewall software and other crap installed.

I'd rather have updates install unwanted adware than delete working applications and replace them with ones that crash at start up.  Things need to have been built and tested properly from a consistent set of source code in a way that can be reproduced to make a STABLE release.

Now with the knowledge that it might completely break Git, I have to wonder whether I want to run the dreaded 'pacman -Syu' again, but I know if I don't, these sorts of problems are going to go unchecked, and then one day when I actually need to install something or upgrade because e.g. I discovered a bug in the gcc compiler version I'm using is causing one of my projects to crash (actually happened), it will all go horribly wrong, some dependency or other stops me having what I want installed, and yet again I won't be able to get anything done, just like now.  Having my weekends ruined seems pretty much unavoidable either way.

**Comment by ColonelJ** [comment] 2016-05-01 15:39
As it turns out, it is not just Git but a large number of applications which are affected by this issue and crash at start up:
* /mingw32/bin/gdbm_load.exe
* /mingw32/bin/git.exe
* /mingw32/bin/git-shell.exe
* /mingw32/bin/git-upload-pack.exe
* /mingw32/bin/gnutls-cli.exe
* /mingw32/bin/gnutls-serv.exe
* /mingw32/bin/nettle-hash.exe
* /mingw32/bin/ocsptool.exe
* /mingw32/bin/pcregrep.exe
* /mingw32/bin/rtmpdump.exe
* /mingw32/bin/rtmpgw.exe
* /mingw32/bin/rtmpsrv.exe
* /mingw32/bin/rtmpsuck.exe
* /mingw32/bin/sexp-conv.exe
* /mingw32/bin/WhoUses.exe

These can all be temporarily fixed using the procedure described above to make the .text section writable.  There may be other apps affected where the feature is still used but, by luck, it doesn't cause a crash.  Obviously, doing git.exe alone is obviously not sufficient to make Git work.

N.B. the apps are using this mechanism to load libraries other than libssp, so just changing that for Git would still leave a lot of things broken.

The MinGW CRT needs fixed and all packages built from scratch.  I am going to try implementing the change in the psuedo relocations module myself and make a merge request from Sourceforge.

**Comment by ColonelJ** [comment] 2016-05-01 16:41
Ticket has been created on Sourceforge: https://sourceforge.net/p/mingw-w64/bugs/537/

**Comment by landstander668** [comment] 2016-05-05 13:45
> I am really disappointed that you are publishing such severely broken packages which simply DO NOT WORK and with no ability to retrieve older working versions

I can't speak to the other stuff, but it's absolutely possible to retrieve [version 2.6.0](https://github.com/git-for-windows/git/releases/tag/v2.6.0.windows.1), which works according to the original reporter. All of the other releases are similarly accessible.

**Comment by dscho** [comment] 2016-05-13 11:44
I wonder why the `mark_section_writable()` function does not do its intended job...

**Comment by michael-vostrikov** [comment] 2016-05-13 16:50
Well, because it has a bug. As mentioned above, VirtualQuery() returns only the size of contiguous region of pages which have the same attributes. In general, it is not the same as section size, so this function cannot be used as it is used in relocation code. In case of git (on my computer), when process starts, the page at address ".text + 0x16A000" is already marked as writable, other pages in text section are read only. I could not find if it happens due to antivirus or system settings or something else.
Also it is strange for me that binary code does not match source code.

**Comment by michael-vostrikov** [comment] 2016-05-13 16:53
Could you change this code locally and make some experimental build, so that we can check it on our machines?

**Comment by ColonelJ** [comment] 2016-05-14 00:57
Yeah, I didn't really make any progress on this yet, I was just going to hack something up around that individual module in isolation, and then make sure it does what is expected with a mix of (very much artificial) starting conditions.  Testing it in situ with the CRT seems like too much effort for what is really just a simple bug.  Also, publishing some test build to run on other machines is also wasted effort when we know exactly what the problem is.  The Windows APIs should do what they say they do, on any Windows version...

If I wanted something for you to test it would be something along the lines of:
* Build MinGW-w64 toolchain from original source, compile something, observe that it crashes
* Build MinGW-w64 toolchain from fixed source, compile something, observe that it doesn't crash

I can guarantee that it wouldn't be a worthwhile use of time for either of us to build it even once, so you can forget it. :)

Regarding the implemention...  To avoid repeatedly scanning through all the section ranges, my thought is that it could allocate a cache for the results from all VirtualQuery calls on a particular section, setting a flag against any ranges it has made writable.  Then at the end you then just scan through looking for the flags, restore the old attributes as necessary, and delete the caches.

**Comment by dscho** [comment] 2017-02-22 00:03
Shall we just close this ticket without any resolution? (I won't have time to do anything about this...)

**Comment by michael-vostrikov** [comment] 2017-02-22 03:10
I think, you can just ask Mingw developers to fix mark_section_writable() function.

**Comment by dscho** [comment] 2017-02-22 12:21
> I think, you can just ask Mingw developers to fix mark_section_writable() function.

I guess I could. But so could you. And as Git for Windows is not a one-man-show but an Open Source project that is only as good as *all* contributors make it, I would like to ask you to follow up on that task so that I can go back to packaging the new cURL, sift through other open issues and finally release a new git for Windows version.

Thank you.

**Closed** 2017-02-22 13:50 UTC
Labels: help wanted
