### ISSUE TITLE
Install reboots without prompt

### ISSUE THREAD

**Issue by sstudley** [git-for-windows/git#2647] opened 2020-06-01 20:09 UTC
Sorry but this is abysmal conduct. Git installer is not ready for polite company. Needs to learn proper behavior.
Please meet out behind woodshed.

```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Win 10 64-bit?

```

**Comment by dakotahawkins** [comment] 2020-06-01 20:26
This didn't happen to me, are you sure the GfW installer triggered the reboot?

**Comment by PhilipOakley** [comment] 2020-06-01 20:53
Didn't happen here. 

What selections did you use on the last page of the install (show RelNotes; Start bash) ?

If you selected either, did you see either activity start? If you had your browser open, and 're-open with previous tabs', did the re-opened browser show the release notes, etc.

If it's not repeatable on everyone's machine, you'll need to be the eyes and ears so we can suggest options.

**Comment by dscho** [comment] 2020-06-01 21:18
> Please meet out behind woodshed.

If this was supposed to sound funny: it wasn't.

For the record, I cannot reproduce here, either.

Do you remember whether a Git process was still running while you tried to upgrade? Or did you try to upgrade via `git update-git-for-windows`? We tried to fix a similar issue in the latter in git-for-windows/build-extra@710b4624408ebce012066d80131a7698edc4db5b.

**Comment by sstudley** [comment] 2020-06-01 23:31
I ran basic update, maintain old settings. was typing in gmail replying to
co-worker. System rebooted.
Behind the woodshed was not meant to be funny. Persons acting that way need
discipline, so does the install process.

**Comment by ROGERSM94** [comment] 2020-06-01 23:41
regardless of your feelings, berating people who volunteer their time and effort to maintaining software you use for free is not a productive way to get any help....

**Comment by dakotahawkins** [comment] 2020-06-01 23:42
Did you try looking in the windows event viewer to see if there was some reason for the reboot? As far as anybody else knows it was a coincidence. If you want help, try not to be a jerk.

**Comment by dakotahawkins** [comment] 2020-06-01 23:45
I am trying, sentiment bot :(

**Comment by rimrul** [comment] 2020-06-02 06:54
This is likely a duplicate of #2604. The 2.26.x releases shipped a version of the updater script that could cause these issues.

If you updated from a 2.26.x release, you've just got the fixed updater script with this update, but the reboot is caused by the old version you're updating from.

**Comment by dscho** [comment] 2020-06-02 11:13
> If you updated from a 2.26.x release, you've just got the fixed updater script with this update, but the reboot is caused by the old version you're updating from.

That is a very good analysis.

> Persons acting that way need discipline, so does the install process.

@sstudley such statements have no place in the Git for Windows project, not from long-time, trusted contributors and certainly not from bug reporters who still have to earn their reputation.

I will see myself forced to block you if you continue this way.

**Comment by sstudley** [comment] 2020-06-02 11:15
Thank you, updated on laptop with no issues. Lost a bit of time and data on
previous install on desktop.

**Comment by sstudley** [comment] 2020-06-02 11:19
Sorry to impact your feelings, lost time and data over an install script of
trusted software.

**Comment by dscho** [comment] 2020-06-02 11:29
> Sorry to impact your feelings

Apology accepted, but I need to point out that @ROGERSM94's comment was spot on. In any case, _any_ threat of violence is unwelcome, here, and everywhere, and it is certainly at least insensitive to threaten violence at this particular time. If you still feel the need to discipline anybody, I would suggest to try radical empathy instead.

**Closed by dscho** 2020-06-02 11:29 UTC
