### ISSUE TITLE
git-push hangs when pushing to remote hosted with git-daemon (git://)

### ISSUE THREAD

**Issue by kokostek** [git-for-windows/git#2328] opened 2019-09-12 15:21 UTC
### Remote repository and `git-daemon`
The remote can be either linux or windows machine - Git for Windows is unable to push to both.
```
mkdir git-srv
cd git-srv
git init --bare some-repo.git
git daemon --export-all --base-path=. --verbose --enable="receive-pack" .
```

### Local repository
Here are the steps I run on Windows 10 machine with Git for Windows from git bash.
```
git init some-repo
cd some-repo
echo "Hello World!" > test.txt
git add .
git commit -m "initial commit"
git remote add origin git://<remote-address>/some-repo.git
git push --set-upstream origin master
```
The last `git push` command hangs indefinitely. Although, I am able to fetch and pull from the remote. And if I try to `git push` from linux machine - it works fine.

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18362.356]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VisualStudioCode
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

**Comment by dscho** [comment] 2019-09-13 21:06
Duplicate of https://github.com/git-for-windows/git/issues/2278

**Closed by dscho** 2019-09-13 21:06 UTC
