### ISSUE TITLE
git now crashes with access violation when run on particular machine

### ISSUE THREAD

**Issue by eeevans** [git-for-windows/git#678] opened 2016-03-01 18:15 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
   or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
   matching what I'm seeing

### Setup
2.6.2 through 2.7.4

Windows 10 64 bit

I am running 64 bit Windows 10 and had git 2.6.4 running great and even gave a presentation on it's use on this machine.  At the end of the presentation, I installed SourceTree from Atlassian and Anaconda (the python env manager).  

Several days later I went to use git and tried to clone a github repo and it operated without error but, the sub-folder was not created at all.  I then tried several other repos that had worked in the past with the same results.

I then uninstalled SourceTree and Anaconda and tried again with the same results.  I uninstalled git 2.6.4 and installed 2.7.4 and at the end of the installation a message popped up that Git for Windows has stopped working and crashed with the following:
Faulting application name: git.exe, version: 2.7.0.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 10.0.14251.1000, time stamp: 0x56a54488
Exception code: 0xc0000005
Fault offset: 0x00000000000a708c
Faulting process id: 0x2abc
Faulting application start time: 0x01d17343f78bdaf5
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: 1cc299b3-e3b1-4be0-b53f-4ee60c43a8d7
Faulting package full name: 
Faulting package-relative application ID: 

It also does this when running git from command prompt.  I have tried uninstalling and reinstalling versions 2.6.2 through 2.7.4 with the same results.

Any ideas welcome,
Thanks,
Ed

**Comment by dscho** [comment] 2016-03-02 19:28
> version: 10.0.14251.1000

This is a certain indicator that this ticket is a duplicate of https://github.com/git-for-windows/git/issues/627 (the eighth duplicate, to be precise).

**Closed by dscho** 2016-03-02 19:28 UTC
