### ISSUE TITLE
Pathspec fatal git stash push keep-index with globs

### ISSUE THREAD

**Issue by christianbumann** [git-for-windows/git#2037] opened 2019-01-23 08:34 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64bit

```
$ git --version --build-options

git version 2.19.0.rc0.windows.2
cpu: x86_64
built from commit: f9c1a9c1a4c1bf131ccf13aeac422b3820fa382f
sizeof-long: 4
sizeof-size_t: 8
The issue is still present in version 2.20.1

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.195]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

Defaults

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 Reproducible on many different machines

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

 CMD

 - What commands did you run to trigger this issue? If you can provide a
 
Add a file, e.g. test.testextension

![untrackedfile](https://user-images.githubusercontent.com/32728064/51593138-ad013580-1ef1-11e9-83e4-f4787861ce69.png)

git stash push --all --keep-index :(glob)**/*.testextension

no error
  
![working](https://user-images.githubusercontent.com/32728064/51593096-8fcc6700-1ef1-11e9-8ed5-583f241e7391.PNG)

Error

![notworking](https://user-images.githubusercontent.com/32728064/51593123-9fe44680-1ef1-11e9-88d3-008368a5fff0.PNG)

**Comment by dscho** [comment] 2019-02-26 09:15
Since this bug report has no easy-to-run [MCVE](https://stackoverflow.com/help/mcve), I'll have to ask you to try again with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by christianbumann** [comment] 2019-03-07 12:43
@dscho I just tested the issue with Git 2.21.0 and on this version, the issue is still there. What is missing for a [MVCE](https://stackoverflow.com/help/mcve) ? In my example above all steps are explained to reproduce this error...

**Comment by dscho** [comment] 2019-03-07 13:15
@christianbumann an MCVE usually comes in the form of a copy/paste'able list of commands, and if necessary with a URL from where to clone a tiny repository to reproduce the issue ;-)

But reading again, I found some commands interspersed with the screenshots (from which I can copy exactly no text whatsoever...). Let me try first in WSL.

**Comment by dscho** [comment] 2019-03-07 13:39
Okay, I tested in WSL, and I have news: `git stash push --all --keep-index ':(glob)**/*.testextension'` does *not* work. Unless `test.testextension` (which BTW could be made more minimal by using e.g. `test.txt`, it does not have to be such a long name) lives in a subdirectory.

And in WSL (and by extension, Linux, because they are close enough for this current issue), this works: `git stash push --all --keep-index ':(glob)*.testextension'`, i.e. when you drop the `**/` part.

You probably come from the Java/Ant world, where `**/` means an arbitrary number of directories. And apparently this is not the case for Git, at least not for `git stash`.

Please test again, dropping the `**/`, to see whether this fixes it for you (the "regression" was caused by `git stash` becoming an optional built-in, which arguably brought it in line with the way Git works on Linux).

**Comment by dscho** [comment] 2019-03-07 13:58
Turns out that a simple `GIT_TRACE=1` points to the *actual* culprit: `git add` is called with `**/*.testextension`, i.e. without the `:(glob)` prefix.

I think we'll need something like this:

```diff
diff --git a/builtin/stash.c b/builtin/stash.c
index 794fba6e2d..23bdda3016 100644
--- a/builtin/stash.c
+++ b/builtin/stash.c
@@ -837,7 +837,7 @@ static void add_pathspecs(struct argv_array *args,
        int i;

        for (i = 0; i < ps.nr; i++)
-               argv_array_push(args, ps.items[i].match);
+               argv_array_push(args, ps.items[i].original);
 }

 /*
```

**Comment by christianbumann** [comment] 2019-03-07 14:32
Dropping `dropping the **/` only solves the problem if the file is in the same directory. No I am working on Windows, but the developer (which is not longer working in our company) used this [glossary](https://git-scm.com/docs/gitglossary#gitglossary-aiddefpathspecapathspec).

The example (command above which is no longer working for us) is only a short part of a script we are using. We created a git alias which cleans up the repo (stashing modified files - cleanup - unstash) and the pattern above is to define files which are created, but shouldn't be deleted during cleanup. Unfortunately we need some expression like **./ because the files can be in any folder inside the repo.

**Comment by dscho** [comment] 2019-03-07 14:33
I actually figured it out... see https://github.com/gitgitgadget/git/pull/159

**Comment by christianbumann** [comment] 2019-03-07 14:35
Ok thank you so much for your effort and fix!

**Comment by dscho** [comment] 2019-03-07 14:39
Please let me take a moment (catching my breath between three parallel projects, where this here ticket is one of them) to thank you for reporting this. Without reports like this one, I would not even be aware of the bugs, and I cannot fix what I do not know about. Granted, I would have liked the MCVE to be a bit more minimal, and a bit more convenient for me to reproduce (i.e. in a scripted form), and I was grumpy about it and shouldn't have been. I am sorry for that!

So to give you an idea what is going to happen now:

- I'll wait until [the build](https://dev.azure.com/gitgitgadget/git/_build/results?buildId=4146) finishes.
- If the build finishes with failures, I'll address them (hopefully there won't be any, or just that bogus t5570 failure on macOS that haunts our CI builds sporadically).
- Then I will send this off to the Git mailing list for review.
- After that, it is a bit of a waiting time (I'll actually not be waiting, but going back to other projects), to see how the core Git reviewers can help me improve the patches.
- Once I am sure enough that the patches will be integrated into core (or "upstream") Git, I will prepare a PR for Git for Windows, and will have at least one other reviewer have a last look.
- Then this PR will be merged, and I will ask you to test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

Hopefully all of this will be done in time for v2.21.1, which I get a feeling will be happening some time soon (if [the Git maintainer's recent "What's cooking"](https://public-inbox.org/git/xmqqzhq7o7sj.fsf@gitster-ct.c.googlers.com/T/#m6c66d945e828d679b4ecd7a7d8149417cca8b429) is any indication).

**Comment by dscho** [comment] 2019-03-11 16:02
So I sent the fix to the Git mailing list via https://github.com/gitgitgadget/git/pull/159, and it was integrated into the "proposed updates" branch; I am confident that it will be make the hop to `master` eventually, so I opened https://github.com/git-for-windows/git/pull/2119. Once [the build](https://dev.azure.com/git-for-windows/git/_build/results?buildId=32810) passes, I will merge, which will kick off the snapshot build.

**Closed** 2019-03-11 18:58 UTC

**Comment by dscho** [comment] 2019-03-11 19:00
Okay, I merged the PR. The snapshot build is running [here](https://dev.azure.com/git-for-windows/git/_build/results?buildId=32830). Once it is done, the snapshot I would like you to test, @christianbumann, will be available at https://wingit.blob.core.windows.net/files/index.html.

**Comment by dscho** [comment] 2019-03-11 19:59
@christianbumann your turn: https://wingit.blob.core.windows.net/files/Git-prerelease-2.21.0.windows.1.80.gdc2ae9a382-64-bit.exe

**Comment by christianbumann** [comment] 2019-03-11 20:50
@dscho A first quick test from my side was successful. I will ask tomorrow some other developers from our company to test this version too...

**Comment by dscho** [comment] 2019-03-12 07:03
> A first quick test from my side was successful. I will ask tomorrow some other developers from our company to test this version too...

Excellent.

Please do make sure that all your use cases are covered. Nothing is more frustrating for me than fixing somebody's bug, releasing a new version of Git for Windows with too little testing by the bug reporter, only to find out that the bug was not fully fixed. You'd be surprised how often that happens...

**Comment by christianbumann** [comment] 2019-03-12 15:37
@dscho This is not working if more than one pattern will be passed.

Example command: 
git stash push --all --keep-index :(glob)**/a.txt :(glob)**/b.txt2

If any of booth files exists this won't work

error message:
git stash push --all --keep-index :(glob)**/a.txt :(glob)**/b.txt2
Saved working directory and index state WIP on master: 48959c6a3b olkj
fatal: pathspec ':(glob,prefix:0)**/a.txt' did not match any files

**Comment by dscho** [comment] 2019-03-13 10:40
Okay, I tried to reproduce that, and was not able to confirm. It works over here. This is what I did (for my own ease, I reused the worktree of the regression test I introduced):

```cmd
C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>echo 1 >untracked.txt

C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>echo 2 >untracked.txt2

C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>dir untracked*
 Volume in drive C is OSDisk
 Volume Serial Number is 02D6-2667

 Directory of C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked

03/13/2019  11:39 AM                 4 untracked.txt
03/13/2019  11:39 AM                 4 untracked.txt2
               2 File(s)              8 bytes
               0 Dir(s)  55,683,592,192 bytes free

C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>git stash push -u :(glob)**/*.txt :(glob)**/*.txt2
Saved working directory and index state WIP on master: 14579a4 Add .gitignore

C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>dir untracked*
 Volume in drive C is OSDisk
 Volume Serial Number is 02D6-2667

 Directory of C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked

File Not Found
```

For the record, this is the version I tested:

```cmd
C:\git-sdk-64\usr\src\git\wip6\t\trash directory.t3905-stash-include-untracked>git version --build-options
git version 2.21.0.windows.1.80.gdc2ae9a382
cpu: x86_64
built from commit: dc2ae9a38264da2af13b0f95cc4fa5eee2ebf893
sizeof-long: 4
sizeof-size_t: 8
```

**Comment by christianbumann** [comment] 2019-03-14 06:33
@dscho Create only one of the file which fits the pattern

```sh
C:\Dev\A\B>echo 1 >untracked.txt

C:\Dev\A\B>echo 2 >untracked.txt2

C:\Dev\A\B>dir untracked*
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 1E13-129E

 Verzeichnis von C:\Dev\A\B

14.03.2019  07:29                 4 untracked.txt
14.03.2019  07:29                 4 untracked.txt2
               2 Datei(en),              8 Bytes
               0 Verzeichnis(se), 121’764’409’344 Bytes frei

C:\Dev\A\B>git stash push -u :(glob)**/*.txt :(glob)**/*.txt2
Saved working directory and index state WIP on master: 88c946a9a Merged PR 11339: Fix typo in release notes

C:\Dev\A\B>dir untracked*
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 1E13-129E

 Verzeichnis von C:\Dev\A\B

Datei nicht gefunden

C:\Dev\A\B>echo 1 >untracked.txt

C:\Dev\A\B>dir untracked*
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 1E13-129E

 Verzeichnis von C:\Dev\A\B

14.03.2019  07:30                 4 untracked.txt
               1 Datei(en),              4 Bytes
               0 Verzeichnis(se), 121’762’541’568 Bytes frei

C:\Dev\A\B>git stash push -u :(glob)**/*.txt :(glob)**/*.txt2
Saved working directory and index state WIP on master: 88c946a9a Merged PR 11339: Fix typo in release notes
fatal: pathspec ':(glob,prefix:0)**/*.txt2' did not match any files

C:\Dev\A\B>
```

**Comment by dscho** [comment] 2019-03-14 08:53
Okay, I can reproduce the issue with one pattern not matching any file. I misread this statement:

> If any of booth files exists (a.txt or b.txt2) this won't work

to mean "any", as in "the first, the second, or both". You clearly meant is as an XOR, though.

However, now it gets really, really interesting. Basically, what I did was to apply this patch on top of `master`:

```diff
diff --git a/t/t3905-stash-include-untracked.sh b/t/t3905-stash-include-untracked.sh
index 29ca76f2fbea..7dfc0cab1be4 100755
--- a/t/t3905-stash-include-untracked.sh
+++ b/t/t3905-stash-include-untracked.sh
@@ -285,7 +285,7 @@ test_expect_success 'stash -u -- <non-existant> shows no changes when there are
 
 test_expect_success 'stash -u with globs' '
 	>untracked.txt &&
-	git stash -u -- ":(glob)**/*.txt" &&
+	git stash -u -- ":(glob)**/*.txt" ":(glob)**/*.txt2" &&
 	test_path_is_missing untracked.txt
 '
 
```

This simply adds a second glob pattern to the `git stash` call, and no files match it. As you reported, this fails thusly:

```
++ git stash -u -- ':(glob)**/*.txt' ':(glob)**/*.txt2'
Saved working directory and index state WIP on master: 777c62c initial
fatal: pathspec ':(glob,prefix:0)**/*.txt2' did not match any files
error: last command exited with $?=1
not ok 26 - stash -u with globs
#
#               >untracked.txt &&
#               git stash -u -- ":(glob)**/*.txt" ":(glob)**/*.txt2" &&
#               test_path_is_missing untracked.txt
#
```

And now for the promised interesting part: This is clearly a regression from the Unix shell script version of `git stash` (i.e. the non-built-in version), right? Well, not exactly a regression, just a change of behavior, and actually a good one. If I run the test with the legacy (i.e. Unix shell script) version of `git stash` via

```sh
GIT_TEST_STASH_USE_BUILTIN=false ./t3905-stash-include-untracked.sh --run=1,26 -i -v -x -d
```

it fails at a much, much later stage:

```
++ git stash -u -- ':(glob)**/*.txt' ':(glob)**/*.txt2'
Saved working directory and index state WIP on master: 777c62c initial
fatal: pathspec ':(glob)**/*.txt2' did not match any files
error: unrecognized input
++ test_path_is_missing untracked.txt
++ test -e untracked.txt
++ echo 'Path exists:'
Path exists:
++ ls -ld untracked.txt
-rw-r--r-- 1 johasc 1049089 0 Mar 14 08:44 untracked.txt
++ test 1 -ge 1
++ echo untracked.txt
untracked.txt
++ false
error: last command exited with $?=1
not ok 26 - stash -u with globs
#
#               >untracked.txt &&
#               git stash -u -- ":(glob)**/*.txt" ":(glob)**/*.txt2" &&
#               test_path_is_missing untracked.txt
#
```

What you see here is that the `git stash` call returned with exit code `0`, indicating success. But later on, we test for the file that should have been stashed, and it was not removed at all! So `git stash` did not actually succeed to do its thing, even if it reported it!

I find it a lot worse when a command fails to do what it promised to do but pretends to succeed, compared to the command spitting out an error message and report failure.

So now we are no longer in "regression in the built-in" country, but instead we are in "long-standing bug in `git stash`, hidden by incorrect error handling" country. That's a different beast, as it clearly has not bitten a whole lot of people, since the bug has been with us for years.

In your particular case, I am actually a bit worried that you might have relied on that `git stash` to work, based on its exit code, when it actually never worked correctly!

**Comment by dscho** [comment] 2019-03-14 09:36
> So now we are no longer in "regression in the built-in" country, but instead we are in "long-standing bug in `git stash`, hidden by incorrect error handling" country. That's a different beast, as it clearly has not bitten a whole lot of people, since the bug has been with us for years.

I still spent the last 45 minutes to investigate where that bug lies (and I am actually no longer *that* sure that it *is* a bug, see 81f45e7dc4e930ffc17dce3e377e6adc3eb3d8de for an explanation why). Here is what I have to say about this:

- Since it would be surprising for `git add -- ':(glob)*matches*nothing'` to succeed even when no files match that pattern, it is safe to assume that the same surprise holds true for `git stash`.
- As you obviously have a use case where you do not care whether any file matches, you need a *new* way to specify that. This could be e.g. an option for `git add` and `git stash`, such as: `--no-fail-on-unmatched-glob` (which is admittedly a bit long to type, maybe you can think of a more concise name).
- It should be relatively easy to implement, too, as there is a related option already: `--ignore-missing`:
    - The option would have to be added here: https://github.com/git/git/blob/v2.21.0/builtin/add.c#L307,
    - The `else` here: https://github.com/git/git/blob/v2.21.0/builtin/add.c#L514 would have to be changed to `else if (fail_on_unmatched_glob)`),
    - the Documentation would have to be modified: https://github.com/git/git/blob/v2.21.0/Documentation/git-add.txt, and
    - a new regression test case to verify that everything works as intended would have to be introduced, probably https://github.com/git/git/blob/v2.21.0/t/t2204-add-ignored.sh.
    - Then, the same option would have to be introduced in `git stash`.
- This new feature is safely outside of the Windows-specific part that we try to keep running over here, so the patches (or if you would prefer to hope that somebody else implements it, the feature request) should be sent to the Git mailing list (git@vger.kernel.org, no HTML!).
- If you prefer a band aid to putting in the effort to patch Git, you could also parse the output of `git add --dry-run --ignore-missing -- ':(glob)**/*.txt' ':(glob)**/*.txt2'`, and parse those files explicitly to `git stash`.

**Comment by dscho** [comment] 2019-03-14 09:38
Oh, and of course: should you choose to accept the mission to implement this feature, feel free to ask for more pointers over here. I am always ready to help Git contributors get over the initial obstacles when they want to enhance Git.

**Comment by christianbumann** [comment] 2019-03-14 10:26
Fist, many thanks for your effort

> In your particular case, I am actually a bit worried that you might have relied on that git stash to work, based on its exit code, when it actually never worked correctly!

We've written a git alias (early 2018) which we rollout with our development environment scripts. Then we have a batch file inside the repositories which calls this git-alias, and there it is possible to exclude glob patterns. In this case this is used in 4 different repositories, with different numbers of glob excludes (3 up to 6). 
So I don't know how often and how many developers uses this batch file to cleanup the solution, and I don't know if they ran into this bug without reporting this. But it can also be the constellation of the globs and files inside the repository which prevents that this bug appears (see my example which I just tried out)

```sh

C:\Dev\A\B>dir untracked*
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 1E13-129E

 Verzeichnis von C:\Dev\A\B

14.03.2019  11:12                 4 untracked.txt
14.03.2019  11:12                 4 untracked.txt3
14.03.2019  11:12                 4 untracked.txt4
               3 Datei(en),             12 Bytes
               0 Verzeichnis(se), 122’499’272’704 Bytes frei

C:\Dev\A\B>git stash push -u :(glob)**/*.txt :(glob)**/*.txt2 :(glob)**/*.txt3
Saved working directory and index state WIP on AddReleaseNotes201930RC: 85a6ea3e9 Add initial release notes for 2019.30.0.1-RC
fatal: pathspec ':(glob,prefix:0)**/*.txt2' did not match any files

C:\Dev\A\B>dir untracked*
 Datenträger in Laufwerk C: ist Windows
 Volumeseriennummer: 1E13-129E

 Verzeichnis von C:\Dev\A\B>

14.03.2019  11:12                 4 untracked.txt2
14.03.2019  11:12                 4 untracked.txt3
               2 Datei(en),              8 Bytes
               0 Verzeichnis(se), 122’497’908’736 Bytes frei

C:\Dev\A\B>git stash push -u :(glob)**/*.txt :(glob)**/*.txt2 :(glob)**/*.txt3
Saved working directory and index state WIP on AddReleaseNotes201930RC: 85a6ea3e9 Add initial release notes for 2019.30.0.1-RC

```

**Comment by christianbumann** [comment] 2019-03-14 10:31
`

> Oh, and of course: should you choose to accept the mission to implement this feature, feel free to ask for more pointers over here. I am always ready to help Git contributors get over the initial obstacles when they want to enhance Git.
`
I will discuss this in our team how we wan't to go further with this issue but you don't need to investigate more time.

**Comment by dscho** [comment] 2019-03-14 14:14
> I will discuss this with our team how we wan't to go further with this issue

Okay.

> but you don't need to investigate more time.

Gee, thanks! 🤣 (Seriously again, the only person who can tell me what I need, or do not need, to invest more time in is my manager...)
