### ISSUE TITLE
LFS is no longer enabled in the default configuration of PortableGit 2.24.0

### ISSUE THREAD

**Issue by kkolinko** [git-for-windows/git#2398] opened 2019-11-08 02:51 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

#2321 is relevant to this issue. In particular,  [rimrul's comment](https://github.com/git-for-windows/git/issues/2321#issuecomment-528383869) (5 Sep 2019).

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64-bit.

```
$ git --version --build-options
git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 10 1903.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.449]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

I use `PortableGit-2.24.0.2-64-bit.7z.exe` that I installed by unpacking it manually. I use a batch script like the following to unpack it into the current directory (`-o.`) and run its `post-install` script.

```
@echo off
set "FILE=PortableGit-2.24.0.2-64-bit.7z.exe"

echo Extracting...
start "Extracting..." /wait /b "%FILE%" -o. -y

if EXIST post-install.bat (
  echo:
  echo Post-install script...
  start "Post-install script..." /wait /b .\git-bash.exe --command=post-install.bat
  echo Post-install script - Done
)
```

(The above steps are followed by some adjustments to the configuration. My script also compares the original `gitconfig` file shipped with PortableGit with the one from the previous version. So I noticed that there was a change.)

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None.

### Details

When I compare the `gitconfig` file shipped with PortableGit 2.24.0.2 with the one from version 2.23.0, the `[filter "lfs"]` section is missing from the file.

 - Steps to reproduce:

Use 7-zip to open a `PortableGit-*-64-bit.7z.exe` and compare contents of `gitconfig` file between versions. The path to the file is known to be different:

2.23.0 and earlier:  `mingw64\etc\gitconfig`
2.24.0 and later:   `etc\gitconfig`

 - Expected behavior:

I expect the `gitconfig` file in 2.24.0 to have the following section (adjusted according to https://github.com/git-for-windows/build-extra/pull/256/files):

```
[filter "lfs"]
	clean = git-lfs clean -- %f
	smudge = git-lfs smudge -- %f
	process = git-lfs filter-process
	required = true
```
 - What actually happened instead?

There is no `[filter "lfs"]` section in the file in 2.24.0, 2.24.0 (2). There was one in 2.23.0.

This change is not mentioned in [Release Notes](https://github.com/git-for-windows/git/releases/) for 2.24.0, 2.24.0(2), thus I guess that it was unintended. From discussion in #2321 I think that it was unintended. If it was intended, please mention it in the Release Notes.

For me personally, I am not really concerned with this change, as I always adjust the configuration.

**Comment by rimrul** [comment] 2019-11-08 08:00
Please don't tell me I've messed this up twice in a row.

**Comment by dscho** [comment] 2019-11-08 10:11
@rimrul no, I fear that I messed this up by not installing the `mingw-w64-git-lfs` package after letting `git-extra` reinitalize `/etc/gitconfig`.

**Comment by dscho** [comment] 2019-11-08 20:25
>  I fear that I messed this up by not installing the `mingw-w64-git-lfs` package after letting `git-extra` reinitalize `/etc/gitconfig`.

And I was correct. This is now fixed, and the next [snapshot](https://wingit.blob.core.windows.net/files/index.html) should have the fix.

**Comment by dscho** [comment] 2019-11-20 10:36
>  the next [snapshot](https://wingit.blob.core.windows.net/files/index.html) should have the fix.

@kkolinko can you please test it?

**Comment by dscho** [comment] 2019-11-21 23:33
I'll just go ahead and close this ticket. It still would be nice to have confirmation that the issue is actually fixed.

**Closed by dscho** 2019-11-21 23:33 UTC
Labels: bug, sdk

**Comment by dscho** [comment] 2019-11-22 12:48
>  It still would be nice to have confirmation that the issue is actually fixed.

In case it was unclear: @kkolinko that means you.

**Comment by kkolinko** [comment] 2019-11-22 14:06
> the next [snapshot](https://wingit.blob.core.windows.net/files/index.html) should have the fix.

I verified the latest snapshot (for commit a4c71cf24325ab5debdec047570135fa6936f160). It is OK. The `[filter "lfs"]` settings are present in the `/etc/gitconfig` file in {PortableGit, MiniGit, MiniGit-BusyBox} x {32, 64}.

The settings are present as well if I use `Git-*-64-bit.exe` installer and choose to enable "LFS support" in the installation wizard.

BTW, I see that the following section disappeared from `/etc/gitconfig` file in PortableGit:
```
[http]
	sslCAinfo = /ssl/certs/ca-bundle.crt
```

I guess that this change was intended. I tested PortableGit 64-bit and I see that `git clone` works successfully if I clone from GitHub using https:// protocol. So HTTPS support was not broken by this change. OK.

Thank you!

**Comment by dscho** [comment] 2019-11-22 15:55
> I see that the following section disappeared from `/etc/gitconfig` file in PortableGit:
> 
> ```
> [http]
> 	sslCAinfo = /ssl/certs/ca-bundle.crt
> ```
> 
> I guess that this change was intended

Indeed. Our version of cURL does not require that setting anymore, for a long time already.
