### ISSUE TITLE
Network Drive Despairingly Slow on Vim

### ISSUE THREAD

**Issue by KSR-Yasuda** [git-for-windows/git#3709] opened 2022-02-22 02:33 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2
cpu: x86_64
built from commit: 5437f0fd368c7faf1a0b5e1fef048232c1f2a3e6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1526]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Mount a network drive (`\\172.27.xxx.xxx\FOOBAR`) onto a drive letter `K:`.

### Details

Opening some entries in the mounted drive `/k/` on vim,
it automatically converts the equivalent path in `//172.27.xxx.xxx/FOOBAR/`
(e.g. `/k/dirA/fileA.txt` -> `//172.27.xxx.xxx/FOOBAR/dirA/FileA.txt`).

Also, vim is terribly slow on network drive.

I think it has happened in these recent ver. of git-for-windows
(I'm not sure for v2.35.1, but it had not happened on v2.35.0).

Bash `cd` is handled as the mounted drive letter `/k/`, so,
only Vim behaves differently.

I'm not sure this path conversion is related with the Vim performance on network drives,
though, at least it has changed in network drive's treatment in recent versions.

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
# Mount a network drive somehow, e.g. with `subst` command beforehand

$ cd /k/dirA/
$ pwd
/k/dirA
# Bash is on the mounted-drive-letter path

$ vim ./
# Directory
# Opened as the original path `//172.27.xxx.xxx/FOOBAR/dirA`;
# and it is TOO SLOW to open.

$ vim ./fileA.txt
# File
# Opened as the original path `//172.27.xxx.xxx/FOOBAR/dirA/FileA.txt`;
# and it is TOO SLOW to open.
```

 - What did you expect to occur after running these commands?

Vim works lightly.

Also, do not convert Vim opening entry's path.

 - What actually happened instead?

Vim behaves too heavy on network drives.

Vim working directory becomes the network drive, so every vim actions get slow across the board
(e.g. `q:` to open Vim command history).

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

No, it isn't related with any Git repository.

**Comment by dscho** [comment] 2022-02-22 09:46
Does this also happen when you use [Cygwin](https://cygwin.com)? I ask because we use a close derivative of the Cygwin runtime, and the underlying problem might actually affect Cygwin, too.

**Comment by dscho** [comment] 2022-02-22 09:47
Also, please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html), it might have a couple of fixes that potentially help your scenario.

**Comment by KSR-Yasuda** [comment] 2022-02-28 01:21
@dscho

> Also, please test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html),

Tried the snapshot at Tue, 22 Feb 2022 10:57:27.

On that version, mounted root directory `/k/` (bound to `\\172.27.xxx.xxx\FOOBAR`) is inaccessible.

```
% git --version
git version 2.35.1.windows.2.7.g158a30d60b.20220224121117

# Root dir access fails
% ls /k/
ls: cannot open directory '/k/': Too many levels of symbolic links

# Subdir, such as `/k/FOO` (is `\\172.27.xxx.xxx\FOOBAR\FOO`), is accessible, though.
```

Vim looks working under the drive letter (such as `/k/FOO`) successfully, in most cases.

**Comment by KSR-Yasuda** [comment] 2022-02-28 01:31
@dscho

> Does this also happen when you use [Cygwin](https://cygwin.com)?

On Cygwin (v3.3.4), behaves like the snapshot of Tue 22 Feb.

```
$ ls /cygdrive/k/
ls: cannot access '/cygdrive/k/': Too many levels of symbolic links

$ uname -r
3.3.4(0.341/5/3)

$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Feb 13 2022 22:15:51)
Included patches: 1-4372
Modified by <cygwin@cygwin.com>
Compiled by <cygwin@cygwin.com>
Huge version without GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
-balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
-browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   -toolbar
+cindent           +job               +popupwin          +user_commands
-clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           +python/dyn        +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby/dyn          +wildignore
+cursorbind        +lua/dyn           +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con        +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            -X11
+digraphs          +mouse             -sound             -xfontset
-dnd               -mouseshape        +spell             -xim
-ebcdic            +mouse_dec         +startuptime       -xpm
+emacs_tags        -mouse_gpm         +statusline        -xsmp
+eval              -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
-farsi             -mouse_sysmouse    -tag_old_static    
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -ggdb -O2 -pipe -Wall -Werror=format-security -fstack-protector-strong --param=ssp-
buffer-size=4 -fdebug-prefix-map=/pub/devel/vim/vim-8.2.4372-1.x86_64/build=/usr/src/debug/vim-8.2.4372-1 -fdebug-prefix-map=/pub/d
evel/vim/vim-8.2.4372-1.x86_64/src/vim-8.2.4372=/usr/src/debug/vim-8.2.4372-1 -fstack-protector-strong -DSYS_VIMRC_FILE=/etc/vimrc 
-D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 
Linking: gcc -L. -fstack-protector-strong -L/usr/local/lib -Wl,--as-needed -o vim.exe -lm -lncursesw -lsodium -liconv -lacl -lattr 
-lintl -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong -L/usr/lib/perl5/5.3
2/x86_64-cygwin-threads/CORE -lperl -lpthread -ldl -lcrypt 

$ vim /cygdrive/k/FOO
# Shows the path `/cygdrive/k/FOO` expectedly, without path replacement.
```

**Comment by dscho** [comment] 2022-03-10 11:01
> $ ls /cygdrive/k/
> ls: cannot access '/cygdrive/k/': Too many levels of symbolic links

Now, that is interesting. Why does Cygwin detect symbolic links where there is a mount point? Maybe the network share itself is using symbolic links on the remote side that are somehow exposed to the client side?

Can you tell us more about your network drive? Could you run [`fsutil reparsepoint`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-reparsepoint) to query both `K:\` as well as the full UNC path that is mounted as `K:`?

**Comment by dscho** [comment] 2022-03-14 12:27
> > Can you tell us more about your network drive? Could you run [`fsutil reparsepoint`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil-reparsepoint) to query both `K:\` as well as the full UNC path that is mounted as `K:`?
> 
> It says they're not reparsepoints.

That's strange.

> On Cygwin (v3.3.4), behaves like the snapshot of Tue 22 Feb.

Since that is the case, your best chance is to [report this bug to the Cygwin project](https://cygwin.com/problems.html). In preparation for that, could you call `strace -o log.txt ls /k/` and see whether there is any obvious smoking gun in `log.txt` that might suggest what is going on here?

**Comment by dscho** [comment] 2022-03-15 06:35
If this reproduces with Cygwin, please send a bug report to that project (and include information about the remote side, i.e. whether it runs Samba or which Windows version is used).

**Comment by KSR-Yasuda** [comment] 2022-03-15 07:54
I found the same issue in [Cygwin mailing list](https://cygwin.com/pipermail/cygwin/2022-March/250979.html) about `Too many level of symbolic links`.
They look already working on it.

**Comment by dscho** [comment] 2022-03-16 09:42
> I found the same issue in [Cygwin mailing list](https://cygwin.com/pipermail/cygwin/2022-March/250979.html) about `Too many level of symbolic links`.

Great find! For lurkers: [here](https://cygwin.com/pipermail/cygwin/2022-March/251032.html) is an explanation of the underlying cause. The [fix](https://github.com/cygwin/cygwin/commit/c098e06d96991694a949a9c913141ae8f9b8e2ba) already made it into the `cygwin-3_3-branch`, and will therefore be part of Cygwin v3.3.5, I think.

@KSR-Yasuda if you need this fix early, please feel free to cherry-pick that commit into a fork of https://github.com/git-for-windows/msys2-runtime/; When you push, [the GitHub workflow](https://github.com/git-for-windows/msys2-runtime/blob/main/.github/workflows/build.yaml) that is kicked off (unless you disabled Actions in your fork) should give you a build artifact containing an `msys-2.0.dll` with which you can replace the existing file in your Git for Windows installation.

**Comment by yashpalgoyal1304** [comment] 2023-02-01 13:18
can this issue be cloded?

**Comment by dscho** [comment] 2023-02-06 14:56
> can this issue be cloded?

Seems as if https://github.com/git-for-windows/msys2-runtime/commit/c098e06d96991694a949a9c913141ae8f9b8e2ba is marked as being part of `main`, and therefore, yes, this should be closed.

**Closed by dscho** 2023-02-06 14:56 UTC
Labels: msys2, unclear
