### ISSUE TITLE
Using commit -a fails with message: "fatal: Paths with -a does not make sense"

### ISSUE THREAD

**Issue by amccarter** [git-for-windows/git#1402] opened 2017-12-12 20:33 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

```
git version 2.15.1.windows.2
built from commit: 5d5baf91824ec7750b103c8b7c4827ffac202feb
sizeof-long: 4
machine: x86_64
```

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.64]
```

```
Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

The only other nonstandard part of my installation is that I'm using posh-git. This issue only appeared since I updated (I'm not sure what my previous version was, but it wasn't too old).

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I use git via PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git commit -a "this is a commit message"
```
 - What did you expect to occur after running these commands?

I expected that it would automatically stage the changed file(s) and commit them with the associated commit message. It would be similar to "git add ." followed by "git commit "this is a commit message". This is how it used to work.

 - What actually happened instead?

I see the following error:
`fatal: Paths with -a does not make sense`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This is happening with every repo I use.

**Comment by boogisha** [comment] 2017-12-12 22:35
Hi @amccarter,

I may be overlooking something, but what you report as an issue seems to be expected and by design.

Here's an excerpt from [`git-commit` documentation][1], regarding commit message:
```
-m <msg>
--message=<msg>
  Use the given <msg> as the commit message. If multiple -m options are given,  
  their values are concatenated as separate paragraphs.
```
Now, while I really suspect that "this is how it used to work" (not recently, at least), I would refrain from claiming it as I wouldn't really know (I guess more knowledgeable people will chime in to comment on that), but I may suggest you use something like this instead:
```
git commit -am "this is a commit message"
```
Note addition of "-m" option above, alongside "-a" you're already providing, and which would be aligned with what documentations states - in order to provide a commit message, you really should be using the "--message" option (or its abbreviated "-m" form), before the message itself. Otherwise, what you provide is eventually considered to be a path, as you observed.

The way you want to use it, it's like telling Git to stage and commit *all* files (modified and deleted), but then saying to stage and commit file named "this is a commit message" *only*, and that really does not make sense, as Git rightfully complains. It can't (and must not!) just assume you actually wanted to provide a commit message instead of a path, as you are not using the "-m" option, as you should.

Regards, Buga

[1]: https://git-scm.com/docs/git-commit#git-commit--mltmsggt

**Comment by PhilipOakley** [comment] 2017-12-13 11:37
I believe Buga's comment covers this issue. I'll close it just now. It can always be re-opened if that's insufficient.

--
Philip

**Closed by PhilipOakley** 2017-12-13 11:37 UTC

**Comment by amccarter** [comment] 2017-12-13 14:15
Thanks for the explanation. I'm just going to have to develop a new habit, then :)
