### ISSUE TITLE
_isatty and file handle redirection in native applications in bash

### ISSUE THREAD

**Issue by dashesy** [git-for-windows/git#833] opened 2016-07-25 16:26 UTC
I am using 64bit GitBash on Windows 10, default settings

$ git --version
git version 2.9.0.windows.1

This is a native application

```c
    #include <stdio.h>
    #include <io.h>
    #include <memory>

    int main() {
        if (_isatty(_fileno(stdout)))
            printf("stdout is tty\n");
        if (_isatty(_fileno(stdout)))
            printf("stderr is tty\n");
        return 0;
    }
```

Both statements are printed on `cmd.exe` but not in bash. 
I also tried `_dup2` and redirection with file handles above 2, e.g. `3>&1` and it did not work as expected. Is this use-case something common? should I use named pipes instead? If yes, what is the purpose of `_dup2` on Windows?

I think [this commit](https://github.com/git-for-windows/git/commit/de0d35dbabf220e47d50e5af7e7c5e9cbe977a13) is very much related to my question. Similar to`MSYS_TTY_HANDLES`, is there any environment variable that emulate file handle 3 in `3>&1`?

**Comment by dscho** [comment] 2016-07-26 11:33
`_isatty()` tests whether the handle in question is connected to a Win32 Console. When you run in *Git Bash*, this is not true, unless you start your process with `winpty`.

So you have two options:

1. use `winpty` to run your native application inside the *Git Bash* window, or
2. recreate the logic you found in your native application.

This is not a bug in Git for Windows, though, so I will close this ticket.

**Closed by dscho** 2016-07-26 11:33 UTC
