### ISSUE TITLE
Failing to push through Android studio

### ISSUE THREAD

**Issue by doraba** [git-for-windows/git#2345] opened 2019-10-03 17:27 UTC
Hello, I'm new to this community and I need some help.
I'm trying to push a local Android project through Android studio to a Github repo and this is the message I get at the event log:
Push failed
			Warning: failed to restrict file handles (87)
			handle #0: 0000000000000144 (type 3, handle info (1) 0
			handle #1: 00000000000001b4 (type 3, handle info (1) 1
			handle #2: 0000000000000a54 (type 3, handle info (1) 1
			This is a bug; please report it at
			https://github.com/git-for-windows/git/issues/new
			To suppress this warning, please set the environment variable
			SUPPRESS_HANDLE_INHERITANCE_WARNING=1
			remote: Repository not found.
			Authentication failed for 'https://github.com/doraba/my-application.git/'

What should I do?

**Comment by landstander668** [comment] 2019-10-03 18:28
My first guess would be that you have an out-of-date version of Git for Windows installed, as "failed to restrict file handles" was a commonly-reported issue from a few releases back. If so, you likely just need to install the [latest version](https://github.com/git-for-windows/git/releases/latest).

If you try running `git version --build-options` at a command prompt, what's the output?

**Comment by dscho** [comment] 2019-10-03 18:37
My guess is that the credential helper is disabled for some reason (and yes, we should not show that warning in that case, but we haven't had any luck to figure out what is going wrong yet, there is simply too little information to go on).

Also: it is not the best idea to delete the bug reporting template. It is designed to help provide better reports, and I think it would have helped here. The problem could be related to the Windows version, for example.

**Comment by doraba** [comment] 2019-10-03 18:55
landstander668, It seems like I have already the latest one.
![Screenshot_1](https://user-images.githubusercontent.com/36210089/66155157-b49fdf00-e627-11e9-9f7a-5968b8dcace1.png)

dscho, I'm completely new to git & GitHub so I don't know how can I check the credential helper status. 

I'd like to mention here that, I _can_ do commits through Android Studio but push gives me the above error. Though, I can do push through the git bash. My aim is to achieve both of them within the Android studio.

**Comment by dscho** [comment] 2019-10-03 20:19
> I don't know how can I check the credential helper status.

`git config credential.helper`

It might make sense to give calling `git config credential.helper manager` in your worktree a try.

**Comment by doraba** [comment] 2019-10-03 20:37
dscho, this is what I get
![Screenshot_2](https://user-images.githubusercontent.com/36210089/66162313-c937a380-e636-11e9-8eb7-a0512d198f6b.png)

**Comment by dscho** [comment] 2019-10-03 21:25
> dscho, this is what I get
> ![Screenshot_2](https://user-images.githubusercontent.com/36210089/66162313-c937a380-e636-11e9-8eb7-a0512d198f6b.png)

I read this in a text-only mail program. Screenshots are quite
cumbersome for me.

Besides, it is time that I turn in for the night, hopefully others will
have splendid ideas how to help you and chime in!

**Comment by doraba** [comment] 2019-10-03 21:35
dscho, I didn't think of that, I apologize. The image was just this:
$ git config credential.helper
manager

For the moment, I'm ok with pushing through the bash shell, 
but I would really appreciate any help tomorrow.

**Comment by PhilipOakley** [comment] 2019-10-03 21:46
there was some discussion on the g-f-w google group https://groups.google.com/forum/#!forum/git-for-windows e.g. https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/git-for-windows/Jl9KG91-Zag/ndARHCfECAAJ

**Comment by doraba** [comment] 2019-10-03 21:56
Contrary to that case, git does not ask me for credentials whenever I clone, push etc through the git bash shell and everything works fine. The problem occurs only in the Android studio when I'm trying to push, although I have put already my username & password at Settings --> Version Control -->GitHub

**Comment by dscho** [comment] 2019-10-04 12:58
Sorry, I have no idea how to debug this. If it works in Git Bash, and not in Android Studio, it strikes me as a bug in IntelliJ rather than Git for Windows, too...

**Comment by doraba** [comment] 2019-10-04 13:49
Yes, it is quite strange. Thank you for trying though.

**Comment by doraba** [comment] 2019-10-04 14:49
@dscho reading your previous comments and searching about it, I finally managed to find the solution. I had to go to File --> Settings --> Git and check the "Use credential helper" checkbox. 
Now I am pushing successfully. Thanks to your intuition!

**Comment by dscho** [comment] 2019-10-04 19:37
I am glad you found it, and equally happy that you let us know! Now other users hitting the same snag have a chance to find your solution.

As the problem is solved for now, let's close this ticket?

**Closed** 2019-10-04 19:45 UTC
