### ISSUE TITLE
Git daemon broken on windows (WSAStartup)

### ISSUE THREAD

**Issue by learn-more** [git-for-windows/git#1952] opened 2018-11-26 09:53 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
   - Git-2.19.2-64-bit.exe
```
$ git --version --build-options
git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.17134.407]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
> type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
Plink Path: D:\Tools\Putty\PLINK.EXE
SSH Option: Plink
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
   - Corporate domain, behind a proxy.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
   - CMD, from a batch script:
```
start git daemon --base-path="d:\My Projects\Visual Studio Projects" --informative-errors --verbose --enable=receive-pack
```

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Not sure if this is relevant, but in case it might be:
The daemon is not used to serve one repository, but instead it serves all repositories in the selected folder.
```
git daemon --base-path="d:\My Projects\Visual Studio Projects" --informative-errors --verbose --enable=receive-pack
```
 - What did you expect to occur after running these commands?
   - A running git daemon

 - What actually happened instead?
   - Git daemon exits with a (localized) error:
```
[16896] getaddrinfo() for (null) failed: De toepassing heeft WSAStartup niet aangeroepen, of WSAStartup is mislukt.
fatal: unable to allocate any listen sockets on port 9418
```
Free-handed translation:
```
[16896] getaddrinfo() for (null) failed: The application has not called WSAStartup, or WSAStartup failed.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
     - n/a

---

update:
Downgrading to `v2.19.1` fixes the issue for me.

ps: Nice bug reporting template 👍

**Comment by dscho** [comment] 2018-11-26 16:08
Could you please test the latest snapshot from https://wingit.blob.core.windows.net/files/index.html? I *think* this bug has been fixed in the meantime.

BTW v2.19.2 has been bumped down to "pre-release" status in part because of that bug.

**Comment by learn-more** [comment] 2018-11-26 17:51
https://git-scm.com/download/win still serves this as download.
I will re-test using the provided link.

**Comment by dscho** [comment] 2018-11-26 21:56
Wonderful. I'll close it here, then.

FWIW my current plan is to *not* release any v2.19.2(2), but to release Git for Windows v2.20.0 short after Git v2.20.0 is released ([expected Dec 2nd](https://tinyurl.com/gitCal)).

**Closed by dscho** 2018-11-26 21:56 UTC
Labels: bug, git

**Comment by learn-more** [comment] 2018-11-27 08:30
Thanks for the quick response!

**Comment by rosti-il** [comment] 2018-12-08 14:18
This bug also prevents cloning remote repositories with git:// URLs, for example: 'git clone git://git.apache.org/commons-compress.git'. The error message is similar and contains: "(port 9418) (Either the application has not called WSAStartup, or WSAStartup failed. )".

I've switched from 2.19.2.windows.1 into 2.20.0.rc2.windows.1 (both 64 bit) and now I'm able to clone remote repositories with git:// URLs.

**Comment by larsmatzer** [comment] 2019-05-24 11:40
Still experiencing the error in git 2.21.0.windows1 with gitkraken 5.0.4 on Windows 10 1809.

**Comment by dscho** [comment] 2019-05-24 13:39
> Still experiencing the error in git 2.21.0.windows1 with gitkraken 5.0.4 on Windows 10 1809.

Are you sure that the version that is actually used is v2.21.0? There are *two* Git versions involved, after all. The client and the server.

**Comment by dscho** [comment] 2019-05-24 13:40
> gitkraken 5.0.4

Also: did you try this without gitkraken in the middle?

**Comment by larsmatzer** [comment] 2019-05-24 13:43
For the server side, I am working on github and the problem only occurs with Gitkraken in between. But after all Gitkraken is just a drilldown, right? So this is weird.

**Comment by dscho** [comment] 2019-05-25 17:11
> But after all Gitkraken is just a drilldown, right?

I have no idea what GitKraken uses.

**Comment by bertyhell** [comment] 2020-09-17 12:50
I'm still having this issue with 
* Gitkraken v7.3.2
* Windows 10 (2004)
* cmd git version 2.28.0.windows.1

Only when pushing to gitlab. Github works fine.

If i try without gitkraken in the middle it also works.

Switching branches works in girkraken
Pushing a commit does not work in gitkraken

**Comment by dscho** [comment] 2020-09-17 13:55
> Maybe gitkraken uses the faulty git version under the hood?

Maybe. Do you have any Git Kraken contact you could ask?

**Comment by bertyhell** [comment] 2020-09-17 14:14
no. They only accept support requests from PRO users.

From this article it seems like they use the system's git version though:
https://support.gitkraken.com/git-workflows-and-extensions/intro-and-requirements/

it's also strange that it only fails for one provider: Gitlab and not for Github. So you would think it has to do with how Gitlab works rather than the git version.

**Comment by dscho** [comment] 2020-09-17 14:21
@bertyhell maybe open a separate ticket, then, just to track your issue (which seems to be totally unrelated to a broken `git daemon`)?

**Comment by bertyhell** [comment] 2020-09-17 14:29
Fair enough. I'll see if i can contact Gitkraken first somehow.

**Comment by bertyhell** [comment] 2020-09-21 07:43
For future reference, here's how to enable the advanced logs for gitkraken:

```
Hello,

Thank you for taking the time to reach out to support. From my experience, this error is usually caused due to the operating system. You can try to see if the SILLY logging will provide additional details to help you troubleshoot. To enable SILLY mode you can follow the steps below.

1. Remove current logs
- C:\Users\{user}\AppData\Roaming\.gitkraken\logs\repos\{repo-in-question}
- C:\Users\{user}\AppData\Roaming\.gitkraken\logs\app.txt

2. Start GitKraken via the command line
- Via the command line navigate to C:\Users\{user}\AppData\Local\gitkraken\app-7.3.2
- Run gitkraken.exe -d SILLY

Hope this information is helpful. Thank you for using GitKraken!
```

I could not reproduce the issue anymore though.
