### ISSUE TITLE
Git for Windows error

### ISSUE THREAD

**Issue by freezestudio** [git-for-windows/git#639] opened 2016-02-01 11:17 UTC
this:

![abc](https://cloud.githubusercontent.com/assets/5157556/12715969/5db334a6-c918-11e5-8cba-9357b7b5c51a.png)

**Comment by shiftkey** [comment] 2016-02-01 11:49
Duplicate of #627 - please read the final comments in the issue as this is an upstream (aka Windows) issue

**Comment by kostix** [comment] 2016-02-01 11:51
I'd say a random cat or baby picture found in the internets would contain exactly the same amount of information relevant to the problem--zero.

**Comment by freezestudio** [comment] 2016-02-01 12:01
sorry 
thanks

**Closed** 2016-02-01 12:55 UTC
