### ISSUE TITLE
Git 2.5.1 (x64) Installer freezes at end of installation

### ISSUE THREAD

**Issue by docrinehart** [git-for-windows/git#351] opened 2015-09-03 17:13 UTC
The installer seems to work fine until the end of the installation process. It simply stops doing anything. It isn't marked as "Not-Responding" by task manager, and shows nothing but a non-changing memory usage. I'm attempting to install from 2.4.6 RC5 on a Windows 10 VM in Parallels. My system is a MacBook Pro Retina running Yosemite 10.10.5.

![screenshot](https://cloud.githubusercontent.com/assets/5891405/9665289/e32d41fe-5234-11e5-9b81-b5e5a6497d53.png)

![screenshot](https://cloud.githubusercontent.com/assets/5891405/9665243/86792a2c-5234-11e5-98ff-458ff57c7bda.png)

**Comment by dscho** [comment] 2015-09-03 21:03
Do you have a `C:\Program Files\Git\usr\bin\git.exe` perchance?

**Comment by dscho** [comment] 2015-09-03 21:04
Oh, and could you run Sysinternals' [Process Monitor](https://technet.microsoft.com/en-us/library/bb896645.aspx) to find out which executable is waiting?

**Comment by docrinehart** [comment] 2015-09-03 21:07
I don't have a git.exe at that path... And I'll give it a shot later if I get a chance to look at that process monitor. After a force quit, it seems to work fine from the command line and source tree. Source Tree also sees it as the proper version.

**Comment by dscho** [comment] 2015-09-03 21:10
Still, the installation did not finish, so I would not be surprised if a subset of the functionality does not work. Now that it is force-quit, it is hard to do a live analysis anyway, so can you reinstall and see whether it hangs again?

**Comment by docrinehart** [comment] 2015-09-03 21:18
I'll try as soon as I have a chance.

**Comment by dscho** [comment] 2015-09-06 12:02
No dice yet, eh?

**Comment by cbo100** [comment] 2015-09-08 05:20
I just had this problem. 

Poked around in procmon for a while with the hung install running. 

Observations:
- Two Git-2.5.1-*.ex running
- Two Git-2.5.1-*.tmp running
- ssh-agent running
- ssh-add running
- No events from any of these processes were being generated in procmon.
- Killed ssh-agent did nothing
- Killed ssh-add caused the installer to continue, giving me the "finish" screen.

I *seem* to be left with a working installation. But not a git.exe in C:\Program Files\Git\usr\bin\

Some info:
- Previous install was a 1.9 in Program Files (x86)\Git
- This install was 2.5.1 64 bit in Program Files\Git
- There is a git.exe in C:\Program Files\Git\bin\

More observations:
- While writing this up I tried reinstalling 2.5.1 again
- Hung again
- This time, I see the last event related to the installer is ssh-add reading/closing my .ssh/id_rsa 
- Then nothing. Again kill ssh-add and installer "finishes"

__Hunch__
- My existing id_rsa is passphrase protected. Could it be prompting me for my passphrase on some hidden console?

**Comment by cbo100** [comment] 2015-09-08 05:27
I think I confirmed my hunch. 

Just tried another reinstall after moving my id_rsa, finished without a hitch. 

My .bashrc has a line which sources a load-ssh-agent script that runs my ssh-adds. I guess that's it. 

The old (1.x) installer never hung on this though.

**Comment by dscho** [comment] 2015-09-08 08:51
Ah, the crucial bit is probably a custom `$HOME/.bash_profile` or `$HOME/.profile` that calls `ssh-agent`?

**Comment by cbo100** [comment] 2015-09-08 22:40
Yeah, that seems to be it, combined with the ssh key being passphrase protected.

Maybe these post install scripts could run on first run of the Git Bash prompt rather than during the installer?

**Comment by dscho** [comment] 2015-09-09 07:57
> Maybe these post install scripts could run on first run of the Git Bash prompt rather than during the installer?

No, that was exactly the problem we tried to *solve*.

I guess we will have to try to redirect stdin when running the initial Bash session.

@cbo100 I would really appreciate if you could test the following (I am really busy juggling three other bugs right now):

1. download and install the [Git for Windows SDK](http://git-for-windows.github.io/#download-sdk)
2. [make an installer](https://github.com/git-for-windows/git/wiki/Making-an-installer)
3. edit [this line](https://github.com/git-for-windows/build-extra/blob/master/installer/install.iss.in#L1558) by inserting a ` </dev/null` after the `-c exit`
4. make another installer
5. test that installer

That would really be helpful.

**Comment by docrinehart** [comment] 2015-09-09 13:25
Sorry for the delay. I was out of town this weekend, and been playing catch-up for a couple days. I'll give that a shot as well this afternoon.

**Comment by docrinehart** [comment] 2015-09-09 13:57
Forgive my unfamiliarity with the scripting language, but that should be part of the arguments like so, right?
    
    if not Exec(Cmd, '--login -c exit </dev/null', AppDir, SW_HIDE, ewWaitUntilTerminated, i) then begin

**Comment by dscho** [comment] 2015-09-09 15:32
@docrinehart yep, that was the change I thought might help. Pity it does not... :-(

**Comment by dscho** [comment] 2015-09-10 09:17
> > Maybe these post install scripts could run on first run of the Git Bash prompt rather than during the installer?
> 
> No, that was exactly the problem we tried to solve.

To be precise: the first run by the Bash needs to execute certain post-install steps. One of those steps is to create special "device" files (they are specific to MSys2, i.e. they cannot be (un)packed by the installer). Of course, these files have to be written with *administrator* privileges. So this step *needs* to be done as part of the installer, delaying it to the first time the user starts a Git Bash will not work, like, at all.

**Comment by docrinehart** [comment] 2015-09-10 14:16
You know... I ran it as an Admin user, but I did NOT "Run as Admin". I wonder if that has anything to do with it? (Will try today)

**Comment by dscho** [comment] 2015-09-10 14:54
> You know... I ran it as an Admin user, but I did NOT "Run as Admin". I wonder if that has anything to do with it? (Will try today)

No. What I was saying is that your suggestion to wait with running the initial Bash session until the user starts a Git Bash won't work.

**Closed** 2015-09-10 20:47 UTC
Labels: enhancement, installer
