### ISSUE TITLE
Scrolling impossible when the git console is focused

### ISSUE THREAD

**Issue by caub** [git-for-windows/git#860] opened 2016-08-24 06:14 UTC
Using the latest version 2.9.3 64bit, I also chose to use the windows console directly, not the emulated one.

When scrolling I observe this:
![git-win](https://cloud.githubusercontent.com/assets/3134574/17920103/9fa355b6-69d2-11e6-96b0-b0c870bb10ed.gif)

On the right, a native windows console, scrolling work always

On the left, the git console can scroll only if it not focused, which isn't practical.

**Comment by dscho** [comment] 2016-08-25 13:35
I do not understand. A detailed description, in English, please.

**Comment by kostix** [comment] 2016-08-25 14:35
@caub, can you verify whether Git Bash on the left runs in a MinTTY window or in a `cmd.exe` window?

**Comment by caub** [comment] 2016-08-25 17:37
@kostix I think no, it's on the last step of installation, the default option iss to have a MinTTY window for git bash, but I tried to pick the one below 'integrated minTTY in cmd.exe'.

**Comment by kostix** [comment] 2016-08-26 12:51
@caub, that should be pretty easily investigated:

1. Learn where MinTTY was installed.
1. Run it by hand — telling it to run Git Bash.

You can also just start Git Bash in the usual way via the menu entry and then use the Task Manager to figure out whether MinTTY was started and whether it started `bash`.

You can also inspect the main menu entry which starts Git Bash to see how exactly that is done.

Please understand that while GIFs are certainly neat, they do little to nail the problem down; especially in this particular case: your GIF shows how it looks like but that's all.

And consider that you can't search through GIFs which maks them unfit as the primary means of reporting bugs.

**Comment by caub** [comment] 2016-08-26 22:21
![image](https://cloud.githubusercontent.com/assets/3134574/18022045/f982f012-6beb-11e6-80de-bb7beefacd97.png)
yes I meant no for your first choice, it wasn't clear, yes it's running in cmd.exe, using the context menu Git Bash

**Comment by dscho** [comment] 2016-09-08 06:42
> A detailed description, in English, please.

This is still missing. It is very frustrating when I *want* to help but am hindered by the lack of information, even after asking for it specifically.

If the "bug" in question is that moving the mouse's scroll wheel while Git Bash is in focus and while the mouse is hovering outside the window: that is by design. The idea is that you can move the mouse to, say, a web browser, and scroll the page in the web browser, without having to switch focus away from the MinTTY window.

I'll just close this ticket pre-emptively, on the assumption that my guess is correct (although it is sad that I have to guess).

**Closed by dscho** 2016-09-08 06:42 UTC
Labels: unclear

**Comment by caub** [comment] 2016-09-08 07:47
Bug is: you can't scroll the terminal (the one you open with "open git Bash here" context menu) with the mousewheel (only when it's focused, if that can help), you can with the scrollbar, and it's not a normal behavior (compared to all other terminals)

is it still not clear?

**Comment by dscho** [comment] 2016-09-08 08:10
Finally a clear bug description.

And one that let's me try to reproduce, but I fail: as long as my mouse pointer is hovering over the MinTTY window, I can scroll Just Fine.
