### ISSUE TITLE
Creating two tags with the same ref can cause you to only checkout the first tag

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#974] opened 2016-11-28 17:05 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit

```
$ git --version --build-options
_TODO_
```
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
windows 10 and it is 64-bit

```
$ cmd.exe /c ver
_TODO_
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?
I chose the defaults I think

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
_TODO_
```

Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Could be the windows insider build I'm running, but I doint think that is the cause otherwise git would fail to work.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
I'm running git bash.

 _TODO_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

* On any branch with a commit do the following for example I did this on a mater branch.

git tag 1

git tag 2

then do git checkout refs/tags/1 and then do git checkout refs/tags/2

```
TODO
```
 - What did you expect to occur after running these commands?
I expected that checking out tag 2 would work but it failed and stayed on the first tag because the ref are the same.

 - What actually happened instead?
Checking out tag 2 would not work because tag 1 had the same ref so instead it checked out tag 1.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Happends with all repo's that use the same ref.

(I am not sure if this is a git problem or a git for windows problem.)

I was creating two tags of the same ref for testing purposes for something else.

**Comment by paladox** [comment] 2016-11-30 18:11
I'm wondering could someone forward this to git please as when I send the email it fails even though they say you doint have to subscribe to the mail list to send bug reports in.

**Comment by PhilipOakley** [comment] 2016-11-30 18:45
The critical thing for sending any message to the git mailing list git@vger.kernel.org is that it must absolutely be plain text, without any HTML.

Unfortunately, many modern email systems auto generate an HTML part resulting in it being instantly marked as Spam. It (No HTML) does keep the size of the list archive down!

Have a look at how to get your email client to do plain text emails (your favourite search engine should help).

Also look at https://public-inbox.org/git/ and it's help https://public-inbox.org/git/_/text/help/, along with the ability to use Git's own send-email - instructions at the bottom of viewed messages.

Reply instructions:

You may reply publically to this message via plain-text email
using any one of the following methods:

* Save the following mbox file, import it into your mail client,
  and reply-to-all from there: mbox

  Avoid top-posting and favor interleaved quoting:
  https://en.wikipedia.org/wiki/Posting_style#Interleaved_style

  List information: http://vger.kernel.org/majordomo-info.html

* Reply to all the recipients using the --to, --cc,
  and --in-reply-to switches of git-send-email(1):

  git send-email \
    --in-reply-to='CAOE4rSxLNh0eWndroNnWsutR3FfLa=QzKPwFPcKOhwSqkKtjLw@mail.gmail.com' \
    --to=davispuh@gmail.com \
    --cc=git@vger.kernel.org \
    --cc=jonathantanmy@google.com \
    --cc=peff@peff.net \
    /path/to/YOUR_REPLY

  https://kernel.org/pub/software/scm/git/docs/git-send-email.html

* If your mail client supports setting the In-Reply-To header
  via mailto: links, try the mailto: link
--
Hope that helps

**Comment by PhilipOakley** [comment] 2016-11-30 18:52
Slight Oops, that example send-email reply was to a specific email in the archive. Hopefully it showed how it all works. The trick is to find the way of making sure your client/ISP can send plain text.

**Comment by paladox** [comment] 2016-12-01 00:24
Oh, I tried sending the email through outlook app on windows 10. So it may be the backend.

**Comment by dscho** [comment] 2016-12-01 10:23
BTW if you are referring to the prompt picking one of the matching tags, I think that you did not hit a bug, but intended behavior.

When you check out a tag, you do not really check out a tag, but the commit to which it points. As soon as the checkout completed, there is no direct relationship between the worktree and the tag other than the currently checked-out revision being pointed to by the tag. That is, when the prompt decides what to print, it deduces from the available tags' target commits what to print. And if that information is ambiguous, it simply picks one.

> Oh, I tried sending the email through outlook app on windows 10. So it may be the backend.

It is well documented that the Git mailing list refuses HTML mail. You could use [Nabble's frontend of the Git mailing list](http://git.661346.n2.nabble.com/) if you find it too hard to send non-HTML mails (and you may want to point out how unwelcoming these struggles are, as my voice was not taken seriously when I said that the mailing list is not really an accessible way for bug reporting or reviewing).

In any case, I close this ticket here because the issue is hardly specific to Windows.

**Closed by dscho** 2016-12-01 10:23 UTC
