### ISSUE TITLE
Typo in setup screen to select default git pull behavior

### ISSUE THREAD

**Issue by jarmistead** [git-for-windows/git#2656] opened 2020-06-02 16:34 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
Git 2.2.70 setup for 64-bit Windows

```
$ git --version --build-options

Irrelevant to this issue, but included for completeness
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18363.836]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Not relevant to this issue

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
Double-clicked and ran the installer Git-2.27.0-64-bit.exe
```
 - What did you expect to occur after running these commands?

An install ...

 - What actually happened instead?

Typo appeared on one of the setup screens.  Notice that for the last option it says "fast-forard" instead of "fast-forward"

![2020-06-02 Typo in Setup for git pull behavior](https://user-images.githubusercontent.com/54991061/83545524-55071580-a4cd-11ea-9e78-59d1e91a23e8.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

N/A

**Comment by PhilipOakley** [comment] 2020-06-02 17:04
Thanks. It's also been reported at #2654, which is a duplicate of #2652, and it's now been fixed at https://github.com/git-for-windows/build-extra/pull/291

**Closed by PhilipOakley** 2020-06-02 17:04 UTC
