### ISSUE TITLE
.../bin/cut: No such file or directory (when running bash.exe provided with git 2.35.0.windows.1 installation)

### ISSUE THREAD

**Issue by goostleek** [git-for-windows/git#3652] opened 2022-01-27 08:20 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.0.windows.1
cpu: x86_64
built from commit: 853373155dce195a91e6e41a58c8b8e5c5a94652
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1466]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
```
I have no `install-options.txt` in `/etc` folder. I used `scoop update git` to install the latest `git-for-windows` version as I always do.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I'm using [Windows Terminal](https://github.com/microsoft/terminal)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
"%USERPROFILE%/scoop/apps/git/current/usr/bin/bash.exe"
```
 - What did you expect to occur after running these commands?

   `bash` shell is started with no error message

 - What actually happened instead?

   `bash` shell is started but with the error message followed by a prompt

```
bash: /c/Users/goost/scoop/apps/git/current/bin/cut: No such file or directory
```
![image](https://user-images.githubusercontent.com/7780330/151318982-3f2ef0da-f88e-498b-936a-823937c4dcdf.png)

The issue does not exist in `git-for-windows` versions prior to 2.35.0.windows.1

**Comment by dscho** [comment] 2022-01-27 09:22
I cannot reproduce here. It looks like a `scoop`-specific problem, or even a bug in your personal setup. To diagnose this better, you may want to follow the guidance at https://github.com/git-for-windows/git/wiki/Diagnosing-performance-issues#trace-executions-in-the-bash-startup.

**Comment by rimrul** [comment] 2022-01-27 09:30
> I'm using [Windows Terminal](https://github.com/microsoft/terminal)

Are you sure? Your screenshot looks like you directly launched `/usr/bin/bash.exe` from some gui application (probably windows explorer). It doesn't really matter though.

>  - What did you expect to occur after running these commands?
> 
>    `bash` shell is started with no error message
> 
>  - What actually happened instead?
> 
>    `bash` shell is started but with the error message followed by a prompt
> 
> ```
> bash: /c/Users/goost/scoop/apps/git/current/bin/cut: No such file or directory
> ```
> ![image](https://user-images.githubusercontent.com/7780330/151318982-3f2ef0da-f88e-498b-936a-823937c4dcdf.png)
>
> The issue does not exist in `git-for-windows` versions prior to 2.35.0.windows.1
 
This exact issue doesn't reproduce for me with that version either. What I do get is 

`bash: cut: command not found`

That's coming from [this line in `/etc/bash.bashrc`](https://github.com/git-for-windows/git-sdk-64/blob/f0d70f6b72edd3ff9dc464a58e34d6ce1a5aa618/etc/bash.bashrc#L57) that hasn't changed in 6 years. We could probably modify that file (in the [`filesystem` package](https://github.com/git-for-windows/MSYS2-packages/blob/main/filesystem/bash.bashrc)) to call `/usr/bin/cut` instead. That seems to fix it for me.

 Running `/usr/bin/bash` as an interractive shell without `-li` isn't exactly recommended, though.

**Comment by goostleek** [comment] 2022-01-31 09:06
> Are you sure? Your screenshot looks like you directly launched /usr/bin/bash.exe from some gui application (probably windows explorer). It doesn't really matter though.

You are right @rimrul. The screenshot comes from directly running `/usr/bin/bash.exe`. I wanted to be sure that my Windows Terminal setup is not the cause of the issue

> That's coming from this [line in `/etc/bash.bashrc`](https://github.com/git-for-windows/git-sdk-64/blob/f0d70f6b72edd3ff9dc464a58e34d6ce1a5aa618/etc/bash.bashrc#L57) that hasn't changed in 6 years. We could probably modify that file (in the filesystem package) to call `/usr/bin/cut` instead. That seems to fix it for me.

👌 

I applied the fix to call `/usr/bin/cut` instead and now the issue has gone. Thx @rimrul.

**Comment by dscho** [comment] 2022-01-31 11:50
> That's coming from [this line in `/etc/bash.bashrc`](https://github.com/git-for-windows/git-sdk-64/blob/f0d70f6b72edd3ff9dc464a58e34d6ce1a5aa618/etc/bash.bashrc#L57) that hasn't changed in 6 years. We could probably modify that file (in the [`filesystem` package](https://github.com/git-for-windows/MSYS2-packages/blob/main/filesystem/bash.bashrc)) to call `/usr/bin/cut` instead. That seems to fix it for me.

That line comes from https://github.com/msys2/MSYS2-packages/commit/73e06b9d4cfd43ff9b2980812095419998ce2658

A better fix would probably be to avoid spawning a separate process altogether. Something like this:

```sh
case "$(declare -p PS1 2>/dev/null)" in
'declare -x '*)
  export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '
  ;;
esac
```

Explanation: `declare` and `case` are built into Bash, and therefore do not require spawning an entire new executable.

**Comment by dscho** [comment] 2022-01-31 11:51
@goostleek could you verify that my suggested solution works for you, too?

**Comment by goostleek** [comment] 2022-01-31 12:08
Hi @dscho, I checked your patched [`bash.bashrc` file](https://raw.githubusercontent.com/msys2/MSYS2-packages/73e06b9d4cfd43ff9b2980812095419998ce2658/filesystem/bash.bashrc) and, unfortunately, it seems it does not fix the issue 😞 
![image](https://user-images.githubusercontent.com/7780330/151791286-7f007887-cc05-4229-8326-22558ac829d4.png)

**Comment by goostleek** [comment] 2022-01-31 12:16
I replaced [the lines](https://github.com/git-for-windows/git-sdk-64/blob/f0d70f6b72edd3ff9dc464a58e34d6ce1a5aa618/etc/bash.bashrc#L57-L58) with your snippet @dscho 
```bash
case "$(declare -p PS1 2>/dev/null)" in
'declare -x '*) ;; # okay
*)
  export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '
  ;;
esac
```
and yes, this also fixes the issue for me 👍

**Comment by dscho** [comment] 2022-02-01 22:57
The [PR was merged](https://github.com/msys2/MSYS2-packages/pull/2837), the [package](https://packages.msys2.org/base/filesystem) was deployed, therefore this will be fixed in the next Git for Windows [snapshot](https://wingit.blob.core.windows.net/files/index.html) or [release](github.com/git-for-windows/git/releases), whichever comes first.

**Closed by dscho** 2022-02-01 22:57 UTC
Labels: unclear
