### ISSUE TITLE
Download git 2.7.0 64bit results in signiture corrupt or invalid 

### ISSUE THREAD

**Issue by paladox** [git-for-windows/git#629] opened 2016-01-28 11:25 UTC
Hi when downloading https://github.com/git-for-windows/git/releases/download/v2.7.0.windows.1/Git-2.7.0-64-bit.exe I get the signature of Git-2.7.0-64-bit.exe is corrupt or invalid.

**Comment by rimrul** [comment] 2016-01-28 20:47
Duplicate of #619 and #592 .

**Closed** 2016-01-29 07:55 UTC

**Comment by dscho** [comment] 2016-01-29 07:57
@paladox I appreciate that you are active on the issue tracker of Git for Windows. To make it more effective, I would like to point you once more to our [issue reporting guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), in this particular instance the search for existing tickets.

I know, I know, there are many open tickets. Maybe you can help with that, too?
