### ISSUE TITLE
Git 2.5.2.2 leaves mtab file after uninstall

### ISSUE THREAD

**Issue by Radrik5** [git-for-windows/git#405] opened 2015-09-18 10:08 UTC
Steps to reproduce:
   1. Uninstall Git 2.5.2 using Control Panel
   1. Go to C:\Program Files\Git\ or C:\Program Files (x86)\Git\

`mtab` file is not deleted. Attempt to delete it shows: "The file 'mtab' is a system file. If you remove it, Windows or another program may no longer work correctly.".

Is it safe to delete it? Can uninstaller do it?

**Comment by Radrik5** [comment] 2015-09-18 10:13
OS is Windows 7 64 bit.

**Comment by dscho** [comment] 2015-09-18 10:13
Should be deleted: https://github.com/git-for-windows/build-extra/commit/bf980fd1623eee9f1866aeaef328c3522a3d8798

**Comment by dscho** [comment] 2015-09-18 10:15
Even worse: when I install Git for WIndows 2.5.2(2), there is no `/etc/mtab` to begin with? How did you get one?

**Comment by nalla** [comment] 2015-09-18 12:27
See https://github.com/git-for-windows/build-extra/commit/bf980fd1623eee9f1866aeaef328c3522a3d8798#diff-a34c467933f9f6091a5f960fd70e16deR164 The file is being generated dynamically at some point by `msys2`. So it might not be there right after install. It is a (symbolic) link to `/proc/mounts` and somehow `msys2` flags it as _Windows System File_.

As for your user question: Yes it is safe to delete and _should_ be by the uninstaller. Maybe because it is marked as _System File_ it is somehow checked when uninstalling by some sort of _UAC_?

**Comment by Radrik5** [comment] 2015-09-18 12:42
@dscho, it's not `/etc/mtab` but `/mtab`. It's created during installation.

**Comment by nalla** [comment] 2015-09-18 12:59
Well I can confirm that the `mtab` file is indeed not in `/etc` anymore. After a fresh install it is in `/`. So either that location moved and we have to adapt the uninstaller or there is something amiss when the file is being generated.

**Comment by nalla** [comment] 2015-09-18 13:08
@dscho maybe https://github.com/git-for-windows/build-extra/blob/master/post-install.bat#L12 interferes with https://github.com/git-for-windows/build-extra/blob/master/post-install.bat#L41 ?

**Comment by rimrul** [comment] 2015-09-18 13:55
When working on #355 I've watched the same thing happen. I think it was already present in git-for-windows/build-extra@0fd86a3.

**Comment by dscho** [comment] 2015-09-18 14:06
> maybe https://github.com/git-for-windows/build-extra/blob/master/post-install.bat#L12 interferes with https://github.com/git-for-windows/build-extra/blob/master/post-install.bat#L41 ?

Hmm. @nalla Were the `post-install` scripts expected to be run in `/etc/`?

**Comment by dscho** [comment] 2015-09-18 14:06
Ah no, it is the `SYSCONFDIR` that is not set correctly... :-(

**Comment by nalla** [comment] 2015-09-18 14:09
Ah right! because `03-mtab.post` needs that.

**Comment by nalla** [comment] 2015-09-18 14:10
I think we have to check every script there - just in case - for other unset variables.

**Comment by nalla** [comment] 2015-09-18 14:11
See `99-post-install-cleanup.post`, I think that is obsolete because the `post-install.bat` removes itself?

**Comment by dscho** [comment] 2015-09-18 14:12
> I think we have to check every script there - just in case - for other unset variables.

Right, I just did.

> See 99-post-install-cleanup.post, I think that is obsolete because the post-install.bat removes itself?

No, `99-post-install-cleanup.post` cleans up `/etc/post-install/`, while `post-install.bat` only removes itself (from the root directory).

**Comment by dscho** [comment] 2015-09-18 14:15
@nalla or @rimrul could you quickly give that PR a test? I am actually in the middle of something else I need to finish ASAP...

**Comment by nalla** [comment] 2015-09-18 14:22
```
Installer is available as C:\Users\nalla\Git-2.5.2-testing-64-bit.exe

nalla@dev MINGW64 /usr/src/build-extra/installer (mtab-location)
$ ls /c/Program\ Files/Git/
ReleaseNotes.html  bin/  cmd/  dev/  etc/  git-bash.exe*  git-cmd.exe*  mingw64/  tmp/  unins000.dat  unins000.exe*  usr/

nalla@dev MINGW64 /usr/src/build-extra/installer (mtab-location)
$ ls /c/Program\ Files/Git/etc/
DIR_COLORS        bash.bashrc      fstab  inputrc  networks       package-versions.txt  pki/     profile.d/  services  vimrc
bash.bash_logout  docx2txt.config  hosts  mtab@    nsswitch.conf  pkcs11/               profile  protocols   ssh/
```

**Comment by dscho** [comment] 2015-09-18 14:27
Woot!

**Closed** 2015-09-18 14:27 UTC
Labels: question, unclear

**Comment by picachuboom** [comment] 2015-12-01 19:30
como lo abro
?? :octocat:

**Comment by picachuboom** [comment] 2015-12-01 19:30
pls
:8ball:

**Comment by picachuboom** [comment] 2015-12-01 19:31
<(")

**Comment by picachuboom** [comment] 2015-12-01 19:31
<3
