### ISSUE TITLE
Reading from stdin in Git Bash with a .Net framework application hangs after some time

### ISSUE THREAD

**Issue by nitrovent** [git-for-windows/git#3075] opened 2021-03-03 08:46 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.30.0.windows.1
cpu: x86_64
built from commit: 18da6dbba950f8cc7b7d07057f7c30bf7cf207b6
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.804]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Running commands in Git Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I am piping the output of one .Net application to another .Net application.
The two applications can be represented as produce.exe and consume.exe with their respective C# source code.
The applications both target .Net Framework 4.7.2.
Further implementations in the consumer have been also tried (async, using StreamReaders, ...).
Note that the problem only occurs if there is a delay in the producer before writing to Stdout.

```csharp
using System;
using System.Threading;

namespace Produce
{
    class Program
    {
        static void Main(string[] args)
        {
            Thread.Sleep(100);
            Console.WriteLine("Hello World.");
        }
    }
}
```

```csharp
using System;

namespace Consume
{
    class Program
    {
        static void Main(string[] args)
        {
            var input = Console.In.ReadToEnd();
            Console.WriteLine(input);
        }
    }
}
```

Compile, then run in Git Bash:

```bash
$ ./produce.exe | ./consume.exe
```
 - What did you expect to occur after running these commands?

I am expecting the output to be `Hello World.` and both processes to terminate.

 - What actually happened instead?

Instead, there is no output and `consume.exe` hangs at `ReadToEnd()`.
This was verified by listing the running processes with `ps aux` as well as by attaching the debugger of Visual Studio to the consumer application.

Piping producer.exe's output into an application supplied with Git Bash, such as `cat` works as expected.
The other way round, piping from another application supplied with Bash into consume.exe fails:

```bash
find * /usr | ./consume.exe
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by dscho** [comment] 2021-03-03 10:45
Hi, and welcome to the Git for Windows project!

Git Bash is actually a close fork of [MSYS2](https://msys2.github.io/)'s Bash, which in turn is based on [Cygwin](https://cygwin.com/). I wonder whether you get the same hang when running this in Cygwin's Bash?

**Comment by nitrovent** [comment] 2021-03-03 11:59
> Hi, and welcome to the Git for Windows project!
> 
> Git Bash is actually a close fork of [MSYS2](https://msys2.github.io/)'s Bash, which in turn is based on [Cygwin](https://cygwin.com/). I wonder whether you get the same hang when running this in Cygwin's Bash?

Just installed Cygwin and tried in Cygwin64 Terminal.
Yes, I get the same hang. Maybe also open the issue there...

**Comment by dscho** [comment] 2021-03-03 14:08
> Just installed Cygwin and tried in Cygwin64 Terminal.
> Yes, I get the same hang.

Right, that's what I half expected

> Maybe also open the issue there...

I don't think they have a bug tracker, but a mailing list. Here are their guidelines how to report problems: https://cygwin.com/problems.html

**Comment by nitrovent** [comment] 2021-03-03 15:18
> I don't think they have a bug tracker, but a mailing list. Here are their guidelines how to report problems: https://cygwin.com/problems.html

I have now subscribed there and wrote an issue report.

**Comment by nitrovent** [comment] 2021-03-03 15:20
I also tested piping the output of an application supplied with git bash into consume.exe and it is also hanging.

```bash
find * /usr | ./consume.exe
```

or any other command taking noticable time to run.

**Comment by dscho** [comment] 2021-03-03 16:28
> 
> 
> I also tested piping the output of an application supplied with git bash into consume.exe and it is also hanging.
> 
> ```shell
> find * /usr | ./consume.exe
> ```
> 
> or any other command taking noticable time to run.

Whoa, that's odd. The `stdout` should definitely be closed in `find`'s side.

**Comment by nitrovent** [comment] 2021-03-03 18:53
> Whoa, that's odd. The `stdout` should definitely be closed in `find`'s side.

Not `find`'s fault. `consume` is hanging before `find` even finishes.
Its the time the piping is active as far as I can observe. `cat "hello world" | ./consume.exe` works fine.

**Comment by dscho** [comment] 2021-03-04 11:25
Hmm. Maybe the problem is on .NET's side? Can you verify whether that pipe works in `cmd` and in PowerShell?

**Comment by nitrovent** [comment] 2021-03-04 11:56
yes. in cmd and ps its working.

**Comment by nitrovent** [comment] 2021-03-05 13:54
There has been a first answer on the cygwin mailing list, whereas the problem is due to the pipe mode.
The author says it is by default `FILE_FLAG_OVERLAPPED` and `PIPE_TYPE_MESSAGE` and that his tests showed the pipe of the example given by me only works for `PIPE_TYPE_BYTE` and not `FILE_FLAG_OVERLAPPED` set. But he is not sure how to solve that issue.

From names of these modes that could makes sense because when piping in `cmd` the whole output is collected (not "overlapped") before it is finally shown and in bash piping multiple lines with delay inbetween from .Net into `cat` outputs them "live" as they come.

**Comment by dscho** [comment] 2022-08-24 14:15
Closing as stale.

**Closed by dscho** 2022-08-24 14:15 UTC
Labels: unclear
