### ISSUE TITLE
`fatal: Needed a single revision` when doing submodule update --remote

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#684] opened 2016-03-03 16:45 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

64-bit

```
$ git --version
git version 2.7.2.windows.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

Windows 8, 64-bit
- What options did you set as part of the installation? Or did you choose the
  defaults?

File caching is the only non-default that was changed (it is enabled)
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Default terminal selected during install
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ git submodule update --init --recursive --remote
```
- What did you expect to occur after running these commands?

All submodules updated to remote branches without error
- What actually happened instead?

Got the error message:

```
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'UI/Test/Data'
```

I set `GIT_TRACE=1` and ran the command again. Full output at the bottom.

Contents of `.gitmodules` file:

```
[submodule "ThirdParty"]
    path = ThirdParty
    url = ../third-party-2.git
    branch = master
[submodule "UI/Test/Data"]
    path = UI/Test/Data
    url = ../../ztd/ui.git
```

Note that this command was executed inside of another submodule itself. However even in the parent repo I get the same error.

Full log output with trace:

```
$ GIT_TRACE=1 git submodule update --init --recursive --remote
10:28:47.183539 git.c:561               trace: exec: 'git-submodule' 'update' '--init' '--recursive' '--remote'
10:28:47.190523 run-command.c:343       trace: run_command: 'git-submodule' 'update' '--init' '--recursive' '--remote'
10:28:48.149585 git.c:348               trace: built-in: git 'rev-parse' '--git-dir'
10:28:48.452612 git.c:348               trace: built-in: git 'rev-parse' '--git-path' 'objects'
10:28:48.705631 git.c:348               trace: built-in: git 'rev-parse' '-q' '--git-dir'
10:28:49.157642 git.c:348               trace: built-in: git 'rev-parse' '--show-prefix'
10:28:49.358693 git.c:348               trace: built-in: git 'rev-parse' '--show-toplevel'
10:28:49.582728 git.c:348               trace: built-in: git 'submodule--helper' 'list' '--prefix' ''
10:28:49.782736 git.c:348               trace: built-in: git 'submodule--helper' 'name' 'ThirdParty'
10:28:50.034748 git.c:348               trace: built-in: git 'config' 'submodule.ThirdParty.url'
10:28:50.236784 git.c:348               trace: built-in: git 'config' '-f' '.gitmodules' 'submodule.ThirdParty.update'
10:28:50.438795 git.c:348               trace: built-in: git 'submodule--helper' 'name' 'UI/Test/Data'
10:28:50.689889 git.c:348               trace: built-in: git 'config' 'submodule.UI/Test/Data.url'
10:28:50.891887 git.c:348               trace: built-in: git 'config' '-f' '.gitmodules' 'submodule.UI/Test/Data.update'
10:28:51.105919 git.c:348               trace: built-in: git 'submodule--helper' 'list' '--prefix' ''
10:28:51.306913 git.c:348               trace: built-in: git 'submodule--helper' 'name' 'ThirdParty'
10:28:51.510941 git.c:348               trace: built-in: git 'config' 'submodule.ThirdParty.url'
10:28:51.811512 git.c:348               trace: built-in: git 'config' 'submodule.ThirdParty.branch'
10:28:52.066528 git.c:348               trace: built-in: git 'config' '-f' '.gitmodules' 'submodule.ThirdParty.branch'
10:28:52.270539 git.c:348               trace: built-in: git 'config' 'submodule.ThirdParty.update'
10:28:52.616879 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:52.820892 git.c:348               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
10:28:53.072908 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:53.285476 git.c:348               trace: built-in: git 'fetch'
10:28:53.303470 run-command.c:343       trace: run_command: 'ssh' '-p' '7999' 'git@stash.tabletopmedia.com' 'git-upload-pack '\''/fe/third-party-2.git'\'''
10:28:53.735738 run-command.c:343       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
10:28:53.887745 run-command.c:343       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
10:28:54.021737 git.c:348               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
10:28:54.107789 run-command.c:343       trace: run_command: 'gc' '--auto'
10:28:54.241781 git.c:348               trace: built-in: git 'gc' '--auto'
10:28:54.535799 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:54.793837 git.c:348               trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
10:28:55.046847 git.c:348               trace: built-in: git 'config' '--get' 'branch..remote'
10:28:55.341509 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:55.544523 git.c:348               trace: built-in: git 'rev-parse' '--verify' 'origin/master'
10:28:55.796521 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:56.015535 git.c:348               trace: built-in: git 'submodule--helper' 'list' '--prefix' ''
10:28:56.231552 git.c:348               trace: built-in: git 'submodule--helper' 'list' '--prefix' ''
10:28:56.439589 git.c:348               trace: built-in: git 'submodule--helper' 'name' 'UI/Test/Data'
10:28:56.642602 git.c:348               trace: built-in: git 'config' 'submodule.UI/Test/Data.url'
10:28:56.946638 git.c:348               trace: built-in: git 'config' 'submodule.UI/Test/Data.branch'
10:28:57.198666 git.c:348               trace: built-in: git 'config' '-f' '.gitmodules' 'submodule.UI/Test/Data.branch'
10:28:57.403664 git.c:348               trace: built-in: git 'config' 'submodule.UI/Test/Data.update'
10:28:57.749505 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:57.953518 git.c:348               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
10:28:58.203550 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:58.414566 git.c:348               trace: built-in: git 'fetch'
10:28:58.424548 run-command.c:343       trace: run_command: 'ssh' '-p' '7999' 'git@stash.tabletopmedia.com' 'git-upload-pack '\''/ztd/ui.git'\'''
10:28:58.826518 run-command.c:343       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all' '--quiet'
10:28:59.044533 run-command.c:343       trace: run_command: 'rev-list' '--objects' '--stdin' '--not' '--all'
10:28:59.180560 git.c:348               trace: built-in: git 'rev-list' '--objects' '--stdin' '--not' '--all'
From ssh://stash.tabletopmedia.com:7999/ztd/ui
* branch            HEAD       -> FETCH_HEAD
10:28:59.254851 run-command.c:343       trace: run_command: 'gc' '--auto'
10:28:59.390859 git.c:348               trace: built-in: git 'gc' '--auto'
10:28:59.683885 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:28:59.945886 git.c:348               trace: built-in: git 'symbolic-ref' '-q' 'HEAD'
10:29:00.196605 git.c:348               trace: built-in: git 'config' '--get' 'branch..remote'
10:29:00.492604 git.c:348               trace: built-in: git 'rev-parse' '--local-env-vars'
10:29:00.696749 git.c:348               trace: built-in: git 'rev-parse' '--verify' 'origin/master'
fatal: Needed a single revision
10:29:01.100523 git.c:561               trace: exec: 'git-sh-i18n--envsubst' '--variables' 'Unable to find current origin/master revision in submodule path '\''$sm_path'\'''
10:29:01.108540 run-command.c:343       trace: run_command: 'git-sh-i18n--envsubst' '--variables' 'Unable to find current origin/master revision in submodule path '\''$sm_path'\'''
10:29:01.417574 git.c:561               trace: exec: 'git-sh-i18n--envsubst' 'Unable to find current origin/master revision in submodule path '\''$sm_path'\'''
10:29:01.424563 run-command.c:343       trace: run_command: 'git-sh-i18n--envsubst' 'Unable to find current origin/master revision in submodule path '\''$sm_path'\'''
Unable to find current origin/master revision in submodule path 'UI/Test/Data'
```

**Comment by dscho** [comment] 2016-04-02 12:11
> $ git submodule update --init --recursive --remote

This is no MCVE by any standard.

The entire report smells as if the problem is 1) specific to a certain set of repositories, and 2) is not specific to Windows (and therefore better reported to the [Git mailing List](mailto:git@vger.kernel.org).

**Comment by dscho** [comment] 2017-02-21 23:38
Closing due to lack of any reaction.

**Closed by dscho** 2017-02-21 23:38 UTC

**Comment by ohhmm** [comment] 2020-10-04 00:13
In case if someone else may need it, I had wrong branch path specified in .gitmodules.
