### ISSUE TITLE
CI failure on the Git `win build` for `xterm-256color`

### ISSUE THREAD

**Issue by PhilipOakley** [git-for-windows/git#3940] opened 2022-07-08 16:55 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

[The CI run..](https://github.com/PhilipOakley/git/runs/7254179201?check_suite_focus=true)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.0.windows.1
cpu: x86_64
built from commit: 989c3a6832b035f6124b0a23da9c0f8f18afa550
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1766]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Don't think so. It's a simple series of short documentation changes. They have been rebased onto `git/main` in readiness for a Gitgitgadget submission.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash, and pushed via Git Gui to `my` remote

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push #
```
 - What did you expect to occur after running these commands?

Email confirming CI run successful ...

I suspect this isn't caused by my code, rather some slight mishap in the extensive CI setup around the `xterm-256color`
`tput: unknown terminal "xterm-256color"` [line 715](https://github.com/PhilipOakley/git/runs/7254179201?check_suite_focus=true#step:4:718)

 - What actually happened instead?

email: [PhilipOakley/git] Run failed: CI - Glossary_terms (8fefb49)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Probably not specific to the repository, but it could be related to whether the project's CI in my repo matches expectation: [PhilipOakley/git](https://github.com/PhilipOakley/git)

**Comment by dscho** [comment] 2022-07-09 00:37
> I suspect this isn't caused by my code, rather some slight mishap in the extensive CI setup around the `xterm-256color`
> `tput: unknown terminal "xterm-256color"` [line 715](https://github.com/PhilipOakley/git/runs/7254179201?check_suite_focus=true#step:4:718)

This is actually a red herring. The problem is not `TERM` at all. The problem is that `.tmp` folder.

https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/411 should fix this.

A work-around to get the CI/PR build to pass is simply to re-run the failed jobs; The `setup-git-for-windows-sdk` will then find the cached version of the folder, which does not leave any `.tmp` folder around (unlike the runs that do not find a valid cache and therefore have to do the partial clone/parallel checkout dance).

**Comment by dscho** [comment] 2022-07-09 01:00
> [git-for-windows/setup-git-for-windows-sdk#411](https://github.com/git-for-windows/setup-git-for-windows-sdk/pull/411) should fix this.

And I just merged it, tagged a new version and published it.

**Closed as completed by dscho** 2022-07-09 01:00 UTC

**Comment by PhilipOakley** [comment] 2022-07-09 06:59
Many thanks. 😃
