### ISSUE TITLE
git svn rebase fail since 2.33.0.2

### ISSUE THREAD

**Issue by caiqichang** [git-for-windows/git#3393] opened 2021-08-25 14:16 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

![1](https://user-images.githubusercontent.com/20108732/130807064-414cfa19-3c66-4a80-baee-8a9619777910.png)

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19043.1165]

```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

no
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn rebase
```
 - What did you expect to occur after running these commands?

update repository

 - What actually happened instead?

no

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

no

**Comment by caiqichang** [comment] 2021-08-25 14:25
it work well in version 2.32.0.1

**Comment by rimrul** [comment] 2021-08-25 14:32
Duplicate of #3392.

**Comment by dscho** [comment] 2021-08-25 15:01
>     * I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

Please be more diligent next time 😄

**Closed by dscho** 2021-08-25 15:01 UTC
Labels: duplicate
