### ISSUE TITLE
bash check `if [-d "directory_name"]` fails

### ISSUE THREAD

**Issue by joelanman** [git-for-windows/git#924] opened 2016-10-21 16:09 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.1.windows.1
sizeof-long: 4
machine: x86_64
```
- Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]

```
- What options did you set as part of the installation? Or did you choose the
  defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled

```
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

don't think so
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
if [ -d \"node_modules\" ]; then gulp; else echo 'node_modules is missing - try running npm install' ; fi
```
- What did you expect to occur after running these commands?

either gulp running, or the error message above
- What actually happened instead?

`-d was unexpected at this time`
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

https://github.com/alphagov/govuk_prototype_kit/issues/300

**Comment by dscho** [comment] 2016-11-01 17:33
I cannot reproduce here. In a plain, freshly started Git Bash:

```sh
me@work MINGW64 ~
$ if [ -d \"node_modules\" ]; then gulp; else echo 'node_modules is missing - try running npm install' ; fi
node_modules is missing - try running npm install
```

I also think that you may want to lose the backslashes in front of the quotes. Unless, that is, you are passing this from node.js to `bash.exe`?

**Comment by joelanman** [comment] 2016-11-02 09:45
@dscho thanks for looking into this. Oops sorry yes the backslashes are because this was copied from package.json.

Strange that we get different results - are you on Windows 10 too? Just to note, this is no longer high priority for us as we've switched to another approach.

**Comment by dscho** [comment] 2016-11-02 15:26
> Strange that we get different results - are you on Windows 10 too?

Yep, I am on Windows 10. I guess the difference is that I type this directly into the Git Bash window?

**Comment by joelanman** [comment] 2016-11-02 16:25
pretty sure I also tried it directly in git bash, unfortunately it was in a virtual machine which I've now deleted

**Comment by dscho** [comment] 2016-11-03 08:10
Okay, let's close this for now. We'll just reopen it if we know how to reproduce the problem, okay?

**Closed by dscho** 2016-11-03 08:10 UTC

**Comment by joelanman** [comment] 2016-11-03 11:00
sure no problem!
