### ISSUE TITLE
Cygwin warning: Couldn't compute FAST_CWD pointer.

### ISSUE THREAD

**Issue by dumbledad** [git-for-windows/git#1029] opened 2017-01-10 11:10 UTC
I'm running 2.11.0.windows.1 64bit, installed with the defaults (apart from line endings, which I leave untouched).

I’m getting a Cygwin warning thrown twice for typical commands. For example:

timregan@timreganxps15 MINGW64 ~/Source/Zanzibar/Software (Task106-SQL)
$ git push --force
Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html

Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html

Counting objects: 6, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (6/6), 1.12 KiB | 0 bytes/s, done.
Total 6 (delta 1), reused 4 (delta 0)
remote: Analyzing objects... (6/6) (501 ms)
remote: Storing packfile... done (85 ms)
remote: Storing index... done (119 ms)
To https://playco.visualstudio.com/Zanzibar/_git/Software
+ d060e6c...9853145 Task106-SQL -> Task106-SQL (forced update)

I get the same error in Git bash, where the Cygwin version is 2.6.0(0.304/5/3), and in Cygwin, where the version is 2.6.1(0.305/5/3).

This may not be a Git nor Cygwin problem but a Windows' problem since I am on a pre-release version of Windows 10 (15007.rs_prerelease.170107-1846) but I thought you’d want it reported anyway.

**Comment by whoisj** [comment] 2017-01-10 15:29
Thanks @dumbledad, we've seen this issue too and I believe @dscho is already looking at a potential fix.

**Comment by NullSoldier** [comment] 2017-01-11 19:48
Thanks, I'm running into it as well.
I wish Github had a better way to say I need this besides reactions.

**Comment by yyjdelete** [comment] 2017-01-12 01:22
Seems already fixed by git-for-windows/build-extra@3cf0687 and git-for-windows/msys2-runtime@5fe6d81

**Comment by dscho** [comment] 2017-01-12 11:41
Yes, and the patch was even accepted into Cygwin already.

I hope to be able to publish another prerelease tomorrow that will include the fix.

**Comment by dscho** [comment] 2017-01-13 17:41
As pointed out earlier, this has been fixed, and the brand-new v2.11.0(2) comes with the fix.

**Closed by dscho** 2017-01-13 17:41 UTC

**Comment by junyuan-z** [comment] 2021-05-18 20:14
i am running into this problem on the latest windows machine with preview enabled:

```
Installed RAM	10.0 GB
Device ID	18707EA1-3ABA-4FAF-9DC4-B0AFD71C9DB8
Product ID	00330-80000-00000-AA567
System type	64-bit operating system, ARM-based processor
Pen and touch	No pen or touch input is available for this display


Edition	Windows 10 Pro
Version	Dev
Installed on	‎5/‎18/‎2021
OS build	21354.1
Experience	Windows 10 Feature Experience Pack 321.7601.0.3
```

**Comment by dscho** [comment] 2021-05-18 21:58
> i am running into this problem on the latest windows machine with preview enabled:
> 
> ```
> Installed RAM	10.0 GB
> Device ID	18707EA1-3ABA-4FAF-9DC4-B0AFD71C9DB8
> Product ID	00330-80000-00000-AA567
> System type	64-bit operating system, ARM-based processor
> Pen and touch	No pen or touch input is available for this display
> 
> 
> Edition	Windows 10 Pro
> Version	Dev
> Installed on	‎5/‎18/‎2021
> OS build	21354.1
> Experience	Windows 10 Feature Experience Pack 321.7601.0.3
> ``` 
> 
> i am using the vhds from https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewARM64

@junyuan-z Feel free to try extending https://github.com/git-for-windows/msys2-runtime/commit/5fe6d81012e97a348608511450f6a63750c906b6 even further (if you open a PR, it will build the MSYS2 runtime as build artifact so you can test).

**Comment by dscho** [comment] 2021-05-19 12:08
For completeness: the PR is here: https://github.com/git-for-windows/msys2-runtime/pull/31

**Comment by dscho** [comment] 2021-05-21 09:31
> System type	64-bit operating system, ARM-based processor

@junyuan-z I just saw that there was a specific bug fix for ARM64: https://github.com/git-for-windows/git/issues/3231

Could you try cherry-picking both of those commits and see whether it works for you, then?

**Comment by junyuan-z** [comment] 2021-05-21 15:42
OK, i have some time today. I will try this today.

**Comment by junyuan-z** [comment] 2021-05-21 18:41
@dscho i got a build ready just wondering how can i test this properly? should i just drop this in my git installer directory?

**Comment by dscho** [comment] 2021-05-21 19:23
I'd just replace the `msys-2.0.dll` file in `usr\bin`...

**Comment by junyuan-z** [comment] 2021-05-21 21:56
hmm, i can't reproduce this issue on my local machine anymore. the git install i am using is `2.31.1.1`. Is there a new release in the last a few days?

**Comment by dscho** [comment] 2021-05-22 06:04
No... The MSYS2 runtime has been unchanged in the Git for Windows project for quite a while now.

Unless you're actually following MSYS2's updates? They indeed took that fix.
