### ISSUE TITLE
Windows 10 Latest Release 2.42.0 GitBash and GitCMD not working

### ISSUE THREAD

**Issue by jtrites** [git-for-windows/git#4633] opened 2023-10-14 22:40 UTC
Git Tech Support,

Yesterday, I installed (upgraded) Git 2.42.0 for my Win 10 Pro laptop.  I tried to run both a GitBash and a GitCMD terminal window from the Start Menu by running as Administrator.   Both came up with the User Account Control popup for Git.  When I clicked Yes, neither opened a terminal window. 

The Git Bash and GitCMD shortcut Icon properties from the Start menu are configured Start in:  %HOMEDRIVE%%HOMEPATH%

I think this should have been configured by your installer in my Registry Editor (But Where? and How?)

Any idea why?  Your help is greatly appreciated.

John Trites

**Comment by dscho** [comment] 2023-10-17 08:54
Not sure what this is all about, as pretty much all the details are missing. As to your question:

> The Git Bash and GitCMD shortcut Icon properties from the Start menu are configured Start in: %HOMEDRIVE%%HOMEPATH%
> 
> I think this should have been configured by your installer in my Registry Editor (But Where? and How?)

It is configured in the installer, via https://github.com/git-for-windows/build-extra/blob/63e0e4a383c736ff086697c5b6c13323a7d861bd/installer/install.iss#L146-L147.

**Comment by camilonore** [comment] 2023-10-19 02:40
Hi, today I had the same issue. If you haven't been able to fix it, this could help you. When you go to the properties of the shortcut icon, you will see something like this in the destination: `"C:\Program Files\Git\git-bash.exe" --cd-to-home`. If you remove the `--cd-to-home` flag and try opening Git Bash again, does it open the bash? If it does, you probably have the same error in the path of your home directory as I did.

I solved this issue by going to my Windows environment variables and correcting the home path to my current home path, which should be something like this: `C:\Users\$USERNAME\AppData\Roaming\SPB_Data`. I hope this helps you, and I'm open to any suggestions and corrections.

**Comment by rustyduncan** [comment] 2023-10-29 14:34
I don't think this will solve everyone's problem, but it solved mine: [Mintty: StatusLine option causes msys2 to fail #3746 ](https://github.com/msys2/MSYS2-packages/issues/3746). In my case, I recently enabled the **Status Line** option and then GitBash would exit before displaying its GUI. After editing ```%USERPROFILE%\.minttyrc``` and setting **StatusLine** to 'no' (or just deleting that line), GitBash would open again.

**Comment by dscho** [comment] 2023-11-03 08:10
> I tried to run both a GitBash and a GitCMD terminal window from the Start Menu by running as Administrator. Both came up with the User Account Control popup for Git. When I clicked Yes, neither opened a terminal window.

FWIW I cannot reproduce this, and without further details I cannot even understand what the bug is, so I will close this ticket.

If you provide enough details, I can always reopen the ticket.

**Closed by dscho** 2023-11-03 08:10 UTC
Labels: unclear
