### ISSUE TITLE
export PATH to subshells doesn't work anymore since 2.11

### ISSUE THREAD

**Issue by aaron-kunde** [git-for-windows/git#1041] opened 2017-01-28 10:21 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Windows 10 Enterprise 64bit
 - Git Version since 2.11.0
```
$ git --version --build-options
```
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64

git version 2.11.0.windows.3
built from commit: e11df2efb3072fe73153442589129d2eb8d9ea02
sizeof-long: 4
machine: x86_64

git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
```
Microsoft Windows [Version 10.0.10586]

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

```
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

My default path as set in the environment
```
>echo %PATH%
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I usually run Bash from CMD and Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

I wrote a little test script (test.sh)
```
#!/bin/sh

export MY_VAR="Test"
export PATH="XXX:$PATH"

exec "$BASH" --login -i
```
and executed it from Bash and CMD like
```
$ ./test.sh
```
```
> "c:\Program Files\Git\bin\bash.exe" --login -i test.sh
```
This opens a subshell in which I expected the variables PATH and MY_VAR exported:
``` $ echo $MY_VAR```
Test

```$ echo $PATH```
at least somehing like

XXX:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0/

or

XXX:/c/Users/kunde/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/kunde/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/usr/bin/vendor_perl:/usr/bin/core_perl

in Version 2.10.2 I get (strangely enough)

/c/Users/kunde/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:**XXX**:/c/Users/kunde/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/kunde/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/bin/vendor_perl:/usr/bin/core_perl

 - What actually happened instead?
The MY_VAR was exported as expected, but the PATH was not updated

```$ echo $PATH```
/c/Users/kunde/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/mingw64/bin:/usr/bin:/c/Users/kunde/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/usr/bin/vendor_perl:/usr/bin/core_perl

**Comment by shiftkey** [comment] 2017-01-28 11:51
@aaron-kunde can you test with the tagged release [2.11.0.windows.3](https://github.com/git-for-windows/git/releases/tag/v2.11.0.windows.3)? And is `v2.10.2.windows.1` a build which doesn't suffer from the issue (it's not clear from the issue details whether it's working or not)?

**Comment by aaron-kunde** [comment] 2017-01-29 11:00
I tested the followin versions:
- 2.11.0.windows.3: Didn't work
- 2.110,windows.1: Didn't work
- 2.10.2.windows.1: Did work
- 2.9.3.windows.2: Did work

**Comment by dscho** [comment] 2017-01-30 12:55
This is actually by design (not ours, but MSYS2's): try inserting an `unset ORIGINAL_PATH` somewhere before the `exec` line.

Please also note that this project is Git for Windows, i.e. different from "We Address All Your Shell Scripting Needs On Windows" ;-)

**Comment by dscho** [comment] 2017-02-20 21:47
> try inserting an unset ORIGINAL_PATH somewhere before the exec line.

I hope you did that? It would be very nice to hear back, too... :smile:

**Comment by aaron-kunde** [comment] 2017-02-22 19:47
I can totally live with the statement, that this behaviour is intented. I recognized the "problem", because other programs like DockerToolbox relied on this behaviour and didn't work with the current Git version.

**Comment by dscho** [comment] 2017-02-23 16:56
> I can totally live with the statement

So you did try it? And it did work? Or what?

> I recognized the "problem", because other programs like DockerToolbox relied on this behaviour and didn't work with the current Git version.

I *think* that we can actually live without the `ORIGINAL_PATH` handling in Git for Windows. It is the MSYS2 project that introduced it. I'd have to dig through some commit history to determine what their intention was, and whether or not we need it here, too.

OTOH maybe you have a couple of cycles to spare? I.e. start from here: https://github.com/Alexpux/MSYS2-packages/search?utf8=%E2%9C%93&q=ORIGINAL_PATH and then click the `Blame` button and then follow the links to the commits that added the `ORIGINAL_PATH` lines.

It would be very helpful if you could help me here.

**Comment by aaron-kunde** [comment] 2017-02-23 20:15
I can totally live with the statement
>
> So you did try it? And it did work? Or what?
>
I'm sorry, I didn't have the time to dig into it and try it. I just 
switched back to version 2.10
>
>     I recognized the "problem", because other programs like
>     DockerToolbox relied on this behaviour and didn't work with the
>     current Git version.
>
> I /think/ that we can actually live without the |ORIGINAL_PATH| 
> handling in Git for Windows. It is the MSYS2 project that introduced 
> it. I'd have to dig through some commit history to determine what 
> their intention was, and whether or not we need it here, too.
>
> OTOH maybe you have a couple of cycles to spare? I.e. start from here: 
> https://github.com/Alexpux/MSYS2-packages/search?utf8=%E2%9C%93&q=ORIGINAL_PATH 
> and then click the |Blame| button and then follow the links to the 
> commits that added the |ORIGINAL_PATH| lines.
>
> It would be very helpful if you could help me here.
>
By taking a quick look, at 
https://github.com/Alexpux/MSYS2-packages/commit/7fd131dde0be023ac0516cbc6bed1eed6f77295c

I see, that they extended an on/off-switch to a 3-value option. But I'll 
have to play a little around with this, to examine it further

**Comment by dscho** [comment] 2017-02-24 13:44
> By taking a quick look, at Alexpux/MSYS2-packages@7fd131d I see, that they extended an on/off-switch to a 3-value option. But I'll have to play a little around with this, to examine it further

Here is an idea that should be really easy to test on your side, and relatively easy for me to integrate into the `git-extra` package: could you simply add the line `unset ORIGINAL_PATH` at the end of `etc/profile` in your installation? After that it should work.

And if you test that, and if that works, I will make the change and your bug will be fixed for real.

**Comment by dscho** [comment] 2017-04-04 21:38
As of Git for Windows v2.12.2, I fixed the MSYS2 runtime to handle `ORIGINAL_PATH` in the same way as `PATH`. That should fix your issue, too.

**Closed by dscho** 2017-04-04 21:38 UTC
Labels: help wanted, question
