### ISSUE TITLE
Git is scanning all work directory during commit even with status.showUntrackedFiles=no

### ISSUE THREAD

**Issue by kovlerm** [git-for-windows/git#1642] opened 2018-04-20 21:15 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.3.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Disabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git.exe commit --no-verify --no-post-rewrite --allow-empty --untracked-files=no --no-gpg-sign -m "XXXXX"
```
 - What did you expect to occur after running these commands?

I am migrating very large ClearCase repository to Git. Due to poor performance of ClearCase I am trying minimize operations on ClearCase file system.
I am staging all files before commit, and use  --untracked-files=no in  commit command or/and  status.showUntrackedFiles=no in config. I expect that git would not scan entire work directory... 

 - What actually happened instead?

However, I see in process monitor that git scans entire work directory during commit.
Is this bug or I miss some another option for disabling this?
 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

**Comment by kovlerm** [comment] 2018-04-20 23:29
I added core.ignoreStat=True - same result...

**Comment by kovlerm** [comment] 2018-04-23 15:26
Thanks for the answer. I added --no-status to commit command, and I have lowercase in core.ignoreStat=true (it was just type in original message). I also added core.untrackedCache=true. Unfortunately, it did not improve performance. Git keeps o scanning entire directory on every commit. I am still using 2.16.3 version of git. Is there available binaries/installation for 2.17.0?

**Comment by dscho** [comment] 2018-04-23 20:10
> Is there available binaries/installation for 2.17.0 for Windows?

Yes, of course. The usual links will get you there: https://gitforwindows.org/, https://git-scm.com/, Google "Git for Windows" 😄

**Comment by kovlerm** [comment] 2018-04-24 00:16
Thanks a lot. I am upgraded now to 2.17.0. I see small performance improvements, but ... main problem is still there. Commits scans all folders in working directory despite all my effort...

**Comment by dscho** [comment] 2018-04-24 12:57
> If the problem was occurring with a specific repository, can you provide the
> URL to that repository to help us with testing?

I fear that I'll need some *easy* way to reproduce this, i.e. if you can find a public repository for which you see this behavior, I can then quickly verify whether I can reproduce the problem.

If it is a regression (i.e. if you know about a known-good Git for Windows version), you could also try to bisect this: first, [install the Git for Windows SDK](https://gitforwindows.org/#download-sdk) (caveat: the installer will clone about half a gigabyte), then call `git-bash.exe` in the cloned worktree and from there first initialize the git-for-windows/git clone: `sdk cd git`.

Then, you can bisect this as follows:

- `git bisect start`
- `git bisect bad HEAD`
- `git bisect good <version>` where <version> is something like v2.14.0.windows.1

Now, test that revision:

```sh
make -j15 install
git -C /path/to/your/repository commit --no-status
```

Depending on the outcome, call `git bisect bad`, `git bisect good` or `git bisect skip`. Lather, rinse, repeat.

**Comment by kovlerm** [comment] 2018-04-25 16:05
I do not have public repository, but as far as I understand you can reproduce this on any repository. As I mentioned before it is not big deal on local drive, but when you are working with slow FS as ClearCase MVFS it becomes huge issue. 
As far as reproducing this, stage few files by "git add" then run git commit (I tried all possible options) and watch all folders git commit opens. I am using Microsoft Process Monitor (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) . I expected to see git opens only staged files and folders, but in fact I see that scans entire working tree.

**Comment by dscho** [comment] 2018-04-26 09:56
> you can reproduce this on any repository

No I can't because I do not have enough time to start debugging if there is a chance that I cannot reproduce the behavior. Please make it easier for me to help you. Otherwise I simply cannot.

**Comment by kovlerm** [comment] 2018-04-26 22:31
Fair enough. I can't push to github (our servers do not have internet access), but here is step-by-step test case:
1. I created following directory structure:
 A/B/D/E/e.c
 A/B/b.c
 A/C/c.c
 A/a.c
Content of all files is word "test".
2. Then I executed following commands:
> c:\gitstore\Bug>**git init**
> Initialized empty Git repository in c:/gitstore/Bug/.git/
> c:\gitstore\Bug>**git update-index --index-version 4**
> c:\gitstore\Bug>**git config gc.auto 0**
> c:\gitstore\Bug>**git config core.untrackedCache true**
> c:\gitstore\Bug>**git add --all**
> c:\gitstore\Bug>**git commit -m "Initial version"**
> [master (root-commit) f25344b] Initial version
 > 4 files changed, 4 insertions(+)
 > create mode 100644 A/B/D/E/e.c
 > create mode 100644 A/B/b.c
 > create mode 100644 A/C/c.c
 > create mode 100644 A/a.c
> c:\gitstore\Bug>**git add A/a.c**
> c:\gitstore\Bug>**git commit -m "change in a.c pre-staged no options"**
> [master d82e32a] change in a.c pre-staged no options
>  1 file changed, 1 insertion(+), 1 deletion(-)
> c:\gitstore\Bug>**git add A/a.c**
> c:\gitstore\Bug>**git commit --no-status --no-verify --no-post-rewrite --allow-empty --untracked-files=no --no-gpg-sign -m "change in a.c pre-staged with extra options"**
> [master 2b08927] change in a.c pre-staged with extra options
>  1 file changed, 1 insertion(+), 1 deletion(-)

During both commits I monitor file operations with [MS process monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon). Here is the result for first
![cmt1](https://user-images.githubusercontent.com/23586755/39334935-c11f0068-4965-11e8-963d-711ac1a36d13.jpg)
and here is for second one with --no-status option:
![cmt2](https://user-images.githubusercontent.com/23586755/39334959-da6f95fa-4965-11e8-9845-b49b3ab9000f.jpg)

As you can see in both cases a.c is staged for commit and in both cases commits scans entire working directory. Defense rests :)

**Comment by drizzd** [comment] 2018-05-01 19:39
I confirm your observation. I tracked the source of these file accesses back to `refresh_cache_or_die` in `prepare_index` (see stack trace below). I do not understand exactly why the index needs to be refreshed here. A comment above says "We still need to refresh the index here." But it might not be needed here, if we do not show the status, do not run any hooks, or anything else that might expect a refreshed index afterwards.

In any case, the file accesses can be avoided by using low-level commands instead of git commit:

```
current=HEAD
current=$(git commit-tree -p $current $(git write-tree))
current=$(git commit-tree -p $current $(git write-tree))
...
```

This will keep creating commits based on the current index, tracking the latest commit in `$current`. I confirmed with procmon that this will not access the disk.

### Stack trace

```gdb
(gdb) r
Starting program: C:\Users\Ricl\src\git\git.exe "--exec-path=C:/Users/Ricl/src/git-forwin-1642/../git" commit -m two --allow-empty --no-status
[...]
(gdb) f
#0  refresh_cache_ent (istate=0x712ca0 <the_index>, ce=0x544bb68, options=16,
    err=0x11ef850, changed_ret=0x11ef854) at read-cache.c:1284
1284            if (lstat(ce->name, &st) < 0) {
(gdb) bt
#0  refresh_cache_ent (istate=0x712ca0 <the_index>, ce=0x544bb68, options=16,
    err=0x11ef850, changed_ret=0x11ef854) at read-cache.c:1284
#1  0x00000000005611e3 in refresh_index (istate=0x712ca0 <the_index>,
    flags=36, pathspec=0x0, seen=0x0, header_msg=0x0) at read-cache.c:1413
#2  0x0000000000421f6b in refresh_cache_or_die (refresh_flags=4)
    at builtin/commit.c:297
#3  0x00000000004222fe in prepare_index (argc=0, argv=0x3951510, prefix=0x0,
    current_head=0x544bbf8, is_status=0) at builtin/commit.c:388
#4  0x000000000042562c in cmd_commit (argc=0, argv=0x3951510, prefix=0x0)
    at builtin/commit.c:1520
#5  0x000000000040285a in run_builtin (p=0x62f238 <commands+504>, argc=5,
    argv=0x3951510) at git.c:346
#6  0x0000000000402bd5 in handle_builtin (argc=5, argv=0x3951510) at git.c:554
#7  0x0000000000402dd3 in run_argv (argcp=0x11efe00, argv=0x11efda8)
    at git.c:606
#8  0x00000000004030d1 in cmd_main (argc=5, argv=0x3951510) at git.c:708
#9  0x00000000004a4b33 in mingw_main (argc=7, argv=0x3951500)
    at common-main.c:43
#10 0x00000000004a4aec in main (argc=7, argv=0x5440498) at common-main.c:26
```

**Comment by dscho** [comment] 2019-10-13 23:02
I'll close this both due to lack of conversation, and because I suspect that Git does this by design. In any case, the code in question seems _far_ from Windows-specific, so if there should still be a problem it would be best raised with the Git project (see https://git-scm.com/community for recommended ways to report bugs).

**Closed by dscho** 2019-10-13 23:02 UTC
Labels: question
