### ISSUE TITLE
[Feature Request] Automatically correcting case during cd

### ISSUE THREAD

**Issue by jamesqo** [git-for-windows/git#579] opened 2015-12-21 00:04 UTC
If you open up CMD and cd to a directory with an incorrectly-capitalized name, it will autocorrect it for you:

``` cmd
C:\Users\James>cd downloads

C:\Users\James\Downloads>
```

Could we also implement this functionality in the Git Bash shell? I found a solution [here](http://stackoverflow.com/a/4763137/4077294) for getting the case-sensitive path name, I just don't know where to find the code for cd.

**Comment by r2evans** [comment] 2015-12-21 18:40
For me, it works almost the same (albeit it displays the mis-typed case):

```bash
r2@myhost MINGW32 ~
$ ls -ld D*
drwxr-xr-x 1 r2 197121 0 Dec 21 09:46 Desktop
drwxr-xr-x 1 r2 197121 0 Dec 15 10:33 Documents
drwxr-xr-x 1 r2 197121 0 Dec 21 09:58 Downloads

r2@myhost MINGW32 ~
$ cd DoWnLoAdS

r2@myhost MINGW32 ~/DoWnLoAdS
$
```

This also works with tab-completion out-of-the-box:

```bash
r2@myhostMINGW32 ~
$ cd DOWN<TAB>
$ cd Downloads/
```

For the record, I'm running bash 4.3.42(4)-release on git-for-windows SDK 1.0.1.

Regardless, `cd` is not a function in `git-for-windows` or `git-bash`, it is a component of `bash`:

```bash
r2@myhost MINGW32 ~/DoWnLoAdS
$ type cd
cd is a shell builtin
```

So your solution might need to be redirected there. Some [related](http://unix.stackexchange.com/questions/60162/how-to-make-cd-arguments-case-insensitive) [questions](http://superuser.com/questions/527559/how-to-make-cd-arguments-case-insensitive) have mentioned the use of `set completion-ignore-case on`, but I have not found it necessary.

(Personally, I have some differently-nested directories that are for various reasons different only by case, and when used with `CDPATH`, I've had some frustrating moments. I'd prefer to go with case-sensitive but have not gotten it working yet. I believe it's at least partially due to the underlying NTFS.)

**Comment by dscho** [comment] 2015-12-30 15:23
> Could we also implement this functionality in the Git Bash shell? [...] I just don't know where to find the code for cd.

@jamesqo the `cd` command is part of the Bash. So here is how you can have a go at fixing this:

1. install the [SDK](https://git-for-windows.github.io/#download-sdk)
2. rebuild the Bash package as described [here](https://github.com/git-for-windows/git/wiki/Package-management#rebuild-packages)
3. initialize a Git repository for the Bash sources:

 ```sh
 cd /usr/src/MSYS2-packages/bash/src/bash-4.3
 git init
 /usr/src/git/contrib/fast-import/import-tars.perl ../../bash-4.3.tar.gz
 git reset import-tars
 ```
4. patch the `builtins/cd.def` file (probably the `change_to_directory()` function) accordingly.
5. rebuild the bash package and verify that your patch works as intended (you can rebuild with `makepkg --noextract --noprepare` so that your changes are not overwritten)
6. once everything works, export the patch via `git format-patch --start-number=8 -1` to `/usr/src/MSYS2-packages/bash/` and modify the `PKGBUILD` file in the same directory similar to [this commit](https://github.com/dscho/MSYS2-packages/commit/e44d4ff945e02843d0d521fcb8e1f1d9f6df906b) (you can use `makepkg --geninteg` to generate the MD5 sums)
7. Commit this change and open a Pull Request with our MSYS2-packages project

For extra bonus points, you could rebase the commit to [upstream](https://github.com/Alexpux/MSYS2-packages) open the Pull Request there instead of detouring via Git for Windows' forked MSYS2-packages.

**Comment by jamesqo** [comment] 2015-12-31 23:58
@dscho Thanks for the support! I finally managed to get the bash sources after an hour (had to skip building git), and I've found the `change_to_directory` function, but I'm not quite sure what to do now. Do I just put a Windows API function like `GetLongPathNameA` straight in the middle of the function? Unfortunately I don't have that much experience in C, so I'm a bit lost.

**Comment by dscho** [comment] 2016-01-01 14:53
> Do I just put a Windows API function like GetLongPathNameA straight in the middle of the function?

I think that might work, but you might have to jump through the `GetLongPathNameW()`/`wcstombs()` hoop to catch even non-ASCII names correctly.

**Comment by dscho** [comment] 2017-02-21 23:47
While it may still be nice to have this, it does not seem that we have any volunteer to see this through. That, combined with the fact that tab-completing the directory will fix the case, is enough for me to close this ticket for now.

**Closed by dscho** 2017-02-21 23:47 UTC
Labels: enhancement, help wanted, sdk-packages
