### ISSUE TITLE
problem to link github and visual studio code

### ISSUE THREAD

**Issue by usha-ui** [git-for-windows/git#3029] opened 2021-02-06 00:57 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** $ git --version --build-options
git version 2.30.0.windows.2
cpu: i686
built from commit: f8cbc844b81bf6b9e72178bbe891a86c8bf5e9e7
sizeof-long: 4
sizeof-size_t: 4
shell-path: /bin/sh
 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

**Microsoft Windows [Version 6.1.7600] **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** > type "C:\Program Files\Git\etc\install-options.txt" **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** whenever i am opening vsc and after committing  after pushing code to github ,
2) in visual studio code i am not getting in command paltette git: add remote command it is showing = no matching command --
3) how to fix it.
**

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** bash**

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

** insert here **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by usha-ui** [comment] 2021-02-06 00:58
sir is there any solution to this problem please let me know, YES/NO

**Comment by rimrul** [comment] 2021-02-06 08:46
Not a Git for Windows issue. Also a duplicate of #3012

**Closed by rimrul** 2021-02-06 08:46 UTC
Labels: duplicate, invalid
