### ISSUE TITLE
fatal: Unable to create 'C:/Users/admin/.git/index.lock': File exists.

### ISSUE THREAD

**Issue by DustinJWalker** [git-for-windows/git#1134] opened 2017-04-12 14:13 UTC
- [x ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** insert your machine's response here **
``` 2.12.2.windows.2


 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** insert your machine's response here **
```
Microsoft Windows [Version 10.0.14393]


 - What options did you set as part of the installation? Or did you choose the
   defaults?
defaults
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** insert your machine's response here **
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** insert your response here **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** insert your response here **
Bash
 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** insert your commands here **
```git add .

 - What did you expect to occur after running these commands?

** insert here **
files to be added
 - What actually happened instead?

** insert here **
fatal: Unable to create 'C:/Users/admin/.git/index.lock': File exists.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by whoisj** [comment] 2017-04-12 17:13
Sometimes Git crashes or is killed by the user (see ctrl+C) and an index.lock file gets left behind.

Are there no more git.exe process running? The simply delete the file at `C:/Users/admin/.git/index.lock` and carry on.

**Comment by ttrunck** [comment] 2017-04-12 17:16
I have the same issue but only intermittently using either `git stash` or `git rebase`.
If I go to the folder after the command fails the file `index.lock` does **not** exist.

It's looks like the command is creating that file deleting it but not fast enough so later in the execution it git believe that this file already exists.
When this happens I usually have only one terminal running git but maybe some editors are also calling git (VS or VSCode)

I'm using `git version 2.12.2.windows.1` on `Microsoft Windows [Version 10.0.14393]`

**Comment by ttrunck** [comment] 2017-04-12 18:04
For what it's worth, I had the issue quite consistently and deactivating fscache solved the issue (for now)

`git config core.fscache false`

**Comment by whoisj** [comment] 2017-04-12 19:16
> For what it's worth, I had the issue quite consistently and deactivating fscache solved the issue (for now)

Very odd as `fscache` is in-memory only. No idea how that would impact `index.lock` other than make everything slow, and thus avoid racy conditions.

**Comment by shiftkey** [comment] 2017-04-22 05:34
> When this happens I usually have only one terminal running git but maybe some editors are also calling git (VS or VSCode)

I'd look at these other tools to see if they're touching the index at the same time as you're performing another command. I think that's the most likely answer for what's happening here.

**Comment by shiftkey** [comment] 2017-04-22 05:35
Closing this out as expected behaviour of Git.

**Closed by shiftkey** 2017-04-22 05:35 UTC
