### ISSUE TITLE
Handling of ANSI control sequences to modify the screen of the shell don't seem to be handled anymore

### ISSUE THREAD

**Issue by martijnhoekstra** [git-for-windows/git#2661] opened 2020-06-03 15:07 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64 Bit

```
$ git --version --build-options

** git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8 **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

** Microsoft Windows [Version 10.0.19041.264]
(c) 2020 Microsoft Corporation. All rights reserved.
 **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
 **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** No **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** sbt **
```
 - What did you expect to occur after running these commands?

** sbt's active shell commands to be displayed in the bottom lines **

 - What actually happened instead?

** sbts shell command are displayed following what seem to be uninterpreted ANSI control sequences **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** https://github.com/scala/scala **

**Comment by dscho** [comment] 2020-06-03 19:55
> `** sbt **`

I am sure you can come up with a much more minimal example than forcing others to install Scala.

**Comment by martijnhoekstra** [comment] 2020-06-06 08:05
Not yet. Bash printf works as expected. I have noticed what I believe to be some changes in behaviour in the terminal in cursor movement too, where typing something while git is still doing something ends up with duplicated text.

I'll need to investigate what kind of shell the launcher uses exactly, and then emulate that in Bash. I don't know bash all that well, so it might be difficult.

**Comment by martijnhoekstra** [comment] 2020-06-06 14:52
the output of rebase also doesn't seem to handle cursor movement correctly anymore, though Im not sure it's the same issue, it does bear similarities.
```
$ git rebase -i 2.13.x
[detached HEAD 05feb807b1] reworded
                                    Date: Sat Jun 6 16:49:03 2020 +0200
                                                                        1 file changed, 22 insertions(+), 13 deletions(-)
```

**Comment by dpodder** [comment] 2020-06-08 17:52
I'm able to reproduce this with gradle, as well. I wonder if it's an issue with handling the way the JVM writes ANSI control sequences? I'll update if I can find a self-contained repro.

**Comment by martijnhoekstra** [comment] 2020-06-08 20:12
I'll check what library, if any, sbt uses.

**Comment by shanman190** [comment] 2020-06-28 01:11
Hi 👋

I recently ran into this issue as well. In my case, I'm running git-bash via Cmder/ConEmu. Bash itself functions normally as expected, but when launching vim, less, etc within that embedded console any of the ANSI sequences for things like arrow keys are broken. When running git-bash independently it's receiving Windows native control sequences, but in my current setup Cmder sends ANSI sequences which as of 2.27.0 are no longer accepted. This works as expected with 2.26 (I think it's 2.26.2, but I'm not in front of my work device at the moment to confirm), so I've just temporarily downgraded as a workaround. I've also tried updating Cmder to send native sequences, but that seems to not quite work out for me and is probably related more to my Cmder setup than anything. I can say that when I do get Cmder to actually send the native sequence through the arrow keys do function, but in my case I can only get it to do that for a single key before something gets tripped up in Cmder and it reverts back to ANSI sequences.

I've verified the sequences used by using vim to capture them. 

Left Arrow
Cmder sends ^[[D (fails)
Cmder sends ^[OD (works)
Git-bash (CMD terminal option) sends ^[OD (works)

NOTE: in order to get Cmder to allow you to use Ctrl+V you'll have to disable the paste function in settings.

**Comment by PhilipOakley** [comment] 2020-06-28 09:50
Have folks tried the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)? 

I think there were some terminal adjustments in there.

**Comment by martijnhoekstra** [comment] 2020-06-30 20:05
I think I'm running the latest snapshot, though I'm not sure how I can see what version of the shell I'm running. The git version number contains the snapshot sha though:

```
marti@LAPTOP-7MK8D0M5 MINGW64 ~
$ git --version
git version 2.27.0.windows.1.8.ga98b073ae2.20200618202904

marti@LAPTOP-7MK8D0M5 MINGW64 ~
$ sbt
←[0m[←[0m←[0minfo←[0m] ←[0m←[0mUpdated file C:\Users\marti\project\build.propert
ies: set sbt.version to 1.3.8←[0m
←[0m[←[0m←[0minfo←[0m] ←[0m←[0mLoading global plugins from C:\Users\marti\.sbt\1
.0\plugins←[0m
←[2K
←[2K
←[2K
←[2K
←[2K
←[2K  | => global-plugins / transitiveUpdate 0s
←[2K  | => global-plugins / transitiveUpdate 0s
←[2K  | => global-plugins / update 0s
←[2K  | => global-plugins / updateCacheName 0s
```

etc.

I still haven't found a way to minimize further than the sbt launcher.

**Comment by shanman190** [comment] 2020-07-01 01:12
I can report that I'm on the latest snapshot (a98b073ae2) and while vim and less still see the native keys they are at least responding as expected now.

@martijnhoekstra, I just installed sbt 1.3.13 via sdkman and the ANSI color sequences work under the snapshot as well. It may be as easy as a minor sbt upgrade for you?

**Comment by dscho** [comment] 2020-07-01 08:13
> I think I'm running the latest snapshot, though I'm not sure how I can see what version of the shell I'm running. The git version number contains the snapshot sha though:

You can run `uname -a` to get the MSYS2 runtime version, which is the most relevant piece of information in the context of this ticket.

> When run via `/git-bash.exe` (at the root) sbt outputs no ANSI color sequences at all. However a terminal started with `/bin/bash --login -i` or `/usr/bin/bash.exe --login -i` the control character is unrecognized.

Do you mean to say that the terminal window in question is MinTTY (`git-bash.exe`) vs ConHost (`/bin/bash --login -i`)?

> Using `echo -e` to print the same data that sbt is writing to the console however works without any issue.

That's because `echo` is MSYS2-aware, while `sbt` is not.

**Comment by martijnhoekstra** [comment] 2020-07-01 08:56
```
$ uname -a
MINGW64_NT-10.0-19041 LAPTOP-7MK8D0M5 3.1.5-340.x86_64 2020-06-08 23:21 UTC x86_64 Msys
```

**Comment by shanman190** [comment] 2020-07-01 12:26
@dscho, Yeah, in my just spot testing case the portable git variant is using MinTTY, so `git-bash.exe` launches that MinTTY terminal. In the other two cases, you are correct that I'm launching it via standard Command Prompt /ConHost window.

**Comment by ean5533** [comment] 2020-07-29 16:31
This issue appears to still be present in the nascent v2.28.0. Like @dpodder , I experience this issue when using [gradle](https://gradle.org/).

**Comment by dpodder** [comment] 2020-07-31 14:38
Update - It looks like overriding the value of the `TERM` environment variable so that it does not start with `xterm-` "fixes"/restores proper output (at least for gradle).

Doing this globally has other repercussions (breaking other things), so I ended up setting up an alias to just change `TERM` for the scope of my gradle commands.

**Comment by martijnhoekstra** [comment] 2020-08-01 19:18
@dpodder what did you set your TERM to? I've now been able to reproduce the issue with jline3, but setting TERM to `other` doesn't do it for me. Maybe the bug is in jline, but I haven't been able to track it down.

**Comment by dpodder** [comment] 2020-08-02 02:11
Usually I just prefix the default value (`xterm-256color`) to make it `buggy-xterm-256color`. I don't recall what other stuff I've tried, but I think everything I've tried seemed to work for gradle, at least.

**Comment by SlySven** [comment] 2020-08-06 05:41
Just passing by, looking for matches to my issue, but (as someone who normally uses Linux/FreeBSD) the thought crosses my mind as to why people seem ***surprised*** that setting their `TERM` variable to a terminal (or variant thereof) that they are not actually using (**`xterm`** or **`xterm-256color`**) is causing software that makes use of things like the `terminfo` or older `termcap` libraries via `ncurses` or other means in order to interface with a (virtual) terminal are getting surprised **when the (virtual) terminal that is not an Xterm behaves *differently* than the actual XTerm**?

T. E. Dickey, the long-time maintainer of `xterm` (and `ncurses`) has reviewed a whole lot of terminal emulators and compared their behaviours and commented on just how many of them do not behave the same ( https://invisible-island.net/vttest/vttest.html ) - and he even participated in this `mintty` discussion [mintty issue 881 - Terminal feature information schemes](https://github.com/mintty/mintty/issues/881) which seems to me to touch upon the sort of issue you are having with different (virtual) terminals.

To my mind you are looking to see on how to handle different virtual terminals by looking at the `TERM` environmental variable - however I think you need to look deeper than that... 😦

**Comment by dpodder** [comment] 2020-08-19 13:16
I agree, the use of `xterm-*` is not ideal. I did not set my `TERM` that way on purpose... unfortunately it seems to be the default that comes with Git Bash in Git for Windows.

**Comment by fcharlie** [comment] 2020-08-20 03:18
We can write a golang program to verify that git does not restore the virtual terminal settings every time: (gitvt.go)

```
go mod init gitvt
go mod tidy
go build
```

```go
package main

import (
	"fmt"
	"os"
	"os/exec"

	"golang.org/x/sys/windows"
)

// const
const (
	EnableVirtualTerminalProcessingMode = 0x4
)

// UseTerminal fixup
func UseTerminal() {
	var mode uint32
	// becasue we print message to stderr
	fd := os.Stderr.Fd()
	if windows.GetConsoleMode(windows.Handle(fd), &mode) == nil {
		fmt.Fprintf(os.Stderr, "ConsoleMode %x\n", mode)
		_ = windows.SetConsoleMode(windows.Handle(fd), mode|EnableVirtualTerminalProcessingMode)
		fmt.Fprintf(os.Stderr, "Set ConsoleMode %x\n", mode|EnableVirtualTerminalProcessingMode)
	}
}

// IsVirtualTerminal is
func IsVirtualTerminal() bool {
	var mode uint32
	// becasue we print message to stderr
	fd := os.Stderr.Fd()
	if windows.GetConsoleMode(windows.Handle(fd), &mode) == nil {
		fmt.Fprintf(os.Stderr, "ConsoleMode %x\n", mode)
		return EnableVirtualTerminalProcessingMode&mode != 0
	}
	return false
}

func showTerminalDetails() {
	if IsVirtualTerminal() {
		fmt.Fprintf(os.Stderr, "\x1b[34mIs Virtual Terminal\x1b[0m\n")
		return
	}
	fmt.Fprintf(os.Stderr, "Not Virtual Terminal\n")
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintf(os.Stderr, "usage: %s cmd args\n", os.Args[0])
		os.Exit(1)
	}
	UseTerminal()
	showTerminalDetails()
	cmd := exec.Command(os.Args[1], os.Args[2:]...)
	cmd.Stderr = os.Stderr
	cmd.Stdout = os.Stdout
	cmd.Stdin = os.Stdin
	if err := cmd.Run(); err != nil {
		showTerminalDetails()
		if ex, ok := err.(*exec.ExitError); ok {
			fmt.Fprintf(os.Stderr, "exit: %v", ex.ProcessState.ExitCode())
			os.Exit(ex.ProcessState.ExitCode())
		}
		fmt.Fprintf(os.Stderr, "error: %v", err)
		os.Exit(1)
	}
	showTerminalDetails()
}
```

```
gitvt git ls-remote not-fonud-url
```

**Comment by szliu-a** [comment] 2020-09-04 08:53
I can reproduce this bug by using TERM=xterm or TERM=xterm-256color, run `git commit --amend` in a git working copy and using vim as the editor, and exit vim.

![gitwin-bug-1](https://user-images.githubusercontent.com/50485815/92220750-0489c480-eecf-11ea-9b5a-f33cf937c368.png)

$ git --version
git version 2.28.0.windows.1

mintty 3.2.0 [Windows 17763]

**Comment by dscho** [comment] 2020-09-28 09:30
@szliu-a please note that this ticket is mainly about ANSI control sequences, with the symptom that line feeds do not imply a carriage return only being strewn in randomly.

Having said that, could you re-test with the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by alexfrostdev** [comment] 2021-04-21 15:35
I have Git-2.26.2-64-bit.exe installed and my Android studio launch terminal inside its tab by command "C:\Program Files\Git\bin\bash.exe" when I run "./gradlew test" it runs gradle command and I see green "OK" and green arrows at my terminal 

but when I update to latest Git-2.31.1-64-bit.exe I see ASCI control sequences like "\033]"

**Comment by dscho** [comment] 2021-04-22 12:02
> but when I update to latest Git-2.31.1-64-bit.exe I see ASCI control sequences like "\033]" instead of colors

@alexfrostdev please spend some time to turn this into [a Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by szliu-a** [comment] 2021-04-23 03:25
@dscho It's fixed in latest snapshot. I tested it in PortableGit-prerelease-2.31.1.windows.1-28-g67e748cc61-20210408225318-64-bit.7z.exe . Thanks!

**Comment by alexfrostdev** [comment] 2021-04-23 15:08
> @alexfrostdev please spend some time to turn this into [a Minimal, Complete & Verifiable Example]

If I could do this I would provide it already

**Comment by szliu-a** [comment] 2021-06-28 08:09
The strange thing is that it is not fixed in 2.32.0.windows.1, despite fixed in PortableGit-prerelease-2.31.1.windows.1-28-g67e748cc61-20210408225318-64-bit.7z.exe

**Comment by dscho** [comment] 2021-06-28 12:49
@szliu-a care to bisect through

**Comment by szliu-a** [comment] 2021-06-29 03:06
@dscho I suspect that it might be due to different packaging. The git snapshot was a portable, but the release is an installer. I would try the corresponding portable snapshot to the release commit if I had time...

**Comment by clemyan** [comment] 2023-02-22 07:29
I am also experiencing weird ANSI handling, **but so far only in git hooks**. The symptom I am seeing is also different. Instead of showing "unprocessed" sequences like `←[0m` the ANSI sequences do not show up at all. Not sure if it is actually related to this issue. I can open a new issue if needed.

---

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
```
# Tested with both released version on winget, and portable version of latest snapshot
$ git --version --build-options

git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon

$ git --version --build-options

git version 2.39.1.windows.1.536.g49a8ec9dac.20230214182258
cpu: x86_64
built from commit: 49a8ec9dac3cec6602f05fed1b3f80a549c8c05c
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? **Windows 10 Home 22H2 Build 19045.2604 (64-bit)**

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2604]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Issue exists when using CMD (10.0.19045.2604) and PowerShell (7.3.2), but does not exist when using git-bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ git init
$ nano .git/hooks/pre-commit # Create pre-commit hook
$ git commit --allow-empty
```
**.git/hooks/pre-commit**
```
#!/bin/sh
printf 'ANSI NOT \x1B[4DWORKING PROPERLY\n'
exit 1
```

 - What did you expect to occur after running these commands?

Prints `ANSI WORKING PROPERLY`

 - What actually happened instead?

Prints `ANSI NOT WORKING PROPERLY`

![image](https://user-images.githubusercontent.com/41266433/220551645-c8db029e-425e-4c9b-9274-016233730beb.png)

**Comment by dscho** [comment] 2023-02-22 09:27
> I can open a new issue if needed.

@clemyan it looks different enough from the original report that I'd indeed prefer a new ticket.

FWIW I can reproduce it: the `pre-commit` hook strips the ANSI sequence. And I can confirm that `git -c alias.x="!.git/hooks/pre-commit" x` _does_ handle the ANSI sequence. I will gladly repeat this finding in a new ticket.

As to this here ticket, there hasn't been any response in too long a time to keep it open.

**Closed by dscho** 2023-02-22 09:27 UTC
