### ISSUE TITLE
git check-ignore not showing some files

### ISSUE THREAD

**Issue by ferpega** [git-for-windows/git#563] opened 2015-12-09 11:37 UTC
Hello, I have last Git for Windows version installed: 2.6.3.windows.1

I have added this value to .gitignore (to ignore locked -while editing- files on LibreOffice):
> .~lock.*  

But, in spite of the file: 
> .~lock.xxxxxx.odp#

Is rightly ignored it does not appear on a git command:
> git check-ignore *

Witch show an empty list (in my example).

It is a bug?  Or the file-format is not supported in this command?

**Comment by PhilipOakley** [comment] 2015-12-09 12:35
have a look at http://stackoverflow.com/questions/466764/show-ignored-files-in-git for some pointers and ideas. It covers the various different command options, and other commands that could be used, along with a comment that there is no reliable way (single check-ignore command) of getting everything...

**Comment by ferpega** [comment] 2015-12-09 16:00
I forgot to say I am _always_ using Git for Windows bash and not cmd to work with git.

Sorry, I cannot find where the link content is saying there is no reliable way with check-ignore command to get ignored-files or there is a substantial difference from linux/windows on this command.

The main difference between `check-ignore` and `clean -ndX` or `status --ignored` is `check-ignore` is telling us what rule is applied to ignore a file.  I have seen another ways to get almost the same information but they are more complex IMHO.

**Comment by rimrul** [comment] 2015-12-15 16:36
>Sorry, I cannot find where the link content is saying there is no reliable way with check-ignore command to get ignored-files or there is a substantial difference from linux/windows on this command.

http://stackoverflow.com/questions/466764/show-ignored-files-in-git#comment17769768_466764
http://stackoverflow.com/a/1446609

**Comment by kgybels** [comment] 2015-12-16 11:28
@ferpega The problem is (probably) not a bug in `git check-ignore`, but the way the shell does [_filename expansion_](http://tldp.org/LDP/abs/html/globbingref.html). Normally, the expansion for `*` will not include _dotfiles_.

You can use `echo *` to see what the star is being expanded too.
Also try `git check-ignore .~lock.xxxxxx.odp#` to verify check-ignore for your case.

**Comment by dscho** [comment] 2016-01-03 15:40
As this seems to really be a misunderstanding how Bash expands wildcards (as pointed out by @kgybels), I close this ticket.

**Closed by dscho** 2016-01-03 15:40 UTC
