### ISSUE TITLE
executables for dashed commands are way too big

### ISSUE THREAD

**Issue by ryuukk** [git-for-windows/git#3247] opened 2021-06-03 12:33 UTC
### Setup

 - 2.31.1 x64

```
$ git --version --build-options
git version 2.31.1.windows.1
cpu: x86_64
built from commit: c5f0be26a7e3846e3b6268d1c6c4800d838c6bbb
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Windows 10 x64

```
Microsoft Windows [Version 10.0.19042.985]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: Nano
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

### Details

![TreeSizeFree_Htj012daaS](https://user-images.githubusercontent.com/44361234/120645312-92073e80-c478-11eb-87c4-6c770d9d5be0.png)

As you can see in the screenshot, all the alias executable seems to be individually statically linked, it results is a huge waste of disk space

What should be tiny, results in a 700mb install..

**Comment by rimrul** [comment] 2021-06-03 14:03
The installer hardlinks the dashed forms and only creates copies if that fails.

**Comment by dscho** [comment] 2021-06-04 19:01
I think this issue is covered by our [Release Notes' "Known Issues" section](https://github.com/git-for-windows/build-extra/blob/master/ReleaseNotes.md#known-issues):

> * Older versions of the Windows Explorer do _not_ calculate Git for Windows' on-disk size correctly, as it is unaware of hard links. Therefore, it might look like Git for Windows takes up 1.5GB when in reality it is about a third of that.

> The installer hardlinks the dashed forms and only creates copies if that fails.

Please note that it should actually use copies of `git-cmd.exe` as a fall-back, which would result in _much_ smaller sizes. So @ryuukk is looking at hardlinked copies of `git.exe`.

BTW this ticket is most likely a duplicate of https://github.com/git-for-windows/git/issues/3204, and at least related to https://github.com/git-for-windows/git/issues/2227

**Closed by dscho** 2021-06-04 19:01 UTC
Labels: question
