### ISSUE TITLE
2.16.1(2) error: cannot spawn git: Function not implemented

### ISSUE THREAD

**Issue by Eli-Zaretskii** [git-for-windows/git#1476] opened 2018-02-04 07:34 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.2
cpu: x86_64
built from commit: e78e3c8ee9c219723d60aa1bccd8348c2269b9ba
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

None that I know of.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git pull --all

(also tried `git pull` and `git fetch`, with same results).
```
 - What did you expect to occur after running these commands?

I expected the repository to be updated.

 - What actually happened instead?

I got an error message:

     error: cannot spawn git: Function not implemented

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It happens in every repository I try.  Downgrading to 2.16.1 solved the issue.

**Comment by shiftkey** [comment] 2018-02-04 08:38
Closing this out in favour of #1475 which reports the same issue on Server 2008.

I'm pretty sure they're the same root cause.

**Closed by shiftkey** 2018-02-04 08:38 UTC
