### ISSUE TITLE
Git svn crash in windows 10

### ISSUE THREAD

**Issue by mmkulikov** [git-for-windows/git#2662] opened 2020-06-04 06:40 UTC
In file 'subversion/bindings/swig/perl/libsvn_swig_perl/swigutil_pl.c' line 1666: assertion failed (get_current_pool_cb != NULL)
0 [main] perl 249 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump

**Comment by rimrul** [comment] 2020-06-04 06:57
Duplicate of #2649

**Closed** 2020-06-04 12:48 UTC
Labels: duplicate
