### ISSUE TITLE
bash-completion package not included in mingw

### ISSUE THREAD

**Issue by andi-blafasl** [git-for-windows/git#4023] opened 2022-09-16 13:46 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.37.3.windows.1
cpu: x86_64
built from commit: c4992d4fecabd7d111726ecb37e33a3ccb51d6f1
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.19043.1889]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

installed kubectl with autocomplete in .bashrc like describe in the official [kubernetes docs](https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

   Windows Terminal

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
kubectl apply -f [TAB]
```
 - What did you expect to occur after running these commands?

Show files for Auto-completion

 - What actually happened instead?

the following error is shown
```
bash: _filedir: command not found
```

### Fix for the Problem

Git-Bash is missing the [bash-completion](https://github.com/scop/bash-completion) package. you have to manually get the main function file ([bash_completion](https://github.com/scop/bash-completion/blob/master/bash_completion)) from the repo and save it in your home direcory under `~/bash_completion.d/bash_completion.bash`. this way it is automatically sourced by `/etc/profile.d/git-prompt.sh`

Please include bash-completion package in your mingw environment.

**Comment by dscho** [comment] 2022-09-16 14:40
This very much looks like a duplicate of https://github.com/git-for-windows/git/issues/2562 (which even was accompanied by [a not-quite-finished PR](https://github.com/git-for-windows/build-extra/pull/293)).

Having said that... The purpose of [Git for Windows](https://git-for-windows.github.io/) is really to bring *Git* to Windows.

While that implies that we have to ship quite a few Unix-like tools, it does not mean that we will include such tools unless they are needed for Git's own operations, or at least for historical reasons (needs of active contributors are sometimes a factor in deciding whether to include a tool or not).

Having said that, what you really are looking for may be [MSYS2](https://msys2.github.io/). Git for Windows leverages MSYS2 and ships with a subset of its files. MSYS2 even sports a package management system called "pacman" to install more tools (including Git...), so why don't you give it a whirl?

**Closed by dscho** 2022-09-16 14:40 UTC
