### ISSUE TITLE
git-bash cyrillic

### ISSUE THREAD

**Issue by sergeychibunin** [git-for-windows/git#567] opened 2015-12-11 11:10 UTC
Hello. Fix, please, insert cyrillic chars into git-bash console via 'inser'-key and 'right-click-in-top-panel-of-window-interface->changes->insert'. Thanks

**Comment by dscho** [comment] 2015-12-11 14:47
I paste non-ASCII characters all the time and it works for me. So unless you [follow our guide lines for kick-ass bug reports](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), I am afraid there is nothing I can do for you.

**Comment by sergeychibunin** [comment] 2015-12-12 08:50
dscho, russian too? I will check your guidelines later. Do not close this issue, please.

**Comment by kostix** [comment] 2015-12-12 12:30
@sergeychibunin, this should not matter provided you have fonts which are able to display Cyrillic.

But at least you have to specify the OS, its locale (Russian, I suppose?), the settings you're using (does Git bash use `cmd.exe` or bundled `mintty` -- the installer had asked you about this).

A screenshot (Alt-PrnScr then paste to `pbrush.exe` then save as PNG) attached here would not hurt either.

**Comment by dscho** [comment] 2015-12-12 15:39
@sergeychibunin you might find that providing a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve) will go a long way when reporting bugs.

**Comment by sergeychibunin** [comment] 2015-12-13 12:25
@kostix, I am not remember how Git was installed via Installer. Where are keep his config file? All right, it's russian locale and win 10.
![2015-12-13 17-22-57 mingw64 c users](https://cloud.githubusercontent.com/assets/5697431/11766963/82bf8e1a-a1be-11e5-87f2-c565c0118499.png)

**Comment by calle2010** [comment] 2015-12-14 10:07
Hello, 
I have a similiar issue with german umlauts.

git version 2.6.3.windows.1 on Windows 7 64bit

I am using the Windows default console window, not mintty. But if I start mintty manually I have the same issue:

There is a difference between insert through right mouse click, using window menu Edit->Paste and using the Insert key. The insert key doesn't insert german umlauts correctly.

1) open notepad.exe and enter some german umlauts, e. g. "abcdäöüÄÖÜabcd"
2) Use Ctrl-A and Ctrl-C to get this into the clipboard
3) Open a Git Bash command line windows
4) press Insert key to paste the clipboard entry

Result:

The german umlauts appear not correctly but as ▒▒▒▒▒▒:

![issue-567](https://cloud.githubusercontent.com/assets/189960/11778031/3ad6377c-a252-11e5-8430-27d865b95d07.png)

The other two methods of inserting (right mouse-click or window menu Edit->Paste) work correctly.

I use Consolas font.

Content of /c/ProgramData/git/config:
[core]
        symlinks = false
        autocrlf = true
[color]
        diff = auto
        status = auto
        branch = auto
        interactive = true
[pack]
[help]
        format = html
[http]
        sslCAInfo = C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
[sendemail]
        smtpserver = /bin/msmtp.exe

[diff "astextplain"]
        textconv = astextplain
[rebase]
        autosquash = true

**Comment by cfbrobak** [comment] 2015-12-15 12:06
Try using "Shift+Insert", not just "Insert".

**Comment by rimrul** [comment] 2015-12-15 16:29
I tried to reproduce this on Git for Windows 2.6.3 x64/Windows 7 Professional x64 de_DE, but it worked flawlessly in my `minTTY` based `git-bash.exe` (context menu or shift+ins) and in `git-cmd.exe`.

I could reproduce @calle2010's results in a `/bin/sh.exe` launced from `cmd.exe` and got a bunch of questionmarks like in the screenshot @sergeychibunin posted from pasting text from some russian Wikipedia article into `cmd.exe` (with or without `/bin/sh.exe`) by all ways to paste known to me.

**Comment by sergeychibunin** [comment] 2015-12-16 04:56
@cfbrobak 
![2015-12-16 09-55-29 mingw64 c users serg documents rightbag www rightbag ru](https://cloud.githubusercontent.com/assets/5697431/11832539/2ae9a968-a3db-11e5-8ee0-4b54ce779ea9.png)

"Shift+Insert" is there

**Comment by sergeychibunin** [comment] 2015-12-16 05:04
@rimrul Your suggestion is reinstall git with minTTY? Just I was not remember this feature while it's install.

**Comment by kostix** [comment] 2015-12-16 11:24
@rimrul, can you somehow verify you have the same fonts both on MinTTY and `cmd.exe` windows -- to rule out possible fonts issue?

**Comment by rimrul** [comment] 2015-12-16 13:01
@kostix, changed the `cmd.exe` to `Lucida Console` to match `git-bash.exe`.
I can still reproduce the issue with the german text, but pasting russian
text via the context menu now shows cyrillic letters. Pasting it via the
Insert key still results in question marks.

2015-12-16 12:24 GMT+01:00 Konstantin Khomoutov <notifications@github.com>:

**Comment by sergeychibunin** [comment] 2015-12-17 07:17
@kostix have you any suggestions about this issue? What you think about?

**Comment by kgybels** [comment] 2015-12-17 18:49
These are the results I'm getting:
![image](https://cloud.githubusercontent.com/assets/2051188/11878404/d208e66c-a4f5-11e5-8402-33184bbcd92d.png)

The only one that works correctly is the paste that is handled by mintty (both context menu and keyboard shortcut). Important to note here is that the Insert key is handled by the shell directly, which will be fixed by git-for-windows/MSYS2-packages#16.

**Comment by sergeychibunin** [comment] 2015-12-18 12:53
@kgybels when a update will be available? or how to update my "git-app"?

**Comment by rimrul** [comment] 2015-12-18 13:58
This will be included in the nett Release after the Pull request geht's
merged. If you can't weit, download the sdk, apply the changes and build an
installer. There should be infos available in the wiki.
Am 18.12.2015 13:53 schrieb "Sergey Chibunin" <notifications@github.com>:

**Comment by dscho** [comment] 2015-12-18 17:05
@kgybels https://github.com/Alexpux/MSYS2-packages/pull/406 was merged (essentially your git-for-windows/MSYS2-packages#16, rebased to upstream).

**Comment by sergeychibunin** [comment] 2015-12-19 09:04
I will be wait a next release. Thanks.

**Comment by sergeychibunin** [comment] 2015-12-29 12:31
Somebody write here about new release when it will be available, please.

**Comment by kostix** [comment] 2015-12-29 12:59
@sergeychibunin, just star this project (upper right corner of the github site's UI) and you'll be notified of the new releases.

Alternatively, subscribe to the [mailing list](https://groups.google.com/d/forum/git-for-windows) and read announcements there.

**Comment by sergeychibunin** [comment] 2015-12-30 04:58
@kostix , oh, thanks.

**Comment by dscho** [comment] 2016-01-03 15:10
@sergeychibunin it would be a token of gratitude to follow [the steps to make a new installer yourself](https://github.com/git-for-windows/git/wiki/Making-an-installer), to verify that the issue is fixed, and to report back.

**Comment by sergeychibunin** [comment] 2016-01-04 06:02
@dscho there is some problems while install sdk https://yadi.sk/i/Nw3tyhivmerxY
Can you help?

**Comment by dscho** [comment] 2016-01-04 09:49
> there is some problems while install sdk https://yadi.sk/i/Nw3tyhivmerxY

Let's not paste stuff in random places. You can copy & paste the text *here*. If you must, you can even insert the screen shot, although plain text is definitely much more appreciated.

**Comment by sergeychibunin** [comment] 2016-01-05 11:36
@dscho 
![2016-01-04 10-59-00 c windows system32 cmd exe](https://cloud.githubusercontent.com/assets/5697431/12114284/6afe8650-b3ca-11e5-9f8e-0ddd3d2b0e0a.png)

**Comment by dscho** [comment] 2016-01-05 13:14
And here is the plain text:

```
Synchronizing package databases...
git-for-windows 2004.0   B  1957K/S 00:00 [####################################################################################################] 100%
mingw32          228.6 KiB   493K/S 00:00 [####################################################################################################] 100%
mingw32.sig       96.0   B  93.8K/S 00:00 [####################################################################################################] 100%
     1 [main] pacman 6348 D:\Program files\Git-sdk-64\usr\bin\pacman.exe: *** fatal error in forked process - fork: can't reserve memory for parent stack 0x600000 - 0x800000, (child has 0x400000 - 0x600000), Win32 error 487
  1206 [main] pacman 6348 cygwin_exception::open_stackdumpfile: Dumping stack trace to pacman.exe.stackdump
     1 [main] pacman 8636 fork: child -1 - forked process 6348 died unexpectedly, retry 0, exit code 0x100, errno 11
error: GPGME error: Invalid crypto engine
error: failed to update mingw32 (invalid or corrupted database (PGP signature))
mingw64          227.5 KiB   977K/S 00:00 [####################################################################################################] 100%
mingw64.sig       96.0   B  93.8K/S 00:00 [####################################################################################################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update mingw64 (invalid or corrupted database (PGP signature))
msys             128.4 KiB  7.84M/S 00:00 [####################################################################################################] 100%
msys.sig          96.0   B  93.8K/S 00:00 [####################################################################################################] 100%
error: GPGME error: Invalid crypto engine
error: failed to update msys (invalid or corrupted database (PGP signature))
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
here was a problem accessing the MSys2 repositories
If your setup requires an HTTP proxy to access the web,
please specify it here, otherwise leave it empty.
```

Unfortuntely, OCRing the pasted image took up all the time I was willing to spend on this ticket this week (hint: you might want to let me spend my time differently next time).

Maybe others want to help?

**Closed** 2016-01-14 16:11 UTC
Labels: invalid
