### ISSUE TITLE
Permission Error on all App Execution Aliases in git-bash

### ISSUE THREAD

**Issue by KyleMit** [git-for-windows/git#2675] opened 2020-06-09 01:40 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

    ```
    $ git --version --build-options

    git version 2.25.1.windows.1
    cpu: x86_64
    built from commit: cceb69da75b4906bb04cfb3a2f7f37b12b985ec3
    sizeof-long: 4
    sizeof-size_t: 8
    ```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

    ```
    $ cmd.exe /c ver

    Microsoft Windows [Version 10.0.18363.836]
    (c) 2019 Microsoft Corporation. All rights reserved.
    ```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

    ```
    # One of the following:
    > type "C:\Program Files\Git\etc\install-options.txt"
    $ cat /etc/install-options.txt

    Editor Option: VisualStudioCode
    Custom Editor Path: 
    Path Option: Cmd
    SSH Option: OpenSSH
    Tortoise Option: false
    CURL Option: OpenSSL
    CRLF Option: CRLFAlways
    Bash Terminal Option: MinTTY
    Performance Tweaks FSCache: Enabled
    Use Credential Manager: Enabled
    Enable Symlinks: Disabled
    ```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

    > Issue should be reproducible in a wide variety of environments

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

   > **Bash**

 - What commands did you run to trigger this issue? If you can provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) this will help us understand the issue.

   1. Install [Git-Bash](https://gitforwindows.org/)
   2. Install [WinGet](https://docs.microsoft.com/en-us/windows/package-manager/winget/)
   3. Run Command:

        ```bash
        winget --version
        ```

 - What did you expect to occur after running these commands?

    ```none
    v0.1.41331 Preview
    ```

 - What actually happened instead?

    ```none
    bash: /c/Users/kylemit/AppData/Local/Microsoft/WindowsApps/winget: Permission denied
    ```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

    > n/a

### More Info

There is a problem with all [**app execution aliases** on Windows 10](https://www.tenforums.com/tutorials/102096-manage-app-execution-aliases-windows-10-a.html) for apps installed via the Windows Store inside of git-bash.  This issue is specific to git-bash (i'm not sure if there is a separate repo to handle terminal issues).  

![image](https://user-images.githubusercontent.com/4307307/84095764-23f77b00-a9ce-11ea-93e0-66013b43a96d.png)

They are located in a folder under the user's local data here:

```none
%LocalAppData%\Microsoft\WindowsApps\
```

![WindowsApps](https://user-images.githubusercontent.com/4307307/84096083-ee06c680-a9ce-11ea-92ed-227b61dad696.png)

Which just contains 0 byte executables that act as shortcuts (or maybe symlinks?) to the actual executables found in this directory:

```none
C:\Program Files\WindowsApps\
```

While this directory appears highly locked down, such that an administrator cannot even open it, it appears to allow traversal rights so you can actually open the apps themselves inside of subfolders (provided you have a way to discover the path... process > details > open file location) like this:

```none
C:\Program Files\WindowsApps\Microsoft.WindowsTerminal_1.0.1401.0_x64__8wekyb3d8bbwe
```

For many executables, a possible workaround is to install the software directly and disable the link to the Windows Store.  However, this is not possible for apps deployed exclusively through the windows store like WindowsTerminal and WinGet

Here's an example in bash vs cmd:

![winget in bash vs command](https://user-images.githubusercontent.com/4307307/84096366-c82df180-a9cf-11ea-8c03-6d4ba2565214.png)

### Related Issues

* [“Permission Denied” trying to run Python on Windows 10](https://stackoverflow.com/q/56974927/1366033)
* [Permission Denied when running from bash #228](https://github.com/microsoft/winget-cli/issues/228)
* [bash: /WindowsApps/python3: Permission denied #6](https://github.com/gmacario/spaceappschallenge-2019/issues/6)

**Comment by rimrul** [comment] 2020-06-09 06:52
I can confirm this issue. I can also say that git handles them fine (I've modified the shebang of `git p4` a little, it launches the specified interpreter),but MSYS2 doen't like them.

There also seems to be some rather current discussion about `IO_REPARSE_TAG_APPEXECLINK` support on [the cygwin mailing list](https://www.mail-archive.com/cygwin@cygwin.com/msg164788.html) and the [MSYS2 issue tracker](https://github.com/msys2/Msys2-packages/issues/1943).

**Comment by denelon** [comment] 2021-01-07 00:37
Is this issue resolved now?

**Comment by felipecrs** [comment] 2021-01-07 00:44
> Is this issue resolved now?

![image](https://user-images.githubusercontent.com/29582865/103836605-53f02500-5068-11eb-8487-97e83c189837.png)

**Comment by dscho** [comment] 2021-03-12 15:03
I _think_ I have a fix for this, in https://github.com/msys2/msys2-runtime/pull/27.

**Comment by dscho** [comment] 2021-03-27 08:16
Fixed via https://github.com/git-for-windows/msys2-runtime/commit/d8692914f5a786a6394a4db5e58fb32fbde86447

**Closed by dscho** 2021-03-27 08:16 UTC
Labels: bug, msys2
