### ISSUE TITLE
mv issue

### ISSUE THREAD

**Issue by drweb86** [git-for-windows/git#972] opened 2016-11-24 14:16 UTC
Git can't rename file under repository.

It writes File is not under version control

Steps to reproduce:

1. Create git repository.
2. Checkout it to folder A
3. Create folder B in folder A
4. Create folder C in folder B
5. Create file about-us.docx and mark it for adding
6. Create empty file .gitignore and mark it for adding
7. Commit and push
8. Try to perform git mv about-us.docx to about-us-13-13-13.docx
==> File is not under version control

**Comment by elieux** [comment] 2016-11-24 14:33
Tried to reproduce, only seems to happen when the path is not entered correctly in respect to character case. In other words `git mv` is case sensitive. (`git mv b\c\d b\c\e` works, while `git mv B\C\D B\C\E` does not, assuming directories were committed lowercase).

**Comment by drweb86** [comment] 2016-11-24 14:39
Try to move file, not directory. Also i just copied file name exactly how it is named.

**Comment by elieux** [comment] 2016-11-24 14:46
Yes, `d` was a file, not a directory, in my example. Do you write file name including its path exactly the same as `git ls-files` says (excluding `/` -> `\`)?

**Comment by drweb86** [comment] 2016-11-24 16:01
im launching git in the directory where file resides, thats why i don't add any path prefixes (Windows).

**Comment by elieux** [comment] 2016-11-24 16:22
Ah, sorry, I missed that in your original report. Then your directories B or C are not the same case as Git thinks they should be. This is not just `git mv`, also `git ls-files` is case-sensitive, but not `git status` for example.

The main problem here is that it seems to happen with `git add`+`git commit`+`git mv` on the same set of files, without any external case changing or renaming. I can't reproduce this yet.

Can you post the exact command lines you executed that result in the error? Omit the clone and push, if possible, `git init .` and local commits should be sufficient AFAICT.

**Comment by drweb86** [comment] 2016-11-24 20:28
Hi.

I will try to reproduce it tomorrow and prepare archive with repo

Thanks.

**Comment by shiftkey** [comment] 2016-12-08 03:53
@drweb86 I ran through the instructions to the best of my ability and couldn't reproduce the issue

```sh
$ git init testing-move-issue
Initialized empty Git repository in C:/Users/shiftkey/src/testing-move-issue/.git/
$ cd testing-move-issue/
$ mkdir A
$ mkdir A/B/
$ mkdir A/B/C
$ touch A/B/C/about-us.docx
$ touch .gitignore
$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .gitignore
        A/

nothing added to commit but untracked files present (use "git add" to track)
```

At this point, note that the files are untracked. I try and commit the changes directly, but because they haven't been staged, the commit doesn't complete:

```sh
$ git commit -am "initial commit"
On branch master

Initial commit

Untracked files:
        .gitignore
        A/

nothing added to commit but untracked files present
```

I then `git add .` and am able to commit:

```sh
$ git add .
$ git status
On branch master

Initial commit

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .gitignore
        new file:   A/B/C/about-us.docx

$ git commit -am "initial commit"
[master (root-commit) 1688b45] initial commit
 2 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 .gitignore
 create mode 100644 A/B/C/about-us.docx
```

Now, we can rename the file successfully:

```sh
$ git mv A/B/C/about-us.docx A/B/C/about-us-13-13-13.docx
$ git status
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    A/B/C/about-us.docx -> A/B/C/about-us-13-13-13.docx
```

Without more details about the shell you were using (i'm in Git Bash here) and the commands that were run, it's hard to say what else this might be...

**Comment by drweb86** [comment] 2017-02-04 12:38
Please close it. Im really have no time to send reproduction sample. If it will bother me too much, i will prepare a video and small sample upon future issue submission.

**Closed** 2017-02-04 12:56 UTC
