### ISSUE TITLE
cannot execute binary file: Exec format error after checking out symlinks

### ISSUE THREAD

**Issue by evandrocoan** [git-for-windows/git#1844] opened 2018-09-19 19:43 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.19.0.rc0.windows.1
cpu: x86_64
built from commit: f9c1a9c1a4c1bf131ccf13aeac422b3820fa382f
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ type "C:\Program Files\Git\etc\install-options.txt"
bash: type: C:\Program Files\Git\etc\install-options.txt: not found

$ type "C:\Program Files (x86)\Git\etc\install-options.txt"
bash: type: C:\Program Files (x86)\Git\etc\install-options.txt: not found

$ type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
bash: type: %USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt: not found

$ cat /etc/install-options.txt
cat: /etc/install-options.txt: No such file or directory
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

mintty.exe from cygwin

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

This is a minimal example scripts which reproduces the problem. To run it, you need to create the file `do_bug.sh` and the example symlink: [python3.zip](https://github.com/git-for-windows/git/files/2398498/python3.zip) (just unzip its contents on the same folder as the `do_bug.sh` and run `./do_bug.sh`:
```sh
#!/usr/bin/env bash
printf '\nCreate the directory structure\n'
rm -r -f main_repo
rm -r -f main_repo_remote
rm -r -f main_repo_new

mkdir main_repo
mkdir main_repo_remote
cp -a python3 main_repo/

printf '\nSetup the main_repo\n'
cd main_repo
git init
git add python3
git commit -m "Added the main repository first commit."

printf '\nCreating a local remote\n'
git init --bare ../main_repo_remote
git remote add origin ../main_repo_remote
git push origin master

printf '\nChecking for the file state\n'
ls -l

printf '\nCloning the repository from thew new remote...\n'
cd ..
git clone ./main_repo_remote main_repo_new
cd ./main_repo_new

printf '\nChecking for the file state\n'
ls -l
```

You will see this:
```
$ ./do_bug.sh
Create the directory structure

Setup the main_repo
Initialized empty Git repository in D:/Test/main_repo/.git/
[master (root-commit) 5862623] Added the main repository first commit.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 python3

Chechign for the file state
total 1
lrwxrwxrwx 1 User None 14 Sep 19 16:07 python3 -> python3.6m.exe

Creating a local remote
Initialized empty Git repository in D:/Test/main_repo_remote/
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 266 bytes | 266.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Creating a new local clone
Cloning into 'main_repo_clone'...
done.

Chechign for the file state
total 1
-rwx---r-x+ 1 User None 42 Sep 19 16:07 python3
```
-->
![image](https://user-images.githubusercontent.com/5332158/45777056-18c55000-bc2b-11e8-9f4e-b67694d1cf50.png)

On it, you can noticed, that after checking out the `python3` file, the `ls -l` command, does not tell it is a symlink anymore. And if you try to run `python3`, you get:
```
$ ./python3
bash: ./python3: cannot execute binary file: Exec format error
```

 - What did you expect to occur after running these commands?
I expect my symlinks to keep working after adding them to git and checking out on another computer.

 - What actually happened instead?
The symlinks stop working and show:
```
$ ./python3
bash: ./python3: cannot execute binary file: Exec format error
```

When I try to run them.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I am hosting my Cygwin files on:

1. https://github.com/evandrocoan/Cygwin

But several symlinked applications as `python3` stopped working when I clone the repository on another computer with the error:
```
$ ./awk
bash: ./awk: cannot execute binary file: Exec format error
```
For now, I put a .zip on https://github.com/evandrocoan/Cygwin/releases with all files before adding and checking out them on git.

**Comment by dscho** [comment] 2019-02-27 12:52
Looks like somehow your `core.symlinks` is set to `false`. This can be changed by re-running the installer and checking the "Enable symbolic links" checkbox. This will require an up to date Windows 10, I think, in Developer Mode.

**Comment by evandrocoan** [comment] 2019-02-28 03:55
Just installed the last git version from 
1. https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/Git-2.21.0-64-bit.exe

And checked this box:
![image](https://user-images.githubusercontent.com/5332158/53539617-0eb84f00-3af1-11e9-89e4-9400eac7444b.png)

I also fixed the script on the first post. I had posted the wrong script. I recreated the script, but it did not get equal to the first script, but I think it is doing the same.

To run it, you need to create the file `do_bug.sh` and the example symlink: [python3.zip](https://github.com/git-for-windows/git/files/2398498/python3.zip) (just unzip its contents on the same folder as the `do_bug.sh` and run `./do_bug.sh`:
```sh
#!/usr/bin/env bash
printf '\nCreate the directory structure\n'
rm -r -f main_repo
rm -r -f main_repo_remote
rm -r -f main_repo_new

mkdir main_repo
mkdir main_repo_remote
mv python3 main_repo/

printf '\nSetup the main_repo\n'
cd main_repo
git init
git add python3
git commit -m "Added the main repository first commit."

printf '\nCreating a local remote\n'
git init --bare ../main_repo_remote
git remote add origin ../main_repo_remote
git push origin master

printf '\nChecking for the file state\n'
ls -l

printf '\nCloning the repository from thew new remote...\n'
cd ..
git clone ./main_repo_remote main_repo_new
cd ./main_repo_new

printf '\nChecking for the file state\n'
ls -l
```

On this new script, I could reproduce the problem and it still does not runs correctly even with `v2.21.0.windows.1`. I used the built-in `git-bash`:
![image](https://user-images.githubusercontent.com/5332158/53540149-209af180-3af3-11e9-9759-e9e8405b0733.png)
``` 
Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/New folder
$ bash do_bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in D:/User/Downloads/New folder/main_repo/.git/
[master (root-commit) b385a59] Added the main repository first commit.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 python3

Creating a local remote
Initialized empty Git repository in D:/User/Downloads/New folder/main_repo_remote/
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 266 bytes | 266.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 1
lrwxrwxrwx 1 Professional 197121 14 Jan  7  2018 python3 -> python3.6m.exe

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 1
-rw-r--r-- 1 Professional 197121 42 Feb 28 00:48 python3

Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/New folder
$ git --version
git version 2.21.0.windows.1
```

Comparing before the clone and after the clone, the file `python3` lost it property of being a symlink:
```
lrwxrwxrwx 1 Professional 197121 14 Jan  7  2018 python3 -> python3.6m.exe
-->
-rw-r--r-- 1 Professional 197121 42 Feb 28 00:48 python3
```

**Comment by dscho** [comment] 2019-02-28 19:47
First of all, when I use the `unzip` included in Git for Windows' SDK to unzip your `.zip` file, it creates a regular file, not a symbolic link, with the contents (piped through `hexdump -C` because there are NUL bytes all over the place):

```
00000000  21 3c 73 79 6d 6c 69 6e  6b 3e ff fe 70 00 79 00  |!<symlink>..p.y.|
00000010  74 00 68 00 6f 00 6e 00  33 00 2e 00 36 00 6d 00  |t.h.o.n.3...6.m.|
00000020  2e 00 65 00 78 00 65 00  00 00                    |..e.x.e...|
0000002a
```

However, I think you meant more something like a regular Windows symlink, as created via

```sh
cmd //c mklink python3 python3.6m.exe
```

Alas, when I run your `do_bug.sh` here, it prints this:

```
$ ./do_bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in D:/test-git/symlink-test/issue-1844/main_repo/.git/
[master (root-commit) 3bea196] Added the main repository first commit.
 1 file changed, 1 insertion(+)
 create mode 120000 python3

Creating a local remote
Initialized empty Git repository in D:/test-git/symlink-test/issue-1844/main_repo_remote/
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 245 bytes | 245.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 0
lrwxrwxrwx 1 johasc 1049089 14 Feb 28 20:42 python3 -> python3.6m.exe

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 0
lrwxrwxrwx 1 johasc 1049089 14 Feb 28 20:42 python3 -> python3.6m.exe
```

So as you can see, for me the bug does *not* reproduce. The symlink stays a symlink. The biggest difference I can see to your report is my Windows version, I guess you're a couple versions behind:

```
$ cmd //c ver

Microsoft Windows [Version 10.0.17763.316]
```

**Comment by dscho** [comment] 2019-02-28 19:49
Also, while you have checked that checkbox, that only sets the config variable in ProgramData. If e.g. your `~/.gitconfig` overrides `core.symlinks`, it won't work as you expect it to. To find out, run this in your worktree:

```sh
git config --show-origin core.symlinks
```

**Comment by evandrocoan** [comment] 2019-03-01 00:43
Thanks for running it. When I did `git config --show-origin core.symlinks``, it showed:
```
$ git config --show-origin core.symlinks
file:C:/Users/Professional/.gitconfig   true
```
Then, I ran `git config --global core.symlinks true` and re-run the `bug.sh`, but still the same. This is the output running it with the `git-bash.exe` shell now:
```
Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$ git config --show-origin core.symlinks
file:C:/Users/Professional/.gitconfig   true

Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$ git --version
git version 2.21.0.windows.1

Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$ ./bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in D:/User/Downloads/new/main_repo/.git/
[master (root-commit) 4b3e857] Added the main repository first commit.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 python3

Creating a local remote
Initialized empty Git repository in D:/User/Downloads/new/main_repo_remote/
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 266 bytes | 266.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 1
lrwxrwxrwx 1 Professional 197121 14 Jan  7  2018 python3 -> python3.6m.exe

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 1
-rw-r--r-- 1 Professional 197121 42 Feb 28 21:18 python3

Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$
```

This is the output running the standard with `cmd.exe`:
```
d:\User\Downloads\new>git config --show-origin core.symlinks
file:C:/Users/Professional/.gitconfig   true

d:\User\Downloads\new\main_repo_new>git --version
git version 2.21.0.windows.1

d:\User\Downloads\new>bash bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in /mnt/d/User/Downloads/new/main_repo/.git/
[master (root-commit) cdb41dc] Added the main repository first commit.
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 python3

Creating a local remote
Initialized empty Git repository in /mnt/d/User/Downloads/new/main_repo_remote/
Counting objects: 3, done.
Writing objects: 100% (3/3), 265 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 25
-rwxrwxrwx 1 root root 42 Jan  7  2018 python3

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 25
-rwxrwxrwx 1 root root 42 Mar  1 00:22 python3

d:\User\Downloads\new>cd main_repo

d:\User\Downloads\new\main_repo>git config core.symlinks
true

d:\User\Downloads\new\main_repo>cd ..\main_repo_new

d:\User\Downloads\new\main_repo_new>git config core.symlinks
true

d:\User\Downloads\new>
```

When I use a symlink you proposed to create with `mklink python3 python3.6m.exe`, everything works fine:
```
Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$ ./bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in D:/User/Downloads/new/main_repo/.git/
[master (root-commit) 18ae441] Added the main repository first commit.
 1 file changed, 1 insertion(+)
 create mode 120000 python3

Creating a local remote
Initialized empty Git repository in D:/User/Downloads/new/main_repo_remote/
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Writing objects: 100% (3/3), 237 bytes | 237.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 0
lrwxrwxrwx 1 Professional 197121 14 Feb 28 21:33 python3 -> python3.6m.exe

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 0
lrwxrwxrwx 1 Professional 197121 14 Feb 28 21:33 python3 -> python3.6m.exe

Professional@PROFESSIONAL-PC MINGW64 /d/User/Downloads/new
$
```

But the problem is not with Windows symlinks, but when Linux ones are commited and checked out. But I make it to work, when I used `Cygwin` built-in version of git and the `mintty.exe` terminal to run things. Then, when I run the `bug.sh` script, the script runs correctly:
```
Professional@PROFESSIONAL-PC$ git --version
git version 2.17.0
Professional@PROFESSIONAL-PC$ git config --show-origin core.symlinks
Professional@PROFESSIONAL-PC$ git config core.symlinks
Professional@PROFESSIONAL-PC$ bash bug.sh

Create the directory structure

Setup the main_repo
Initialized empty Git repository in /cygdrive/d/User/Downloads/new/main_repo/.git/
[master (root-commit) cad0bf8] Added the main repository first commit.
 1 file changed, 1 insertion(+)
 create mode 120000 python3

Creating a local remote
Initialized empty Git repository in /cygdrive/d/User/Downloads/new/main_repo_remote/
Counting objects: 3, done.
Writing objects: 100% (3/3), 237 bytes | 118.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To ../main_repo_remote
 * [new branch]      master -> master

Checking for the file state
total 1
lrwxrwxrwx 1 Professional None 14 Jan  7  2018 python3 -> python3.6m.exe

Cloning the repository from thew new remote...
Cloning into 'main_repo_new'...
done.

Checking for the file state
total 1
lrwxrwxrwx 1 Professional None 14 Feb 28 21:39 python3 -> python3.6m.exe
Professional@PROFESSIONAL-PC$
```

I guess that the problem is that the git used here, is not capable of correctly adding Linux symlinks. More precisely, the `unzip` included in Git for Windows' SDK is not capable of unzipping Linux files correctly, as you said:
> First of all, when I use the `unzip` included in Git for Windows' SDK to unzip your `.zip` file, it creates a regular file, not a symbolic link

Then, this is a bug on the Windows' SDK unzip tool?

**Comment by evandrocoan** [comment] 2019-03-01 00:54
PS: I used WinRar to unzip (and zip it too) the [python3.zip](https://github.com/git-for-windows/git/files/2398498/python3.zip) file.

**Comment by dscho** [comment] 2019-03-01 10:09
I think we're slowly circling in. Can you use `fsutil` to inspect the unzipped symlink? For me, the correct symbolic link (created via `mklink`) has this information:

```sh
$ cmd //c fsutil reparsePoint query python3
Reparse Tag Value : 0xa000000c
Tag value: Microsoft
Tag value: Name Surrogate
Tag value: Symbolic Link

Reparse Data Length: 0x00000044
Reparse Data:
0000:  1c 00 1c 00 00 00 1c 00  01 00 00 00 70 00 79 00  ............p.y.
0010:  74 00 68 00 6f 00 6e 00  33 00 2e 00 36 00 6d 00  t.h.o.n.3...6.m.
0020:  2e 00 65 00 78 00 65 00  70 00 79 00 74 00 68 00  ..e.x.e.p.y.t.h.
0030:  6f 00 6e 00 33 00 2e 00  36 00 6d 00 2e 00 65 00  o.n.3...6.m...e.
0040:  78 00 65 00                                       x.e.
```

**Comment by evandrocoan** [comment] 2019-03-02 02:48
Running it here on [python3.zip](https://github.com/git-for-windows/git/files/2398498/python3.zip) (unzipped, of course) it shows this:
```
D:\User\Downloads>fsutil reparsePoint query python3
Error:  The file or directory is not a reparse point.
```

The [python3.zip](https://github.com/git-for-windows/git/files/2398498/python3.zip) file is not a file I had created by myself. It is a file created by `Cygwin` installer.

**Comment by dscho** [comment] 2019-03-02 08:46
Cygwin faces a very special problem with symbolic links: it started supporting them *way* before Windows Vista introduced Windows-native symbolic links. So their symbolic links aren't really symbolic links: no non-Cygwin (or non-MSYS2) application recognizes them.

`git.exe` is such an application that does not recognize them. So is `fsutil`. Or Windows Explorer. Or pretty much any application you might use.

Except, of course, the MSYS2 Bash that is included in your Git for Windows. Especially that `ls` call you included in your script.

If you need Git to understand Cygwin symlinks, your best bet is to use Cygwin's build of `git.exe`.

Since your symlink talks about Python, I guess you're using Cygwin's build of Python, anyway?

**Comment by evandrocoan** [comment] 2019-03-02 15:21
I use both. When I open a `cmd.exe`, I have this:
```
C:\Users\Professional>where python
F:\Cygwin\bin\python
F:\Python\python.exe

C:\Users\Professional>where git
C:\Program Files\Git\cmd\git.exe
F:\Cygwin\bin\git.exe
```

But when I open `mintty.exe`, I have this:
```
Professional@PROFESSIONAL-PC$ where python
F:\Cygwin\bin\python
F:\Python\python.exe
Professional@PROFESSIONAL-PC$ where git
F:\Cygwin\bin\git.exe
C:\Program Files\Git\cmd\git.exe
```

This problem with Cygwin `python3` symlink, happened when I had created a git repository on the root of the Cygwin installation. Then,
1. I added all Cygwin files with `git add --all && git commit`
1. Checkout the Cygwin git repository on another Windows computer
1. Once there, all Cygwin installation was broken because all its symlinks as `python3` where broken.

To create the Cygwin git repository I used the SmartGit tool, which I launched Windows explorer, then, it defaulted to use the `C:\Program Files\Git\cmd\git.exe`, which seem to break git symlinks when adding them to a repository.

I think, it would only have worked, if I had launched `SmartGit` from a `mintty.exe` shell, then, `SmartGit` would have defaulted to use `F:\Cygwin\bin\git.exe`, which seems to correctly add Cygwin symlinks to a git repository when committing them.

**Comment by dscho** [comment] 2019-03-02 19:21
Indeed, you cannot easily mix Cygwin Git and Git for Windows, not when you require Cygwin features (such as Cygwin's symlinks) to be recognized.

Can we close this ticket, then, as this is not a bug in Git for Windows (it works as intended)?

**Comment by evandrocoan** [comment] 2019-03-02 23:27
Well, I am not sure, because there are two sides:
1. The first is that Git for Windows cannot add & commit every kind of file existent in Windows. Adding binary files shouldn't just be straightforward?
1. The second is that the kind of file it cannot add, can be added and committed by a "fork" a Git for Windows (Git for Cygwin). So, the question remains, what kind of thing Git for Cygwin is doing that Git for Windows is not doing?

It seems that the solution would be quite simple. As Git for Cygwin can handle more things than Git for Windows, I should just use Git for Cygwin. But I am not sure if Git for Cygwin is a direct fork from Git for Windows. May be both are directly forking the main git repository.

Therefore, there are two forks and programmer teams doing the same thing. Supporting a git command line client on Windows. Shouldn't these teams work together?

I researched and found this
1. https://cygwin.com/git.html (https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git)

By one side is nice to have two different projects because some times one project has a bug the other does not, then, for a production environment this is awesome because I can just change the git I am using and continue working.

Hence, I would suggest to keep this issue open and understand why there are some kind of binary files Git for Windows cannot correct add and commit. Is it a bug which should be reported somewhere else as in some library or tool Git for Windows use?

Although, I am not maintaining Git for Windows, so if this issue remains open, it would not be me which would look into it and fix it or forward a bug report somewhere else.

Some programmers just cannot see an issue open if they do not have the time or are not planing  to fix it, but even if they do not have the time or are not planing to fix it, it does not mean the issue does not exists. I would just recommend add some label like `very low priority` or some more creative name like `not planning to spend time on this` or `does it really needs fixing?`

I would not close this as an `won't fix` because I yet do not know the answer to the question `why not fix it?` or leave it there as an opened issue until someone else (which are not the actual maintainers) volunteer themselves to fix it?

One can argue, just because it is closed, it does not mean anyone cannot find it on the closed issues list and fix it. But, why someone would be looking for things to fix in the `closed` issues list? Then, just closing this would make it more difficult for some volunteer to find it, except the ones which found this issue in the closed list because they are having the exactly same problem.

As a last suggestion, it would be nice if Git for Windows could detect which kind of binary files it cannot correctly add and commit, then, issue an warning or error message to the user, so it know that when he checkout the files on another computer, the user will not get the files correctly, i.e., they are going to be in a broken state.

Then, this could be a new feature of Git for Windows, detect when it is adding and committing some file, but when that file is checked out somewhere else, it will be broke.

**Comment by dscho** [comment] 2019-03-03 09:27
@evandrocoan okay, then dig deeper.

Or I do, since I cannot even find a link to the description of Cygwin's symlink feature.

So I dug deeper, and found that `cmd //c attrib python3` (or Windows Explorer) showed that it is labeled as a system file before being committed, and when Git restores it, it is marked as a file.

When you now call `cmd //c attrib +S python3`, it is shown as a symlink again!

So now you have your explanation. The Windows-specific attributes are not only not tracked in Git, Git was never even prepared for such a possibility.

So you will be stuck with a workaround no matter what. At least now you know what the workaround would need to accomplish.

**Comment by dscho** [comment] 2019-03-03 09:33
> I cannot even find a link to the description of Cygwin's symlink feature.

Of course, now I found some pointers:

https://github.com/cygwin/cygwin/blob/30782f7de4936bbc4c2e666cbaf587039c895fd3/winsup/utils/path.cc#L128 and https://github.com/cygwin/cygwin/blob/30782f7de4936bbc4c2e666cbaf587039c895fd3/winsup/utils/path.cc#L165-L176

**Comment by evandrocoan** [comment] 2019-03-03 22:23
Thank you for your patience and dedication in maintaining git for windows!

I had ran `attrib +S python3`on the file after being checkout, and it was fixed! Black magic, isn't?

If git is not prepared to handle such thing, why Cygwin git can do it?

In the code you showed, there is this `local.dwFileAttributes & FILE_ATTRIBUTE_SYSTEM`, then, it means git is tracking whether the files are system files?

Or Cygwin git is hacking git and somehow managing to check the `File System` property and restoring this property when checking out the files?

Then, should I open a bug report on the main git project for tracking this `File System` property?

**Comment by dscho** [comment] 2019-03-04 15:21
> If git is not prepared to handle such thing, why Cygwin git can do it?

That's the wrong question.

The right question is: which Git is aware of Cygwin's hacks to emulate Unix symlinks on Windows? Because you are not talking about Windows features (which Git for Windows is aware of), but Cygwin features.

> In the code you showed, there is this `local.dwFileAttributes & FILE_ATTRIBUTE_SYSTEM`, then, it means git is tracking whether the files are system files?

The code I showed is *in Cygwin*. So no, it is not about Git at all.

> Or Cygwin git is hacking git and somehow managing to check the `File System` property and restoring this property when checking out the files?

No, the code I showed is the code in Cygwin that emulates symlinks via special-formatted files *marked as system files*.

> Then, should I open a bug report on the main git project for tracking this `File System` property?

You can, if you want to be criticized for even wanting to do such a dumb thing ;-)

Seriously again, first of all, you should not open a bug report at all, but dive deep into the code to patch it as you want it to be patched.

Second, you will want to do that in the Windows port of Git, as your problem is very, very specific to Cygwin, which is squarely Windows-only.

Third, you could start by implementing support for a `core.symlinks = cygwin` mode that teaches Git for Windows to interpret files as symbolic links that are marked as system files and whose contents start with `!<symlink>` and whose contents' remainder is a UTF-16LE BOM followed by a UTF-16LE-formatted, NUL-terminated string.

This would most likely require overriding [the platform-agnostic test for "core.symlinks"](https://github.com/git-for-windows/git/blob/2481c4cbe949856f270a3ee80c802f5dd89381aa/config.c#L1119-L1121) in [the Windows-specific config handling](https://github.com/git-for-windows/git/blob/2481c4cbe949856f270a3ee80c802f5dd89381aa/compat/mingw.c#L263-L290) to interpret the special value `"cygwin"`, which should set not only `has_symlinks = 1;` but also a new flag defined in `compat/mingw.c` and declared in `compat/mingw.h`, say `int emulate_cygwin_symlinks;`.

The reason why this flag cannot be local to `compat/mingw.c` is that the `compat/win32/fscache.c` code also needs to know about it (as it currently only interprets reparse point-based symlinks as symlinks).

Then, the `stat()`, `lstat()` and `readlink()` emulations in `compat/mingw.c` need to be updated to interpret those special files as symbolic links.

Finally, the [`create_symlink()`](https://github.com/git-for-windows/git/blob/v2.21.0.windows.1/compat/mingw.c#L2601-L2646) function needs to be taught to generate such system files when `emulate_cygwin_symlinks` is set.

**Comment by dscho** [comment] 2019-03-04 15:22
BTW I think that files can be marked as system files similar to how they are marked as hidden files, see how we do the latter in https://github.com/git-for-windows/git/blob/v2.21.0.windows.1/compat/mingw.c#L594-L605

**Closed** 2020-03-08 00:14 UTC
Labels: enhancement, git, up for grabs
