### ISSUE TITLE
Git in cmd.exe console have wrong encoding.

### ISSUE THREAD

**Issue by lygstate** [git-for-windows/git#65] opened 2015-04-04 09:25 UTC
C:\Users\luoyonggang>git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

×ÓõÄ git ÃüÁîÓУº
   add        Ìí¼ÓÎļþÄÚÈÝÖÁË÷Òý
   bisect     ͨ¹ý¶þ·ֲéÕҶ¨λÒýÈë bug µıä¸ü
   branch     Áгö¡¢´´½¨»òɾ³ý·Ö֧
   checkout   ¼ì³öһ¸ö·Ö֧»ò·¾¶µ½¹¤×÷Çø
   clone      ¿Ë¡һ¸ö°汾¿⵽һ¸öÐÂĿ¼
   commit     ¼Ç¼±ä¸üµ½°汾¿â
   diff       ÏÔʾÌύ֮¼䡢Ìύº͹¤×÷Çø֮¼äµȵĲîÒì
   fetch      ´ÓÁíÍâһ¸ö°汾¿âÏÂÔضÔÏóºÍÒýÓÃ
   grep       Êä³öºÍģʽƥÅäµÄÐÐ
   init       ´´½¨һ¸ö¿յÄ Git °汾¿â»òÖØÐ³õʼ»¯һ¸öÒѴæÔڵİ汾¿â
   log        ÏÔʾÌύÈÕ־
   merge      ºϲ¢Á½¸ö»ò¸ü¶࿪·¢Àúʷ
   mv         Òƶ¯»òÖØÃüÃûһ¸öÎļþ¡¢Ŀ¼»ò·ûºÅÁ´½Ó
   pull       »ñȡ²¢ÕûºÏÁíÍâµİ汾¿â»òһ¸ö±¾µطÖ֧
   push       ¸üÐÂԶ³ÌÒýÓúÍÏà¹صĶÔÏó
   rebase     ±¾µØÌύתÒÆÖÁ¸üÐºóµÄÉÏÓηÖ֧ÖÐ
   reset      ÖØÖõ±ǰHEADµ½ָ¶¨״̬
   rm         ´ӹ¤×÷ÇøºÍË÷ÒýÖÐɾ³ýÎļþ
   show       ÏÔʾ¸÷ÖÖÀàÐ͵ĶÔÏó
   status     ÏÔʾ¹¤×÷Çø״̬
   tag        ´´½¨¡¢Áгö¡¢ɾ³ý»òУÑéһ¸öGPGǩÃûµÄ tag ¶ÔÏó

ÃüÁî 'git help -a' ºÍ 'git help -g' ÏÔʾ¿ÉÓõÄ×ÓÃüÁîºÍһЩ¸ÅÄî°ïÖú¡£
²鿴 'git help <ÃüÁî>' »ò 'git help <¸ÅÄî>' ÒԻñȡ¸ø¶¨×ÓÃüÁî»ò¸ÅÄîµÄ
°ïÖú¡£

Warning: Your console font probably doesn't support Unicode. If you experience strange characters in the output, consider switching to a TrueType font
 such as Consolas!

C:\Users\luoyonggang>

**Comment by sschuberth** [comment] 2015-04-04 10:54
Have you read the warning and ensured that your console font supports Unicode? If not, there nothing Git can do about it.

**Comment by lygstate** [comment] 2015-04-04 10:56
@sschuberth  I am familiar with this issue, this comes from the fact, I you want to output correct unicode things into cmd.exe console, we should not directly output UTF8 string, instead, we need to 
output UTF16 string directly.

**Comment by dscho** [comment] 2015-04-04 18:15
@lygstate this is *really* a developers' preview. If you want to see this bug fixed, this is the perfect time to start digging into the code.

**Comment by lygstate** [comment] 2015-04-04 20:43
@dscho  Thanks for your works, I am busy on something, when I am free, I'll dig into this.

**Comment by lygstate** [comment] 2015-04-05 05:10
Looks like not the msys2 problem, it's just comes from the git.

```
bash: cls: 未找到命令
 MINGW64 ~ (master)
$ git
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

▒▒õ▒ git ▒▒▒▒▒У▒
   add        ▒▒▒▒ļ▒▒▒▒▒▒▒▒▒▒▒
   bisect     ͨ▒▒▒▒▒ֲ▒▒Ҷ▒λ▒▒▒▒ bug ▒ı▒▒
   branch     ▒г▒▒▒▒▒▒▒▒▒ɾ▒▒▒▒֧
   checkout   ▒▒▒һ▒▒▒▒֧▒▒·▒▒▒▒▒▒▒▒▒▒
   clone      ▒▒¡һ▒▒▒汾▒⵽һ▒▒▒▒Ŀ¼
   commit     ▒▒¼▒▒▒▒▒▒汾▒▒
   diff       ▒▒ʾ▒ύ֮▒䡢▒ύ▒͹▒▒▒▒▒֮▒▒ȵĲ▒▒▒
   fetch      ▒▒▒▒▒▒һ▒▒▒汾▒▒▒▒▒ض▒▒▒▒▒▒▒▒
   grep       ▒▒▒▒▒ģʽƥ▒▒▒▒▒
   init       ▒▒▒▒һ▒▒▒յ▒ Git ▒汾▒▒▒▒▒▒³▒ʼ▒▒һ▒▒▒Ѵ▒▒ڵİ汾▒▒
   log        ▒▒ʾ▒ύ▒▒־
   merge      ▒ϲ▒▒▒▒▒▒▒▒▒࿪▒▒▒▒ʷ
   mv         ▒ƶ▒▒▒▒▒▒▒▒▒һ▒▒▒ļ▒▒▒Ŀ¼▒▒▒▒▒▒▒▒▒
   pull       ▒▒ȡ▒▒▒▒▒▒▒▒▒▒İ汾▒▒▒һ▒▒▒▒▒ط▒֧
   push       ▒▒▒▒Զ▒▒▒▒▒ú▒▒▒صĶ▒▒▒
   rebase     ▒▒▒▒▒ύת▒▒▒▒▒▒▒º▒▒▒▒▒η▒֧▒▒
   reset      ▒▒▒õ▒ǰHEAD▒▒ָ▒▒״̬
   rm         ▒ӹ▒▒▒▒▒▒▒▒▒▒▒▒▒ɾ▒▒▒ļ▒
   show       ▒▒ʾ▒▒▒▒▒▒▒͵Ķ▒▒▒
   status     ▒▒ʾ▒▒▒▒▒▒״̬
   tag        ▒▒▒▒▒▒▒г▒▒▒ɾ▒▒▒▒У▒▒һ▒▒GPGǩ▒▒▒▒ tag ▒▒▒▒

▒▒▒▒ 'git help -a' ▒▒ 'git help -g' ▒▒ʾ▒▒▒õ▒▒▒▒▒▒▒▒һЩ▒▒▒▒▒▒▒▒▒
▒鿴 'git help <▒▒▒▒>' ▒▒ 'git help <▒▒▒▒>' ▒Ի▒ȡ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒

lygstate@lygstate-PC MINGW64 ~ (master)
$

```

**Comment by KamranMackey** [comment] 2015-04-05 05:40
@lygstate then fix it. However, your font might actually be messed up, because this isn't happening on my machine.

**Comment by lygstate** [comment] 2015-04-05 06:08
@KamranMackey  which langauge you are using? I am RPC/ code page 936

**Comment by dscho** [comment] 2015-04-05 11:04
> when I am free, I'll dig into this.

Please do. This project cannot work any other way.

**Comment by lygstate** [comment] 2015-04-05 16:47
@dscho 
It's seems the building procedure already have the problem
```
Generating catalog po/ru.msg
msgfmt --statistics --tcl po/ru.po -l ru -d po/
Generating catalog po/bg.msg
msgfmt --statistics --tcl po/bg.po -l bg -d po/
Generating catalog po/pt_br.msg
msgfmt --statistics --tcl po/pt_br.po -l pt_br -d po/
    * new Tcl/Tk interpreter location
Generating catalog po/ja.msg
msgfmt --statistics --tcl po/ja.po -l ja -d po/
Generating catalog po/it.msg
msgfmt --statistics --tcl po/it.po -l it -d po/
245 ▒▒▒ѷ▒▒▒▒▒Ϣ.
284 ▒▒▒ѷ▒▒▒▒▒Ϣ.
Generating catalog po/fr.msg
msgfmt --statistics --tcl po/fr.po -l fr -d po/
Generating catalog po/sv.msg
msgfmt --statistics --tcl po/sv.po -l sv -d po/
302 ▒▒▒ѷ▒▒▒▒▒Ϣ.
290 ▒▒▒ѷ▒▒▒▒▒Ϣ.
Generating catalog po/es.msg
msgfmt --statistics --tcl po/es.po -l es -d po/
Generating catalog po/hu.msg
283 ▒▒▒ѷ▒▒▒▒▒Ϣ▒▒6 ▒▒δ▒▒▒▒▒▒Ϣ.
msgfmt --statistics --tcl po/hu.po -l hu -d po/
Generating catalog po/vi.msg
msgfmt --statistics --tcl po/vi.po -l vi -d po/
200 ▒▒▒ѷ▒▒▒▒▒Ϣ▒▒7 ▒▒δ▒▒▒▒▒▒Ϣ.
276 ▒▒▒ѷ▒▒▒▒▒Ϣ▒▒4 ▒▒ģ▒▒▒▒Ϣ.
Generating catalog po/de.msg
304 ▒▒▒ѷ▒▒▒▒▒Ϣ.
msgfmt --statistics --tcl po/de.po -l de -d po/
288 ▒▒▒ѷ▒▒▒▒▒Ϣ.
    GEN gitk-wish
304 ▒▒▒ѷ▒▒▒▒▒Ϣ.
289 ▒▒▒ѷ▒▒▒▒▒Ϣ.
    SUBDIR perl
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/I18N.pm >blib/lib/Git/I18N.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Memoize/YAML.pm >blib/lib/Git/SVN/Memoize/YAML.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/IndexInfo.pm >blib/lib/Git/IndexInfo.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Prompt.pm >blib/lib/Git/SVN/Prompt.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Fetcher.pm >blib/lib/Git/SVN/Fetcher.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN.pm >blib/lib/Git/SVN.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Utils.pm >blib/lib/Git/SVN/Utils.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Migration.pm >blib/lib/Git/SVN/Migration.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Editor.pm >blib/lib/Git/SVN/Editor.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git.pm >blib/lib/Git.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Ra.pm >blib/lib/Git/SVN/Ra.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/Log.pm >blib/lib/Git/SVN/Log.pm
/usr/bin/perl.exe -pe "s<\Q++LOCALEDIR++\E></mingw64/share/locale>" <Git/SVN/GlobSpec.pm >blib/lib/Git/SVN/GlobSpec.pm
Manifying blib/man3/Git.3pm
Manifying blib/man3/Git.I18N.3pm
Manifying blib/man3/Git.SVN.Editor.3pm
Manifying blib/man3/Git.SVN.Fetcher.3pm
Manifying blib/man3/Git.SVN.Memoize.YAML.3pm
Manifying blib/man3/Git.SVN.Prompt.3pm
Manifying blib/man3/Git.SVN.Ra.3pm

```

**Comment by dscho** [comment] 2015-04-06 16:26
For the record, I *still* have no [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve).

**Comment by lygstate** [comment] 2015-04-06 17:04
@dscho  You can not reproduce it cause your locales is not chinese,
Open mingw64_shell.bat

```
$ echo $LANG
zh_CN.UTF-8
$export LANG=zh_CN.UTF-8
msgfmt
``
This procedure will reproduce the problem if you are lucky

**Comment by dscho** [comment] 2015-04-06 17:22
> This procedure will reproduce the problem if you are lucky

Hmm. I do not really feel that you have a lot of respect for my time here.

**Comment by lygstate** [comment] 2015-04-07 03:16
@dscho  You should respect my time too

**Comment by KamranMackey** [comment] 2015-04-07 03:19
@lygstate No, he's saying that he thinks that you don't have a lot of respect for his time.

**Comment by KamranMackey** [comment] 2015-04-07 03:26
@lygstate Also, stop submitting useless PRs & issues. Or at least make your
damn issues more detailed, please.

On Mon, Apr 6, 2015 at 9:16 PM, Yonggang Luo <notifications@github.com>
wrote:

> @dscho <https://github.com/dscho> You should respect my time too
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/git-for-windows/git/issues/65#issuecomment-90333979>.
>



-- 
- Kamran Mackey

**Comment by KamranMackey** [comment] 2015-04-07 03:28
@lygstate Also, please don't use the stupid Command Prompt for working with Git. Use `Git Bash` please.

**Comment by lygstate** [comment] 2015-04-07 03:42
@KamranMackey 
You should look carefully before judge me!
I am using BASH!

**Comment by lygstate** [comment] 2015-04-07 03:44
@KamranMackey I do not need you explain his statements

**Comment by elyscape** [comment] 2015-04-07 04:29
What's the active code page?  You can find this by running `cmd //c chcp`.

**Comment by dscho** [comment] 2015-04-07 06:54
Here is some potentially useful information. After running the following steps in a `cmd.exe`:

```cmd
C:\git-sdk-64>path=c:\git-sdk-64\mingw64\bin;c:\git-sdk-64\usr\bin;%PATH%

C:\git-sdk-64>set MSYSTEM=MINGW64

C:\git-sdk-64>set LANG=zh_CN.UTF-8
```

`msgfmt` says this:

```cmd
C:\git-sdk-64>msgfmt
msgfmt:
msgfmt --help
```

However, in `mintty` the following happens:

```bash
$ LC_ALL=zh_CN.UTF-8 msgfmt
C:\git-sdk-64\mingw64\bin\msgfmt.exe: û▒и▒▒▒▒▒▒▒▒ļ▒
▒▒▒ԡ▒C:\git-sdk-64\mingw64\bin\msgfmt.exe --help▒▒▒鿴▒▒▒▒▒▒Ϣ▒▒
```

This is despite setting the font to "Lucida Console" in both the `cmd` window and the `mintty` window.

Just to make sure that Chinese symbols can be displayed, I copied and pasted " 未找到命令" (from https://github.com/git-for-windows/git/issues/68) into both windows; in mintty, it worked fine, in the cmd window, I got five square boxes instead (and five question marks when switching back to the default font "Raster Fonts".

Further, the file `/usr/share/locale/zh_CN/LC_MESSAGES/gettext-tools.mo` appears to contain valid UTF-8 (you can pipe it into `less.exe` to see for yourself).

Next step is trying to guess the encoding of the output of `msgfmt`:

```bash
$ LC_ALL=zh_CN.UTF-8 msgfmt 2>&1 | hexdump -C
00000000  43 3a 5c 67 69 74 2d 73  64 6b 2d 36 34 5c 6d 69  |C:\git-sdk-64\mi|
00000010  6e 67 77 36 34 5c 62 69  6e 5c 6d 73 67 66 6d 74  |ngw64\bin\msgfmt|
00000020  2e 65 78 65 3a 20 c3 bb  d3 d0 b8 f8 b3 f6 ca e4  |.exe: ..........|
00000030  c8 eb ce c4 bc fe 0d 0a  ca d4 ca d4 a1 b0 43 3a  |..............C:|
00000040  5c 67 69 74 2d 73 64 6b  2d 36 34 5c 6d 69 6e 67  |\git-sdk-64\ming|
00000050  77 36 34 5c 62 69 6e 5c  6d 73 67 66 6d 74 2e 65  |w64\bin\msgfmt.e|
00000060  78 65 20 2d 2d 68 65 6c  70 a1 b1 b2 e9 bf b4 b0  |xe --help.......|
00000070  ef d6 fa d0 c5 cf a2 a1  a3 0d 0a                 |...........|
0000007b
```

So it appears to be valid UTF-8; Printing the first non-ASCII character from that hexdump succeeds to output something Chinese character like:

```bash
$ printf '\uc3bb\ud3d0\ub8f8\ub3f6\ucae4\uc8eb\ucec4\ubcfe'
쎻폐룸돶쫤죫컄볾
```

However, pasting this into Google Translate (sorry, I have no training on reading Chinese whatsoever) suggests that this is Korean instead, and fails to make sense of it (it suggests that the English translation reads "Ssyeotpye rumdwat jjwarsjyorb kyakborm", in other words "gobblediwog").

I could imagine, therefore, that the translations of gettext got mixed up somehow.

At this point, however, it *really* becomes impossible for somebody who is not even able to understand Chinese to investigate further.

**Comment by lygstate** [comment] 2015-04-07 07:00
@dscho So I prefer disable gettext in the first place by removing the whole /mingw64/share/locale
directory, before the gettext is fixed for mingw64.

**Comment by dscho** [comment] 2015-04-07 07:00
@lygstate is this really all you have to say, after I presented you with an example how *thorough* an investigation I expect of a competent developer?

**Comment by dscho** [comment] 2015-04-07 07:51
To clarify what I expect you to do if you want to provide helpful information:

- state -- clearly! -- whether the output of `msgfmt` is actually UTF-8 encoded Korean or whether it is actually Chinese
- investigate why msgfmt fails to display the output as UTF-8 in mintty:
 - Test whether you get obtain the relevant strings from the `gettext-tools.mo` file using other gettext tools and get it to display properly
 - Find out whether the `gettext-tools.mo` actually contains correct Chinese messages
 - Test whether starting mintty after setting the locale changes the output
 - Run `msgfmt` via `strace` to investigate whether there is an obvious problem with the encodings
 - If necessary, recompile gettext to understand where the encoding gets broken
- test whether `LC_ALL=C make` works around your issue.

And once you did that, please take the time to describe your findings *clearly* and in enough detail for others to understand.

Thank you in advance for your efforts.

**Comment by dscho** [comment] 2015-04-09 06:20
@lygstate are you still working on this, or should I close this ticket?

**Comment by lygstate** [comment] 2015-04-09 08:01
I am working on this, do not close this ticket.

**Comment by dscho** [comment] 2015-04-09 08:31
@lygstate good. So what is the progress of the past two days on working off of [the list I gave above](https://github.com/git-for-windows/git/issues/65#issuecomment-90433458)?

**Comment by lygstate** [comment] 2015-04-09 15:47
@kblees  Does this means we need to fix locale_charset upstream?

**Comment by lygstate** [comment] 2015-04-09 15:47
@kblees  Does this means we need to fix nl_langinfo upstream?

**Comment by lygstate** [comment] 2015-04-09 16:19
Seems not works yet, don't know why
```
$ git --version
git version 2.3.5.windows.6.2.gd846717

LUOYONGGANG@luoyonggang MINGW64 /usr/src/git (master)
$ git --help
▒÷▒▒▒git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

▒▒õ▒ git ▒▒▒▒▒У▒
   add        ▒▒▒▒ļ▒▒▒▒▒▒▒▒▒▒▒

```

**Comment by PhilipOakley** [comment] 2015-04-09 16:46
Hi @lygstate,
 Could you try `git --h` ? It should give a shorter output, allowing a tighter hunt for the problem. 

On my older msysgit bash (only thing I have here) I get:
```
 $ git -h
Unknown option: -h
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

while `git --help` is much longer (and without the "Unknown option: -h" line ;-).

Also, are you able to try other code page settings (y/n?) to see what they do, to see if there is a middle ground code that appears to work, while yoiur code page could be a difficult case.

**Comment by lygstate** [comment] 2015-04-09 17:34
@PhilipOakley  I am sorry, git --h output full English.

**Comment by lygstate** [comment] 2015-04-09 17:36
@PhilipOakley I am using `git --help >a.txt`
The content of `a.txt`'s encoding is GB2312, and that the correct characters, just the encoding is not correct.

**Comment by KamranMackey** [comment] 2015-04-09 18:07
Holy crap man, change your dang encoding to UTF-8,  that will fix all
encoding issues.

**Comment by lygstate** [comment] 2015-04-09 18:08
@KamranMackey  do you means $LANG or what?

**Comment by KamranMackey** [comment] 2015-04-09 18:10
@lygstate I guess.

**Comment by lygstate** [comment] 2015-04-09 18:11
@KamranMackey  $LANG is zh_CN.UTF-8

**Comment by KamranMackey** [comment] 2015-04-09 18:13
@lygstate Uh, have you tried to reproduce this issue in the actual Git Bash? It should be called `git-bash.exe`.

**Comment by kblees** [comment] 2015-04-09 21:25
@KamranMackey The problem is that gettext is a pure MinGW library, based on stock MSVCRT functionality, which does not support UTF-8.

PR #83 should fix the issue by explicitly telling gettext to use UTF-8 (rather than relying on MSVCRT's setlocale() or Win32 GetACP()).

@lygstate Can you verify that PR #83 works for you (and close the issue if it does)?

**Comment by PhilipOakley** [comment] 2015-04-09 21:37
> I am using git --help >a.txt
Ah, you had an extra hidden step (redirecting the output). It is worth 
showing these 'obvious' steps.

> The content of a.txt's encoding is GB2312, and that the correct 
> characters, just the encoding is not correct

So it is not the encoding of the output (from the git command) that is 
at fault. [have I understood correctly?]

Rather it is the interpretation of the correct (expected GB2312) 
characters by the display window [y/n?].

So, Can you try creating some alternate content for a.txt so that you/we 
can see which decoding it (the display window) is using.

Philip

**Comment by kblees** [comment] 2015-04-09 21:43
> So it is not the encoding of the output (from the git command) that is
at fault. [have I understood correctly?]

No, the git command (or rather: the gettext library used for i18n) should output UTF-8, as both mintty and git's native console emulation (in compat/winansi.c) expect UTF-8.

**Comment by lygstate** [comment] 2015-04-11 07:51
@kblees  Great, it's works now, I mark this as closed. Is this can be upstream?

**Closed** 2015-04-11 07:54 UTC
Labels: help wanted, msys2
