### ISSUE TITLE
Spelling mistake in installer for 2.27.0

### ISSUE THREAD

**Issue by mikepyne** [git-for-windows/git#2654] opened 2020-06-02 11:45 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? 64-bit; upgrading from 2.26.2.windows.1 to 2.27.0

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

64-bit
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1217]
```

The installer has a spelling mistake on the 'default behaviour' screen:
"Only ever fast-forard"; should be "fast-for**w**ard".

**Comment by mikepyne** [comment] 2020-06-02 11:46
![Screenshot](https://user-images.githubusercontent.com/9084903/83516512-196d4b00-a4cf-11ea-884e-4a967289224e.png)

**Comment by rimrul** [comment] 2020-06-02 11:53
Duplicate of #2652, already fixed.

**Closed** 2020-06-02 12:05 UTC
