### ISSUE TITLE
mintty.exe.stackdump problem in git

### ISSUE THREAD

**Issue by TahaMeziane** [git-for-windows/git#2691] opened 2020-06-16 16:52 UTC
![Capture](https://user-images.githubusercontent.com/66535132/84803650-2d01d100-affa-11ea-8ed3-6f5221a681b5.PNG)
I installed git (32bits version for windows 8.1). But when I want to launch git bash it doesn't open and I notice that a file named "mintty.exe.stackdump" was created. 
I don't know what is the problem ?
Can you give me a solution please ?

**Comment by Paultergeist** [comment] 2020-06-16 18:08
I thinks it's a duplicate of #2687

**Comment by dscho** [comment] 2020-06-16 21:25
This might indeed have the same underlying cause. @TahaMeziane it's late over here, so I cannot monitor [the build](https://dev.azure.com/git-for-windows/git/_build/results?buildId=57937&view=results), but once (or, if) it succeeds, a new snapshot will be automatically uploaded to https://wingit.blob.core.windows.net/files/index.html for you to test.

**Comment by dscho** [comment] 2020-06-17 08:54
@TahaMeziane please test again with the latest snapshot.

**Comment by NathanGibbs3** [comment] 2020-06-24 20:05
Had the same Issue on Windows 7 32 bit.
Installing the Snapshot for Thu, 18 Jun 2020 fixed it.
Thanks. :smile:

**Closed** 2020-06-25 10:30 UTC
Labels: duplicate
