### ISSUE TITLE
[2.5.2 64bit] Error in startup script:  couldn't read file "C:\Program Files\Git\cmd\mingw64\libexec\git-core\git-gui" no such file or directory

### ISSUE THREAD

**Issue by Benargeez** [git-for-windows/git#385] opened 2015-09-12 19:16 UTC
It seems like when I try to launch GIT GUI it looks in the wrong place for certain files. Either the installer is not functioning properly or GIT GUI is looking in the wrong place.

It is looking for: 
"C:\Program Files\Git\cmd\mingw64\libexec\git-core\git-gui"

But is actually located here:

"C:\Program Files\Git\mingw64\libexec\git-core\git-gui" 
("C:\Program Files\Git\\~~cmd~~\mingw64\libexec\git-core\git-gui")

cmd and mingw64 are in the same directory. cmd is not a parent directory of mingw64!

EDIT:

copying mingw64 into the cmd folder seems to work for the most part. This should be done by the installer in the first place.

**Comment by dscho** [comment] 2015-09-12 21:57
This is a duplicate of both https://github.com/git-for-windows/git/issues/382 and https://github.com/git-for-windows/git/issues/376.

**Closed by dscho** 2015-09-12 21:57 UTC
