### ISSUE TITLE
Git 2.7.0-64-bit installation error on windows 10

### ISSUE THREAD

**Issue by sadrulk** [git-for-windows/git#634] opened 2016-01-30 09:42 UTC
Error message displayed: "The signature of Git- 2.7.0-64-bit.exe is corrupt or invalid."
![git installation error](https://cloud.githubusercontent.com/assets/16971442/12694952/f05459aa-c74e-11e5-917f-94e0bc318a35.JPG)

**Comment by linquize** [comment] 2016-01-30 13:27
Duplicate of #592

**Closed** 2016-01-30 16:14 UTC
