### ISSUE TITLE
Garbled characters when running Angular tests

### ISSUE THREAD

**Issue by basseur** [git-for-windows/git#2793] opened 2020-08-18 07:32 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.28.0.windows.1
cpu: x86_64
built from commit: 77982caf269b7ee713a76da2bcf260c34d3bf7a7
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.17763.1282]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Not really.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I am using git Bash as it is.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

This is not a command issue but rather a visual issue which occurs when running
```ng test --code-coverage```

 - What did you expect to occur after running these commands?

I am expecting to see green checkmarks or red x-es (Screenshot taken using `2.24.0.windows.2`)

![image](https://user-images.githubusercontent.com/32487587/90482579-b9805b00-e133-11ea-98d5-e7dddb1b6cc2.png)

 - What actually happened instead?

I am seeing garbled characters.

![image](https://user-images.githubusercontent.com/32487587/90482673-dc127400-e133-11ea-9604-8283ed5c0840.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Not applicable.

### Further details

This was taken using `ng test --code-coverage`. However, this should not be an issue with Karma oder any of the node packages used.
This issue did not occur before upgrading from 2.24.0 to 2.28.0. The node packages or my repository was not changed in between the upgrade.

**Comment by dscho** [comment] 2020-08-18 09:00
Thank you for your bug report. The issue is most likely due to the Pseudo Console support that was added to Cygwin v3.1.x (even if said support is disabled, there seem to be some regressions, unfortunately).

In the Cygwin project, there seems to be active work on the Pseudo Console, so I think we will have to wait a bit to see whether those changes fix this (it would not make sense to try to work on this on our side at this stage because 1) working on the Cygwin runtime always takes way more time than one would think, a week for a simple bug is not unheard of, and 2) even if we came up with a fix, and even if Cygwin did not fix it independently, a fix might not apply after the currently-discussed refactoring).

Here are a couple options to work around this for the time being:

- You could try with Pseudo Console support enabled
- You could use ConHost instead of MinTTY (you can choose that option when reinstalling Git for Windows)
- You could try running through `winpty`
- You could stay with a Git version older than v2.27.0 for the time being (which was the first version that upgraded to MSYS2 runtime v3.1.x).

**Comment by basseur** [comment] 2020-08-18 09:13
Thank you for the comprehensive reply!

I will stick with version 2.28.0 for now, as this is more of a minor annoyance than a serious bug for me. Because of the additional color output it doesn't prevent me from seeing if the tests passed or failed.

**Comment by dscho** [comment] 2020-09-01 13:35
Seems that there is a work-around: `cmd //c chcp 65001`, but I think we have a good grasp on https://github.com/msys2/MSYS2-packages/issues/1974 and once that is resolved, this here bug will be fixed, too.

**Comment by dscho** [comment] 2020-09-24 10:29
Could you re-test with the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html), please?

**Comment by dscho** [comment] 2020-09-25 12:12
(Based on the feedback from related tickets, I assume that this ticket can be closed, too.)

**Closed** 2020-09-25 12:12 UTC
Labels: bug, msys2
