### ISSUE TITLE
SSL certificate validation

### ISSUE THREAD

**Issue by fliiiix** [git-for-windows/git#401] opened 2015-09-17 14:48 UTC
If I'm not mistaken all ssl certificates are validated against `curl-ca-bundle.crt`. 
But windows has it's own certificate center thing. 
My understanding is that it's not possible to use the windows certification center thing with git.

Are there any plans to support this? 
And anyone with a bit inside in the git code how hard would it be to implement it?

**Comment by dscho** [comment] 2015-09-17 16:43
Please feel free to search the issues before opening a new ticket, [as described in our guide lines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines).

This is a duplicate of https://github.com/git-for-windows/git/issues/301

**Closed by dscho** 2015-09-17 16:43 UTC
Labels: duplicate

**Comment by fliiiix** [comment] 2015-09-17 17:38
Ah sorry I tried the search but it looks like I was to stupid to use it.
