### ISSUE TITLE
When I quit a long git diff in sh.exe with CTRL+C, I cannot see anymore the commands I write in the console, but only their result

### ISSUE THREAD

**Issue by Siron777** [git-for-windows/git#800] opened 2016-06-23 07:28 UTC
### Setup

I have git 2.9.0.windows.1 (but the issue concerns older version too), 64 bits. I am on windows 7.
### Details

If I use git by launching the binary sh.exe provided with the git package, when I display to much information in the console, for example with a git diff, afterward, I am not able to see anymore what I write in the console (during the writing phase, if I press enter the command is displayed correctly). To fix the issue, I have to restart the console. 

I am not using git-bash.exe because I am using git through ConEmu which needs sh.exe. But the issue exist even bu using directly sh.exe, so this is not a ConEmu issue.

**Comment by dscho** [comment] 2016-06-24 10:13
Sorry, you lost me. Are you saying that the commands you try to launch after a `git diff`'s output is pasted are not echoed to the console? If so, is this issue also happening with Git Bash?

**Comment by Siron777** [comment] 2016-06-24 12:17
No problem, I realize it is indeed not very clear and in fact I can now narrow the issue:

1. I do a git diff in the console sh.exe which requires me to scroll (since the diff is long),
2. Then I quit it by a CTRL + C, 
3. Now, if I write a command in the console, I do not see what I write. But if I press ENTER to validate the command, I can see the output of the command in the console.
4. To fix the situation, I need to restart the console sh.exe.

I just realize that if I quit the diff with 'q' instead of CTRL+C, I do not have this issue. And this issue is not present with git bash, only with sh.exe which is the git console used by ConEmu.

**Comment by dscho** [comment] 2016-06-24 17:34
Okay, so it seems to be more of a ConEmu issue than a Git issue to me.

**Comment by Siron777** [comment] 2016-06-28 12:04
dscho: No this is not a ConEmu issue. I though that too at the beginning (and I created an issue on their bug tracker). But if I launch git directly with sh.exe, I have exactly the same problem. But maybe the issue is within sh.exe ?

jeffhostetler: Indeed, although I have not the knowledge to understand all this, the command "stty sane" fix the console :)

**Comment by dscho** [comment] 2016-06-28 13:02
> No this is not a ConEmu issue. I though that too at the beginning (and I created an issue on their bug tracker). But if I launch git directly with sh.exe, I have exactly the same problem

So "ConEmu" was a red herring. Might be better to change the description how to reproduce the issue without even mentioning ConEmu?

**Comment by simonthum** [comment] 2016-07-12 09:24
I think I know this one quite well, but it never bugged me hard enough to report. What I think happens is the git diff invokes a bunch of helpers (e.g. pdf to text) which seem to get the ctrl-c instead, causing havoc up the chain. With the caching of diff helper output, the problem more or less vanishes.

What always helps me is ctrl-C, ctrl-D or ctrl-Z until you're on a working promt again.

**Comment by PhilipOakley** [comment] 2016-07-12 20:46
An aside... I think I may be  getting a similar issue with plain bash (mintty) (on XP!) when I'm trying to copy and paste things, e.g. a carefully built up send-email (long line) for patches etc. Everything works OK unless I've accidently used a wrong control sequence at some point. I then seem to find that when I paste the long line, rather than it wrapping onto a new line when the column width is reached it overwrites from the beginning of the line. the history also then fails Usually if that (finger trouble) happens then I need to completely close the bash/mintty window and try again. I'll try and make better notes, in case it repeats...

**Comment by bgoscinski** [comment] 2017-01-02 21:12
On Windows 10 Home x64 without ConEmu
```sh
$ git --version --build-options
git version 2.11.0.windows.1
sizeof-long: 4
machine: x86_64
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
$ cat /c/Program\ Files/Git/etc/install-options.txt
Path Option: BashOnly
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Difftool: Disabled
```

I can repro with following steps
1. Open `Git Bash`
1. `cd` to any git repo
1. `git log` or `git diff` (when output doesn't fit window and is scrollable)
1. `ctrl + c`
1. type anything - it doesn't appear but hitting `enter` evaluates it

**Comment by ashelley** [comment] 2017-01-06 23:38
i can confirm that i have the exact same behavior using the repro from @bgoscinski using the same versions of git and windows.

**Comment by dscho** [comment] 2017-04-04 22:00
Is this still an issue with v2.12.2?

**Comment by dscho** [comment] 2017-05-15 20:06
I still cannot reproduce (Windows 10 Enterprise here), therefore I will close this for now.

**Closed by dscho** 2017-05-15 20:06 UTC
Labels: missing-info, unclear
