### ISSUE TITLE
Git for windows 2.6.3 installer rebase.exe crashes under Wine on OSX

### ISSUE THREAD

**Issue by virtuald** [git-for-windows/git#551] opened 2015-12-01 04:36 UTC
It's a rather esoteric use case, and the installer seems to actually work -- but the error is a bit annoying. Here's the console output from wine:

```
Unhandled exception: page fault on read access to 0x00000000 in 32-bit code (0x611870f5).
Register dump:
 CS:001b SS:0023 DS:0023 ES:0023 FS:1007 GS:000f
 EIP:611870f5 ESP:006bc2d4 EBP:006bc9d8 EFLAGS:00010202(  R- --  I   - - - )
 EAX:00000000 EBX:00000000 ECX:00000002 EDX:00002923
 ESI:006bc57a EDI:006bc380
Stack dump:
0x006bc2d4:  006bc9f4 006bc57a 611252c5 006bc57a
0x006bc2e4:  00000000 00002923 006bc47a 00000221
0x006bc2f4:  006bc3ec 006bca58 00000005 00000000
0x006bc304:  00000000 00000005 610033c1 00000038
0x006bc314:  006bc3f8 001e001c 006bc7fc 612fd17c
0x006bc324:  20000008 00000000 61003fac 612fd17c
0200: sel=1007 base=7ffc0000 limit=00000fff 32-bit rw-
Backtrace:
=>0 0x611870f5 in msys-2.0 (+0x1870f5) (0x006bc9d8)
  1 0x611252c5 in msys-2.0 (+0x1252c4) (0x006bc9d8)
  2 0x61127e90 in msys-2.0 (+0x127e8f) (0x00000000)
  3 0x61085b7b in msys-2.0 (+0x85b7a) (0x00000000)
  4 0x61086a0e in msys-2.0 (+0x86a0d) (0x00000000)
  5 0x61122d98 in msys-2.0 (+0x122d97) (0x006bcc68)
  6 0x61123172 in msys-2.0 (+0x123171) (0x006bcc68)
  7 0x61007518 in msys-2.0 (+0x7517) (0x006bcc68)
  8 0x61005f6b in msys-2.0 (+0x5f6a) (0x00000000)
  9 0x61006021 in msys-2.0 (+0x6020) (0x006bfed0)
  10 0x61007141 in msys-2.0 (+0x7140) (0x006bfed0)
  11 0x00418160 in rebase (+0x1815f) (0x006bfed0)
  12 0x7b846d7c in kernel32 (+0x36d7b) (0x006bfee8)
  13 0x7b8494fe in kernel32 (+0x394fd) (0x006bff28)
  14 0x7bc5d35c (0x006bff38)
  15 0x7bc5f501 (0x006bffb8)
  16 0x7bc5d322 (0x006bffd8)
  17 0x7bc3c879 (0x006bffe8)
0x611870f5: movzwl	0x0(%ebx),%ebx
Modules:
Module	Address			Debug info	Name (8 modules)
PE	  400000-  4b1000	Export          rebase
PE	40290000-40294000	Deferred        advapi32
PE	402f0000-402f3000	Deferred        netapi32
PE	40330000-40334000	Deferred        iphlpapi
PE	40350000-40354000	Deferred        ws2_32
PE	61000000-61500000	Dwarf           msys-2.0
PE	7b810000-7b866000	Export          kernel32
PE	7bc10000-7bc14000	Deferred        ntdll
Threads:
process  tid      prio (all id:s are in hex)
00000008 Git-2.6.3-32-bit.exe
	00000009    0
0000000c services.exe
	0000002f    0
	0000002e    0
	0000000e    0
	0000000d    0
00000012 explorer.exe
	00000016    0
	00000013    0
0000002c winedevice.exe
	00000033    0
	00000032    0
	00000031    0
	0000002d    0
00000034 Git-2.6.3-32-bit.tmp
	00000035    0
00000042 cmd.exe
	00000043    0
00000046 (D) C:\Program Files\Git\bin\rebase.exe
	00000047    0 <==
```

**Comment by dscho** [comment] 2015-12-01 09:49
As per [our guidelines](https://github.com/git-for-windows/git/wiki/Issue-reporting-guidelines), please [search the issues before reporting a bug](https://github.com/git-for-windows/git/issues?q=is%3Aissue+wine+is%3Aclosed) to avoid duplicate tickets. In your case, it looks like a duplicate of https://github.com/git-for-windows/git/issues/150.

**Closed by dscho** 2015-12-01 09:49 UTC
