### ISSUE TITLE
Packaging error - duplicated GCM

### ISSUE THREAD

**Issue by AnrDaemon** [git-for-windows/git#5044] opened 2024-07-06 10:03 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.45.2.windows.1
```

### Details

The released archives contains two copies of Git-Credential-Manager: one installed in `~\mingw64\libexec\git-core` as it should (except the core helper executable), and another in the `~\mingw64\bin` (all files this time).

**Comment by dscho** [comment] 2024-07-08 07:26
> The released archives contains two copies of Git-Credential-Manager: one installed in `~\mingw64\libexec\git-core` as it should (except the core helper executable), and another in the `~\mingw64\bin` (all files this time).

It is unfortunately quite unclear what you mean by "The released archives". If you are referring to the `.tar.bz2` archives, then I cannot see the problem here:

```console
$ tar tvf ~/Downloads/Git-2.45.2-64-bit.tar.bz2 | grep git-credential-manager
-rwxr-xr-x runneradmin/197121   81232 2024-06-03 10:01 mingw64/bin/git-credential-manager.exe
-rw-r--r-- runneradmin/197121    2225 2024-06-03 10:01 mingw64/bin/git-credential-manager.exe.config
-rw-r--r-- runneradmin/197121     1102 2024-06-03 10:01 mingw64/doc/git-credential-manager/LICENSE
-rw-r--r-- runneradmin/197121     2597 2024-06-03 10:01 mingw64/doc/git-credential-manager/NOTICE
-rw-r--r-- runneradmin/197121     6797 2024-06-03 10:01 mingw64/doc/git-credential-manager/README.md
-rw-r--r-- runneradmin/197121     6591 2024-06-03 10:01 mingw64/share/doc/git-doc/git-credential-manager.html
```

One copy. Not two. One in `mingw64/bin/`, none in `mingw64/libexec/git-core/`.

**Comment by AnrDaemon** [comment] 2024-07-08 10:21
Yes, the binary is only one, although it shouldn't be in `mingw64/bin`.
There are links to DLL's in `mingw64/libexec/git-core/`, but in reality, it is enough to place executables directly in there and don't pollute `mingw64/bin`.

**Comment by dscho** [comment] 2024-07-08 11:54
> Yes, the binary is only one, although it shouldn't be in `mingw64/bin`.

That is incorrect. It should be in `mingw64/bin/`, as `mingw64/libexec/git-core/` is for Git-internal stuff, and Git Credential Manager is a 3rd-party executable that is not part of Git itself.

> There are links to DLL's in `mingw64/libexec/git-core/`, but in reality, it is enough to place executables directly in there and don't pollute `mingw64/bin`.

You mean something like `Microsoft.AzureRepos.dll`? I.e.

```console
$ tar tvf ~/Downloads/Git-2.45.2-64-bit.tar.bz2 |grep Microsoft.Azure
-rwxr-xr-x runneradmin/197121   73552 2024-06-03 10:01 mingw64/bin/Microsoft.AzureRepos.dll
hrwxr-xr-x runneradmin/197121        0 2024-06-03 10:01 mingw64/libexec/git-core/Microsoft.AzureRepos.dll link to mingw64/bin/Microsoft.AzureRepos.dll
```

These hardlinks are there on purpose, to avoid DLL injection attacks. Technically, the Git Credential Manager dependencies would not need to be there because they only need to be in the same directory where the executable resides. Practically, it is too fragile to try to disentangle which DLLs do need to be hardlinked in `libexec/git-core/` and which ones do not.

And please don't use harsh judgments like "don't pollute `mingw64/bin`", even when you believe that you understand the reasons why things are the way they are. Harsh judgements are simply incompatible with the welcoming nature that Git for Windows' code of conduct asks every contributor to respect.

I will close this ticket as this is working as designed.

**Closed by dscho** 2024-07-08 11:54 UTC
Labels: unclear
