### ISSUE TITLE
Win10 system AMD64 architecture has the following problems

### ISSUE THREAD

**Issue by jiaxiaoxu** [git-for-windows/git#3802] opened 2022-04-15 15:26 UTC
### Once installed, run Git, the following error appears
- Version used: Git-2.35.3-64-bit.exe

```
C:\Users\Administrator>git
fatal: could not open '/dev/null' for reading and writing: No such file or directory
```

**Comment by rimrul** [comment] 2022-04-15 16:08
Can't reproduce this here.

**Comment by dscho** [comment] 2022-04-19 10:58
Looks like a duplicate of https://github.com/git-for-windows/git/issues/1016

**Closed** 2023-03-08 14:58 UTC
Labels: unclear
