### ISSUE TITLE
Unable to type uppercase characters in commit message

### ISSUE THREAD

**Issue by CoolNamesAllTaken** [git-for-windows/git#2712] opened 2020-06-23 02:12 UTC
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
Microsoft Windows [Version 10.0.18363.535]
(c) 2019 Microsoft Corporation. All rights reserved.
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash (MINGW64)

 - What commands did you run to trigger this issue? If you can provide a

Whenever I create a new commit, Vim opens up and displays the commit message. Bizarrely, I am unable to use the shift key to capitalize letters within my commit message (holding shift and typing a key results in no character being typed). Using caps lock works fine to type uppercase characters, and lowercase characters can be typed without issue. This problem is reproducible with the following command sequences.

```
# sequence A
git commit --amend

# sequence B
git add .
git commit

```
 - What did you expect to occur after running these commands?

I expected to be able to edit the commit message normally in Vim.

 - What actually happened instead?

I was able to edit the commit message in Vim, but was unable to type uppercase characters using the shift key.

**Comment by rimrul** [comment] 2020-06-23 05:40
Sounds like a duplicate of #2689.

Should be fixed in the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Closed** 2020-06-23 08:52 UTC
Labels: duplicate
