### ISSUE TITLE
git update-git-for-windows downgrades git from 2.19.2 to 2.19.1

### ISSUE THREAD

**Issue by createdbyjurand** [git-for-windows/git#1953] opened 2018-11-27 06:06 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

git version 2.19.2.windows.1
cpu: x86_64
built from commit: 26dcaa1b6b5fd862db3ec40983e33ff3432f1166
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.785]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VisualStudioCode
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git update-git-for-windows
```
 - What did you expect to occur after running these commands?

Nothing or new version of Git

 - What actually happened instead?

Downgrade to 2.19.1

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by lll000111** [comment] 2018-11-27 07:49
I just saw that too, but the popup windows said "2.19.17" as (implausible) version number. I double-checked my eyes but that's what I saw.

**Comment by jumoog** [comment] 2018-11-27 08:13
download the intaller manually helps

**Comment by lll000111** [comment] 2018-11-27 08:16
@jumoog We don't need a workaround (especially not this time when we already have the current version installed), we just report a problem :)

**Comment by Harmon758** [comment] 2018-11-27 10:51
I also received a prompt to downgrade to 2.19.1 when I have 2.19.2 installed:

![image](https://user-images.githubusercontent.com/9403740/49075872-56cb8b00-f1fd-11e8-8290-ab8c99911323.png)
![image](https://user-images.githubusercontent.com/9403740/49075960-8d090a80-f1fd-11e8-83f4-f646bda8fb52.png)

This [is due to](https://github.com/git-for-windows/git-sdk-64/blob/ebc41b7cbb97b896c59cb03f818a098f669a691d/mingw64/libexec/git-core/git-update-git-for-windows#L141-L142) https://api.github.com/repos/git-for-windows/git/releases/latest showing 2.19.1 as the lastest release, as can also be seen on https://github.com/git-for-windows/git/releases:

![image](https://user-images.githubusercontent.com/9403740/49076082-d35e6980-f1fd-11e8-9e52-24c82afdc612.png)

I believe this is because 2.19.2 was [a tag pushed to the repository without a title, description, or assets and without having a release formally created](https://github.community/t5/How-to-use-Git-and-GitHub/Why-last-release-is-not-marked-as-quot-latest-release-quot/m-p/1852/highlight/true#M573).
This should be easily resolved by publishing a new release through https://github.com/git-for-windows/git/releases/new using the existing tag.

**Comment by coldino** [comment] 2018-11-27 11:35
I received an automatic update prompt today, which tries to downgrade from the previously automatically-installed 2.19.2 to 2.19.1:
![image](https://user-images.githubusercontent.com/28345893/49078988-68318900-f237-11e8-9041-4b3b1a0c10b4.png)

On checking the GitHub releases I see 2.19.2 has been marked `pre-release` due to breaking bugs, but this information is not communicated to users at all during the automatic update process. Without scanning through the issues, I don't know whether allow the automatic downgrade - or if something nefarious is going on.

**Comment by Harmon758** [comment] 2018-11-27 12:06
@coldino [2.19.2](https://github.com/git-for-windows/git/releases/tag/v2.19.2) is released and is the [default download](https://git-scm.com/download/win) now.
You're referring to a [pre-release tag](https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1) prior to the 2.19.2 tag.
The "breakages" referred to in this pre-release are [breaking changes](https://github.com/git-for-windows/build-extra/blob/6d8ce0cb3bf27425a491718319016303fe6a9a5e/ReleaseNotes.md#bug-fixes), not bugs.
If you're not affected by them, there is no reason to downgrade.

**Comment by dscho** [comment] 2018-11-27 13:01
https://github.com/git-for-windows/git/releases/tag/v2.19.2.windows.1 is available, still, but was demoted to "pre-release" status because it has two serious bugs. See also this part of the description on that very page:

> **EDIT November 26th 2018**: marking as pre-release because of [two major breakages in this version](https://github.com/git-for-windows/build-extra/blob/6d8ce0cb3bf27425a491718319016303fe6a9a5e/ReleaseNotes.md#bug-fixes); Git for Windows v2.20.0 (which is slated for December 3rd) will fix them both.]

In other words, there will not be any v2.19.2(2) this close to v2.20.0.

**Closed by dscho** 2018-11-27 13:01 UTC

**Comment by coldino** [comment] 2018-11-27 22:36
There is certainly a discrepancy here.
* https://git-scm.com/download/win gives users 2.19.2.
* The auto-update system will try to downgrade users to 2.19.1.

If 2.19.2 has been demoted from being the *latest* then it should not be the default version offered for download.

This was not a clean way to handle reverting a release.

**Comment by dscho** [comment] 2018-11-28 09:05
>     * https://git-scm.com/download/win gives users 2.19.2.

Bummer. It should have updated by now.

> This was not a clean way to handle reverting a release.

Sorry, there was no good option. I already integrated an upgrade from OpenSSL v1.0.2p to v1.1.1a which I deemed possibly incurring new bugs, and therefore could not simply upgrade Git for Windows to v2.19.2(2).

Also, to be quite honest, it is quite a lot of work y'all let me do here on my own.

**Comment by JTBrinkmann** [comment] 2018-11-30 09:41
I can confirm that git-scm.com **still** offers 2.19.2 as download. See https://github.com/git/git-scm.com/issues/1278


> This was not a clean way to handle reverting a release.

If this is deemed worth the efford, maybe a routine could be found that also (automatically) addresses git-scm.com issue. Alternatively, a simpler way might be to push a 2.19.2(2) which simply reverts to the codebase of 2.19.1. This should might a smooth experience with little efford. The downside would be, that it would incorrectly imply this git-for-windows version would be based on git version 2.19.2.

**Comment by dscho** [comment] 2018-11-30 10:45
> Alternatively, a simpler way might be to push a 2.19.2(2) which simply reverts to the codebase of 2.19.1.

Are you going to do the work?

It's not as simple BTW as "revert the code base to v2.19.1". Git for Windows bundles many other components, e.g. OpenSSL. And that OpenSSL package in particular is a problem here, as it is a pretty steep upgrade from v1.0.2p to v1.1.1a, and for technical reasons, we *still* have to ship the v1.0.2p `.dll` files, even if `git.exe` does not link against them.

I understand that this comment was meant to be helpful. Unfortunately, in this instance it was particularly not so... :-(
