### ISSUE TITLE
git gui fails in rc2

### ISSUE THREAD

**Issue by techtonik** [git-for-windows/git#196] opened 2015-06-13 20:40 UTC
At first it shows:
```
couldn't execute "C:\Program Files\Git\mingw32\libexec\git-core\git-update-index.exe": invalid argument
couldn't execute "C:\Program Files\Git\mingw32\libexec\git-core\git-update-index.exe": invalid argument
    while executing
"error $err"
    (procedure "_open_stdout_stderr" line 16)
    invoked from within
"_open_stdout_stderr [concat $opt $cmdp $args]"
    (procedure "git_read" line 26)
    invoked from within
"git_read update-index  -q  --unmerged  --ignore-missing  --refresh  "
    (procedure "rescan" line 40)
    invoked from within
"rescan ui_ready"
    (procedure "do_rescan" line 2)
    invoked from within
"do_rescan"
    ("after" script)
```

And then hangs with "Refreshing file status..."

**Comment by dscho** [comment] 2015-06-16 09:23
Please provide a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve).

**Comment by techtonik** [comment] 2015-06-16 10:50
1. Get Windows Vista 32
2. Install rc3
3. Run git gui
4. Enjoy the error

**Comment by dscho** [comment] 2015-06-20 15:44
@techtonik obviously you also need a repository in which you see that error. And guess what, I would not have been unable to reproduce your error, that is why I asked politely for an MCVE in the first place.

Maybe you find it in you to provide a step-by-step guide that lets other people reproduce the issue consistently. It could be, for example, that the problem only occurs in specific directories but [the instructions](https://github.com/git-for-windows/git/issues/196#issuecomment-112384036) did not even list that, they completely missed out on pretty much anything. They did not even say *how* Git GUI was started, and that is pretty relevant. You can start Git GUI from the context menu in the Explorer, via Start Menu, via Git CMD and via Git Bash.

Please understand that I want to help you, but I am getting the impression that it may not be as gratifying an experience for me as I would have expected originally.

**Comment by techtonik** [comment] 2015-06-20 17:24
@dscho I see. Do you have a diag script that can dump needed info about the installation? If I reinstall it, the current state may change. Answers:

Not using repository.
Installed from installer https://github.com/git-for-windows/git/releases/tag/v2.4.4.windows.2 Git-2.4.4.2-3rd-release-candidate-32-bit.exe (not sure about the options).
Occurs in pretty much any directory, for example `C:\wesnoth`.
Executed `git gui` from standard `cmd.exe` window after changing dir into project location.

![image](https://cloud.githubusercontent.com/assets/515889/8268306/c93cc868-1789-11e5-96f4-9a64df7589c7.png)

**Comment by techtonik** [comment] 2015-06-20 17:25
Correction - Occurs in pretty much any directory **with clone**, e.g. with `.git` inside.

**Comment by dscho** [comment] 2015-06-21 13:02
Git GUI works *here*. In pretty much any directory with an associated Git repository:

![git-gui-works](https://cloud.githubusercontent.com/assets/127790/8271719/5a518b1e-1815-11e5-9b39-9f2e2170eee6.png)

So something fishy is going on in your setup. You could try to call `Git Bash`, change the directory to a Git-tracked one and then call `GIT_TRACE=1 git gui` to try to diagnose the situation better.

**Comment by techtonik** [comment] 2015-06-21 14:32
I executed git gui **from standard cmd.exe window**. And you're running it from cygwin window.

**Comment by techtonik** [comment] 2015-06-21 14:35
With `GIT_TRACE=1` the error windows changes to this:

![image](https://cloud.githubusercontent.com/assets/515889/8272017/c98da44c-183b-11e5-8f85-cdc29ed5fa54.png)

**Comment by dscho** [comment] 2015-06-21 15:29
> I executed git gui from standard cmd.exe window. And you're running it from cygwin window.

I was actually running from the Git Bash, as [hinted earlier](https://github.com/git-for-windows/git/issues/196#issuecomment-113784028).

> With GIT_TRACE=1 the error windows changes to this:

Oh yes, that's right, Git GUI and `GIT_TRACE=1` are incompatible. But there is a way out: as per [the git man page](https://github.com/git/git/blob/v2.4.4/Documentation/git.txt#L963-L982):

> [...] if the variable is set to an absolute path (starting with a '/' character), Git will interpret this as a file path and will try to write the trace messages into it.

**Comment by techtonik** [comment] 2015-06-21 17:56
Setting to absolute path doesn't work. Git GUI thinks that root filesystem is at `%programfiles%\Git`.

    > set GIT_TRACE=/__py/trace.log
    > git gui

![image](https://cloud.githubusercontent.com/assets/515889/8272747/dacbb7d2-1857-11e5-88ae-d03d24acc2ea.png)

Looks like Git should borrow Python code for dealing with paths in cross-platform way.

**Comment by dscho** [comment] 2015-06-21 18:13
Did you create a `C:\Program Files\Git\__py` directory? If not, it is totally understandable that Git refuses to write to that file. And it even says so: No such file or directory.

**Comment by dscho** [comment] 2015-06-21 18:14
And if you mean the `C:\__py` directory, you should specify *that*. Because as far as the POSIX emulation of the Bash is concerned, the root directory `/` *is* `C:\Program Files\Git`. You see, in Windows there *is no* root directory. There are root director*ies*, but that is not the same.

**Comment by techtonik** [comment] 2015-06-21 18:57
> Did you create a C:\Program Files\Git\__py directory?

`C:\Program Files\Git` is a installation directory for Windows installer. It is r/o as required by Windoze. I didn't intend to write there, because I gave path to the absolute dir `/__py/trace.log` as requested. And the file is actually there even with the error, but it is not descriptive:
```
20:55:19.363919 git.c:557               trace: exec: 'git-gui'
20:55:19.363919 run-command.c:347       trace: run_command: 'git-gui'
```

> And if you mean the C:\__py directory, you should specify that

I did specify *that*. If you mean that I need to add `C:\` to absolute path, then if I do `set GIT_TRACE=C:\__py\trace.log` I got another error.

![image](https://cloud.githubusercontent.com/assets/515889/8272924/dd802456-185f-11e5-8178-547c508ee54f.png)

`trace.log` contents are now different:
```
21:52:31.829719 git.c:557               trace: exec: 'git-gui'
21:52:31.829719 run-command.c:347       trace: run_command: 'git-gui'
21:52:32.083719 git.c:348               trace: built-in: git 'version'
21:52:32.143719 git.c:348               trace: built-in: git 'rev-parse' '--git-dir'
21:52:32.162719 git.c:348               trace: built-in: git 'rev-parse' '--show-prefix'
21:52:32.182719 git.c:348               trace: built-in: git 'config' '--null' '--list'
21:52:32.210719 git.c:348               trace: built-in: git 'rev-parse' '--show-toplevel'
21:52:32.255719 git.c:348               trace: built-in: git 'rev-parse' '--is-bare-repository'
21:52:41.078719 git.c:348               trace: built-in: git 'rev-parse' '--verify' 'HEAD'
```

Why don't you choose Python or Go? They have solid cross-platform API instead of POSIX emulation hacks.

> You see, in Windows there is no root directory. There are root directories, but that is not the same.

I don't see. The [man page](https://github.com/git/git/blob/v2.4.4/Documentation/git.txt#L963-L982) talks about absolute paths, not about root directory, and paths starting with `/` are absolute on Windows.

**Comment by dscho** [comment] 2015-06-22 09:33
> > Did you create a C:\Program Files\Git__py directory?
> 
> C:\Program Files\Git is a installation directory for Windows installer. It is r/o as required by Windoze.

True, but you explicitly asked for the log file to be inside `/__py/` which *does* get translated to `C:\Program Files\Git\__py`. So all that means is that you should have specified another, correct location.

> Why don't you choose Python or Go? They have solid cross-platform API instead of POSIX emulation hacks.

You are welcome to work on that front.

> trace.log contents are now different:

That trace looks incomplete: it does not mention `update-index`, yet that command is obviously called in order to produce the originally reported issue.

Are you *certain* that there is no mention of `update-index` in the `trace.log` file?

**Comment by techtonik** [comment] 2015-06-22 10:47
> True, but you explicitly asked for the log file to be inside /__py/ which does get translated to C:\Program Files\Git\__py. So all that means is that you should have specified another, correct location.

If all paths are translated to `C:\Program Files\Git` then I see no way to specify that on Windows. Wait..
`set GIT_TRACE=/../../__py/trace.log` seem to do the trick, but there is still the yellow error box as above.

> Are you certain that there is no mention of update-index in the trace.log file?

Yes. This is the full `trace.log` message. Isn't the yellow box warn about that GIT_TRACE value is ignored by GUI?

And `git gui` hangs with "Refreshing file status..." 

![image](https://cloud.githubusercontent.com/assets/515889/8280324/0f3e645a-18e5-11e5-998a-861f121c2caa.png)

**Comment by dscho** [comment] 2015-06-22 11:27
> If all paths are translated to C:\Program Files\Git then I see no way to specify that on Windows.

No, that is a misunderstanding.

To replicate POSIX semantics for Bash and Perl, we need a single "root" directory, referenced by `/`. Since this does not exist in Windows -- and would disagree with Windows' file system layout -- the MSys2 strategy to handle that is to declare the directory relative to `usr\bin\bash.exe` as root directory.

So yes, `/hello` references `C:\Program Files\Git\hello` when you call it from an installed Git for Windows.

However, there are *of course* ways to reference other directories. They are "mounted", as is the POSIX convention. To reference `C:\hello`, you would write `/c/hello`.

> > Are you certain that there is no mention of update-index in the trace.log file?
> 
> Yes. This is the full trace.log message. Isn't the yellow box warn about that GIT_TRACE value is ignored by GUI?

Quite possibly. Which means that you will have to edit Tcl code yourself to debug further. My guess is that the problem lies somewhere around line 307 in `C:\Program Files\Git\mingw32\share\git-gui\lib\checkout_op.tcl`.

For the record, I installed a 32-bit XP (that's the only 32-bit Windows to which I have access right now) and tried to reproduce the failure you reported, failing. Something else must be going on in your setup that is very, very strange and very, very different from everything in my setups.

It would be good of you to think of everything that might be set up in a non-standard way on your side. For future record: it is always good to think of such things (e.g. "I have Vista", "at work, I have to use LDAP", "Norton Antivirus is installed and running") and specify them in the report, to avoid a lot of unnecessary back and forth and failed attempts to find the root of the problem.

**Comment by techtonik** [comment] 2015-06-22 11:53
> To reference C:\hello, you would write /c/hello.

Tried. Nothing new in the `trace.log`

> 32-bit XP (that's the only 32-bit Windows to which I have access right now) 

I don't think it is related to platform bitness. Have you tried it on any vista, 7, or newer?

> For future record: it is always good to think of such things (e.g. "I have Vista", "at work, I have to use LDAP", "Norton Antivirus is installed and running") and specify them in the report, to avoid a lot of unnecessary back and forth and failed attempts to find the root of the problem.

It is always good to have good configuration detection scripts and error messages that don't require manual back and forth from users. It already takes a lot of time. So I'd wait until https://github.com/git-for-windows/git/issues/218 is fixed.

**Comment by dscho** [comment] 2015-07-02 09:04
It appears that this problem cannot be reproduced, so I am closing the ticket.

**Closed by dscho** 2015-07-02 09:04 UTC
Labels: missing-info
