### ISSUE TITLE
'git svn' doesn't work anymore in v2.33.0.2_64 bits version

### ISSUE THREAD

**Issue by sbordoni70** [git-for-windows/git#3403] opened 2021-08-31 13:41 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - v2.33.0.2_64 bits setup

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.1165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

no

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

cmd, powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn
(but the problem is present for any of 'git svn *' commands).
```
 - What did you expect to occur after running these commands?

help screen about 'svn' params branch

 - What actually happened instead?

```C:\Users\WDAGUtilityAccount>git svn
Can't load '/usr/lib/perl5/vendor_perl/auto/SVN/_Core/_Core.dll' for module SVN::_Core: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line 193.
 at /usr/lib/perl5/vendor_perl/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/SVN/Core.pm line 5.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
Compilation failed in require at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

**Comment by rimrul** [comment] 2021-08-31 13:51
Duplicate of #3392, #3397, #3402.

Please try the latest snapshot.

**Closed** 2021-08-31 13:51 UTC
Labels: duplicate

**Comment by sbordoni70** [comment] 2021-08-31 14:16
- I downloaded the 'latest snapshot'
- I opened my Windows Sandbox and copied the file
- I ran the setup and clicked always the 'next' button
- I opened the Command Prompt
- I typed 'git svn'

from what I can see, it is working fine (ie 'Can't load...' problem doesn't occur anymore).

I also tried a couple of other 'svn' commands, but they worked fine.
(I had no repo, so they gave the proper error).

**Comment by ahsan-kaukab** [comment] 2022-10-13 14:29
I have the same issue on widowns 10 with old git version :
D:\Project_dir>git svn clone https://svn.dpdev.com/svn/Retron_4/trunk/Software/RF2_PCB_B/RF2B-new
Can't load '/usr/lib/perl5/vendor_perl/auto/SVN/_Core/_Core.dll' for module SVN::_Core: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line 193.
 at /usr/lib/perl5/vendor_perl/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/SVN/Core.pm line 5.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
Compilation failed in require at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.

**Issue is by using updating the git on windows 
Actually running following command :
C:\> git update-git-for-windows
ORRR
C:\> git update **

**Comment by dscho** [comment] 2022-10-17 13:04
> with old git version :

As a general rule, I do not support old Git versions. Only new Git versions. They are the ones with fixes.
