### ISSUE TITLE
Git.exe 2.12.2.1 crashes

### ISSUE THREAD

**Issue by Lexey** [git-for-windows/git#1125] opened 2017-04-04 16:48 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

64 bit from git-scm.com

```
$ git --version --build-options

git version 2.12.2.windows.1
built from commit: 212247dd6345c820deeae61fcdf2f10cea10525a
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

Windows 7 x64

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Path Option: Cmd
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing special

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git.exe status --porcelain -z --untracked-files
```
 - What did you expect to occur after running these commands?

Get a list of modified files.

 - What actually happened instead?

Git.exe crashes.

The following is logged to the Event log:
Faulting application name: git.exe, version: 2.12.2.1, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 6.1.7601.19018, time stamp: 0x560a0083
Exception code: 0xc0000005
Fault offset: 0x000000000004c579
Faulting process id: 0x3204
Faulting application start time: 0x01d2ad62012058dc
Faulting application path: C:\Program Files\Git\mingw64\bin\git.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: 3eebc5fc-1955-11e7-a70f-fcaa1457a06b

Here is the stack trace from the VS debugger:
 	ntdll.dll!strncmp()	Unknown
>	git.exe!0000000001408706()	Unknown
 	git.exe!0000000001408c6e()	Unknown
 	git.exe!0000000001490088()	Unknown
 	[External Code]	

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unfortunatetely, it is a private repository.

**Comment by dscho** [comment] 2017-04-04 18:50
This smells like a duplicate of #1111. Can you test the [snapshot installer or portable Git](https://wingit.blob.core.windows.net/files/index.html) to see whether your issue has the same root cause, hence fixed?

**Comment by Lexey** [comment] 2017-04-04 20:00
Will try it tomorrow.

**Comment by Lexey** [comment] 2017-04-05 09:56
Snapshot version works fine.

**Comment by dscho** [comment] 2017-04-05 14:35
> Snapshot version works fine.

Perfect! Thanks for testing.

**Closed by dscho** 2017-04-05 14:35 UTC
