### ISSUE TITLE
2.35.0.rc0.windows.1: git fsck claims repository is corrupt, old versions don't agree

### ISSUE THREAD

**Issue by t-b** [git-for-windows/git#3627] opened 2022-01-12 13:49 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.35.0.rc0.windows.1
cpu: x86_64
built from commit: 616161508dff4ec625d168ea60961aa61b4cfd75
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1415]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ cat /etc/install-options.txt
Editor Option: VIM
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: ConHost
Git Pull Behavior Option: Rebase
Use Credential Manager: Disabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nope.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

The problem is that I can't clone a certain repo anymore with 2.35.rc0. It works with 2.34.1.windows.1. I could boil it down to fsck being the culprit.
```
// git version 2.35.0.rc0.windows.1
$ git fsck --strict
Checking object directories: 100% (256/256), done.
error: bad object header0/1169)
error: bad object header
error: unknown object type -1 at offset 11668635 in .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
error: cannot unpack 25a7f77c7ec8b95d092e2c9c2ababf7359e6cbff from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack at offset 11668635
error: bad object header
error: bad object header
error: unknown object type -1 at offset 457465481 in .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
error: cannot unpack 21847c9e9498c581e7ee4600861f5df7b91592b8 from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack at offset 457465481
error: bad object header
error: bad object header
error: unknown object type -1 at offset 663048891 in .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
error: cannot unpack a58e599844e71c0858cd9d7b1c8ca6b18b320739 from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack at offset 663048891
error: bad object header
error: unknown object type -1 at offset 663048891 in .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
error: failed to read delta base object a58e599844e71c0858cd9d7b1c8ca6b18b320739 at offset 663048891 from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
error: cannot unpack b32c3b2a36506d242856dc7c1e2fb66897ea86ce from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack at offset 761108628
Checking objects: 100% (1169/1169), done.
broken link from    tree 32d8475c5ac5dc92cb1496851b632561928ed161
              to    blob a58e599844e71c0858cd9d7b1c8ca6b18b320739
missing blob a58e599844e71c0858cd9d7b1c8ca6b18b320739

// git version 2.34.1.windows.1
$ git fsck --strict
Checking object directories: 100% (256/256), done.
Checking objects: 100% (1169/1169), done.
```
 - What did you expect to occur after running these commands?
 
That fsck works.

 - What actually happened instead?

Fsck complains.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

I tried fast-export with --anonymize but that did not show the problem. So [here](https://byte-physics.de/Downloads/repo-215242cf1abc811faff7b19cf36652660be1bb95395878a53267523d4c2625a8.zip) is the link to the repo. This repo is semi-private, so please *don't* upload the repo anywhere else and tell me when I can remove it again. The hash like part of the filename is a SHA256 one of the contents.

**Comment by dscho** [comment] 2022-01-12 13:53
> This repo is semi-private

Please remove it immediately if it is not public.

**Comment by t-b** [comment] 2022-01-12 14:01
I meant that I said. It is okay to share on my website for this specific issue.

**Comment by dscho** [comment] 2022-01-13 16:20
> $ git fsck --strict
> Checking object directories: 100% (256/256), done.
> error: bad object header0/1169)
> error: bad object header
> error: unknown object type -1 at offset 11668635 in .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack
> error: cannot unpack 25a7f77c7ec8b95d092e2c9c2ababf7359e6cbff from .git/objects/pack/pack-896d4dbf477809ccbf821081124d1dc4d7d1cad0.pack at offset 11668635

If I were you, I would try to use the "old" Git version to look at that commit via `git cat-file -p 25a7f77c7ec8b95d092e2c9c2ababf7359e6cbff`.

**Comment by t-b** [comment] 2022-01-13 16:47
@dscho The repo is referenced above.

**Comment by t-b** [comment] 2022-01-13 21:24
Here is a recipe:

```
$ mkdir test
$ dd if=/dev/zero of=data.bin count=1000000
1000000+0 records in
1000000+0 records out
512000000 bytes (512 MB, 488 MiB) copied, 9.61109 s, 53.3 MB/s
$ ls -lh
total 489M
-rw-r--r-- 1 thomas 197121 489M Jan 13 22:21 data.bin
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test
$ git init
Initialized empty Git repository in C:/Users/thomas/test/.git/
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git add data.bin
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git commit -m "changes"
[main (root-commit) d0d34a7] changes
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 data.bin
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git fsck --strict
Checking object directories: 100% (256/256), done.
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git gc
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 12 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (3/3), done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git fsck --strict
Checking object directories: 100% (256/256), done.
error: bad object header0/3)
error: bad object header
error: unknown object type -1 at offset 139 in .git/objects/pack/pack-42bad39fda41b1b218f437ff54a602f2bf15dc6b.pack
error: cannot unpack 350873237a4adb589ef61eae5e54c0eb73824c66 from .git/objects/pack/pack-42bad39fda41b1b218f437ff54a602f2bf15dc6b.pack at offset 139
Checking objects: 100% (3/3), done.
Verifying commits in commit graph: 100% (1/1), done.
(base)
thomas@Win10-Thomas-PC MINGW64 ~/test (main)
$ git --version
git version 2.35.0.rc0.windows.1
```

I've therefore removed my repo.

**Comment by rimrul** [comment] 2022-01-15 13:28
I can reproduce this in `rc0`, but not in `rc1`, it seems to be fixed. Could you check if the new release candidate fixes this issue for you?

**Comment by dscho** [comment] 2022-01-15 16:42
I bet the fix is in a5c97b016421.

**Comment by dscho** [comment] 2022-01-15 17:33
And sure enough, the fix bisects to https://github.com/git-for-windows/git/commit/a5c97b016421a2869b460bbf6bdcd43dc186d433. So this is "magically" fixed in -rc1, by virtue of the Git maintainer [providing a patch](https://lore.kernel.org/git/xmqq4k68u30t.fsf@gitster.g/) in response to [a thorough bug report to the mailing list](https://lore.kernel.org/git/5ab9257c-9eba-a171-86d6-3fe7d3a4faec@syntevo.com/) that even went so far as identifying the commit that introduced the bug.

@t-b quite honestly, I am surprised. Surprised that you did not investigate the problem yourself. Surprised that such an excellent, thorough bug report did not originate with someone of your caliber. It's not like you are any random run-of-the-mill Git user. You are in one exclusive club:

```console
$ git for-each-ref | sed -n 's/ .*\.\(windows\|msysgit\)\..*//p' | xargs git log --no-walk --pretty="%cn %h %d" | grep -v '^\(Johannes Schindelin\|GitHub\|dscho\) ' | sed 's/[0-9a-f]\+  (.*//' | sort | uniq -c | sort -nr
     14 Pat Thoyts
      6 Victoria Dye
      5 Derrick Stolee
      4 Jameson Miller
      1 Thomas Braun
      1 Stepan Kasal
      1 Steffen Prohaska
      1 Heiko Voigt
      1 Erik Faye-Lund
```

Only ten people in this universe (including you) can claim that they released an official Git for Windows version, and I would expect _each_ of these Tenacious Ten to be _quite_ capable of figuring out _any_ Git problem themselves, and not need to leave the entire bug search to others. Render me very puzzled.

**Closed by dscho** 2022-01-15 17:33 UTC
Labels: unclear

**Comment by t-b** [comment] 2022-01-17 11:24
I don't have time anymore to hunt bugs in git. I would have thought that a proper bugreport with reproduction repo would suffice. In addition the bug was not present on x64 linux.

**Comment by changyuheng** [comment] 2022-01-19 03:29
Having a similar issue with 2.35.0.rc0:
![image-2022-01-19-10-08-54-311](https://user-images.githubusercontent.com/1842626/150058710-717a9c29-9df3-41a4-808d-e690d903420e.png)

https://github.com/git-for-windows/git/issues/3627#issuecomment-1013682580
Same here

**Comment by dscho** [comment] 2022-01-19 06:57
@changyuheng and did -rc1 also fix it for you?

**Comment by changyuheng** [comment] 2022-01-19 06:59
Yes sir, that's what I meant by same here.
