### ISSUE TITLE
worktree is set to the wrong path when git init is started into a hardlink directory

### ISSUE THREAD

**Issue by SamuelEtterlen** [git-for-windows/git#2273] opened 2019-07-25 08:05 UTC
- [ X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit? 64 bits

```
$ git --version --build-options

c:\OSC\WORKSPACES\myProject>git --version --build-options
git version 2.22.0.windows.1
cpu: x86_64
built from commit: d003d728ffa6c0006da875ec6318d3f6b28a4ddb
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

c:\OSC\WORKSPACES\myProject>cmd.exe /c ver

Microsoft Windows [Version 10.0.14393]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

> type "C:\Program Files\Git\etc\install-options.txt"

c:\OSC\WORKSPACES\myProject>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: Notepad++
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
mkdir c:\temp
mkdir d:\destdir
cd temp
mklink /H sourcedir d:\destdir
cd sourcedir
git clone <myrepo> myProject
cd myProject
git init
```
 - What did you expect to occur after running these commands?

I except to have myProject/.git/config file with no worktree attribut 

 - What actually happened instead?

the myProject/.git/config file contains worktree=D:\destdir\myProject

This is wrong because I start git init into c:\temp\sourcedir\myProject and not in d:\destdir\myProject.
The consequence is that I'm unable to any other git commands from c:\temp\sourcedir\myProject (getting the following error: 
fatal: C:/Program Files/Git/mingw64/libexec/git-core\git-submodule cannot be used without a working tree.

(The same behavour occurs in Jenkins with the scmResolve command which is also doing a git init in the same wait and then all my pipeline is failing.)

**Comment by dscho** [comment] 2019-07-25 10:02
Interesting way to use Git ;-)

First of all, the easy workaround is to call `git config --unset core.worktree`, I guess.

But more interesting: which command sets this? The `git clone` command? Or the `git init` command (which is actually unnecessary, as `git clone` already initialized the repository)?

**Comment by SamuelEtterlen** [comment] 2019-07-25 13:23
Hi,

I'm using it in this way because it's a part of a Jenkins Pipeline which can be started on different servers. For this reason I need to set a Symlink to a folder location where I've enough space ;)

So the command which set the worktree attribute is git init.
The git clone command generate the config file. The git init command update it.

**Comment by dscho** [comment] 2019-07-25 18:50
> The git clone command generate the config file. The git init command update it.

This is what I meant by "interesting" (and I really meant "unorthodox"): why run `git init` after `git clone`? That is supposed to be totally unnecessary.

I am not sure if reinitializing the repository that way would actually _need_ `core.worktree` to be set.

But I am fairly sure that you want to get rid of that redundant (and problem-causing) `git init` call in your flow.

**Comment by tonischilling** [comment] 2020-02-13 17:16
Hello to all.
It seems I've got a similar problem with the same reason (or same symptom?).
I tried it with Git-for-Windows  and MSYS2+its_own_git.
I got the same effect in both cases - so I think the Git-Version is not relevant here.

##### Git-for-Windows:
$ git --version --build-options
git version 2.24.0.windows.2
cpu: x86_64
built from commit: 02af2cc5bfc37d4500e8a09333269e57f442198a
sizeof-long: 4
sizeof-size_t: 8

### How to reproduce:
 
The visible effect is always that - after a  `git init foo`
the option  `core.worktree`  is set to the **resolved path** of the new working directory
**if I do the `git init` from directory-path containing a "windows-link"** to some other directory.

The target-dir:
` mkdir -p /c/tmp-2/foo/bar`

To create a link I use a bash script which passes the /J or the /D option to the
windows `mklink` command. For the /D option I need an admin-shell:

````
mingw64 (admin)> 
> cd /c/tmp-3
> mklink -v -j foo-j   /c/tmp-2/foo
 mklink /J "C:\tmp-3\foo-j" "C:\tmp-2\foo"  
> mklink -v  foo-d   /c/tmp-2/foo
 mklink /D "C:\tmp-3\foo-d" "C:\tmp-2\foo" 
````

#### Then in the same **elevated shell**

````
> cd /c/tmp-3/
> git init foo-d/bar/ggg-d
> git init foo-j/bar/ggg-j
> cat foo-d/bar/ggg-d/.git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        worktree = /c/tmp-2/foo/bar/ggg-d
        symlinks = false
        ignorecase = true
> cat foo-j/bar/ggg-j/.git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        worktree = /c/tmp-2/foo/bar/ggg-j
        symlinks = false
        ignorecase = true
````
**WOW! Both repos have  `core.worktree`** (and I have problems in both repos!)

#### Now from a non-admin-shell:

````
$ cd /c/tmp-3
$ ls -l
total 0
lrwxrwxrwx 1 EQN158+shi 197121 12 2020-02-13 16:34 foo-d -> /c/tmp-2/foo
lrwxrwxrwx 1 EQN158+shi 197121 12 2020-02-13 16:33 foo-j -> /c/tmp-2/foo

$ git init foo-d/bar/nnn-d
Initialized empty Git repository in C:/tmp-3/foo-d/bar/nnn-d/.git/
$ git init foo-j/bar/nnn-j
Initialized empty Git repository in C:/tmp-3/foo-j/bar/nnn-j/.git/
$ cat foo-d/bar/nnn-{d,j}/.git/config
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        worktree = C:/tmp-2/foo/bar/nnn-d
        symlinks = false
        ignorecase = true
[core]
        repositoryformatversion = 0
        filemode = false
        bare = false
        logallrefupdates = true
        symlinks = false
        ignorecase = true
````

**This time the "/J-repository" has no `core.worktree` option!**

### The Problems ... 

The effects are always ... let´s call it "strange".
**The workaround** was always  `git config --unset core.worktree`.

(just an example)
````
$ cd foo-d/bar/ggg-d

.../foo-d/bar/ggg-d     #<1> Prompt does not show the current branch!?
$ ls -A
.git

.../foo-d/bar/ggg-d
$ git status -s
fatal: Invalid path '/c': No such file or directory

.../foo-d/bar/ggg-d
$ cd ../nnn-d

.../foo-d/bar/nnn-d (master)    #<2> Hey! there´s the branch!
$ mkdir -p aaa/bbb ; touch aaa/bbb/ccc.h

.../foo-d/bar/nnn-d (master)
$ git add aaa/bbb/ccc.h

.../foo-d/bar/nnn-d (master)
$ git status -s
A  aaa/bbb/ccc.h

 .../foo-d/bar/nnn-d (master)
$ cd aaa/bbb/

 .../nnn-d/aaa/bbb (master)
$ touch ccc.c

 .../nnn-d/aaa/bbb (master)
$ git add ccc.c        #<3> Why?! The file is there!
fatal: pathspec 'ccc.c' did not match any files

 .../nnn-d/aaa/bbb (master)
$ git status -s
A  aaa/bbb/ccc.h       #<4> Oops! This should be "A_ ccc.h" - right?
?? aaa/bbb/ccc.c        #<5>  ... and  this should be "?? ccc.c".

 .../nnn-d/aaa/bbb (master)
$ git add aaa/bbb/ccc.c    #<6> This should not work, because we are in "bbb"

 .../nnn-d/aaa/bbb (master)
$ pwd
/c/tmp-3/foo-d/bar/nnn-d/aaa/bbb

 .../nnn-d/aaa/bbb (master)
$ git status -s
A  aaa/bbb/ccc.c
A  aaa/bbb/ccc.h
````

Hope this helps.
Greetings
Toni Schilling

**Comment by tonischilling** [comment] 2020-02-13 17:31
BTW: I saw, you closed #1178 after waiting too long.
Because I have a workaround and I'm an overworked developer, I will probably not follow this issue actively.
If needed, feel free to contact me directly - at `equicon` de
Greetings
Toni Schilling

**Comment by tonischilling** [comment] 2020-02-13 18:08
I forgot ...

#### My Git in MSYS2 (64):
````
$ git --version --build-options
git version 2.23.0
cpu: x86_64
no commit associated with this build
sizeof-long: 8
sizeof-size_t: 8
````
The Git-for-Windows produces:  `core.worktree = C:/tmp-2/foo...`
The Git-MINGW64 produces:  `core.worktree = /c/tmp-2/foo...`
In both cases the "create-symlink" feature (I can not remember its name) is *deactivated*.

Gruß
Toni

**Comment by dscho** [comment] 2020-02-13 20:58
A good next step would be to test the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html).

**Comment by tonischilling** [comment] 2020-02-14 09:03
why?

**Comment by dscho** [comment] 2020-02-14 11:39
@tonischilling because there have been changes around resolving paths recently? And if the snapshot already works, I do not have to get distracted from my actual work to hunt down an already-fixed bug?

**Comment by tonischilling** [comment] 2020-02-14 12:47
I could not find any commit, pull-request or so, mentioning this issue.
(Though I´m not good in searching git-hub ... sorry.)
I hope I gave you enough information to reproduce the problem.
Could you? May be with that snapshot?
I have no test-environment at hand and I´m not allowed to change our work-environment without good reason. So we´ll have to live with the workaround.
If a future release should change the situation - I´ll let you know.

**Comment by dscho** [comment] 2020-02-14 13:22
The Portable Git snapshots should help: no need to change your work setup.

I cannot afford the time to try reproducing this over here. Especially given how much time I spent on the related issues.

**Comment by tonischilling** [comment] 2020-02-20 10:28
**The Problems are gone** with `git version 2.25.1.windows.1`.
May be it´s related to #2449 - which was mentioned in the release notes.

**Comment by dscho** [comment] 2020-02-20 13:14
> **The Problems are gone** with `git version 2.25.1.windows.1`.

Excellent!

> May be it´s related to #2449 - which was mentioned in the release notes.

I would think so, yes.

**Closed by dscho** 2020-02-20 13:14 UTC
