### ISSUE TITLE
Installer Error while upgrading from 2.38.1 to 2.39.2

### ISSUE THREAD

**Issue by Skgland** [git-for-windows/git#4329] opened 2023-03-07 17:40 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.39.2.windows.1
cpu: x86_64
built from commit: a82fa99b36ddfd643e61ed45e52abe314687df67
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.2311]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

$ type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

 - Updated as part of `winget.exe update --all` in powershell in Windows Terminal
```
$ $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      19041  1682

```

### Details

Copied error message with Ctrl+Insert:
--------------------------------------

```log
---------------------------
Git 2.39.2 Setup
---------------------------
Line 3361: Could not reconfigure Scalar enlistments (output: (no output), errors: (no output)).
---------------------------
OK   
---------------------------
```

 - What did you expect to occur?

Update succeeds without error.

 - What actually happened instead?

Update gave an error and succeeded anyway after clicking OK in the error dialog.

**Comment by rimrul** [comment] 2023-03-07 18:15
Duplicate of #4050

**Closed** 2023-03-07 18:15 UTC
Labels: duplicate
