### ISSUE TITLE
git init --bare results in fatal: unable to get current working directory: No error when using UNC

### ISSUE THREAD

**Issue by Barzi2001** [git-for-windows/git#1078] opened 2017-03-02 08:02 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing. 

I created a link from the DOS shell with (I had to run the DOS shell as Administrator)

`C:\Users\Rob> mklink /D MyRepo  \\somewhere\MyRepo`

Next, from MINGW  I got

> $ cd "C:\Users\Rob"
> $ ls 
> MyRepo@

Next, if I do

> $ cd MyRepo
> $ touch A.txt

I can see the A.txt file in the network location opened in Windows Explorer. That means this mechanism works. On the other hand, it happens that

> $ git init --bare 
> fatal: unable to get current working directory: No error

What I have noticed from the Windows Explorer is that a folder has been actually created in the network location, but then it seems that git cannot get it. 

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
_64-bit (Portable)_

> $ git --version --build-options
git version 2.12.0.windows.1
built from commit: d4baef1cdfef9de62d43f9682a98ba57adc842e4
sizeof-long: 4
machine: x86_64

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
_Windows 7_

> $ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]

 - What options did you set as part of the installation? Or did you choose the
   defaults?
_None really. Just the ordinary settings (eventually alias like loggg for having customized views of git log,, etc.)_

# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

`/etc/install-options.txt: No such file or directory`
_The other options don't work either._

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?
_Not really. Just Ordinary Win7 with a portable git installed._ 

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other
_git-bash_

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.
_See above description_

 - What did you expect to occur after running these commands?
_The git repo has been created._

 - What actually happened instead?

> fatal: unable to get current working directory: No error

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?
_It happens on a UNC location._

**Comment by dscho** [comment] 2017-03-21 15:38
I cannot reproduce that issue here, but then, I am on Windows 10.

Are you able to compile some code for testing? For example, Git via the [Git for Windows SDK](https://git-for-windows.github.io/#download-sdk)?

**Comment by Barzi2001** [comment] 2017-03-22 13:02
Hello.
I have just discovered that we will soon migrate on Windows 10, so I can
survive a bit more by mapping the network locations on drives.
If I will experience the same problem on Win10, then i will post a reply
here.

**Comment by dscho** [comment] 2017-03-23 17:11
Let's close this, then. If anybody comes along offering to compile test code on Windows 7 and report results back, we can easily reopen.

**Closed by dscho** 2017-03-23 17:11 UTC
Labels: help wanted

**Comment by Barzi2001** [comment] 2017-03-24 10:26
Agreed.

Best,
/Ubaldo
