### ISSUE TITLE
Git Bash Sets USERNAME Instead of USER

### ISSUE THREAD

**Issue by jcburley** [git-for-windows/git#1878] opened 2018-10-12 14:50 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.16.0.windows.2
cpu: x86_64
built from commit: a56c4f9e2a9513d2be57dc4346e0e84887399cd9
sizeof-long: 4
$ bash --version
GNU bash, version 4.4.12(2)-release (x86_64-pc-msys)
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
 - Windows 7 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Editor Option: Nano
Path Option: BashOnly
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

No idea, other than I've got my own `.bash_profile` and similar files.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Pressed Windows button, typed "bash", it selected "Git Bash", hit Enter, got Git Bash window.

 - What did you expect to occur after running these commands?

An environment with `$USER` set to my username.

 - What actually happened instead?

An environment with `$USERNAME` set to my username.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Unsure of source; installed this awhile back.

**Comment by jcburley** [comment] 2018-10-12 14:51
(Note that I'm not sure this Git repo is the proper place to report Git Bash issues, as I couldn't find the Git Bash emulation code after looking around awhile....)

**Comment by PhilipOakley** [comment] 2018-10-13 08:57
Hi @jcburley The Git for Windows `bash` is provided as a minimalist convenience capability to allow us to run the regular Git commands and test suite. It does not attempt to emulate a full Linux environment so only sets the most limited number of environment variables needed. (there is always WSL for a larger experience)

The `bash` is borrowed from MSYS2. The [Git for Windows FAQ](https://github.com/git-for-windows/git/wiki/FAQ), part of our wiki, is a good place to start for some of these nuances, and maybe to add clarifications where needed. Contributions are welcome.

Also have a look at https://github.com/git-for-windows/git/wiki/Building-msys2-runtime

**Comment by dscho** [comment] 2018-11-28 11:36
Even if it looks a little bit like Unix/Linux, Git Bash does not magically turn your Windows into a Unix. Therefore, the `USERNAME` environment variable is set, as is common on Windows, not the `USER` variable. Likewise, you will note the absence of the `UID` variable.

If you must have those, then you can set them yourself in `~/.bash_profile`, I would think.

In any case, this is definitely not a bug or a problem in Git, so I am closing this.

**Closed by dscho** 2018-11-28 11:36 UTC

**Comment by jcburley** [comment] 2018-11-28 14:44
Okay, that makes sense, thanks! (And I do indeed work around this in my **~/.bash_profile**.)

**Comment by jcburley** [comment] 2018-11-28 14:45
(But Git Bash _is_ fairly magical IMO.  ;) )
