### ISSUE TITLE
`git worktree` config file uses Windows style path (`C:\...`)

### ISSUE THREAD

**Issue by KSR-Yasuda** [git-for-windows/git#3782] opened 2022-04-11 00:54 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.35.1.windows.2.7.g158a30d60b.20220224121117
cpu: x86_64
built from commit: 158a30d60b1676f8e52457478eaf7b4db95e9949
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19044.1586]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: LFOnly
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I found it in using Vim plugin [fugitive][] ([issue][]).

[fugitive]: https://github.com/tpope/vim-fugitive
[issue]:    https://github.com/tpope/vim-fugitive/issues/1970

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

Call `git worktree` command.

It generates `.git` file in the worktree dir to refer to parent git repo,
however, the path in the file is in the manner of Windows (`C:/...`),
instead of POSIX manner (`/c/...`) that git-for-windows mainly uses.

```bash
# Initialize repository
% git init repo
% cd repo
% git commit -m "Initial commit"

# Create worktree `wt` and move to it
% git branch develop
% git worktree add wt develop
% cd wt

# Check git config file in the worktree dir
% cat .git
gitdir: C:/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
```

Windows path (`C:/...`) is replaced with POSIX path (`/c/...`) sometimes.
The paths are different literally, so, in some cases, such as git utilities like [fugitive][] may work unexpectedly.

 - What did you expect to occur after running these commands?

Use POSIX path in worktree `.git` config file.

```
% cat wt/.git
gitdir: /c/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
```

 - What actually happened instead?

It uses Windows path.

```bash
% cat wt/.git
gitdir: C:/Users/xxxxxxxx/xxxxxxxx/xxxxxxxx/repo/.git/worktrees/wt
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

* [Issue for vim fugitive plugin][issue]

**Comment by dscho** [comment] 2022-04-19 15:58
The problem is that the `vim` we ship is an _MSYS_ program, and therefore knows about these Unix-y paths (they are not really POSIX ones, otherwise VMS' paths would not be valid). But Git for Windows itself is _not_ an MSYS program, and therefore has _no idea_ what `/c/` is supposed to mean.

Therefore, Git does the right thing.

And the problem simply is that `fugitive` has no way of knowing that it runs in an emulated Unix-y environment while the `git.exe` it uses does not.

**Comment by KSR-Yasuda** [comment] 2022-04-20 00:38
At least, it was only a relative path, it could have be rescued...
(as `git submodule` is so).

The reason why `git worktree` uses an absolute path is,
it can be used for locations out of the repository?

Now I have no choice but editing the `.git` file path by hand, right?

**Comment by dscho** [comment] 2022-04-21 07:28
> Now I have no choice but editing the `.git` file path by hand, right?

It would be better if `fugitive` was taught to:

1. _not_ read any files internal to Git, but instead use `git` commands to query the information
2. learn to detect the MSYS2 environment and use the `cygpath` tool to convert from Windows paths if it cannot handle those.

**Comment by dscho** [comment] 2022-04-21 07:29
Since Git seems to work as designed here, I am going to close this ticket.

**Closed by dscho** 2022-04-21 07:29 UTC
Labels: question
