### ISSUE TITLE
Git bash crashes, other git commands throw "CreateProcessW failed" and "errno 11" 

### ISSUE THREAD

**Issue by ShacharWeis** [git-for-windows/git#1370] opened 2017-11-20 22:38 UTC
Hey all,
I can't get Git Bash and the other git command line tools to work on my laptop. It's a new Windows 10 machine, I installed the latest git for windows. 

When I run Git Bash, it crashes without an error. 

I can run some git command line actions like "git clone", but "git submodule" and "git stash" both throws a bunch of errors like this:

```
          0 [main] sh 1760 fork: child -1 - CreateProcessW failed for 'C:\Users\XXX\AppData\Local\Programs\Git\usr\bin\sh.exe', errno 13
    C:\Users\XXX\AppData\Local\Programs\Git\mingw64/libexec/git-core\git-stash: fork: Permission denied
          0 [main] sh 7592 C:\Users\XXX\AppData\Local\Programs\Git\usr\bin\sh.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x54), Win32 error 5.  Terminating.
          0 [main] sh 15308 fork: child 7592 - died waiting for dll loading, errno 11
    /mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
          0 [main] sh 7040 C:\Users\XXX\AppData\Local\Programs\Git\usr\bin\sh.exe: *** fatal error in forked process - MapViewOfFileEx '(null)'(0x54), Win32 error 5.  Terminating.
```

Any ideas ?
 

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.15.0.windows.1
built from commit: ed3d106bc93775b62b3860176d7501e079a089b9
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.15063]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

**Comment by dscho** [comment] 2017-12-08 16:20
Is this maybe a duplicate of https://github.com/git-for-windows/git/issues/1244?

**Comment by dscho** [comment] 2018-04-04 13:15
> Is this maybe a duplicate of #1244?

I'll assume that it is, having heard only the "silent majority" answer.

**Closed by dscho** 2018-04-04 13:15 UTC
