### ISSUE TITLE
Misspelling foward instead of forward in the installer

### ISSUE THREAD

**Issue by supermitsuba** [git-for-windows/git#2663] opened 2020-06-04 13:30 UTC
- [X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64

Installer has misspelling on version 2.27.0

![image](https://user-images.githubusercontent.com/2320336/83762784-e7322980-a645-11ea-9478-9f952421b4db.png)

**Comment by rimrul** [comment] 2020-06-04 14:21
Duplicate of #2552, #2554, #2556, #2557 and #2660.

**Closed** 2020-06-04 15:32 UTC
Labels: duplicate
