### ISSUE TITLE
Submodule commit changes not reliably detected when usebuiltinfsmonitor=true

### ISSUE THREAD

**Issue by joschock** [git-for-windows/git#3580] opened 2021-12-08 18:58 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.34.1.windows.1
cpu: x86_64
built from commit: 2ca94ab318509b3c271e82889938816bad76dfea
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22000.318]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing obviously relevant.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

powershell

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git config core.usebuiltinfsmonitor true
cd <submodule path>
git checkout <new commit SHA>
cd ..
git status
git config core.usebuiltinfsmonitor false
git status
```
 - What did you expect to occur after running these commands?

I expect to see the submodule path status show up as modified: (new commits) in both instances of `git status` above

 - What actually happened instead?

The first instance of `git status` shows no modifications to the submodule. 
Note that this is intermittent - the repo I'm observing this in has a number of submodules. If I change them all to new commits, only a couple may show up in the first instance of `git status` above - but all show up in the second instance of `git status`

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Internal non-public repo.

**Comment by jeffhostetler** [comment] 2021-12-08 20:37
I suspect that if FSMonitor thinks the directory mtime is unchanged, then it sets the clean flag and doesn't bother looking to see if it is a submodule -- and therefore doesn't try to go inside to do the recursive status.  i've not confirmed this, but I think that may be the cause.

**Comment by mems** [comment] 2022-01-19 13:16
I've got the same issue. Change `core.usebuiltinfsmonitor` to `false`, workaround the "invisible changes" of project submodules

**Comment by dscho** [comment] 2022-01-20 13:34
@mems could you try your hand at adding a test case to `t/t7527-builtin-fsmonitor.sh`, maybe imitating [this one](https://github.com/microsoft/git/blob/7a514b4c2d5df7fdd2f66f048010d8ddcb412d0b/t/t7527-builtin-fsmonitor.sh#L479-L495), then open a PR?

**Comment by jeffhostetler** [comment] 2022-02-24 21:59
I have a fix for this.  It should be in the next release.  I'll leave this open until I actually have a patch merged into the GFW tree.

**Comment by dscho** [comment] 2022-02-25 06:56
Yes, let's update FSMonitor in Git for Windows once https://github.com/gitgitgadget/git/pull/1041 advances in core Git.

**Comment by dscho** [comment] 2024-10-18 14:30
I'll just go ahead and assume that that fix addressed the issue _long_ ago.

**Closed by dscho** 2024-10-18 14:30 UTC
