### ISSUE TITLE
Node Console not loading on Win 8.1

### ISSUE THREAD

**Issue by radulemnaru** [git-for-windows/git#400] opened 2015-09-17 11:35 UTC
I have the latest release of Node installed on Windows 8.1 and unfortunately the console does not load when I run >node. Running JS scripts directly with the node commands works fine but the console is not accessible.

**Comment by dscho** [comment] 2015-09-17 11:47
This is a duplicate of https://github.com/git-for-windows/git/issues/399

**Closed by dscho** 2015-09-17 11:47 UTC
Labels: duplicate

**Comment by dscho** [comment] 2015-09-17 12:03
@radulemnaru Did you have a look at the other ticket?

**Comment by radulemnaru** [comment] 2015-09-19 19:16
Thanks the previous solution worked out well.
