### ISSUE TITLE
on windows, git svn rebase can't load perl error

### ISSUE THREAD

**Issue by snoopydo** [git-for-windows/git#3407] opened 2021-09-02 01:41 UTC
### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19042.1165]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"

Editor Option: VisualStudioCode
Custom Editor Path:
Default Branch Option: main
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: ConHost
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing special.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn rebase
```
in repositories that are sourced from svn, no local git commits made, just calling git svn rebase to update with changes made in our svn repositories.

 - What did you expect to occur after running these commands?

to have merged new svn commits into local git repository

 - What actually happened instead?

Can't load '/usr/lib/perl5/vendor_perl/auto/SVN/_Core/_Core.dll' for module SVN::_Core: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line 193.
 at /usr/lib/perl5/vendor_perl/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/SVN/Core.pm line 5.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN/Utils.pm line 6.
Compilation failed in require at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/share/perl5/Git/SVN.pm line 32.
Compilation failed in require at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.
BEGIN failed--compilation aborted at C:/Program Files/Git/mingw64/libexec/git-core\git-svn line 64.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

local, any git svn rebase fails

**Comment by landstander668** [comment] 2021-09-02 02:23
Duplicate of #3392, #3393, #3397, #3402, #3403.

**Closed** 2021-09-02 04:16 UTC
Labels: duplicate
