### ISSUE TITLE
Mintty.exe is a dialog instead of a terminal

### ISSUE THREAD

**Issue by mschroen** [git-for-windows/git#2463] opened 2020-01-10 10:28 UTC
Git usually brings the mintty terminal, which can be found at `Git/usr/bin/mintty.exe`.
Today I updated Git for Windows (for a long time I didn't), and I found that executing mintty does not open a terminal anymore. Instead, it opens a dialog offering msys2 and mingw variants: 
![grafik](https://user-images.githubusercontent.com/7942719/72140578-5ce4e280-3391-11ea-9a88-f5093b6f2feb.png)

How can mintty (i.e., msys2) be opened directly without the dialog?
(msys2 seems not to have a single executable, the folder `Git/usr/bin/` only contains dlls...)

**Comment by zufuliu** [comment] 2020-01-10 10:59
Open Git/usr/bin/bash.exe
execute `pacman -S msys2-launcher-git`
you will get mingw32.exe, mingw64.exe and msys2.exe under Git/ folder.

**Comment by dscho** [comment] 2020-01-10 13:36
> Git usually brings the mintty terminal, which can be found at `Git/usr/bin/mintty.exe`

Git for Windows' console window is usually started via the "Git Bash" shortcut in the Start Menu. If you *must* call it directly, call `Git/git-bash.exe`.

If you call `mintty.exe` directly, it is easy to get lost if you do not understand what you are doing, as you totally forgot to specify what command-line interpreter to run in that window.

Closing, as this is not a bug, but a pilot error.

**Closed by dscho** 2020-01-10 13:36 UTC

**Comment by mschroen** [comment] 2020-01-10 13:43
I intended to use the mintty terminal "for free" without having to install cygwin. The issue is completely unrelated to using Git, because as you said, for any Git-related work I use the Git bash. However, Git brings lots of additional linux tools, so I expected that they can be used for purposes other than related to Git. It appears that mintty can be not, I just hoped that the executable that is called by the "msys2" button is somewhere hidden in the bin folder under a different name.

**Comment by dscho** [comment] 2020-01-10 14:21
> Git brings lots of additional linux tools, so I expected that they can be used for purposes other than related to Git.

You can do that, as long as you avoid relying on support from the Git for Windows maintainer (read: from me) for such use cases. I have no desire to support any use cases of Git for Windows as sort of a Cygwin on the cheap, that would cost me way too much time.

> It appears that mintty can be not

Sure it can. You just erroneously assumed that it would run `bash.exe` or something. It does not. Try `mintty.exe --help` to get more information about the correct way to call `mintty.exe`. There, now I had to spend another five minutes of my life supporting Git for Windows as sort of a Cygwin on the cheap. ☹️

**Comment by mschroen** [comment] 2020-01-10 14:28
Thanks for the hint, so `mintty -` was the command I was looking for. For me the issue is closed now. For you I'd suggest to communicate how users can buy you a beer to make up for the 5 minutes ;-)
