### ISSUE TITLE
mistyping "git add:/"  (<- missing space) results in warning: failed to restrict file handles (2)

### ISSUE THREAD

**Issue by chrisfcarroll** [git-for-windows/git#1624] opened 2018-04-10 12:00 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup
 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.1.windows.4
cpu: x86_64
built from commit: ef6d451bbfef86a529ebf12620289e0f15a93d8e
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.309]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: CmdTools
SSH Option: OpenSSH
CURL Option: WinSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

PowerShell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.16299.251
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.16299.251
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

 - What commands did you run to trigger this issue? If you can provide a

```
git branch renamedproj
git checkout renameproj
git add:/ #OOh look I mistyped 

```
 - What did you expect to occur after running these commands?

git: 'add:/' is not a git command. See 'git --help'.

 - What actually happened instead?

warning: failed to restrict file handles (2)

handle #0: 0000000000000008 (type 2, handle info (1) 7ffa
handle #1: 0000000000000168 (type 2, handle info (1) 1
handle #2: 000000000000016c (type 2, handle info (1) 1

This is a bug; please report it at
https://github.com/git-for-windows/git/issues/new

To suppress this warning, please set the environment variable

        SUPPRESS_HANDLE_INHERITANCE_WARNING=1

git: 'add:/' is not a git command. See 'git --help'.

**Comment by dscho** [comment] 2018-04-10 15:43
This is a duplicate of #1578 and #1583, and the underlying issue has been fixed in Git for Windows v2.17.0. Please update.

**Closed by dscho** 2018-04-10 15:43 UTC
