### ISSUE TITLE
git version >=2.25.x broke cloning in non-system drive letters [ramdisk]

### ISSUE THREAD

**Issue by n3rd4i** [git-for-windows/git#2518] opened 2020-02-14 17:47 UTC
Tyring to clone repository in Windows, on non-system drive does not work.

To reproduce, git version `>=2.25`:
* in `cmd.exe` switch to non-system drive, e.g. T:
  * `t:`
* `git clone <repo_url>`
* Result: clone fails:
  * `fatal: unable to get current working directory: No such file or directory`

To confirm this:
* run the above procedure on git `<2.25`

**Comment by rimrul** [comment] 2020-02-14 18:36
I've just tried this in both Git-Bash and Git-CMD. Both can clone this very repo via https just fine on my F:\ partition. So let me give you some details on the machine I tried this on:

* OS: Windows 8.1 64bit
* System drive: C:\ a NTFS partition on an SSD
* Drive I tested on: F:\ a NTFS partition on an HDD
* Command I ran: `git clone https://github.com/git-for-windows/git.git`
* Git for Windows version: 2.25.windows.1 (64 bit installed via the setup)

Please see if there are some more details about your setup that make this reproducible.

We also have an issue reporting template that asks for a bunch of these details already, but you decided to delete that. Please, feel free to fill that out next time.

**Comment by n3rd4i** [comment] 2020-02-14 18:45
System info:
OS: Windows 10 64bit, `Microsoft Windows [Version 10.0.18362.657]`
System drive: C:\ a NTFS partition on an SSD
Drive I tested on: T:\ a NTFS partition on an RAMDISK
Command I ran: `git clone https://github.com/git-for-windows/git.git`
Git for Windows version: `2.25.0.windows.1` (64 bit installed via the [chocolatey](https://chocolatey.org/install))

Complete steps to reproduce:
```
T:\>choco install git --version 2.24.1.2 --params "/NoAutoCrlf"
[...]

T:\>git --version
git version 2.24.1.windows.2

T:\>git clone git@github.com:n3rd4i/zandronum.git
Cloning into 'zandronum'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (27/27) eceiving objects: 100% (43/43), 14.77 KiB | 4.92 MiB/s, done.
remote: Compressing objects: 100% (27/27), done.R
Resolving deltas:  86% (13/15)eused 40 (delta 12), pack-reused 0
Resolving deltas: 100% (15/15), done.
```

Upgrade to 2.25.0
```
T:\>choco upgrade git
Chocolatey v0.10.15
Upgrading the following packages:
git
By upgrading you accept licenses for the packages.

You have git v2.24.1.2 installed. Version 2.25.0 is available based on your source(s).
[...]

T:\>git --version
git version 2.25.0.windows.1

T:\>git clone git@github.com:git-for-windows/git.git
fatal: destination path 'git' already exists and is not an empty directory.
```

**Comment by n3rd4i** [comment] 2020-02-14 19:00
Additionally, chocolatey package uses the following hash, from [here](https://chocolatey.org/packages/git.install#files), `legal\VERIFICATION.txt`, meaning installer is the same as official one:
```
T:\>%chocolateyinstall%\tools\checksum -t sha256 Git-2.25.0-64-bit.exe
6FFB0674A5F5FEC2A328DD40456EDE87ED3C7DE653ECD6950F9CF132BCA2F94C
```
Official one for download to check the hash:
https://github.com/git-for-windows/git/releases/download/v2.25.0.windows.1/Git-2.25.0-64-bit.exe

**Comment by rimrul** [comment] 2020-02-14 19:01
>I did not, I've used Android application, FastHub to report the issue, there was no template there.

Oh, I see. Github apps are a bit of a mixed bag unfortunately. They are often more comfortable to use than the website but tend to lack features somewhere.

>on an RAMDISK

now that is an interestiung detail.

There has been a fix regarding ramdisks after 2.25.0 (see #2480 ). Could you try the [latest snapshot](https://wingit.blob.core.windows.net/files/index.html)?

**Comment by n3rd4i** [comment] 2020-02-14 19:05
Used the above binary:
```
T:\>git --version
git version 2.25.0.windows.1.26.g69c22a9a95

T:\>git clone git@github.com:git-for-windows/git.git
fatal: destination path 'git' already exists and is not an empty directory.
```

**Comment by dscho** [comment] 2020-02-14 20:00
Let's chalk this up as a duplicate of #2480, then.

**Comment by dscho** [comment] 2020-02-14 20:01
BTW @rimrul great work helping @n3rd4i so quickly!

**Closed by dscho** 2020-02-14 20:00 UTC
