### ISSUE TITLE
The console don't display user input and I can't commit

### ISSUE THREAD

**Issue by glhez** [git-for-windows/git#307] opened 2015-08-23 20:44 UTC
Hello,

I don't know if this is due to Git for Windows 2.5.0-windows-1 (under Windows 7x64) or ConEmu 150816, from times to times, vim fail to display its buffer, and print something like that:

```
[22:32:09] /e/git/tg/test-toolbox (develop) [1.8.0_51]
$ git commit
Aborting commit due to empty commit message.
[0;36m[22:32:12] /e/git/tg/test-toolbox (develop) [1.8.0_51]
$ [22:32:14] /e/git/tg/test-toolbox (develop) [1.8.0_51]
$ Aborting commit due to empty commit message.
[0;36m[22:32:27] /e/git/tg/test-toolbox (develop) [1.8.0_51]
```
After vim fails, I don't see any-more what I type.

If I type the reset command, I can again see what I'm typing. But if I try to commit, I have the same problem: vim launch, but incorrectly, leading git to think the commit is empty (which is probably the same).

This is rare and I don't even have a clue of what I've done wrong to get into those trouble.

**Comment by dscho** [comment] 2015-08-24 10:00
Hmm. The most closely related hits from a web search indicate that ConEmu used to have some issues with vim: https://code.google.com/p/conemu-maximus5/issues/detail?id=1060

And that maybe it is related to using `ConEmuHk`? https://code.google.com/p/conemu-maximus5/wiki/ConEmuHk

**Comment by glhez** [comment] 2015-08-24 18:11
In the first link, it is more about a crash which I never had.
It is more like I did trigger some "hide the input" short-cut (I excel at finding strange short-cut, anyway... :)). 

This seems to help reproduce the problem (but it really depends :/)

```
git reset --hard usbkey/develop ; for (( i = 0; i < 100; ++i )); do echo $i > $i; git add "$i"; git commit ; done
```

I'll go create an issue in ConEmu (https://github.com/Maximus5/ConEmu/issues )

**Comment by Maximus5** [comment] 2015-08-24 23:10
Do not see any problems with these versions.

* Show your screenshots. The steps to reproduce the problem are not clear.
* Show your configuration files like .bashrc, .vimrc, etc.
* Reveal [RealConsole](http://conemu.github.io/en/RealConsole.html) and repeat problematic steps.
* Check with basic settings

        ConEmu64.exe -basic -cmd git-cmd.exe --no-minimal-search-path --no-cd --command=usr/bin/bash.exe -l -i

![git-25](https://cloud.githubusercontent.com/assets/1222388/9454758/3aa812de-4acd-11e5-8fc2-b173694fdebc.gif)

**Comment by Maximus5** [comment] 2015-08-24 23:13
BTW, I see at least parts of unprocessed ESC sequences. Without exact screenshots nobody can be sure what they are in fact: `[0;36m[22:32:12] `

**Comment by dscho** [comment] 2015-08-25 08:12
I am not sure whether this is a problem with some unset environment variables or some such, or whether it is a locale issue. Eager to find out!

**Comment by Maximus5** [comment] 2015-08-25 08:26
Without information I'm asking about, nobody may be sure. It may be unchecked ConEmu options or just scrolled out real console.

**Comment by glhez** [comment] 2015-08-25 09:51
The step to reproduce the problems are not clear, because it is "random" (even if I don't believe in randomness when it comes to computer): on the issue I created at ConEmu's issue list, I do that:

```
rm -f .git/.COMMIT_EDITMSG.swp ;
git reset --hard usbkey/develop ; 
for (( i = 0; i < 100; ++i )); do echo $i > $i; git add "$i"; git commit ; done
```
1. Delete the vim swap file (when the bug did not occur, the loop will create 100 files, and git commit will open vim... so I need to kill it using process explorer).
2. Reset current branch to some initials state.
3. Create 100 dummy files, and for each commit. Git will invoke vim. 

The step 3 is here to make the whole fail. 
It did make it fail successfully from times to times.

My vimrc (and console emu settings) is here: https://gist.github.com/glhez/a0c07e8d9794f59b4fe2#file-_vimrc

For the other (bashrc and screenshot of real console [but really it only display what I've put in https://github.com/git-for-windows/git/issues/307 ]),

I'll retry tonight with an empty bashrc + git cmd directly (I completely forgot to test with it, if the bug appear using the simple git-cmd, then I'll close the issue https://github.com/git-for-windows/git/issues/307 )

*Note:* I never had this problem with msysGit, but I do remember having from time to time the same behavior (eg: the input does not show anymore). .

**Comment by dscho** [comment] 2015-08-25 11:13
@glhez please note that @Maximus5 asked for a real screenshot; you can paste them into this ticket, just like he did.

**Comment by glhez** [comment] 2015-08-25 11:20
No problem for that. I'll do that tonight (i'm on XP now, and I don't think it exhibits the problem).

**Comment by dscho** [comment] 2015-08-25 11:30
> i'm on XP now, and I don't think it exhibits the problem

Well, better test it! :smiley:

**Comment by Maximus5** [comment] 2015-08-25 12:22
The problem may occur if you resize window while vim is active. That's why I request evidences (screenshots).

**Comment by glhez** [comment] 2015-08-25 23:25
@Maximus5:

- I almost never resize my ConEmu. It is always maximized. Eventually, I split into vertically when I need to commit, but is is split before running git commit/vim.
- `[0;36m[22:32:12]` the [22:32:12] is the current time (`\t` in PS1). The rest in ANSI.

@dscho: testing on XP would be fine if not at work. Not that I don't want, but it is only when I have time. And I don't have (hopefully!) XP at home.

By the way, my current PS1 is (ugly):
```\e[0;36m[\e[1;36m\t\e[0m\e[0;36m]\e[0m \e[0;33m\w\e[0m`__git_ps1 ' \e[0;31m(\e[1;31m%s\e[0m\e[0;31m)\e[0m'``_zb_java_version ' \e[0;36m[\e[1;36m%s\e[0m\e[0;36m]\e[0m'``_zb_env_print ' \e[0;35m[\e[1;35m%s\e[0m\e[0;35m]\e[0m'`\n$```
The gives me this:
![ps1](https://cloud.githubusercontent.com/assets/10855953/9482137/2c40acbe-4b91-11e5-8915-856df3a33590.png)

**Comment by Maximus5** [comment] 2015-08-25 23:31
As you can easily see, there is no `[0;36m` on your screenshot. So, you are misleading us with your code quotation...

Waiting for screenshots with the problem.

**Comment by glhez** [comment] 2015-08-25 23:36
@Maximus5  sorry for misleading. It is not intended. 

Here are some more tests, and screenshot of real console. A checked checkbox indicate a success, none a failure.

Git here, which opens mintty:

- [X] without ~/.bashrc: reproducing first case using ConEmu (:q enter), did not fail.
- [X] without ~/.bashrc: reproducing second case using ConEmu (Ctrl + C), fail with an assertion: [see screenshot](https://cloud.githubusercontent.com/assets/10855953/9479616/61cb23d6-4b7e-11e5-8af8-dcc1bc475ac0.png) .
- [X] with ~/.bashrc: reproducing first case using ConEmu (:q enter), did not fail.
- [X] with ~/.bashrc: reproducing second case using ConEmu (Ctrl + C), did not fail.

ConEmu with actual ConEmu settings:  

- [ ] without ~/.bashrc: [reproduced the problem](https://cloud.githubusercontent.com/assets/10855953/9481777/87cec682-4b8d-11e5-8402-0a895ab8bdeb.png)
    
  Same behaviour of blind typing, but not the same steps to reproduce: I've done ":q enter" rapidly (instead of using process explorer to kill Bash process tree), and at some point it failed.
  During a second run of this test, I had vim which was consuming 12.5% CPU (100% of 1 core). Running another vim from another ConEmu tab, and the same file (.git/COMMIT_EDITING) did not exhibit the 100% CPU load.

- [X] without ~/.bashrc, typing ":q", then Enter with Ctrl + C prepared to kill the whole process: it does not fail, but the result is not as responsive as with mintty (Git here). 
- [ ] with ~/.bashrc [click to see real console](https://cloud.githubusercontent.com/assets/10855953/9478748/d9b04476-4b79-11e5-8e81-570edd4f7e6c.png) I've hit Ctrl + C like a brute, and it failed.
- [ ] with ~/.bashrc [click to see real console](https://cloud.githubusercontent.com/assets/10855953/9479247/ceaebd52-4b7c-11e5-8830-37be4cd229f7.png) Using ":q enter" rapidly, vim goes wrong and consume 12.5% CPU. If I kill it, then I enter another git commit step, and vim consume again 12.5%.

ConEmu with "-basic" `ConEmu64.exe -basic -cmd "C:\Program Files\Git\git-cmd.exe" --no-minimal-search-path --no-cd --command=usr/bin/bash.exe -l -i`

- [X]  without ~/.bashrc, hitting :q + enter in vim -> no problem
- [X] without ~/.bashrc, hitting :q + enter in vim + Ctrl + C  -> no problem; not as responsive as mintty
- [X] with ~/.bashrc, hitting :q + enter in vim -> no problem
- [ ]  with ~/.bashrc, hitting :q + enter in vim + Ctrl + C-> no problem until the end of command. See [image here](https://cloud.githubusercontent.com/assets/10855953/9481121/e3a7aeca-4b87-11e5-854f-7c74bd30fe67.png) blind typing "reset" seems to correctly reset the terminal, and calling `git commit` works.

I also notice in Process Exploret the following:

- My process explorer (opened as Administrator) often shows me that:
![process-explorer-01](https://cloud.githubusercontent.com/assets/10855953/9478749/d9b69132-4b79-11e5-8a3d-f469afb42944.png)
- If I look into the process in the red rectangle, its parent process (git-cmd  6384) has gone away.
![process-explorer-02](https://cloud.githubusercontent.com/assets/10855953/9478750/d9b8b8cc-4b79-11e5-9283-46872908a410.png)
- In the last case (ConEmu -basc + with bashrc), using ConEmu in Basic mode + .bashrc, I've got the very same git-cmd gone away: tasklist tells me that bash.exe does not have a parent, but Process Explorer tells me it has `git-cmd (2164)` as parent PID (not shown in tasklist output, or in Process Explorer list).

**Comment by glhez** [comment] 2015-08-25 23:45
And finally, my configuration files:

- [current ~/.bashrc](https://gist.github.com/glhez/a0c07e8d9794f59b4fe2#file-bashrc)
- [current ~/_vimrc](https://gist.github.com/glhez/a0c07e8d9794f59b4fe2#file-_vimrc)
- [result of env with ~/.bashrc](https://gist.github.com/glhez/a0c07e8d9794f59b4fe2#file-env)
- [`export` for my Windows @ home](https://gist.github.com/glhez/a0c07e8d9794f59b4fe2#file-windows-default-env)

I use a set of script files (at this [bitbucket repository](https://bitbucket.org/glhez/zeta-bash)) that I disabled by not sourcing `~/.bashrc` in `~/.bash_profile` (by default, Msys2 "Git for Windows" Bash does not source ~/.bashrc but that is another problem, I think https://github.com/git-for-windows/git/issues/317 relate to that).

Theses scripts are sourced from `~/.bashrc` (`. '/e/git/zb/zeta-bash/init.bash' /e/git/zb/zeta-bash-user`), and in last part, and it add aliases, completions, update the PATH (it build the PATH using MVN_HOME, JAVA_HOME, etc).

I won't expand much on my script, but I do set the following enviromnent variable:

``` 
# git bash does not set it well
export TZ=CET-1CEST
# avoid french message in english console...
export LANG=en_US.utf8
```

The TZ was because with msysGit there was an error in the time displayed (it was GMT+0), under a French Windows 7 (Paris hour, GMT+1 / GMT + 2).
And the language, because it is not very helpful to have error reported in French when you need to look for them on Google.

**Comment by Maximus5** [comment] 2015-08-26 00:10
> And the language, because it is not very helpful to have error reported in French when you need to look for them on Google.

+1. First thing I do when configure git - force it to use english.

## Process Explorer

Looks like usual forking technique of cygwin/msys. I don't know how you start second tab (ConEmuC64.exe with PID 3956) so can't say anything concrete. Or, may be, `git-cmd.exe` exits as reaction for some event, like `Ctrl+C`, but I'm not sure.

## screenshots

So, you've found way to reproduce? Than, it would be interesting to see 3 screenshots with

* Before running vim, in vim, after exit vim (where the error appears)
* Both ConEmu and real consoles must be there to compare
* Please enable on the StatusBar columns: "Console visible rectangle" and "Visible region lock".

## Git here, which opens mintty

Why do you mention "ConEmu" in this paragraph? What is on screenshot: mintty or real console?

## vim 100% CPU load

It would be nice to see memory dump of this vim.exe process. I suppose, vim is not responsive in that case?

**Comment by glhez** [comment] 2015-08-26 11:06
**Process Explorer**

Can't say for sure that is related to Ctrl + C: I often see that bash.exe is detached from ConEmuC/git-cmd.  When it happens, it is usually long time after I used the console (Process Explorer is not always displayed).

For what I could test at work (XP), when I do Ctrl C on a fresh tab with git-cmd, the git-cmd is killed and bash.exe is no longer attached to ConEmuC.

**screenshots + reproductibility**

Well, if you see my test, I have to do a loop and open 100 vims. In my screenshot, it begins to bug at the 80 iterations. It would be better to take a video with Process Explorer, ConEmu + Real console.

What tools did you use to generate your gif ?

By the way, I did not dig too much into that at the time, but I had the same kind of bug with msysGit: my input was invisible but still, was sent to bash: typing "Enter" would tell me "<whatever I typed> command not found".

The process to make it fail is however still unclear to me (I don't do 100 commit at a time every day and I don't try to Ctrl + C every time).

**vim 100%:** 

Yes, vim is not responsive. I don't even know what it does or expect.
I did do a dump using Process Explorer 's Debug then Full dump. 

Still, when I had my problem originally, vim was not doing that.

**Git here, which opens mintty** 

- `git-cmd` is what the Default tasks in ConEmu 150821 set up.  
- `git-bash` is open by the "Git here" on the Explorer context menu (`D:\apps\installed\git\git-bash.exe --cd-to-home`), and it opens a mintty. 

On XP, ConEmu provide two default tasks:

- *Bash::Git bash 2.5 x86 (1)* which is `D:\apps\installed\git\git-cmd.exe --no-cd --command=usr/bin/bash.exe -l -i`
- *Bash::Git bash 2.5 x86 (2)* which is `D:\apps\installed\git\bin\sh.exe --login -i -new_console:C:"D:\apps\installed\git\etc\git.ico"`

Mine is (at work): `"D:\apps\installed\git\git-cmd.exe" --cd="D:\git" --command=usr/bin/bash.exe -l -i -new_console:d:"D:\git":C:"D:\apps\installed\git\mingw32\share\git\git-for-windows.ico"`

**Comment by Maximus5** [comment] 2015-08-26 11:39
[Gif-Animate](https://github.com/Maximus5/gif-animate) from my own )

**Comment by dscho** [comment] 2015-08-26 18:14
> by default, Msys2 "Git for Windows" Bash does not source ~/.bashrc but that is another problem

Indeed, it is another problem, and one that we solved (the bug fix will be part of the next Git for Windows version): https://github.com/git-for-windows/build-extra/pull/71 (In general, I *really* prefer to keep separate tickets for separate problems)

**Comment by glhez** [comment] 2015-08-26 20:45
@dscho I understand. However ... it was damn helpful to switch off my bashrc ;)
@Maximus5 I'll give a try to ShareX tomorrow. 

Beside, I confirm that Ctrl + C also kill git-cmd on Windows 7.

Here is a link to the vim dump (using *Process Explorer > Create Dump > Create Full Dump* on vim at 100%): https://bitbucket.org/glhez/zeta-bash/downloads/vim.7z
Size is 6MiB compressed, 30MiB uncompressed:

**Comment by Maximus5** [comment] 2015-08-26 21:16
I suppose that vim hung is another issue. Call stack shows the following functions:
![2015-08-27_00-14-39](https://cloud.githubusercontent.com/assets/1222388/9506443/d7248ff0-4c50-11e5-9180-74238d13fa8f.png)

**Comment by glhez** [comment] 2015-08-29 15:39
Now ... I have a crash while testing my use case with ShareX; 

- CrashDump found in `%USERPROFILE%\AppData\Local\CrashDumps`: https://bitbucket.org/glhez/zeta-bash/downloads/conemu-crashdump.7z
- Screenshot (12Mb, using Gif Animate): https://bitbucket.org/glhez/zeta-bash/downloads/conemu_with_crash.gif
- Screenshot (7.4 Mb, same as previous, but using Gimp): https://bitbucket.org/glhez/zeta-bash/downloads/animation_web_optimized.gif

And the Windows error content:

```
Signature du problème :
  Nom d’événement de problème:	APPCRASH
  Nom de l’application:	conhost.exe
  Version de l’application:	6.1.7601.18869
  Horodatage de l’application:	5563565c
  Nom du module par défaut:	conhost.exe
  Version du module par défaut:	6.1.7601.18869
  Horodateur du module par défaut:	5563565c
  Code de l’exception:	c0000005
  Décalage de l’exception:	00000000000234df
  Version du système:	6.1.7601.2.1.0.256.48
  Identificateur de paramètres régionaux:	1036
  Information supplémentaire n° 1:	463e
  Information supplémentaire n° 2:	463e730d1e253c293e36ee5cc431169b
  Information supplémentaire n° 3:	9869
  Information supplémentaire n° 4:	98692f6230bd416337091cd55820eb49
```

**Comment by dscho** [comment] 2015-09-09 13:02
Hmpf. I lost track on this one, what is the status?

**Comment by glhez** [comment] 2015-09-09 23:00
As said in last comment, now, vim crashes (at 100% CPU), and make ConEmu crashes. 
Not always, but from times to times. 

Since that last comment, I never had the initial bug, which was more a problem of escape sequence shown on the console. Also, I updated to Git for Windows 2.5.1 and ConEmu 150821. So, perhaps it shifted from simple display problem to crashes.

**Comment by dscho** [comment] 2015-09-10 06:37
Hmm. It looks like you are stuck with a ConEmu problem now. So I have no idea how Git for Windows can help, until the point when you can reproduce the original problem (which I now suspect to be pretty much the same problem as https://github.com/git-for-windows/git/issues/353: wrong terminfo).

Would you agree? If so, please close this ticket (but feel free to reopen it as soon as you can reproduce the original issue, of course).

**Closed** 2015-09-10 08:33 UTC
Labels: unclear
