### ISSUE TITLE
Issues with core.symlinks

### ISSUE THREAD

**Issue by dra27** [git-for-windows/git#310] opened 2015-08-24 14:05 UTC
The recent support for symbolic links is a great addition, though I've found two minor issues:
1. If `core.symlinks` is `false`, you get an error message adding a native symlink (i.e. created by mklink) from the working directory:

> [master] C:\Scratch\Sym>git add Bar.txt
> error: readlink("Bar.txt"): Function not implemented
> error: unable to index file Bar.txt
> fatal: adding files failed

Is that intentional behaviour? While `core.symlinks = false` means that virtual files should be *created* by Git, is it necessary for Git to pretend it doesn't know how to read native symbolic links?
2. If `core.symlinks` is true and the current user doesn't have SeCreateSymbolicLinkPrivilege (e.g. an administrator in an unelevated command prompt) then git checkout silently fails. Surely it should at least display a warning or preferably terminate with an error (as it would on a write failure, for example)? In both cases, the error could suggest changing `core.symlinks` to `false` although it's also possible to detect if the user could obtain the privilege by elevation and in that instance it would be a good second suggestion.

**Comment by dscho** [comment] 2015-08-24 14:11
> If core.symlinks is false, you get an error message adding a native symlink (i.e. created by mklink) from the working directory:
> 
>     [master] C:\Scratch\Sym>git add Bar.txt
>     error: readlink("Bar.txt"): Function not implemented
>     error: unable to index file Bar.txt
>     fatal: adding files failed

Yes, this is intentional: `core.symlinks` does not *quite* enable symbolic links because Git's idea of symbolic links matches POSIX semantics *exactly* while our emulation does not. It is close, but not close enough to enable by default. For example, we cannot assume that plain developers have permission to create a symlink, as you pointed out in...

> 2. If core.symlinks is true and the current user doesn't have SeCreateSymbolicLinkPrivilege (e.g. an administrator in an unelevated command prompt) then git checkout silently fails. Surely it should at least display a warning or preferably terminate with an error (as it would on a write failure, for example)? In both cases, the error could suggest changing core.symlinks to false although it's also possible to detect if the user could obtain the privilege by elevation and in that instance it would be a good second suggestion.

Your suggestions make a lot of sense, but are you prepared to follow up and do something about them? In other words, would you please follow the advice in https://github.com/git-for-windows/git/wiki/How-to-participate#fix-bugs-or-add-features-in-the-git-code-itself and in https://github.com/git-for-windows/git/wiki/Building-Git?

**Comment by dra27** [comment] 2015-08-25 08:46
> > If core.symlinks is false, you get an error message adding a native symlink (i.e. created by mklink) from the working directory:

> > ```
[master] C:\Scratch\Sym>git add Bar.txt
error: readlink("Bar.txt"): Function not implemented
error: unable to index file Bar.txt
fatal: adding files failed```


> Yes, this is intentional:  `core.symlinks`  does not *quite* enable symbolic links because Git's idea of symbolic links matches POSIX semantics *exactly* while our emulation does not.

I have recently been working on symlinks in another project (https://github.com/dra27/ocaml/commit/eeece9629ff2b35a4f2d2ed85ceee346dc09209e & https://github.com/dra27/ocaml/commit/559747ad661265244d1c67f20dd342f4a000816d) - is the semantics you refer to Windows' having separate directory and filename symlinks, or is there a further gotcha? (curiosity only!)

>  It is close, but not close enough to enable by default.  For example, we cannot assume that plain developers have permission to create a symlink, as you pointed out in...

I can see why `core.symlinks` is not turned on *for writing* by default, but why does it ever have to be the case that Git refuses to *read* them (all users can read them, even if following them is fully disabled using fsutil behavior set SymlinkEvaluation, despite the unclear documentation of FILE_FLAG_BACKUP_SEMANTICS in MSDN)? The error message reads as though Git is in some way deficient, which it clearly isn't!

> > 1.If core.symlinks is true and the current user doesn't have SeCreateSymbolicLinkPrivilege (e.g. an administrator in an unelevated command prompt) then git checkout silently fails. Surely it should at least display a warning or preferably terminate with an error (as it would on a write failure, for example)? In both cases, the error could suggest changing core.symlinks to false although it's also possible to detect if the user could obtain the privilege by elevation and in that instance it would be a good second suggestion.

> Your suggestions make a lot of sense, but are you prepared to follow up and do something about them? In other words, would you please follow the advice in https://github.com/git-for-windows/git/wiki/How-to-participate#fix-bugs-or-add-features-in-the-git-code-itself and in https://github.com/git-for-windows/git/wiki/Building-Git?

Possibly - although probably not soon, alas! But it's helpful to know that the change would be considered useful, so I'll keep this on my ToDo list :smiley:

**Comment by dscho** [comment] 2015-08-25 11:07
@dra27 I just invited you into the active team so I can assign this issue to you.

**Comment by dscho** [comment] 2015-09-09 13:08
@dra27 did you have any chance to work on this?

**Comment by dscho** [comment] 2015-09-17 21:30
@dra27 ping?

**Comment by kblees** [comment] 2015-09-18 08:53
@dra27 Regarding your first point:

My utmost goal when adding symlink support was that with ```core.symlinks=false```, git should behave **exactly** as before, so that we don't introduce regressions. The one instance where I deviated from this principle (```stat()``` for symlinks failing with ELOOP instead of returning false data) already caused problems (#186).

So ```core.symlinks=false``` on Windows behaves as if symlinks weren't supported by the platform, with ```[l]stat()``` beeing a notable exception (as in earlier git versions).

**Comment by dscho** [comment] 2015-09-18 09:20
@kblees I really appreciate your careful approach. IIRC we had a different approach before, and had to revert it wholesale because it caused real problems (#186 was a minor issue that was easily addressed, thanks to the excellent design of the `core.symlinks` support). If all Git for Windows contributions were that excellent, my job as maintainer would be sweet as a lazy Sunday morning :smiley:

**Comment by dscho** [comment] 2015-09-24 10:01
@dra27 everything okay with you?

**Comment by dra27** [comment] 2015-09-24 10:08
@dscho - apologies, I missed the ping. Not had a chance to work on this yet - I'm afraid I really did mean "not soon". Should hopefully be able to get to this in late October.
@kblees - I completely see your point, but I think that the previous behaviour was a bug which should be fixed. The platform does support symlinks, so the assumption in Git that they didn't exist and an error message reading them is an error (but *not*, I hasten to add, an error in your patch to preserve that behaviour!)

**Comment by simonfox** [comment] 2015-11-02 20:20
Not sure this is the best place for me to point this out, but I also have an issue with symlink'd folders that are specified in the .gitignore. The .gitignore lines for the symlinks aren't respected and the folders are shown as new items.

**Comment by dscho** [comment] 2015-11-07 15:45
@simonfox please be precise what kind of "symlink'd folders" you talk about. The best way to be precise is to state explicitly the command you used to create the symlinks. This is unfortunately necessary because people refer to two, very different things as "symlinks" in Windows.

**Comment by simonfox** [comment] 2015-11-08 20:49
@dscho sorry...
The symlinks are created as part of our build using `gulp-symlink` which uses [nodejs fs.symlink function](https://nodejs.org/api/fs.html#fs_fs_symlink_destination_path_type_callback). `gulp-symlink` passes `'dir'` for the value of the `type` parameter which I think creates a true symlink. Windows Explorer displays the folder as a shortcut...

**Comment by dscho** [comment] 2015-11-09 14:54
> The symlinks are created as part of our build using gulp-symlink which uses nodejs fs.symlink function.

You really had to send me on a wild goose chase to find out whether junction points are created or whether Vista-style symlinks requiring admin privileges are created instead, didn't you :stuck_out_tongue:

**Comment by dscho** [comment] 2015-11-09 15:11
node.js parses the symlink type [here](https://github.com/nodejs/node/blob/9148114c93861359a502801499d4c26d0b761174/src/node_file.cc#L595-L604), and it is used [here](https://github.com/nodejs/node/blob/6fff47ffacfe663efeb0d31ebd700a65bf5521ba/deps/uv/src/win/fs.c#L1661). The `dir` type will be parsed into the `UV_FS_SYMLINK_DIR` flag which in turn indeed creates a Vista style symlink.

Such a symlink can be created using the `/d` flag to the `mklink` executable.

And I cannot reproduce what you are claiming at all: as adminstrator, I created such a symlink in `/usr/src/build-extra`:

```cmd
mklink /d a1 portable
```

A `git status` correctly reports this as an untracked file. Adding the line `/a1` to the `.gitgnore` file changes that: now `git status` reports a modified `.gitignore` file, but no untracked `a1` file anymore. In other words, my test contradicts your claim that symlinks are not ignored correctly after adding them to the `.gitignore` file.

Are you sure you want to continue to be parsimonious with your description of your problem? I did sink quite a bit into this issue with my research, so I am no longer willing to do all the bidding myself, and will require you to volunteer much more, including a [Minimal, Complete & Verifiable Example](http://stackoverflow.com/help/mcve) if I am to spend any more time on assisting you to resolve your issues.

**Comment by simonfox** [comment] 2015-11-09 20:48
@dscho again, please accept my apologies, it wasn't my intention to muck you around.

I have determined the _issue_ is caused by a trailing slash in the `.gitignore`. The reason it has come up for me as the behavior is different between git 1.9.5 which is what I was using until I raised this.

In `1.9.5` using either `a1` or `a1/` in `.gitignore` would both ignore a dir symlink created using gulp-symlink (which from your investigation is a Vista style symlink). We were using trailing slashes in our .gitignore and so after upgrading to `2.6.2.windows.1` the ignore lines were not respected. I can confirm that by removing the trailing slash, the symlinks are ignored.

If you require any further information or if you would like me to try anything else please let me know.

**Comment by dscho** [comment] 2015-11-10 11:44
> In 1.9.5 using either a1 or a1/ in .gitignore would both ignore a dir symlink created using gulp-symlink (which from your investigation is a Vista style symlink)

That was because we did not support symlinks at all back then. So your symlink was mistaken for a directory, and the behavior you saw is consistent with that.

Symlinks are *not* directories, however, so adding their name with a trailing slash to `.gitignore` tells Git to ignore the *contents* of a *directory* of that name. Since there is no such directory, the entry is essentially a no-op.

You will see the same behavior if you gitignore, say, `git-for-windows/` and then put a *file* of that name into the directory.

**Closed by dscho** 2015-11-10 11:44 UTC
Labels: question, wontfix
