### ISSUE TITLE
git push hangs in object packing

### ISSUE THREAD

**Issue by yegorich** [git-for-windows/git#2314] opened 2019-08-29 09:01 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

$ git --version --build-options
git version 2.23.0.windows.1
cpu: x86_64
built from commit: 4db2e5cc9e1522131a039cbad3970f147a39f0ce
sizeof-long: 4
sizeof-size_t: 8

Windows 10 64-bit

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.18362.295]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
>type "C:\Program Files\Git\etc\install-options.txt"
Editor Option: VIM
Custom Editor Path:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
Enable Builtin Interactive Add: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

I've setup this option to fix a well known bug for the git:// protocol.

`git config --global sendpack.sideband 0`

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

I've tried both Bash/CMD/PowerShell and GUI

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git push
```
 - What did you expect to occur after running these commands?

Ordiniray git push response that everything got pushed.

 - What actually happened instead?

The command hangs and when I press Ctrl-C I get the following message:

error: pack-objects died of signal 2

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

It is an internal repository (the size is about 2MB) and it uses git:// as a protocol. On my previous intallation I used Windows 7 64-bit and with the following command I could fix this error:

`git config --global sendpack.sideband 0`

This time it doesn't help.

**Comment by landstander668** [comment] 2019-08-29 14:48
Looks like this is a duplicate of #907.

**Comment by assarbad** [comment] 2019-08-29 20:15
... and by extension the more recent #2278 ...

@yegorich Your first and fastest workaround will be to downgrade to [v2.21.0](https://github.com/git-for-windows/git/releases/tag/v2.21.0.windows.1) ...

**Comment by yegorich** [comment] 2019-08-30 06:14
@assarbad thankk. The suggested workaround works like a charm.

**Closed** 2019-08-30 06:20 UTC
