### ISSUE TITLE
GCM Core unresponsive & no Git Bash added to Terminal on Insiders build 21390.2025

### ISSUE THREAD

**Issue by fkelava** [git-for-windows/git#3291] opened 2021-06-22 20:00 UTC
- [ X ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

This is the regular 2.32.0 64-bit installer.

```
$ git --version --build-options

git version 2.32.0.windows.1
cpu: x86_64
built from commit: 4c204998d0e156d13d81abe1d1963051b1418fc0
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

This is the latest available Dev Channel Insiders build. It is 64-bit.

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.21390.2025]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Nothing in particular. This is an fresh install of Windows, updated to the latest Cumulative and Insider build, and outfitted with no applications that seem to me as though they should conflict with Git/GCM Core. To illustrate, here's a list of installed applications at present.

```
$ choco list -li
Chocolatey v0.10.15
7zip.install 19.0
chocolatey 0.10.15
chocolatey-core.extension 1.3.5.1
chocolatey-windowsupdate.extension 1.0.4
dotnetcore-desktopruntime 3.1.16
dotnetcore3-desktop-runtime 3.1.16
Everything 1.4.11009
foobar2000 1.6.6
irfanview 4.58
irfanviewplugins 4.58
keepassxc 2.6.6
mpc-hc-clsid2 1.9.13
notepadplusplus.install 8.1
powertoys 0.37.2
qbittorrent 4.3.5
vcredist140 14.29.30037
vcredist2015 14.0.24215.20170201
24 packages installed.

Git version 2.32.0|2.32.0
Microsoft Edge Dev|93.0.916.1
Microsoft OneDrive|21.099.0516.0003
Microsoft Update Health Tools|2.81.0.0
Microsoft Visual Basic/C++ Runtime (x86)|1.1.0
Microsoft Visual C++ 2005 Redistributable|8.0.61187
Microsoft Visual C++ 2005 Redistributable (x64)|8.0.61186
Microsoft Visual C++ 2008 Redistributable - x64 9.0.30729.7523|9.0.30729.7523
Microsoft Visual C++ 2008 Redistributable - x86 9.0.30729.7523|9.0.30729.7523
Microsoft Visual C++ 2010  x64 Redistributable - 10.0.40219|10.0.40219
Microsoft Visual C++ 2010  x86 Redistributable - 10.0.40219|10.0.40219
Microsoft Visual C++ 2012 x64 Additional Runtime - 11.0.61135|11.0.61135
Microsoft Visual C++ 2012 x64 Minimum Runtime - 11.0.61135|11.0.61135
Microsoft Visual C++ 2012 x86 Additional Runtime - 11.0.61135|11.0.61135
Microsoft Visual C++ 2012 x86 Minimum Runtime - 11.0.61135|11.0.61135
Microsoft Visual C++ 2013 x64 Additional Runtime - 12.0.40664|12.0.40664
Microsoft Visual C++ 2013 x64 Minimum Runtime - 12.0.40664|12.0.40664
Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.40664|12.0.40664
Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.40664|12.0.40664
Microsoft Visual C++ 2019 X64 Additional Runtime - 14.29.30130|14.29.30130
Microsoft Visual C++ 2019 X64 Minimum Runtime - 14.29.30130|14.29.30130
Microsoft Visual C++ 2019 X86 Additional Runtime - 14.29.30130|14.29.30130
Microsoft Visual C++ 2019 X86 Minimum Runtime - 14.29.30130|14.29.30130
Microsoft Visual Studio 2010 Tools for Office Runtime (x64)|10.0.60833
Microsoft Visual Studio Code|1.57.1
Microsoft Windows Desktop Runtime - 3.1.16 (x64)|3.1.16.30112
Microsoft Windows Desktop Runtime - 3.1.16 (x86)|3.1.16.30112
NVIDIA Graphics Driver 456.71|456.71
Python 3.9.5 (64-bit)|3.9.5150.0
Python Launcher|3.9.7427.0
30 applications not managed with Chocolatey.
```

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
$ env GIT_TRACE=1 git clone https://github.com/fsbracingteam/vulpesr
21:46:41.543114 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
21:46:41.544113 git.c:455               trace: built-in: git clone https://github.com/fsbracingteam/vulpesr
Cloning into 'vulpesr'...
21:46:41.553088 run-command.c:667       trace: run_command: git remote-https origin https://github.com/fsbracingteam/vulpesr
21:46:41.559169 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:46:41.560167 git.c:744               trace: exec: git-remote-https origin https://github.com/fsbracingteam/vulpesr
21:46:41.560167 run-command.c:667       trace: run_command: git-remote-https origin https://github.com/fsbracingteam/vulpesr
21:46:41.567228 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:46:41.759096 run-command.c:667       trace: run_command: 'git credential-manager-core get'
21:46:41.796395 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:46:41.796395 git.c:744               trace: exec: git-credential-manager-core get
21:46:41.796395 run-command.c:667       trace: run_command: git-credential-manager-core get

# No progress is made from this point on. The call hangs.
```
 - What did you expect to occur after running these commands?

A GCM Core prompt is shown. Authentication takes place. The repository is cloned.

 - What actually happened instead?

The call does not complete. No GCM prompt is shown. The call hangs indefinitely.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

This happens on every repository that requires authentication. I do not believe this is related to the specific repository from the example above, as other users (none of which are on version 2.32) report the repository functions as intended. Git is still perfectly functional if the repository does _not_ require authentication, as such:

```
$ env GIT_TRACE=1 git clone https://github.com/git-for-windows/git
21:53:52.246937 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
21:53:52.246937 git.c:455               trace: built-in: git clone https://github.com/git-for-windows/git
Cloning into 'git'...
21:53:52.262558 run-command.c:667       trace: run_command: git remote-https origin https://github.com/git-for-windows/git
21:53:52.262558 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:53:52.262558 git.c:744               trace: exec: git-remote-https origin https://github.com/git-for-windows/git
21:53:52.262558 run-command.c:667       trace: run_command: git-remote-https origin https://github.com/git-for-windows/git
21:53:52.278180 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:53:53.028038 run-command.c:667       trace: run_command: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 9764 on panopticon' --check-self-contained-and-connected
21:53:53.043635 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
21:53:53.043635 git.c:455               trace: built-in: git index-pack --stdin -v --fix-thin '--keep=fetch-pack 9764 on panopticon' --check-self-contained-and-connected
remote: Enumerating objects: 480837, done.
Receiving objects:  39% (187527/480837), 136.61 MiB | 10.38 MiB/s
```

Another anomaly is that the installer option to _Add Git Bash profile to Windows Terminal_ did not seem to function. My Terminal install does not show a Git Bash profile, even after a restart. I'd be happy to provide any information you need to get to the bottom of this. I distinctly remember this working in <=2.31.

I'm certain that this is somehow my failing, but I have no idea _why_. I _have_ been able to get everything working on Insider with prior releases of GfW. I don't see an obvious culprit. A cursory search has yielded no solutions. I'd be extremely grateful for any advice. I'll provide any additional info you may want as best I may.

I'm well aware that normally a private repository to which access is not given is not considered a proper MCVE. However, due to the nature of the issue being with _pre-clone authentication_ steps, it can serve as an adequate example, as you do not need to actually perform a successful clone. Failing authentication would also be a correct result in this instance.

**Comment by fkelava** [comment] 2021-06-22 20:41
For further posterity, attached is the GCM_TRACE of the same command used in the example above.

```
$ env GCM_TRACE=1 GIT_TRACE=1 git clone https://github.com/fsbracingteam/vulpesr
22:40:41.029494 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
22:40:41.029494 git.c:455               trace: built-in: git clone https://github.com/fsbracingteam/vulpesr
Cloning into 'vulpesr'...
22:40:41.044586 run-command.c:667       trace: run_command: git remote-https origin https://github.com/fsbracingteam/vulpesr
22:40:41.044586 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
22:40:41.044586 git.c:744               trace: exec: git-remote-https origin https://github.com/fsbracingteam/vulpesr
22:40:41.044586 run-command.c:667       trace: run_command: git-remote-https origin https://github.com/fsbracingteam/vulpesr
22:40:41.054521 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
22:40:41.284624 run-command.c:667       trace: run_command: 'git credential-manager-core get'
22:40:41.314184 exec-cmd.c:237          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
22:40:41.314184 git.c:744               trace: exec: git-credential-manager-core get
22:40:41.314184 run-command.c:667       trace: run_command: git-credential-manager-core get
22:40:41.389492 ...\Application.cs:80   trace: [RunInternalAsync] Version: 2.0.474.41365
22:40:41.389492 ...\Application.cs:81   trace: [RunInternalAsync] Runtime: .NET Framework 4.0.30319.42000
22:40:41.389492 ...\Application.cs:82   trace: [RunInternalAsync] Platform: Windows (x86-64)
22:40:41.389492 ...\Application.cs:83   trace: [RunInternalAsync] AppPath: git-credential-manager-core
22:40:41.389492 ...\Application.cs:84   trace: [RunInternalAsync] Arguments: get
22:40:41.434342 ...GitCommandBase.cs:35 trace: [ExecuteAsync] Start 'get' command...
22:40:41.434342 ...GitCommandBase.cs:49 trace: [ExecuteAsync] Detecting host provider for input:
22:40:41.444391 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   protocol=https
22:40:41.444391 ...GitCommandBase.cs:50 trace: [ExecuteAsync]   host=github.com
22:40:41.474292 ...viderRegistry.cs:149 trace: [GetProviderAsync] Performing auto-detection of host provider.
22:40:41.474292 ...viderRegistry.cs:162 trace: [GetProviderAsync] Checking against 3 host providers registered with priority 'Normal'.
22:40:41.474292 ...GitCommandBase.cs:52 trace: [ExecuteAsync] Host provider 'GitHub' was selected.
22:40:41.484610 ...\HostProvider.cs:128 trace: [GetCredentialAsync] Looking for existing credential in store with service=https://github.com account=...
22:40:41.484610 ...\HostProvider.cs:133 trace: [GetCredentialAsync] No existing credentials found.
22:40:41.484610 ...\HostProvider.cs:136 trace: [GetCredentialAsync] Creating new credential...
22:40:41.504479 ...bHostProvider.cs:250 trace: [GetSupportedAuthenticationModesAsync] https://github.com/ is github.com - authentication schemes: 'OAuth, Pat'
22:40:41.544490 ...ndowsTerminal.cs:188 trace: [.ctor] Setting console echo state to 'True'

# There is no further progress made. The call hangs.
```

**Comment by dscho** [comment] 2021-06-22 21:30
This looks like a straight duplicate of #3284. Please download the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) and install it, that should fix the issue.

**Closed** 2021-06-22 21:31 UTC
Labels: duplicate

**Comment by fkelava** [comment] 2021-06-22 21:37
My apologies for the mistake, then. Duly noted. Thank you for your time.

**Comment by dscho** [comment] 2021-06-23 09:34
No worries. Did you download the latest snapshot and verify that it works?

**Comment by fkelava** [comment] 2021-06-24 22:45
Yes. Everything is back to normal.
