### ISSUE TITLE
Git wont install

### ISSUE THREAD

**Issue by Reddgum** [git-for-windows/git#2539] opened 2020-03-09 22:54 UTC
Background:
Git 2.18 was installed circa 2018-ish  and was running fine until the SSD drive it was installed on completely detonated. 

**Today:** Fresh download of GIT ver 2.25 x64. Try to run installer and it's falling all over itself trying to find the config files from the old install. So, I've gone through the registry trying to find any and all vestiges of the old GIT install and delete them.

Repeat attempting install, multiple pop-ups telling me it cant find things.

It seems that the installer insanely keeps trying to find a file named 'git-config-get.txt' from a non-existant folder: C:\Users\(myname)\AppData\Local\Temp\is-ISCH4.tmp\git-config-get.txt

If I click OK and let it continue, it fails with a message about the path or UNC is unavailable but there's no option(s) or opportunities (like every app I've seen in 40 some years) to change it.

I'm running Agent Ransack in the background at the moment scanning the entire drive for anything containing the filename but (as of 14:11 into the scan, nothing) -- it's got my i7 CPU pegged at 98% valiantly trying to find this top-secret little gremlin.

**I'd like help identifying what files / registry keys and their locations I need to delete so that I can get a FRESH install of GIT on this machine.**

OS: Win 10 Pro [Version 10.0.17763.1039] 
Dev Env: Visual Studio 2017 & 2019, Jetbrains Pycharm

Wishlist:

It might be worthwhile to publish all the configuration file locations & registry settings that git puts in, because sometimes bad things happen to our drives and this kind of nonsense could have been easily remedied if there was some facility within the installer to re-create configs etc.

Maybe someone might write a cleaner tool someday?

**Comment by dscho** [comment] 2020-03-10 09:24
> It seems that the installer insanely keeps trying to find a file named 'git-config-get.txt' from a non-existant folder: C:\Users(myname)\AppData\Local\Temp\is-ISCH4.tmp\git-config-get.txt

This folder exists only during an installation run, it is InnoSetup's temporary folder.

> If I click OK and let it continue, it fails with a message about the path or UNC is unavailable but there's no option(s) or opportunities (like every app I've seen in 40 some years) to change it.

So this is simply a duplicate of https://github.com/git-for-windows/git/issues/1074

You can work around it via the command-line option `/DIR=<folder>` of the installer.

**Closed by dscho** 2020-03-10 09:24 UTC
Labels: duplicate

**Comment by Reddgum** [comment] 2020-03-10 16:25
Ok, that allowed the installer to push past the issue - thank you!

Still curious as to what / where the installer is looking and finding those old files / settings. Agent Ransack sucked amps for 9 hours trying to find it.. I'd write a clean up utility, but since the /DIR option hack-a-round works, probably not worth anyone's time.

Just a note though - from the viewpoint of an old dog, since the installer is a GUI, the option should be given to the user to force / change the install directory (with a little admonition that it could blow up existing install.) within the operation of the GUI at the time of failure.

Thanks.

**Comment by dscho** [comment] 2020-03-10 21:34
It's InnoSetup, and [this part of the installer code](https://github.com/git-for-windows/build-extra/blob/c5ed36dbaadda06d090bbdb24b49353a4847d3c6/installer/install.iss#L2326-L2355) indicates that the registry key is `Microsoft\Windows\CurrentVersion\Uninstall\Git_is1`.

**Comment by manikiran949** [comment] 2025-02-06 17:20
- I encountered the same problem when I merged my drives while trying to install Git.  
- To fix it:  
  1. Open the **Control Panel**.  
  2. Uninstall the program completely.  
  3. If you see a message saying, *"The program does not exist. Do you want to remove it?"*, select **"Yes"**.  
  4. Reinstall the application.  
- This method worked for me.
