### ISSUE TITLE
Installer incorrectly prompts for UAC/admin rights when user does not have them

### ISSUE THREAD

**Issue by bbodenmiller** [git-for-windows/git#941] opened 2016-11-03 09:30 UTC
- [X] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

The installer is prompting with the UAC prompt when the user does not have admin rights. Regardless I select yes and it seems to proceed and try to install in AppData however the installer never finishes. The installation status green bar has been stuck at 100% for 30 minutes now and it does appear Git is installed.

In summary two issues:
- [ ] UAC should not prompt
- [ ] Installer should finish on non-admin account

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.10.2.windows.1
sizeof-long: 4
machine: x86_64
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 6.1.7601]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt
Path Option: Cmd
SSH Option: OpenSSH
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

N/A

**Comment by dscho** [comment] 2016-11-03 15:21
> The installation status green bar has been stuck at 100% for 30 minutes now and it does appear Git is installed.

Could you run the installer with `/LOG=<filename>` and simply kill the `bash.exe` process running at the end of the installation? This should produce a more verbose output in the log file.

**Comment by dscho** [comment] 2016-11-03 15:22
> The installer is prompting with the UAC prompt when the user does not have admin rights. Regardless I select yes and it seems to proceed and try to install in AppData

It is actually highly discouraged to install Git non-system-wide. So the fallback to AppData is purely for your pleasure, and it is not really the intended usage.

**Comment by bbodenmiller** [comment] 2016-11-03 22:47
I haven't been able to reproduce the installer not finishing issue.

I understand it's better to install system wide but sometimes in corporate world we have no choice so installing to AppData is nice. Is there no way to prevent the UAC prompt from opening for non-admin users?

**Comment by dscho** [comment] 2016-11-04 11:43
> I understand it's better to install system wide but sometimes in corporate world we have no choice so installing to AppData is nice.

Understandable. The same reasoning led to the PortableGit.

> Is there no way to prevent the UAC prompt from opening for non-admin users?

I am afraid I have not found any way, except by breaking the system-wide install :-( Maybe you find a way (you could start by verifying that I did not miss anything at http://www.jrsoftware.org/ishelp/index.php that would suggest that there is a way)?

**Comment by dscho** [comment] 2016-11-18 22:06
> I am afraid I have not found any way, except by breaking the system-wide install :-( Maybe you find a way?

Until the time somebody comes up with a yes (which will make me very happy), I will close this ticket.

**Closed by dscho** 2016-11-18 22:06 UTC
Labels: question

**Comment by bmcdonnell-ionx** [comment] 2018-01-03 19:37
@dscho,

> It is actually highly discouraged to install Git non-system-wide. So the fallback to AppData is purely for your pleasure, and it is not really the intended usage.

Discouraged by whom?

I think it is becoming more common for IT departments to not give local admin rights even to developers, and user-level installations are becoming more popular.

Have you asked about it on the [Inno Setup newsgroup](http://www.jrsoftware.org/newsgroups.php)? If the capability isn't there, I think a conditionally-elevated installation is a reasonable feature request.

@bbodenmiller said:
> The installer is prompting with the UAC prompt when the user does not have admin rights. Regardless I select yes and it seems to proceed and try to install in AppData

@dscho, this is unintuitive in the UI. I didn't expect the UAC prompt since I was attempting a user-level install, and then I didn't expect it to work once I dismissed the UAC prompt. Also, tasks appeared stuck at the end, so I used Task Manager to kill them. So in the meantime, unless/until the UAC prompt is launched *only* when needed, can you add some explanatory text in the window before the prompt?

**Comment by dscho** [comment] 2018-01-04 19:44
> Have you asked about it on the Inno Setup newsgroup? If the capability isn't there, I think a conditionally-elevated installation is a reasonable feature request.

@bmcdonnell-ionx it is cute that you think I have all the time in this world... but there is hope: this is Open Source. You do not need to rely on me to do everything. You can easily do this yourself, you can even read the entire source code for making a Git for Windows installer, suggest fixes via Pull Requests, and I have a track record of merging such Pull Requests.

As to the UAC prompt: since Git for Windows' installer is marked as installing into Program Files, it has to do this.

You are warmly welcome to work on changing this, as long as you do not break the traditional way to install Git for Windows.

**Comment by bmcdonnell-ionx** [comment] 2018-01-04 20:00
@dscho, sorry if I was unclear, or seemed demanding. I meant I think it would be a "reasonable feature request" for you to make of the Inno Setup development team. And I didn't even mean by that to say that they should automatically do it. I just meant that I think it's a reasonable thing to ask for.

**Comment by PhilipOakley** [comment] 2018-01-04 21:56
@bmcdonnell-ionx 

> "reasonable feature request" for [...] the Inno Setup development team.

I think that what @dscho was saying was that it would help the GFW 'team' greatly, if perchance, you might raise this issue with the InnoSetup folks, obviously referring back to here to this issue. The voice of a real user / use case may well be more valid than some perceived maintainers 'wish'. 

Anything we can do to ease the maintenance burden is a help. I believe you have already identfied where the innosetup news group is, so a quick post there would help.

It maybe that part of the issue is in the way UAC policy is supposed to be implemented versus how it is typically implemented, versus how IT depts are now limiting users UAC options. If it's the latter, it maybe that we just need something in the release notes advising on the complexity of the UAC policy. (A "rock / hard-place / between" rearrange for a well known "Head-wall-bash" scenario...)

**Comment by bmcdonnell-ionx** [comment] 2018-01-04 22:02
@PhilipOakley, thanks for your input.

> I believe you have already identfied where the innosetup news group is, so a quick post there would help.

IIRC, their github says you have to post an issue on the newsgroups before posting an issue on github. TBH, I couldn't figure out how to do so (post). I thought the devs here might know.

**Comment by dscho** [comment] 2018-01-04 23:17
The UAC requirement is controlled by these lines, FYI: https://github.com/git-for-windows/build-extra/blob/2e3de090f6419eb3e8115e0d60902ee589621e1e/installer/install.iss#L68-L72

Now it's up to you if you want to dive into this, or not. If not, I'll just leave this ticket closed.

**Comment by bmcdonnell-ionx** [comment] 2018-01-26 22:58
> I think that what @dscho was saying was that it would help the GFW 'team' greatly, if perchance, you might raise this issue with the InnoSetup folks

Posted:
http://news.jrsoftware.org/read/article.php?id=105701&group=jrsoftware.innosetup

**Comment by dscho** [comment] 2018-01-27 13:53
Thank you for posting the issue. However, have you followed the link I posted? You will see that there is already a knob and we use it and maybe you just need to find the right setting.

**Comment by bmcdonnell-ionx** [comment] 2018-01-31 15:09
> there is already a knob and we use it and maybe you just need to find the right setting.

It is a build-time setting. There is no setting with Inno Setup for deciding the type of install at runtime, and apparently implementing such a feature would require a significant redesign.

Follow the thread on my post linked above for details. The [last post](http://news.jrsoftware.org/read/article.php?id=105708&group=jrsoftware.innosetup) has a suggestion on how it might be done using Inno:

> If you want to get fancy, you can use ISPP to write a single script that you can compile twice to get one per-machine and one per-user installer, but it's usually not worth the extra maintenance and testing overhead.

Alternatively, as I noted there, other installer creators (like Install Shield) do support this feature. I don't know that I would go so far as to advocate that Git for Windows switch for this reason, but I'm just noting that it's an option. (Not a task I intend to take on.)
