### ISSUE TITLE
git clone use Standard Error as output.

### ISSUE THREAD

**Issue by hguy** [git-for-windows/git#3991] opened 2022-08-25 12:59 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.37.2.windows.2
cpu: x86_64
built from commit: c5597badf94101f0076e6667edee120ab1ee5bac
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [version 10.0.19044.1889]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

default
```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

nope

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD via [MedallionShell](https://github.com/madelson/MedallionShell)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone ${repo}
```
 - What did you expect to occur after running these commands?

Having the output message `Cloning into ...` using `Standard Output`.

 - What actually happened instead?

git use `Standard Error` even if the command succeed.

![image](https://user-images.githubusercontent.com/31834707/186670586-281c3b3c-1b3d-4bf2-8920-ebac8ce8a8ba.png)

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

not specific

**Comment by rimrul** [comment] 2022-08-25 13:04
Yes. Pretty much all `git` commands use `stdout` and `stderr` this way. `stdout` for the main command output and `stderr` for "chatty" output like progress information.

**Comment by dscho** [comment] 2022-08-25 13:24
In addition to being a duplicate of #3598, this issue is not specific to Windows, and therefore a question for the "upstream" Git project. Please take it to [the Git mailing list](mailto:git@vger.kernel.org) (send plain-text messages, HTML messages are dropped silently).

**Closed by dscho** 2022-08-25 13:24 UTC
Labels: duplicate, question, git-upstream
