### ISSUE TITLE
git windows version 2.47.1 issue with cloning via ssh

### ISSUE THREAD

**Issue by davidsreb** [git-for-windows/git#5214] opened 2024-10-16 10:03 UTC
- [ ] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git --version --build-options
git version 2.47.0.windows.1
cpu: x86_64
built from commit: d53e4648cb65eb75dd8d8a093d17400a18a9a15d
sizeof-long: 4
sizeof-size_t: 8
shell-path: D:/git-sdk-64-build-installers/usr/bin/sh
feature: fsmonitor--daemon
libcurl: 8.10.1
OpenSSL: OpenSSL 3.2.3 3 Sep 2024
zlib: 1.3.1

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.22631.4169]
(c) Microsoft Corporation. All rights reserved.

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path:
Default Branch Option:
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable FSMonitor: Disabled

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

tried to run this from many different environments including running from windows serve 22 core container to isolate the issue from different machines (in domain /out of domain/ server 2019/server 2022, docker image mcr.microsoft.com/windows/servercore:ltsc2022 added git installation on top of it)and different networks
 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

git bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git clone git@github.com:winsw/winsw.git
or 
git clone git@github.com:git-for-windows/git.git

```
 - What did you expect to occur after running these commands?

i expected the repo to be cloned into my machine/docker container

 - What actually happened instead?
 
git clone git@github.com:git-for-windows/git.git
Cloning into 'git'...
remote: Enumerating objects: 623437, done.
Receiving objects:   2% (12469/623437), 2.61 MiB | 5.20 MiB/s

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

any github or gitlab including selfhosted gitlab repos it happens sporadically because sometimes it does succeeds.
tried to run the command with -vvv and got no info regarding the issue

**Comment by rimrul** [comment] 2024-10-16 10:46
Duplicate of #5199

**Comment by rimrul** [comment] 2024-10-16 10:47
Please upgrade to the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html). That fixes this issue.

**Closed** 2024-10-16 10:47 UTC
Labels: duplicate
