### ISSUE TITLE
Pager is not utilized for aliases using '!' syntax to run git

### ISSUE THREAD

**Issue by rcdailey** [git-for-windows/git#85] opened 2015-04-09 19:16 UTC
I'm running the 3rd iteration of the developer preview.

When I run my git alias to show my log graph with special formatting, pagination is not being used when it should. I have `core.pager` set to `less`.

I have the following aliases in my `.gitconfig`:

```
[alias]
    short-log-base = log --abbrev-commit --decorate --date=relative --format=format:'%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'
    l = !git short-log-base
```

I have not verified this but I suspect the usage of `!` to execute git to chain aliases together is the root cause. I say this because if I run `git short-log-base`, pagination works. But if I run `git l`, pagination does not work. In the logs below, I show the differences between the two. Note in the trace that less is not executed for the former example.

```
|-- robert@M5536:/e/code/frontend (timeline-ids) --|
$ GIT_TRACE=1 git l -1
14:09:51.997143 git.c:557               trace: exec: 'git-l' '-1'
14:09:51.997143 run-command.c:351       trace: run_command: 'git-l' '-1'
14:09:51.999147 run-command.c:351       trace: run_command: 'git short-log-base' '-1'
14:09:52.068563 git.c:557               trace: exec: 'git-short-log-base' '-1'
14:09:52.069564 run-command.c:351       trace: run_command: 'git-short-log-base' '-1'
14:09:52.070565 git.c:282               trace: alias expansion: short-log-base => 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'
14:09:52.071565 git.c:348               trace: built-in: git 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)' '-1'
5a382db | (6 days ago) (HEAD, timeline-ids) Robert Dailey - [TOOLING] WIP: Backward compatibility option in LC for legacy timeline export

|-- robert@M5536:/e/code/frontend (timeline-ids) --|
$ GIT_TRACE=1 git short-log-base -1
14:10:18.343755 git.c:557               trace: exec: 'git-short-log-base' '-1'
14:10:18.344756 run-command.c:351       trace: run_command: 'git-short-log-base' '-1'
14:10:18.345757 git.c:282               trace: alias expansion: short-log-base => 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'
14:10:18.346769 git.c:348               trace: built-in: git 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)' '-1'
14:10:18.367786 run-command.c:351       trace: run_command: 'less'
5a382db | (6 days ago) (HEAD, timeline-ids) Robert Dailey - [TOOLING] WIP: Backward compatibility option in LC for legacy timeline exp
```

**Comment by kblees** [comment] 2015-04-09 21:57
Could you try that in a native console window (`cmd //c "start bash -li"`)? Sounds similar to the pager problems in a second mintty window (see issue #74).

Suspected cause: when git starts another process (which the '!' alias would do), it dup()licates the in/out/err descriptors (in run-command.c::start_command). This means that the in/out/err streams of the child process no longer match MSYS_TTY_HANDLES.

**Comment by dscho** [comment] 2015-04-09 23:14
@kblees good analysis!

**Comment by rcdailey** [comment] 2015-04-13 14:59
@kblees I ran the command from CMD in Windows and pager works as expected. Thanks for your help and analysis.

I'm not well versed in git development, so would this issue be specific to the Git for Windows project or better reported to the original git mailing list?

**Comment by kblees** [comment] 2015-04-13 15:30
> I ran the command from CMD in Windows and pager works as expected.

Thanks, so it seems to be caused by mintty as well...

> so would this issue be specific to the Git for Windows project

Yes

> or better reported to the original git mailing list

No

**Comment by dscho** [comment] 2015-04-22 09:05
@rcdailey if you have not done so yet, could you please set up a [Git SDK](https://git-for-windows.github.io/#download-sdk) and test the `kb/msys-tty` branch: https://github.com/dscho/git/commits/kb/msys-tty -- it should fix this problem, but I'd like to read your confirmation that it does fix that.

**Comment by rcdailey** [comment] 2015-04-22 16:59
@dscho Verified working (git version info at the bottom of the snippet)

```
|-- Robert@M5536:/e/code/frontend (develop-ah3k) --|
$ GIT_TRACE=1 git l -1
17:54:14.321698 git.c:557               trace: exec: 'git-l' '-1'
17:54:14.321698 run-command.c:351       trace: run_command: 'git-l' '-1'
17:54:14.324718 run-command.c:351       trace: run_command: 'sh -c : git log ; git short-log-base' '-1'
17:54:14.501826 git.c:557               trace: exec: 'git-short-log-base' '-1'
17:54:14.501826 run-command.c:351       trace: run_command: 'git-short-log-base' '-1'
17:54:14.504828 git.c:282               trace: alias expansion: short-log-base => 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'
17:54:14.505829 git.c:348               trace: built-in: git 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)' '-1'
17:54:14.553864 run-command.c:351       trace: run_command: 'less'
3499309 | (5 days ago) (HEAD, develop-ah3k) Robert Dailey - Make the bamboo unit test script executable

|-- Robert@M5536:/e/code/frontend (develop-ah3k) --|
$ GIT_TRACE=1 git short-log-base -1
17:56:48.138948 git.c:557               trace: exec: 'git-short-log-base' '-1'
17:56:48.138948 run-command.c:351       trace: run_command: 'git-short-log-base' '-1'
17:56:48.141951 git.c:282               trace: alias expansion: short-log-base => 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)'
17:56:48.143952 git.c:348               trace: built-in: git 'log' '--abbrev-commit' '--decorate' '--date=relative' '--format=format:%C(bold blue)%h%C(reset) | %C(bold green)(%ar)%C(reset)%C(bold yellow)%d%C(reset) %C(dim white)%an%C(reset) - %C(white)%s%C(reset)' '-1'
17:56:48.197990 run-command.c:351       trace: run_command: 'less'
3499309 | (5 days ago) (HEAD, develop-ah3k) Robert Dailey - Make the bamboo unit test script executable

|-- Robert@M5536:/e/code/frontend (develop-ah3k) --|
$ git version
git version 2.3.5.windows.8.14.g7cee121
```

The git version shows what appears to be a shorthand SHA1 hash at the end, which doesn't align with what shows up on your branch, so I do not know for sure if I've built git correctly (all I did was checkout your branch and run `make`):

```
|-- Robert@M5536:/usr/src/git (kb/msys-tty) --|
$ git last
ba20c83cfc97022ec032d071ab1458c5cffed58a - 2015-04-22 09:26:50 +0100 (8 hours ago) (HEAD, dscho/kb/msys-tty, kb/msys-tty)
--- Johannes Schindelin <johannes.schindelin@gmx.de> ---

squash! Revert "mingw: Work around MSVCRT's isatty() not knowing about MSys2"

Replace commit subject with:

fixup! mingw: Work around MSVCRT's isatty() not knowing about MSys2

to remind myself to drop that patch.
```

**Comment by dscho** [comment] 2015-04-22 18:10
> The git version shows what appears to be a shorthand SHA1 hash at the end, which doesn't align with what shows up on your branch

That's okay, you built the `master` of `git-for-windows`. Which is at a different SHA-1.

Thanks for the feedback! We can finally close this ticket, thanks to the excellent contribution of @kblees.

**Closed by dscho** 2015-04-22 18:10 UTC
Labels: bug, git, help wanted

**Comment by rcdailey** [comment] 2015-04-22 18:52
@dscho The installer built master, but even though I switched to your branch and ran `make` that wasn't enough? I followed the instructions here:

https://github.com/git-for-windows/git/wiki/Building-Git

In any case, if I was running a build off of master, that means I did not test your changes. How can I get it to actually build your branch?

**Comment by dscho** [comment] 2015-04-22 19:40
> I switched to your branch and ran `make`

You probably wanted to run `make install` so that the newly built `git.exe` would be found on the `$PATH`.

**Comment by dscho** [comment] 2015-04-22 19:41
> if I was running a build off of master, that means I did not test your changes.

Not so. By the time you tested, I had merged the branch into `master` after running my own set of (unfortunately interactive) tests.
