### ISSUE TITLE
gitk: For tags the name of the author with UTF-8 characters will not be displayed correctly.

### ISSUE THREAD

**Issue by bitjo** [git-for-windows/git#767] opened 2016-05-26 16:16 UTC
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen)
  or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue
  matching what I'm seeing
### Setup
- Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
  output of `git version` as well.

```
$ uname
MINGW64_NT-6.1
```
- Which version of Windows are you running? 32-bit or 64-bit?

```
$ uname
MINGW64_NT-6.1
```
- What options did you set as part of the installation? Or did you choose the
  defaults?

defaults
- Any other interesting things about your environment that might be related
  to the issue you're seeing?

no
### Details
- Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

tty/bash
- What commands did you run to trigger this issue? If you can provide a
  [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
  this will help us understand the issue.

```
$ git clone https://github.com/bitjo/git-issue1
$ cd git-issue1/
$ gitk
```
- What did you expect to occur after running these commands?

After click on Tag1 in gitk  I should see:

```
Tag: Tag1
object 4a34266866646ef1d722f3ca5fe89f987e26ceef
type commit
tag Tag1
tagger Groß <gross@example.com> 1464276169 +0200

Tag message
```
- What actually happened instead?

gitk shows:

```
Tag: Tag1
object 4a34266866646ef1d722f3ca5fe89f987e26ceef
type commit
tag Tag1
tagger GroÃŸ <gross@example.com> 1464276169 +0200

Tag message
```

The taggers name in line 5 (Groß) is not correctly (GroÃŸ).
- If the problem was occurring with a specific repository, can you provide the
  URL to that repository to help us with testing?

see above: https://github.com/bitjo/git-issue1

**Comment by dscho** [comment] 2017-02-22 00:01
> Which version of Git for Windows are you using? 32-bit or 64-bit? Include the
>     output of git version as well.
> 
> $ uname
> MINGW64_NT-6.1

That is not the git version.

In any case, I think this may be fixed in the meantime, as I could not reproduce it with v2.11.1.

**Comment by bitjo** [comment] 2017-02-22 20:58
The issue isn't fiexed:

```
$ git clone https://github.com/bitjo/git-issue1
$ cd git-issue1/
$ gitk
```
gitk screenshot, note red text: ![screenshot gitk](https://github.com/bitjo/git-issue1/blob/master/issue.png)

Version infos:
```
user@ADMIX MINGW64 /t/tmp/git-issue1 (master)
$ uname -a
MINGW64_NT-6.1 ADMIX 2.6.1(0.306/5/3) 2017-01-20 15:23 x86_64 Msys
user@ADMIX MINGW64 /t/tmp/git-issue1 (master)
$ git version
git version 2.11.1.windows.1
```
An expected screenshot: ![screenshot gitk unix](https://github.com/bitjo/git-issue1/blob/master/expected.png)

**Comment by dscho** [comment] 2017-02-24 15:14
This is how it looks here:

![gitk-encoding-issue-767](https://cloud.githubusercontent.com/assets/127790/23308691/52369bb0-faac-11e6-9a23-9617a658da29.png)

**Comment by bitjo** [comment] 2017-02-24 23:57
@dscho 

You have to click on 'Tag1' to see the malformed output (don't click on branch or commit summary).

This bug is related to #761.

There is a basic problem with the endcoding in Git Gui / Gitk on Windows.
It's probably easy to solve by a TcL / TK expert.

I'm not that expert, but I know that this bug, #761. and more unpublished bugs have the same cause.

**Comment by bitjo** [comment] 2017-02-25 00:00
BTW @dscho 

I do not know github well.

What do I need to do to make my images look inline?

**Comment by PhilipOakley** [comment] 2017-02-25 19:39
I had a look at the repo. Cloned as instructed.
Here are screen shots of `gitk` with `Tag1` (yellow) clicked - note that the 'Tagger' (lower left) is poorly formed.

![bad gitk tagger](https://cloud.githubusercontent.com/assets/914343/23334112/23d3ef40-fb90-11e6-9826-2286edb96385.PNG)


Also note `gitk` has no font encoding preference (`git gui` does).

Now here is the same in the mintty window (I keep bash separate from cmd, and it's an XP netbook - still works!!)

`git cat-file -p Tag1` 

![bad gitk tagger mintty](https://cloud.githubusercontent.com/assets/914343/23334171/68d17d78-fb91-11e6-9b98-e1bf412315bd.PNG)

(took me a bit to get the right tag foo invocation!)

See that the tagger name is correctly formed here. So problem [gitk fails to render tagger names correctly] repeated!

Just need some spare time to look at gitk's code.

For inserting the images see the line just below the writing pane
"Attach files by dragging & dropping, _selecting them_, or pasting from the clipboard. "
I did the Alt-PrtScn snapshot and dropped it into paint then saved as a png, before using the select.

**Comment by bitjo** [comment] 2017-02-25 20:15
(For inserting the images ...
I had linked to the Github pages containing the image.
This is bad.
I need to link to the URL of the image.)

**Comment by PhilipOakley** [comment] 2017-02-25 22:36
https://github.com/git/git/blob/master/gitk-git/gitk#L11262-L11277 
```
proc add_tag_ctext {tag} {
    global ctext cached_tagcontent tagids

    if {![info exists cached_tagcontent($tag)]} {
	catch {
	    set cached_tagcontent($tag) [exec git cat-file -p $tag]
	}
    }
    $ctext insert end "[mc "Tag"]: $tag\n" bold
    if {[info exists cached_tagcontent($tag)]} {
	set text $cached_tagcontent($tag)
    } else {
	set text "[mc "Id"]:  $tagids($tag)"
    }
    appendwithlinks $text {}
}
```
The two lines `set cached_tagcontent($tag) [exec git cat-file -p $tag]` and `set text $cached_tagcontent($tag)` look to be the part that accesses the tag and gets its text.

Not sure yet about how the equivalent commit text info is aquired for dispay in the same window, which may show how to do the displaying right (or at least how to tweak stuff).

**Comment by PhilipOakley** [comment] 2017-02-25 23:43
The regular commit display starts at https://github.com/git/git/blob/master/gitk-git/gitk#L7261 
`proc selectline {l isnew {desired_loc {}} {switch_to_patch 0}} {` 
(found by searching for the "Follow" line (L7392) that is added  in the display.

We then see the author at https://github.com/git/git/blob/master/gitk-git/gitk#L7348 `$ctext insert end "[mc "Author"]: [lindex $info 1]  $date\n"`

So now search for how `$info` was generated.

**Comment by PhilipOakley** [comment] 2017-02-25 23:48
try https://github.com/git/git/blob/master/gitk-git/gitk#L7343-L7346 to see its loaded via `getcommit($id)`

https://github.com/git/git/blob/master/gitk-git/gitk#L1736 `proc getcommit {id} {`

bed time. time for someone else to pick up the thread...

**Comment by PhilipOakley** [comment] 2017-02-26 13:37
A bit more Yak-shaving on this.

Intersting point of note: the `info exists commitdata($id)` and the `[lindex $info 1]` are completely different uses of `info`.

There is a Tcl command called `info`, with subcommand `exists` that will tell you if a variable exists, so you can see if you need to create or set it. http://wiki.tcl.tk/1185

Meanwhile parts of the gitk code also create a variable called `info` which has higher priority in the local scope and would then hide the `info` command (because tcl is interpreted...). Thankfully the `info` variable is tightly scoped but it's something to look out for.

Back to the https://github.com/git/git/blob/master/gitk-git/gitk#L1736 `proc getcommit {id}`

This either `parsecommit` a commit it knows, or `readcommit` (with post parsing) for ones it doesn't  know

https://github.com/git/git/blob/master/gitk-git/gitk#L1671-L1698 `proc parsecommit` (there is more after that range)

At lines https://github.com/git/git/blob/master/gitk-git/gitk#L1686-L1687 of `parsecommit` we see that the `header` and `comment` parts of the commit object are set. 

They **both use** the `string` command keyword. Maybe this is it. Didn't notice a `string` keyword for the tag message (https://github.com/git/git/blob/master/gitk-git/gitk#L11272).

Need to double check the `string` command, and the `appendwithlinks $text {}` https://github.com/git/git/blob/master/gitk-git/gitk#L11272 in the tag processing.

**Comment by PhilipOakley** [comment] 2017-02-26 14:37
In http://wiki.tcl.tk/1500 section **Using string functions for binary data** it says:

The following subcommands force promotion to unicode strings:

    string first
    string last
    string map
    string replace
    string reverse

--
Try http://wiki.tcl.tk/_//search?submit=Search&S=ByteArray+UTF&_charset_=UTF-8 to review what they do internally to hide the encoding issues of [Everything is a string ](http://wiki.tcl.tk/3018)

**Comment by PhilipOakley** [comment] 2017-02-26 15:39
Did a quick try at wrapping the [line](https://github.com/git/git/blob/master/gitk-git/gitk#L11267)  that gets the tag data `set cached_tagcontent($tag) [exec git cat-file -p $tag]` with a `[string range <str> 0 end]` but no luck.

So, Back to the other side of the commit data. the `[do_readcommit](https://github.com/git/git/blob/master/gitk-git/gitk#L1648-L1664) procedure. And, lo and behold, it has loads of stuff on encoding.

Looked at the code that reads the commit data `git log --no-color --pretty=raw -1` and tried to find a revision notation `git help revisions` [here](https://git-scm.com/docs/gitrevisions) for the tag itself, but no luck there. 

So it has to be the special `git cat-file -p Tag1` format` hence we'll need to repeat the do_readcommit logic, or at least pass in the base command string !

**Comment by PhilipOakley** [comment] 2017-02-26 23:07
two commits at https://github.com/PhilipOakley/gitk/tree/tagger on top of the master I had.

Took a bit to get the second inovcation right. needed to drop the `{ }` brackets in the `set contents [do_readgitcmd $tag $basecmd]`.

**Comment by dscho** [comment] 2017-08-08 13:32
@bitjo you seemed interested in this issue. I will reopen, expecting you to brush up @PhilipOakley's patches and open a clean and polished Pull Request.

**Comment by dscho** [comment] 2017-12-21 14:32
> I will reopen, expecting you to brush up @PhilipOakley's patches and open a clean and polished Pull Request.

@bitjo ping.

**Comment by dscho** [comment] 2018-01-03 12:54
@bitjo happy new year. And ping. You wanted this, right?

**Comment by bitjo** [comment] 2018-08-27 21:14
@dscho
(Sorry to English readers: I just write German, because @scho understands it and I wanted to save time.
DL; DR: I do not have time to submit the patch.)

Ich schaffe es zeitlich nicht, weil dieses Ticket für mich keine hohe Priorität hat.

Der Patch von @PhilipOakley funktionierte bei mir mir lokal.

Um den Patch als Pull Request einzureichen, fehlt  mir aber die Zeit.
Ich müsste mich mit der der Art und Weise der Einreichung und den geforderten Richtlinien  zur Qualität im  Projekt auseinandersetzen. Dazu fehlt mir aber derzeit die Zeit.

Ich bitte um Verzeihung, dass ich hier nicht aktiv werde. Aber ich sehe es schon als guten Beitrag an, dass ich das Ticket überhaupt geöffnet habe.

Aus meiner Sicht ist #761  viel bedeutender, da dort nicht nur in git gui/gitk etwas falsch dargestellt wird, sondern das Repo falsch geändert wird.

**Comment by dscho** [comment] 2018-08-28 13:03
@PhilipOakley do you have the time to brush up those commits? If not, I suggest to just close this ticket (if it was important enough, somebody would have found the time to address this).

**Comment by PhilipOakley** [comment] 2018-09-02 22:56
Hi @dscho At the moment I'm a bit thin on time. I may get more time from 2019, assuming retirement goes well...

The priority on this one is probably elsewhere as there is still no maintainer/curator for the git-gui/gitk repos anyway.

Were there any changes that needed brushing up on anyway? Or was it just a case of re-validation?

**Closed** 2019-10-13 23:15 UTC
