### ISSUE TITLE
git difftool suddenly dies in 2.20

### ISSUE THREAD

**Issue by MarkKharitonov** [git-for-windows/git#1974] opened 2018-12-10 15:53 UTC
I have already downgraded to 2.18, but I am pretty certain the regression comes from 2.20:
```
C:\DFDeploymentSmokeTests [master ↑3 +0 ~12 -0 !]> git difftool
error: cannot spawn Í?: No such file or directory
fatal: external diff died, stopping at NonUITests/SiteCheck.cs
```
Everything works once I downgraded to 2.18.

**Comment by dscho** [comment] 2018-12-10 16:12
And I am pretty certain that this bug report is incomplete:

```sh

$ git difftool                                                                                                                                                    This message is displayed because 'diff.tool' is not configured.
See 'git difftool --tool-help' or 'git help config' for more details.
'git difftool' will now attempt to use one of the following tools:
opendiff kdiff3 tkdiff xxdiff meld kompare gvimdiff diffuse diffmerge ecmerge p4 merge araxis bc codecompare emerge vimdiff
Viewing (1/1): 'README.md'
Launch 'vimdiff' [Y/n]?
```

When I say `y`, it works.

This is with a 64-bit Git for Windows installed via the official installer, using Secure Channel and the "check daily for updates" checked, otherwise default options.

**Comment by dscho** [comment] 2018-12-10 21:04
@dakotahawkins that sounds worrisome. Hopefully you can gather more information on this.

**Comment by gunnar22** [comment] 2018-12-14 15:13
I observed the same problem (as reported by MarkKharitonov) in git v2.20 on Windows. (I have not tried other versions after v2.20, I can not say for sure when the regression started).

I did a little bit research. Try to do like this:
Keep watching the Temp folder where the temporary files are placed before diff starts (repeated for each pair of files in a loop), which is C:\Users\<username>\AppData\Local\Temp
Start diffing between two commits where there are several altered files.
git difftool <commit1> <commit2>
Not necessary to use the -y option. (You may, but it is easier to analyse if you don't).
And answer n to all the Launch 'toolname' [Y/n]? n
so that it does not actually try to do any real diffing of the files.
In my system it loops from file to file and runs fine for the approximately first 5 to 8 file pairs
Watching the Temp folder, I can see that it places temporary files with decorated names (e.g., q97v0a_MySource.h) there to be diffed.
Then suddenly the error occurs:

When the error occurs, it has NOT placed the temporary files to be diff'ed into the Temp folder.

So, it is not the diffing that is the problem. It seems to be more related to what the error message says: "No such file..."

**Comment by dscho** [comment] 2018-12-17 10:13
> When the error occurs, it has NOT placed the temporary files to be diff'ed into the Temp folder.

Is it always the same file?

**Comment by gunnar22** [comment] 2018-12-17 13:13
Each experiment is repeatable, but if I change the experiment (i.e., specify other commits) it may have a different number of successes and fail on a different file than in the previous experiment.

**Comment by vdurante** [comment] 2018-12-17 17:56
I have the same issue here. The issue feels random but it feels like it has more chances of happening on some files.

**Comment by morgaalb** [comment] 2018-12-18 02:51
I also have this issue. It seems to occur when using `git difftool` on a repo with more than 23 submodules.

**Comment by dscho** [comment] 2018-12-18 12:31
> It seems to occur when using `git difftool` on a repo with more than 23 submodules.

Can you verify that by making a really small repository from scratch, with 23 fake submodules?

**Comment by gunnar22** [comment] 2018-12-18 14:07
I guess that submodules is not the reason. My case also has submodules, but a lot fewer than quoted.

**Comment by morgaalb** [comment] 2018-12-18 19:55
Thanks for the reply, @dscho. Here's the (quick and dirty) script I used to reproduce the problem (assumes that you have already created the submodule repo that gets added):

```
#!/bin/bash

mkdir original$1
cd original$1
git init
touch foo
git add foo
git commit --no-verify -m "Foo"
for i in $( eval echo {1..$1} );
do
    git submodule add /d/foo/git_bug_test/sub sub$i
done
echo "Hello world" > foo
git difftool
```

When running the script with '23' as an argument, difftool works fine. When using '24' or more, I get the following output (many many lines of submodule creation removed)

```
...
error: cannot spawn D:/foo/git_bug_test/original24/.git/objects/: No such file or directory
fatal: external diff died, stopping at foo
```

Oh, this is under Windows 10, and I've reproduced it using 2.20.0 and 2.20.1 on different machines.

**Comment by morgaalb** [comment] 2018-12-18 21:02
Additional note: when running difftool on different repos, sometimes it says it cannot spawn "Í?" or some other garbage characters, sometimes it says it cannot spawn some path in the ".git" folder (like in my example) and sometimes it seems to make up some nonexistent path in the ".git" folder, although I haven't been able to reproduce the different ways it seems to fail with a test repo.

**Comment by gunnar22** [comment] 2018-12-18 22:13
I have reproduced the issue in another repository. I forked and cloned to my PC the open source project https://github.com/osmandapp/Osmand
Then on my PC
`git difftool master~50 master`
`Viewing (1/25): 'OsmAnd-java/src/net/osmand/data/Postcode.java`
`Launch 'p4merge' [Y/n]? n`
and so on to
`Viewing (7/25): 'OsmAnd/src/net/osmand/plus/OsmandApplication.java'`
`Launch 'p4merge' [Y/n]? n`
`error: cannot spawn Q?: No such file or directory`
`fatal: external diff died, stopping at OsmAnd/src/net/osmand/plus/OsmandSettings.java`

The `master~50 master` was arbitrarily chosen, `master~30 master~10` gave same effect and number of successes (6) before fail. (To be 100% exact, master was at d7ba8b39d0)

**Comment by dscho** [comment] 2019-01-11 09:12
@PhilipOakley yep, I think you are spot on, this is likely the same bug as #2007.

**Comment by dscho** [comment] 2019-01-18 12:46
Can y'all try the latest snapshot at https://wingit.blob.core.windows.net/files/index.html? It should be fixed there.

**Comment by gunnar22** [comment] 2019-01-22 05:59
git version 2.20.1.windows.1.25.g9e107c96c0 works for me. Problem is fixed. Thanks kgybels and dscho!

**Comment by dscho** [comment] 2019-01-23 08:32
@gunnar22 thanks for testing and confirming the fix!

**Closed by dscho** 2019-01-23 08:32 UTC
Labels: bug, git
