### ISSUE TITLE
ERROR:   fatal: insanely long object directory when execute "git submodule update --init --recursive --force"

### ISSUE THREAD

**Issue by junneyang** [git-for-windows/git#762] opened 2016-05-20 03:44 UTC
1. $ git --version
git version 2.8.2.windows.1

2.$ cat ~/.gitconfig
[core]
longPaths=true

3.my script:
![qq 20160520115842](https://cloud.githubusercontent.com/assets/6802322/15416846/3aeb5538-1e82-11e6-98b5-0a28db4a31da.png)

4.details:
![qq 20160520114230](https://cloud.githubusercontent.com/assets/6802322/15416620/fcd90ec2-1e7f-11e6-9708-4511edad74d0.png)

i stuck in the problem for a very long time(i google many solutions but failed), any one should help me? thanks very much!

**Comment by dscho** [comment] 2016-05-21 05:52
This looks very much like a duplicate of https://github.com/git-for-windows/git/issues/342

Please note that while graphical screenshots (as opposed to copied&pasted text) might be more convenient for you, they are really inconvenient for me.

**Comment by dscho** [comment] 2016-10-04 15:44
If there are any new developments, let's discuss them over at #342.

**Closed by dscho** 2016-10-04 15:44 UTC
Labels: duplicate
