### ISSUE TITLE
Error in git svn with version 2.33.0.windows.2

### ISSUE THREAD

**Issue by hklene** [git-for-windows/git#3443] opened 2021-09-27 08:57 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options
git version 2.33.0.windows.2
cpu: x86_64
built from commit: 8735530946cced809cc6cc4c2ca3b078cdb3dfc8
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver
Microsoft Windows [Version 10.0.18363.1734]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Nano
Custom Editor Path:
Default Branch Option:
Path Option: CmdTools
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Core
Performance Tweaks FSCache: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Enabled
Enable FSMonitor: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

This is a VM access through VM-Ware-Horizont. But I could also reproduce in the local Notebook and a second VM with slightly different parameters.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Using the Bash, that comes with it.

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git svn fetch
```
 - What did you expect to occur after running these commands?

It should get the latest changes from the repository

 - What actually happened instead?

```
$ git svn fetch
Can't load '/usr/lib/perl5/vendor_perl/auto/SVN/_Core/_Core.dll' for module SVN:
:_Core: No such file or directory at /usr/lib/perl5/core_perl/DynaLoader.pm line
 193.
 at /usr/lib/perl5/vendor_perl/SVN/Base.pm line 59.
BEGIN failed--compilation aborted at /usr/lib/perl5/vendor_perl/SVN/Core.pm line
 5.
Compilation failed in require at C:/SnapVolumesTemp/MountPoints/{1ce26209-a688-1
1eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/share/
perl5/Git/SVN/Utils.pm line 6.
BEGIN failed--compilation aborted at C:/SnapVolumesTemp/MountPoints/{1ce26209-a6
88-11eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/sh
are/perl5/Git/SVN/Utils.pm line 6.
Compilation failed in require at C:/SnapVolumesTemp/MountPoints/{1ce26209-a688-1
1eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/share/
perl5/Git/SVN.pm line 32.
BEGIN failed--compilation aborted at C:/SnapVolumesTemp/MountPoints/{1ce26209-a6
88-11eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/sh
are/perl5/Git/SVN.pm line 32.
Compilation failed in require at C:/SnapVolumesTemp/MountPoints/{1ce26209-a688-1
1eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/libexe
c/git-core\git-svn line 64.
BEGIN failed--compilation aborted at C:/SnapVolumesTemp/MountPoints/{1ce26209-a6
88-11eb-b153-005056b0180e}/SVROOT/Users/uj5sh7g/Compass/Programme/git/mingw64/li
bexec/git-core\git-svn line 64.

$ 
```

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

Sorry, internal customer project ...
But after downgrade to 2.32.0 I can fetch the same repository no problem!

**Comment by rimrul** [comment] 2021-09-27 09:10
This seems to be a duplicate of #3392.
Please try the latest [snapshot](https://wingit.blob.core.windows.net/files/index.html) with the fix.

**Closed** 2021-09-27 09:11 UTC
Labels: duplicate

**Comment by hklene** [comment] 2021-09-27 10:18
Yeah, looks familiar ... sorry, didn't think of searching the closed tickets as the default is only concerned with open tickets.
