### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by DJm00n** [git-for-windows/git#496] opened 2015-10-20 12:05 UTC
We need to support l10n for Git.
Upstream Git uses gettext po files for localization of console git, git-gui and gitk. 
MSYS git uses them too:
![Russan MSYS git](http://dump.bitcheese.net/images/upehodo/git-ru.png)

**Comment by nalla** [comment] 2015-10-20 12:24
This is a duplicate of https://github.com/git-for-windows/git/issues/378.

Nevertheless, you can use the _SDK_ to build yourself an installer that will have localization support. 

`WITH_I18N=1 /usr/src/build-extra/installer/release.sh 2.6.1-with-i18n`.

**Comment by dscho** [comment] 2015-10-20 12:26
@DJm00n It would have been nice if you had worked a little bit toward fulfilling your wish.

For starters, this is a duplicate of https://github.com/git-for-windows/git/issues/403 and of https://github.com/git-for-windows/git/issues/378.

Also, I had *just* added this commit: https://github.com/git-for-windows/build-extra/commit/f54833da8b71fc6f55e120881c891cd7ae5f530d

And finally, you could have investigated a little bit why we exclude the language support. It was done to save space: https://github.com/git-for-windows/git/issues/262

As it happens, I was curious and built an installer with, and another without, localized messages. The difference is 4MB, nothing to laugh about when the installer is a mere 29MB to begin with.

**Comment by dscho** [comment] 2015-10-20 12:30
Oh yeah, and the plan is to automate the release engineering quite a bit. When that finally is said and done, I will add installers with multi-language support.

Feel free to help make that happen by working on https://github.com/git-for-windows/build-extra/compare/cmd-scripts

**Closed by dscho** 2015-10-20 12:30 UTC
Labels: duplicate
