### ISSUE TITLE
Enable core.longpaths by default on fresh versions Windows

### ISSUE THREAD

**Issue by mfilippov** [git-for-windows/git#2641] opened 2020-05-29 08:28 UTC
Starts from Windows 1607 Microsoft remove MAX_PATH limit in Windows( https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later).
I offer to enable **core.longpaths** by default in git for Windows.
Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.26.2.windows.1
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19041.264]
```

**Comment by dscho** [comment] 2020-05-29 14:30
> Starts from Windows 1607 Microsoft remove MAX_PATH limit in Windows( https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later).

Have actually you read this? It says this:

> To enable the new long path behavior, both of the following conditions must be met:
>
> * The registry key HKLM\SYSTEM\CurrentControlSet\Control\FileSystem LongPathsEnabled (Type: REG_DWORD) must exist and be set to 1. [...]
> * The application manifest must also include the longPathAware element.
> ```xml
> <application xmlns="urn:schemas-microsoft-com:asm.v3">
>     <windowsSettings xmlns:ws2="http://schemas.microsoft.com/SMI/2016/WindowsSettings">
>         <ws2:longPathAware>true</ws2:longPathAware>
>     </windowsSettings>
> </application>
> ```

Almost nobody sets that registry option. I have spoken to a couple users who I thought might benefit from it, and none of them had it set. One user even reported having such big problems after enabling it that they had to immediately disable it again.

Even _if_ that registry option were set in many setups, in order to benefit from it, Git would not only have to set the `longPathAware` attribute in its manifest, it would actually have to have _tons of code changes_!

And none of this has _anything_ to do with `core.longPaths`, which uses a very different mechanism that does not rely on that registry setting and that manifest attribute at all.

So I offer instead that this idea is not even half-way thought through.

**Comment by JojOatXGME** [comment] 2021-03-20 17:22
I have set this registry key a long time ago – I would say at least two years. I never had any problems with it. However, not everything works if you have paths that long. For examples Windows Explorer can navigate through directories behind such paths and open files, but Windows Explorer cannot rename such files. It is difficult to tell how many applications support it since I rarely exceed `MAX_PATH`. Git for Windows obviously doesn't. I think it is kind of a chicken-egg problem.

**Comment by cmcornish** [comment] 2022-11-14 10:18
I have hit this issue. We have long file names in an SVN imported repository. I set the registry value and it had no effect on the GIT clone - still didn't support long file names. I then removed it. GIT for windows appears to behave as a 32 bit application even though the 64 bit version was installed (Git-2.38.1-64-bit) on windows 10. I have managed to clone the repository successfully using a Cygwin GIT installation, so it's not the PC or file system. I will be unable to use GIT for windows because of this.

**Comment by dscho** [comment] 2024-10-18 14:34
I will close this ticket, as we got too bogged down in the confusion between the registry setting (which Git for Windows does not respect) and `core.longPaths` (which takes a totally different approach, and adds a performance hit to every I/O-related Git operation).

**Closed by dscho** 2024-10-18 14:34 UTC

**Comment by JojOatXGME** [comment] 2024-10-18 17:16
@dscho At least I am aware that these are two different and independent solutions. Anyway, do you know if there have been any benchmarks or other evaluations about the performance hit caused by `core.longPaths`? As long as the performance hit is not too high (maybe below 10 %), I think it would still be a good idea to make it the default. For me, it feels like everybody I know who uses Git on Windows has set this option to `true`. (At least I came across the instruction to set this option to `true` a lot in various different projects.)

**Comment by dscho** [comment] 2024-10-18 18:16
> do you know if there have been any benchmarks or other evaluations about the performance hit caused by `core.longPaths`?

It added 3-4% to the runtime, in my tests. Given that we clawed back performance in Git for Windows and in `microsoft/git` in monorepos in tedious 1-2% increments, this is a rather bad deal.

> As long as the performance hit is not too high (maybe below 10 %), I think it would still be a good idea to make it the default.

While you may think it a good idea, I don't think the majority of Git users would agree with you. I even have evidence that 1-2% speed regressions earn me conversations I could just as well do without.

So no, I don't think it would be a wise choice to make that the default.
