### ISSUE TITLE
Bash fts_read fails on exFAT when relative folder depth > 5

### ISSUE THREAD

**Issue by eGust** [git-for-windows/git#1536] opened 2018-03-04 10:50 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.248]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
$ cat /etc/install-options.txt

Editor Option: VIM
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Only happens when I manipulate directories on a driver with exFAT file system (512 bytes/sector, 8 sectors/cluster, 4KB/cluster)

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Bash

 - What commands did you run to trigger this issue? 

```
$ mkdir -p f1/f2/f3/f4/f5/f6 && touch f1/f2/f3/f4/f5/f6/foo.bar
$ rm -rf f1
```
 - What did you expect to occur after running these commands?

Everything will be fine if max relative folder depth <= 5 (not absolute path depth). 
Any command recursively does something to a folder contains more than 5 levels (like `chmod -R`) will raise the error `fts_read failed: No such file or directory` and stop, although the files inside that folder have been removed.

 - What actually happened instead?

```
rm: fts_read failed: No such file or directory
```

**Comment by dscho** [comment] 2018-03-05 12:58
Does this same error occur also when you use [Cygwin](https://cygwin.com/)?

**Comment by eGust** [comment] 2018-03-06 06:57
Just tried Cygwin. works fine
![cygwin_test](https://user-images.githubusercontent.com/3207934/37018259-98dcec6a-2178-11e8-8b87-a92e511f8e31.png)

**Comment by dscho** [comment] 2018-03-06 10:34
And with plain [MSYS2](https://msys2.github.io/)?

**Comment by eGust** [comment] 2018-03-06 12:44
Got `fts_read failed: No such file or directory` with `rm -rf` on msys2 x64, but `chmod -R` is ok. 
Already switched default term of my ConEmu to Cygwin. Unfortunately, Cygwin doesn't work well with VSCode.

**Comment by dscho** [comment] 2018-03-13 14:19
I wonder whether you have any suggestion how I could get to reproduce this locally, as quickly as possible? (Read: I won't have several hours to spend on just *trying* to reproduce this, but if you have e.g. an Azure VM where this reproduces to which you could give me access... then we'd be in business.)

**Comment by jameschenjav** [comment] 2018-03-13 23:18
I don't have any cloud win VM.
I prepared a zipped VMDK file ( 100MB, <300MB decompressed, 160GB disk, exFAT, 4k cluster size ), so you should be able to open it with any VM software:
https://drive.google.com/open?id=1mfhxR3Y6W7JV67WI2tHH4nYqPOrqaHN4

I downloaded a new VirtualBox image [MSEdge on Win10 (x64) Stable (16.16299)](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) to my macbook (macOS 10.13.3 17D102), attached the above VMDK to it, and successfully reproduced the issue in VirtualBox (5.2.8). I think this issue is very likely reproducible with any Win10 x64 on any VM.

sorry for replying from my another account.

**Comment by dscho** [comment] 2018-03-14 16:16
@jameschenjav I just tried to convert this to a Hyper-V machine (which is the only VM software I have installed on my machine) and it failed to convert:

> ConvertTo-MvmcVirtualHardDisk : The entry 06eca83e-f773-4b8d-afb3-e9f0e36f542d is not a supported disk database entry for the descriptor.

Happily, I *think* that this bug might have the same root cause as https://github.com/git-for-windows/git/issues/1497 and therefore I would like to ask you to download [msys2-runtime-fat-fix.zip](https://github.com/git-for-windows/git/files/1811964/msys2-runtime-fat-fix.zip) and unpack the `msys-2.0.dll` contained therein into your Git's `usr\bin` folder (overwriting the existing file), then test whether it really fixes your problem?

**Comment by eGust** [comment] 2018-03-15 06:16
That fix is working. My tests passed on both real PC and VM. 
Thanks

**Comment by dscho** [comment] 2018-03-15 09:08
Awesome! Thanks for the feedback!

**Comment by dscho** [comment] 2018-03-15 22:09
Fixed in https://github.com/git-for-windows/msys2-runtime/commit/50159fe297ca46145558b60a0354701e3ce1bb54.

The next [snapshot](https://wingit.blob.core.windows.net/files/index.html) will have the fix.

**Closed by dscho** 2018-03-15 22:09 UTC
Labels: unclear
