### ISSUE TITLE
The "Use the OpenSSL library" option is not being taken into account during the installation process since Git version 2.41.

### ISSUE THREAD

**Issue by cassassi** [git-for-windows/git#4829] opened 2024-02-21 08:25 UTC
- [ x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

** git version 2.43.0.windows.1
cpu: x86_64
built from commit: 4b968f3ea3b32a7bc50846bab49f3f381841d297
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon **
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver

** Microsoft Windows [version 10.0.19045.2006]
(c) Microsoft Corporation. Tous droits réservés. **
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
> type "$env:USERPROFILE\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

** Editor Option: VIM
Custom Editor Path: 
Default Branch Option:  
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Use Credential Manager: Enabled
Performance Tweaks FSCache: Enabled
Enable Symlinks: Disabled
Enable Pseudo Console Support: Disabled
Enable FSMonitor: Disabled **
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

** No internet access **

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

** Bash **

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
** curl https://local_website **
```
 - What did you expect to occur after running these commands?

** return web HTML page**

 - What actually happened instead?

** revocation error because it uses windows store instead of git store **

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

** insert URL here **

 - issue explinantion?
 
** I observed that starting from version 2.41 of Git, when selecting the "Use the OpenSSL library" option, which is supposed to utilize the ca-bundle.crt file, it instead utilizes the Windows Certificate Stores. Consequently, the option to use the OpenSSL library is not being considered. I have tested this behavior across versions 2.41 to 2.44.0-rc2.windows.1, and the issue persists. Versions 2.40.1 and earlier functioned correctly, with the option being taken into account **

**Comment by rimrul** [comment] 2024-02-21 11:32
Duplicate of #4755

**Closed by rimrul** 2024-02-21 11:32 UTC
Labels: duplicate
