### ISSUE TITLE
git.exe svn fetch Error

### ISSUE THREAD

**Issue by MrXhh** [git-for-windows/git#2670] opened 2020-06-05 08:15 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?
64-bit
```
$ git --version --build-options

git version 2.27.0.windows.1
cpu: x86_64
built from commit: 907ab1011dce9112700498e034b974ba60f8b407
sizeof-long: 4
sizeof-size_t: 8
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
Win10 64-bit
```
$ cmd.exe /c ver

Microsoft Windows [版本 10.0.19631.1]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: VIM
Custom Editor Path: 
Path Option: Cmd
SSH Option: OpenSSH
Tortoise Option: false
CURL Option: OpenSSL
CRLF Option: CRLFAlways
Bash Terminal Option: MinTTY
Git Pull Behavior Option: Merge
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Enabled
Enable Pseudo Console Support: Disabled

```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

git.exe svn fetch
svn: E235000: In file 'subversion/bindings/swig/perl/libsvn_swig_perl/swigutil_pl.c' line 1666: assertion failed (get_current_pool_cb != NULL)
0 [main] perl 1619 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

TortoiseGit 2.10.0.2 (C:\Program Files\TortoiseGit\bin)
git version 2.27.0.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig)

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
TortoiseGit--》SVN Rebase
```
 - What did you expect to occur after running these commands?

** insert here **

 - What actually happened instead?

git.exe svn fetch
svn: E235000: In file 'subversion/bindings/swig/perl/libsvn_swig_perl/swigutil_pl.c' line 1666: assertion failed (get_current_pool_cb != NULL)
0 [main] perl 1619 cygwin_exception::open_stackdumpfile: Dumping stack trace to perl.exe.stackdump

[perl.exe.stackdump.zip](https://github.com/git-for-windows/git/files/4734782/perl.exe.stackdump.zip)

**Comment by MrXhh** [comment] 2020-06-05 08:17
Git-2.26.2-64-bit.exe Using the normal

**Comment by rimrul** [comment] 2020-06-05 08:57
Duplicate of #2649 and #2662

**Closed** 2020-06-05 20:53 UTC
Labels: duplicate
