### ISSUE TITLE
Git flow hotfix won't start a hotfix off a tag (git 2.16.2.windows.1)

### ISSUE THREAD

**Issue by chhh** [git-for-windows/git#1546] opened 2018-03-08 21:46 UTC
- [x] I was not able to find an [open](https://github.com/git-for-windows/git/issues?q=is%3Aopen) or [closed](https://github.com/git-for-windows/git/issues?q=is%3Aclosed) issue matching what I'm seeing

### Setup

 - Which version of Git for Windows are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.16.2.windows.1
cpu: x86_64
built from commit: e1848984d1004040ec5199e749b5f282ddf4bb09
sizeof-long: 4
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?

```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.16299.248]
```

 - What options did you set as part of the installation? Or did you choose the
   defaults?

```
# One of the following:
> type "C:\Program Files\Git\etc\install-options.txt"
> type "C:\Program Files (x86)\Git\etc\install-options.txt"
> type "%USERPROFILE%\AppData\Local\Programs\Git\etc\install-options.txt"
$ cat /etc/install-options.txt

Editor Option: Notepad++
Path Option: Cmd
SSH Option: OpenSSH
CURL Option: OpenSSL
CRLF Option: CRLFCommitAsIs
Bash Terminal Option: MinTTY
Performance Tweaks FSCache: Enabled
Use Credential Manager: Enabled
Enable Symlinks: Disabled
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

Opened a ticket with git-flow-avh as well: https://github.com/petervanderdoes/gitflow-avh/issues/354

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

Git Bash

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
git flow hotfix start v5.2 v5.1
```
History log context:
![git-flow-hotfix-bug](https://user-images.githubusercontent.com/107902/37178374-21d68382-22d7-11e8-9f51-8ca43e7984b2.png)

 - What did you expect to occur after running these commands?

A new hotfix/v5.2 branch spawned off from v5.1 tag.

 - What actually happened instead?

Fatal: Base 'v5.1' needs to be a branch. It does not exist and is required.

 - If the problem was occurring with a specific repository, can you provide the
   URL to that repository to help us with testing?

https://github.com/chhh/MSFragger-GUI

**Comment by shiftkey** [comment] 2018-03-08 22:36
@chhh this is a third party package that is not maintained by the Git for Windows maintainers. The current version and packaging details can be found here: https://github.com/git-for-windows/MSYS2-packages/tree/master/git-flow

`petervanderdoes/gitflow-avh` is the correct place to report this issue, and once a version has been released you can submit a PR to update the build script which will make it into the next release of Git for Windows.

**Comment by chhh** [comment] 2018-03-08 22:43
@shiftkey Ok, as I mentioned in the "interesting details" section, I already opened a ticket with them: petervanderdoes/gitflow-avh#354

**Comment by dscho** [comment] 2018-03-13 11:36
To be quite honest, I am pretty unfamiliar with Git Flow (and intend to stay that way, as the regular "topic branches into `master`" workflow works splendidly fine with me), so maybe it was intentional that you can create hotfix branches only off of branches and not off of tags?

**Comment by mfriedrich74** [comment] 2018-03-13 13:54
> the regular "topic branches into master" workflow works splendidly fine with me
@dscho Git Flow is not much more than that. It just adds a naming convention to "topic" branches.

**Comment by dscho** [comment] 2018-03-13 16:29
@mfriedrich74 no. The development in Git Flow happens on a `develop` branch. Only from time to time, this branch (and this branch only) is merged into `master`. That's as far as I care to learn what Git Flow is, and that is already too far from the workflow I prefer.

But since you seem to be familiar with Git Flow, and since you are here already, why don't you attempt to answer @chhh's concern and help this project along while doing so?

**Comment by mfriedrich74** [comment] 2018-03-13 21:14
@dscho I guess i deserved your response ;) - I should have tried an answer right away.

Here is the issue discussed on the original github project:
https://github.com/nvie/gitflow/issues/375

@chhh
Whats the output of `git flow version`?

As the error message indicates, this seems to be by design.

Before Git Flow performs a checkout like `git flow hotfix start v5.2 v5.1` it runs a couple of checks.

These are the checks done by the original edition:
The branch hotfix/v5.2 must not yet exist (require_branch_absent)
v5.1 is on master (require_base_is_on_master)
no hotfix	branches exist (require_no_existing_hotfix_branches)
require_tag_absent "hotfix/v5.2"

The AVH edition adds a check:
https://github.com/petervanderdoes/gitflow-avh/blob/develop/git-flow-hotfix#L190
require_base_is_local_branch "$base"
This is the one that fails for you.

@dscho If i remember correctly, there was a reason why the AVH edition is included in Git for Windows. What was it?

If someone likes to learn more about Git Flow:
http://nvie.com/posts/a-successful-git-branching-model/
https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow

**Comment by mfriedrich74** [comment] 2018-03-13 21:28
According to you screenshot, your master currently points to v5.1. So, to work around that limitation, you can either create a branch from the tag v5.1 or you could just use master.

I think this comes from the idea that you have a broken branch and need to apply a hotfix to it.
Fixing an (old) release (not master) is done by creating release branches, which technically is not covered by the original Git Flow, if i remember correctly.

**Comment by dscho** [comment] 2018-03-14 17:41
> @dscho If i remember correctly, there was a reason why the AVH edition is included in Git for Windows (instead of the one from nvie). What was it?

Yes, that's an easy one. The original Git Flow project had become *awfully* quiet. It seems that the inventor became too happy with his fame and simply stopped responding. There are currently almost 200 [open issues](https://github.com/nvie/gitflow/issues) and approaching 100 [open Pull Requests](https://github.com/nvie/gitflow/pulls). At the time I checked, nvie had not replied to any question in a loooong time (a year, IIRC?) and he did not even respond via any other channel, whether email or even Twitter. That was not a project I was comfortable bundling.

AVH Git Flow was much more responsive at the time, and even has released new versions in the meantime.

**Comment by chhh** [comment] 2018-03-14 21:56
I guess hotfix is just not a popular option, however I encountered it on my 2nd day of use gitflow.  
The AVH edition also looks to be not maintained anymore - questions are unanswered and the author does not show up on github anymore (he mentioned getting a new job in one of his last comments).

**Comment by dscho** [comment] 2018-03-15 09:55
> The AVH edition also looks to be not maintained anymore - questions are unanswered and the author does not show up on github anymore (he mentioned getting a new job in one of his last comments).

@chhh what a bummer!!!

Seems the only active forks are now @arutkowski00's and yours. Hopefully one of you will step up and take over maintainership, then we can switch to that maintained version.

**Comment by arutkowski00** [comment] 2018-03-19 21:08
I'm just tweaking git-flow for my company's needs 😄

**Comment by dscho** [comment] 2018-03-21 23:53
> I'm just tweaking git-flow for my company's needs 😄

@arutkowski00 yeah, yeah. The old story. Nobody steps up to maintain Open Source, apart from preciously few idiots like me.

**Comment by dscho** [comment] 2019-10-13 22:52
> I already opened a ticket with them: [petervanderdoes/gitflow-avh#354](https://github.com/petervanderdoes/gitflow-avh/issues/354)

I'll just go ahead of myself and assume that the help you received there was enough to address the issue. In any case, this problem does not seem to be specific to Git for Windows, and is therefore best discussed upstream.

**Closed by dscho** 2019-10-13 22:52 UTC
Labels: question
